== [big-number]#2064# Schwachstellen in Computern

[text-caps]#Lasse und Sigur saßen# am Esstisch der Hausküche und hielten sich beide an einer große Tasse mit dickem Kakao fest.
Lilly saß im Schneidersitz auf dem Tisch und lächelte immer noch.

„Das hast du vorbereitet“, schnautze Lasse sie an.
„Das ging zu schnell.
Das war ein Computer-Programm, oder?“

Lilly: „Klar! Da habe ich den ganzen Abend gestern dran geschrieben.
Heute morgen habe nur einen Befehl eingegeben und butzzz …“

Sigur: „Aber wie ging das? Ich hatte alles dicht.
Ich bin gestern und heute morgen noch einmal alles durchgegangen.
Es war keine Lücke da.
Wo bist du durchgekommen?“

Lilly: „Eine noch unbekannte Schwachstelle in eurer Firewall.
Die hat ein großer amerikanischer Geheimdienst einbauen lassen und dafür viel Geld bezahlt.
Sie funktioniert super.
Ihr könnt euch das ja nach dem Spiel in den Logdateien anschauen, da steht alles drin.
Erst einmal gehe ich damit noch ein wenig auf Raubzug.
Über diese Hintertür kann man in viele Computer hereinkommen.
Sie ist weit verbreitet und niemand kennt sie.“ Sie grinste breit.

Schwachstellen oder Hintertüren gab es in allen Computern und Programmen.
Man konnte sie schließen, wenn man wusste wie.
Wenn man sie erst einmal kannte.
Über Schwachstellen konnte man Computer dazu bringen, alle möglichen Dinge zu tun, die die Programmierer und Computerverwalter nicht vorgesehen hatten.
Manchmal ganz verrückte Dinge.
Manchmal konnte man einen Computer aus der Ferne komplett übernehmen, als wäre es der eigene, und dann alles mit ihm machen, was man wollte.

„Das ist doch unfair!“, murrte Sigur.
„Du kennst eine Hintertüre und sagst sie niemandem.
Geheime Hintertüren sollte es im Spiel nicht geben.
Das ist doof.
Wie soll man sich dagegen schützen? Ich habe mir echt viel Arbeit gemacht, es war keine Lücke mehr da.“

Lasse: „Ich glaube, es ist gar nicht erlaubt, Schwachstellen für sich zu behalten.
Das ist gegen die Spielregeln.
Schwachstellen gehören der Allgemeinheit wie Wasser und Luft.
Man muss sie sofort bekannt machen.
Das ist ein Menschenrecht … habe ich in meinem Computerverwalterkurs gelernt.
Außerdem ist das auch eine Cypherpunk-Regel.“ Man kann sogar sein Arbeitsrecht verlieren, wenn man eine Schwachstelle nicht bekannt macht.

Lilly: „Heute … heute ist das so.
Damals war es erlaubt, das geheim zu halten! Glaube ich zumindest.
Auf jeden Fall war es Gang und Gäbe.
Ich habe eine E-Mail gelesen, wo jemand eine noch unbekannte Schwachstelle einem anderen zum Verkauf angeboten hat.
Für wahnsinnig viel Geld.
Und der andere hat gekauft.“

„Blödsinn!“ Sigur schüttelte den Kopf.
„Schwachstellen verkaufen?! Vielleicht wenn du die Mafia spielst, aber sonst nicht.
Das wäre ja total korrupt.
Super schlecht.
Das ist so schlecht wie Leute krank machen und dann an der Medizin verdienen.“

Lilly zog die Augenbrauen hoch.
„Pfff.
Hej, wacht auf.
Die Welt damals war anders.
Das haben alle gemacht damals.
Regierungen, Unternehmen, Geheimdienste.
Die haben ganze Schwachstellen-Arsenale aufgebaut, genauso wie Waffen-Arsenale.
Sie haben sie gehortet.
Massenweise.“

Beide Jungs prusteten los.

„Lilly, das ist jetzt wirklich Quatsch“, meinte Lasse immer noch lachend.
„Wer hat dir so etwas erzählt?“

Lilly verschränkte ihre Arme und machte ein ernstes Gesicht: „Nee.
Echt! Massenweise, Berge … Ich sag euch.
Ich habe …“ Sie stockte.

Lasse: „Lilly, bleib auf dem Teppich.“

„Du hast …?“, fragte Sigur.
„Was hast du?“ Er rutschte zu ihr herüber.

Lilly schaute zu Boden.

„Du hast noch mehr Schwachstellen gefunden?“, fragte Sigur und schaute sie intensiv an.

Lilly schaute zurück: „Pfffff.
Jede Menge.
Unglaubliche Sachen.
Ihr könnt euch nicht vorstellen, was alles geht“, sie grinste.
„Ich habe eine Datenbank bei der NSA gefunden: ‘Zero Day Exploits’, das sind alles Schwachstellen, die noch niemand kennt.
Marie ist dort Agentin, sie hat mir dabei geholfen, da dran zu kommen.
Sie selbst darf ja in der Datenbank alles nachschauen, aber sie darf nichts damit tun, was nicht zu ihrem Auftrag passt, und alles, was sie tut und sagt, wird aufgezeichnet, alles, jeder Tastendruck, jedes Gespräch, jeder Gesichtsausdruck.
Sie nehmen echt alles auf! Von allen Mitarbeitern.
Bescheuert.
Echt Scheiße, dort zu arbeiten.
Aber ich konnte mit ihrer Hilfe die Datenbank dort heraus bekommen! War nicht ganz einfach … Und jetzt kann ich … Uuuuuhhhh“, sie schüttelte den Kopf, „… so viel machen … Hi.
Hi.
… Ich weiß, dass das unfair ist, aber es ist ein Spiel.
Da muss man auch verlieren können.“

Sigur murrte: „Du arbeitest mit der NSA zusammen? Das sind Gegner.
Das ist gemogelt.
Und Marie gibt dir die Informationen, weil ihr auch normal befreundet seid.“

„Überhaupt nicht.
Ich habe zwei Computer von Hackerinnen für sie geknackt, die sie für ihre Mission gebraucht hat.
Sie hat die Mission dadurch fast fertig.
Die beiden Hackermädels müssen nur noch ins Gefängnis, und mehr als 10 Jahre bekommen.
Sie sind gerade vor Gericht.
Wenn das durch ist, hat sie es geschafft.
Das war der Deal.
Wir haben halt als Frauen gut zusammen gearbeitet, nicht gemogelt! Man kann ja noch jede Menge andere Dinge machen, viel Psychozeugs: Du kannst erpressen, anwerben, bestechen, einschüchtern, lügen.
Ihr wisst schon, was das für eine Welt damals war? Ich meine, wie wollt ihr einen fliegenden Kampfroboter bekommen, ohne jemand bei der CIA zu haben, der tut, was ihr wollt? Kein Wunder, dass ihr noch keinen habt.
Marie hat schon einen.“

Lasse und Sigur schauten sich an.
Fliegende Kampfroboter.
Das war ihr höchstes Ziel.
Sie kannten niemanden, der es geschafft hatte, einen zu übernehmen.
Sigur fasste sich an den Bauch: „Mir wird schlecht.“ Lasse kniff seine Lippen zusammen und schaute zu Lilly rüber: „Wie kann man jemanden bei der CIA umdrehen? Aus dem Kampfroboter-Verband?“, fragte Lasse.

„Ich weiß nicht wie Marie das gemacht hat.
Aber du musst halt rauskriegen wie sie dort ticken.
Ich meine, sie hat ja Zugriff auf alle Kommunikationsdaten: Sie schaut, was er so für E-Mails schreibt und bekommt, mit wem er telefoniert, wen er trifft, was er kauft, ob er Feinde hat, ein Verhältnis, von dem seine Frau nichts wissen darf, Schulden, und dann schaut sie, ob sie etwas findest, mit dem sie ihn erpressen kann.
Sie hat anscheinend etwas gefunden.
Oder vielleicht ist jemand auch einfach richtig unzufrieden in seinem Job.
Dann kannst du ihn möglicherweise anwerben.
Marie ist zum Beispiel unzufrieden, sie hat gerade einen Auftrag bekommen, den sie überhaupt nicht machen will.
Aber sie muss.
Und sie kann nicht einmal weggehen von dort.
Das geht nicht so einfach bei Geheimdiensten.
Du kannst es ja mal versuchen, sie für etwas anzuwerben.
Aber pass extrem auf.
Du darfst dich dort wirklich nicht erwischen lassen.
Sonst ist da ist die Hölle los.
Dann ist sofort der halbe Geheimdienst hinter dir her.
Und zack hast du eine Rakete im Zimmer und siehst deine Ehrenmedaille auf dem Bildschirm.
Wie Lars letztes Mal.“

Sigur: „Lars hat gemogelt.
Deswegen ist er rausgeflogen.
Erpressung und so gehört nicht zum Spiel.
TRON nimmt einen aus dem Spiel, wenn man so etwas macht.“

Lilly: „Tut er nicht.
Marie kann jederzeit auf ihren Kampfroboter zugreifen und schauen, was der gerade macht.
Und das geht nicht ohne Erpressung.
Das gehört klar zum Spiel dazu.
Das heißt ‘social engineering’, soziale Technik.“

Sigur schwieg.

Lilly: Wenn du das nicht willst, kannst du ja Cypherpunks-Missionen spielen.
Da geht es nicht darum, möglichst viele Computer zu übernehmen oder Hacker zu fangen, sondern darum, dass Dinge ans Licht kommen, dass Ungerechtigkeiten ausgeglichen werden und dass immer mehr Menschen der Unterdrückung entkommen können.
Da musst du eher so denken, wie wir heute denken.
Dann kannst du vielleicht herausfinden, wie die Cypherpunks den Krieg gewonnen haben.
Ich meine, das war schon eine Übermacht damals, die Geheimdienste, die Armeen, Riesenunternehmen.
Aber am Ende haben sie es geschafft.
Ich habe mal überlegt, ob es nicht auch spannend wäre, Cypherpunk zu spielen.
Vielleicht ist das sogar der eigentliche Sinn des ganzen Spiels: dass wir lernen können wie der Befreiungskampf war.“

Lasse und Sigur schauten sich an.
Lilly wollte ihnen gerade erzählen, was der eigentliche Sinn von TRON ist, dem Spiel, mit dem sie hunderte Stunden verbracht hatten, alles angeschaut, ausprobiert, gelernt hatten, was ihnen über den Weg gelaufen war.

Lasse: „Hej, Lilly.
Ich spiele TRON jetzt seit drei Jahren und es geht am Ende darum, die Welt zu erobern, die Politik zu bestimmen, den Lauf der Geschichte zu ändern, aber nicht um die Befreiung des Internets.
Ich wollte Julian Assange nicht spielen, um das Überwachungssystem von damals zu brechen, Geheimdienste abzuschaffen, Regierungen transparent zu machen, sondern weil er eine Menge coole Leute um sich herum hat, die jede Menge drauf haben, und weil die halbe Welt hinter ihm her ist.“

Lilly: „Und, hast du die Rolle bekommen?“

Lasse: „Nein.
Das weißt du.“

Lilly: „Du kannst sie nicht bekommen, wenn du den Fragebogen am Anfang nicht so ausfüllst, dass es dir hauptsächlich um die Zukunft des Internets geht.
Julian ist ein Cypherpunk.
Wenn du nur Abenteuer willst, dann bekommst du ihn nicht.“

Sigur fauchte dazwischen: „Woher weißt du das alles?“

Lilly: „Ich habe Marianne Lasser gelesen: Die Geschichte der Cypherpunks, bevor ich überhaupt angefangen habe, TRON zu spielen.
Sie schreibt über 2019 und danach, bis zum Kriegsende.
Wie es damals war, wie sie Hacken gelernt hat und dann Cypherpunk geworden ist.
Und sie schreibt, um was es wirklich ging, wie die Leute bei den Geheimdiensten dachten und bei den Unternehmen und wie die Hacker waren, mit weißen, grauen und schwarzen Hüten, also solche, die nur erforschen und nichts kaputt machen, solche bei denen die Grenzen nicht ganz klar sind, die auf ihren eigenen Vorteil aus sind und solche, die echt klauen und zerstören wollen.
Und dann die Hacks, die sie gemacht haben.
Wow! Echt Wahnsinn.
Da habe ich gedacht, das probiere ich in TRON aus, was sie da schreibt.
Und das stimmte alles im Spiel.
Ganz genau.
Edward Snowden.
Das war genau so, wie Marianne Lasser darüber geschrieben hat.
Genauso hat sie ihren eigenen Hack beschrieben, wie sie die Datenbank mit den Schwachstellen aus dem Hauptquartier der NSA herausschmuggeln konnte.
Und das habe ich dann zusammen mit Marie gemacht.
Das ging gut.
Man braucht dafür einen NSA-Mitarbeiter, sogar einen bestimmten.
Und so haben wir alle Schwachstellen herausgebracht.“

Sigur: „Alle? – Wie viele sind das?“

Lilly: „Ich weiß nicht.
Es ist ein heilloses Durcheinander.
Ich kann mir nicht vorstellen, dass sie selbst eine Übersicht darüber haben.
Bei diesen Geheimdiensten haben viele Schnarchnasen und Langweiler gearbeitet, wie in allen großen Regierungsbehörden.
Aber insgesamt sind es bestimmt tausende, vielleicht zehntausende Schwachstellen, für alle Computer, die du dir nur denken kannst, auch für Satelliten.
Und eine einzelne Schwachstelle davon ist eben die Hintertür, über die ich gerade eben bei euch hineinspaziert bin.“

Lasse: „Du kannst uns unsere Computer auch wiedergeben …“

Lilly: „Nee.
Erstens hat die schon Marie und zweitens wäre das gemogelt.
Für euch ist jetzt erst einmal Flucht dran.“
