== [big-number]#2019# Einbruch in Amerika

[text-caps]#Marianne zog einen vollgekritzelten Zettel# aus ihrer Tasche.
Auf ihm stand alles, was sie jetzt brauchte.
Das letzte Mosaiksteinchen links unten war gestern erst dazugekommen.
Zwei Worte.
„karlibender“ und „LV7jolgS7brT5M“, Name und Passwort, und sie wusste, wo die passten.
Der Weg dorthin war eine kleine Weltreise, aber sie würde nicht lange dauern.
Sie begann die Reise, indem sie sich an einem Berliner Unirechner anmeldete, mit einem Konto, das schon lange niemand mehr nutzte.
Von dort ging es weiter nach New York, ein Abstecher nach Brasilien und dann nach New Jersey an die Princeton Universität.
Dort arbeitete Karl Bender und andere Wissenschaftler in einem Projekt, in dem auch amerikanische Geheimdienste mitmischten.
Es ging um Satelliten, Spionage-Satelliten, natürlich streng geheim.
Alles, sogar der Projektname war geheim.
Aber Marianne wusste davon.

Karl Bender hatte ein Freundin, Corinne, und die war schon jahrelang Mariannes beste anonyme Freundin.
Das heißt, sie hatten sich niemals in Wirklichkeit getroffen und keinen Kontakt miteinander gehabt, von dem irgendjemand wissen konnte.
Sie hatten sich geschützt im Tor-Netzwerk kennengelernt, in einem Chat-Raum, und beide hatten über die Jahre streng darauf geachtet, dass sie sich immer nur anonym begegneten, immer geschützt durch Tor-Masken.
Sie erzählten sich voneinander, immer mehr auch Persönliches.
Danach konnten sie im Internet recherchieren und herausfinden, ob es wirklich stimmte, was die andere gesagt hatte.
Und so hatten sie mit der Zeit immer mehr Vertrauen zueinander gefasst und angefangen, sich alles über einander zu erzählen.
Es war einfach spannend, eine solche anonyme Beziehung zu haben.
Inzwischen kannten sie sich sehr, sehr gut.

Corinne hatte ihr davon erzählt, dass bei Karl ein Geheimdienstmann der NSA zu Besuch war, um mit Karl den Start eines ganz neuen Satelliten vorzubereiten.
Die NSA war ein Geheimdienst der Amerikanischen Armee, es war der größte Geheimdienst überhaupt.
Und bei diesem Besuch ging fast alles schief.
Nichts stimmt zusammen und um ein Haar hätten sie den Start abbrechen müssen.
Aber gemeinsam schafften sie es gerade noch, ein Programm, das im Satelliten laufen sollte, fertig zu kriegen, buchstäblich in letzter Sekunde.
Wohl in der Hektik hatte der NSA-Mann den Geheimschlüssel für seinen eigenen Computer bei der NSA auf Karls Rechner hinterlegt.
Und dann dort vergessen.
Ein Geheimdienst-Schlüssel! Karl hatte das einen Tag später Corinne auf einem Spaziergang erzählt.
Eigentlich hätte er ihn sofort löschen müssen, aber er hatte es nicht getan.

Als Marianne davon erfahren hatte, begann sie sofort zu recherchieren.
Ihr Bruder Paul war ein bekannter Cypherpunk.
Cypherpunks waren Hacker, die Verschlüsselungsprogramme schrieben, und kostenlos an alle Menschen weitergaben, die sie haben wollten.
Es waren die besten, die es gab.
Selbst die größten Geheimdienste hatten vor ihnen Respekt.
Marianne war oft nächtelang neben ihm gesessen, wenn er im funkgesicherten Keller saß und in der Welt herumreiste, und sie hatte dabei vieles gelernt.
Paul nahm sich auch oft Zeit, ihr Dinge genauer zu erklären, ihr vergangene Hacks zu zeigen oder eine Programmiersprache beizubringen.
Sie konnte immer zu ihm kommen, mit allem, hatte er gesagt, jederzeit.
Und sie hatte auch daran gedacht, in dieser Sache Paul um Hilfe zu fragen.
Das würde vieles einfacher machen, aber sie hatte dann entschieden: Nein! Anonyme Beziehungen sind anonyme Beziehungen, Punkt.
Dieser Schlüssel war für sie, für sie allein.

„k a r l i b e n d e r“ tippt sie hinter das Wort „login“ in die Konsole.
„Passwort:“ antwortete der Computer.
Jetzt wurde es zum ersten Mal spannend: „War das Passwort in der Zwischenzeit geändert worden?“

„L V 7 j o l g S 7 b r T 5 M“ und dann die Enter-Taste.

****
....

„karlibender@trt.princton.edu: ~$“, 
....
****

erschien auf dem Bildschirm.

„JAH!“, rief sie laut und schaute sofort über den Rathausplatz.
Niemand schien sie bemerkt zu haben.
Sie war drin! Keine großartige Meldung.
Nur die Befehlseingabe des Terminalprogramms, aber diesmal die vom Computer von Karl Bender an der Princeton Univerität.
Wow! Ihre Finger huschten über die Tastatur.
Wie automatisch suchte sie alle Logdateien zusammen, die sie finden konnte, alle Passwort- und alle Schlüsseldateien.
Ihr Bruder tat das auch immer als erstes.
Über die Logdateien konnte sie herausfinden, was auf dem Computer alles passierte, detailliert aufgelistet, und aus den Passwortdateien konnte man, wenn man Glück hatte, einzelne Passworte entschlüsseln, wenn die schlecht geschützt waren, zum Beispiel wenn sie zu kurz waren oder Worte aus Wörterbüchern enthielten.

Sie schaute schnell, ob etwas vom Tag des Satellitenstarts dabei war und tatsächlich, das war es.
Dann beendete sie die Verbindung mit Karls Computer, sie wollte nicht zu lange drin bleiben.
Sie klickte auf „Identität wechseln“, um von Tails eine neue Verkleidung zu bekommen.
Und eine Drittelsekunde später war sie im Internet jemand völlig anderes.
Nichts erinnerte mehr an die Verkleidung, mit der sie gerade in Karls Computer war.
Sie atmete durch.
Jetzt konnte sie in Ruhe die Dateien durchschauen, die sie erbeutet hatte.

Den Schlüssel des NSA-Manns hatte sie schnell entdeckt.
Er lag ganz offen bei den anderen Schlüsseln.
Aber wo passte er? Auf welche Computer außerhalb der Universität hatten Karl und der NSA-Mann an dem Tag zugegriffen? Das war die Frage.
Und nach einigem Stöbern hatte sie Spuren zu sieben Computern gefunden, davon führten vier zu anderen Universitäten.
Drei waren also übrig.
Ihre Adressen waren:

****
....
23.66.234.12

23.66.177.120

23.66.177.121
....
****

Internet-Adressen von Computern bestanden aus mit Punkten getrennten Zahlen, oft aus vier Zahlen zwischen 0 und 255.
Jeder Computer im Internet hatte eine solche Adresse, darüber konnte man sie erreichen.
Sie hatten meistens zusätzlich auch lesbare Namen, wie www.torproject.org oder www.google.com.
Aber diese hier nicht.
Und sie konnte auch nicht verfolgen, wohin Daten gingen, die sie an diese Adressen schickte.
Auf dem Weg dorthin verschwanden sie in einer dunklen Internetwolke.
Marianne hatte keine Ahnung, wo die Computer mit diesen Adressen standen, was das für Computer waren.
Sie dachte kurz nach und öffnete dann ein Chat-Programm.
Ihr Bruder war online und sie tippte die drei Adressen ein, mit drei Fragezeichen dahinter.
Sonst nichts.
Nach ein paar Sekunden war ihr Bruder verschwunden.
Ohne zu antworten.

„Hmm“, dachte sie.
„Wenn man ihn einmal braucht… Na gut.
Dann muss ich eben allein weiter kommen.“ Sie begann im Internet nach Hinweisen zu suchen.

„Pling“ klang es einige Minuten später aus dem Laptop.
Ihr Bruder war wieder online.

„BIST DU VERRÜCKT GEWORDEN?“, erschien auf Maries Bildschirm.

Marie stutzte.
Was ist jetzt los?

Paul: „WECHSLE DEINE TAILS IDENTITÄT!“

Marie klickte auf „Neue Identität“ und bekam von Tor eine neue Verkleidung.

Marianne: „Ok.“

Paul: „DU KANNST NICHT EINFACH SOLCHE ADRESSEN SCHICKEN, OHNE ZU WISSEN AN WELCHEM COMPUTER ICH GERADE SITZE!“

„Woher soll ich wissen, vor welchem Computer mein Bruder gerade sitzt?!?“ dachte Marie.
“So ein Quatsch.” Paul war immer in Tails mit Maske unterwegs, ohne Ausnahme.
Sie hatte ihm immer schreiben können, ohne zu überlegen wohin.
Sie verstand nicht.

Paul: „WO HAST DU DIE ADRESSE HER?“

Marianne platzte der Kragen: „Kannst du mal aufhören zu schreien???“

Paul: „NEIN.
KANN ICH NICHT.
WIR MÜSSEN SPRECHEN, SCHNELL, WO BIST DU?“

Jetzt fühlte sie sich endgültig wie ein kleines Mädchen.
Und das bei ihrem Bruder, bei dem sie das am Allerwenigsten erwartet hätte.

Paul: „SAG JETZT!!!“

„NIRGNDWO!!!!!!!!!!“, tippe sie in das Chatfenster und schloss es.
Dann klappte sie den Laptop zu und schaute über den Platz.

„Die Adresse!“, dachte sie.
„Er hat ‘die Adresse’ gesagt.
Es ist nur eine von den dreien.“ Sie schaute auf die Adressen.
„Es muss die erste sein!“

Je länger sie wartete, umso größer war die Wahrscheinlichkeit, dass sie nicht in den NSA-Computer hineinkommen würde.
Corinne sagte zwar, dass sie mit Karl übers Wochenende fischen gehen würde und sie kein Smartphone und kein Handy dabei haben würden, aber es gab bei der Princeton-Universität auch andere, die eingreifen konnten, wenn ihnen etwas komisch vorkam.
Sie klappte ihren Laptop auf und ging den selben Weg wie beim ersten Mal: Berlin – New York – Belo Horizonte – New Jersey, Princeton.
Sie gab Name und Passwort ein.
Wieder drin! Sie atmete kurz durch.

„Weiter!“, dachte sie und tippte:

****
....
ssh randw@23.66.234.12
....
****

Ihr Herz klopfte.
ssh, dass waren nur drei Buchstaben, aber ein Schlüssel, um andere Welten aufzuschließen.
Damit konnte man von einem zum nächsten Computer springen.
Und jetzt war sie vielleicht in einen NSA-Computer gesprungen.
„randw“ war anscheinend der Name des NSA-Manns, zumindest stand er so in den Logdateien.
Sie drückte die Enter-Taste.

****
....
*** NSA T.A.O.
SECTION 23-54 ***
* THIS COMPUTER IS FOR AUTHORIZED ACCESS ONLY.

* WARNING: UNAUTHORIZED ACCESS CAN RESULT IN FEDERAL PROSECUTION
* FOLLOWING THE ESIONAGE ACT OF 1917.
* STOP! IMMEDIATLY! IF YOU ARE IN ANY DOUBT OF YOUR AUTHORIZATION.

*** ****************************
Welcome, Randy!

randw@randy.tao.nsa.mil:~$
....
****

Sie konnte kaum atmen.
Ihr Herz schlug spürbar.
Sie war drin! In einem NSA-Computer.
Zum ersten Mal in ihrem Leben.
So leicht.
Der Schlüssel hatte funktioniert.
Wie im Trance kopierte sie sich alle Log-, Passwort- und Schlüsseldateien, dann versuchte sie so gut es geht ihre Spuren zu verwischen.
Ihre Finger saußten wie wild über die Tastatur.
Sie sagte immer, dass sie definitiv schneller tippen als denken konnte und das war hier wirklich so.
Dann loggte sich wieder aus und landete dadurch wieder auf Karls Rechner.
Alles zusammen hatte nicht mehr als 30 Sekunden gedauert.
Sie wusste nicht einmal, in welcher Stadt der Computer stand, in dem sie gerade gewesen war.
Vielleicht in Fort Meade, wo das Hauptquartier der NSA war.
Sie hatte Schweiß an den Händen.
Dann verwischte sie sorgfältig alle Spuren auf Karls Rechner, und zog den USB-Stick aus dem Computer.
Alles, was sie gesammelt hatte war jetzt auf einem kleinen Stick.
Sie umschloss ihn in ihrer Hand und lehnte sich zurück.

„Hallo Mari“, sagte eine Stimme von der Seite und ein junger Mann setzte sich neben sie.

„OSKAR!“, Marianne schaute ihn an, dann wieder weg und wieder an.
„Was machst du hier??“

Oskar war ein guter Freund von ihr und ihrem Bruders.
Er war auch ein Cypherpunk.
Von ihm hatte sie den Rechner bekommen, mit dem sie gerade bei der NSA war.
Er war, wie Paul, auch unter direkter Überwachung von mindestens zwei Regierungsstellen.
Vielleicht sogar von den Amerikanern.

„Guter Platz“, meinte Oskar während er sich umschaute, „anonymes Internet und keine Überwachungskamera, wenn man sich an die Wand drückt.“

Marianne: „Was machst du hier??? Scheiße! Mein Bruder hat dich geschickt?“

Oskar nickte.

Marianne: „Scheiße! Werde ich jetzt von meinem eigenen Bruder überwacht? Und … wie habt ihr rausgefunden wo ich bin?“

Oskar: „Es ist alles ok.
Wir haben nicht viel Zeit.
Du musst jetzt zum „The Bird“ in Kreuzberg gehen.
Setz dich dort an den freien Tisch im ersten Hinterraum und bestell zwei Hamburger.
So etwa in 20 Minuten.“

Marianne: „Einen Scheiß werde ich.
Nur weil du das sagst? Warum soll ich das tun?“

Oskar: „Ich weiß es nicht.“

Marianne schaute ihn erstaunt an.

Oskar: „Ich weiß nur, dass es um Leben und Tod geht!“

Er schaute sie ernst an.
In Marianne ließ nicht von seinen Augen ab.
Sie kämpfte mit der Wut, die in ihr hochstieg, ihr Gesicht wurde rot.
Oskar schaute ernst und ruhig zurück.

Oskar: „Geh jetzt … aber langsam.
Und geh nicht direkt, sondern kaufe vorher noch irgendetwas ein.“

Marianne stand langsam auf und schritt die Stufen hinunter, ohne sich noch einmal umzudrehen.
