== [big-number]#1913# Wilhelm

=== SZENE 1: Berlin 1913
____

Das Brandenburger Tor, angefüllt mit Menschen, Fahrrädern, Pferde-Droschken, vereinzelt Uniformierte.
/// Blende /// Seitenstraße: drei Uniformierte prügeln auf einen einfach angezogenen jungen Mann ein, beschimpfen ihn, er blutet aus der Nase, vergräbt seinen Kopf unter seinen Armen, noch ein Tritt in den Bauch /// Blende /// Eine junge Frau, die Flugblätter verteilt.
Alle Menschen, die sie trifft, nehmen eins, fangen im Weitergehen konzentriert und ernst zu lesen an /// Blende /// Eine Festwiese, angefüllt mit Tausenden von Menschen mit Plakaten, Schildern, vereinzelt Schlagstöcke.
/// Blende /// Ein Raum hinter der Bühne der Festwiese.
Man hört im Hintergrund die Menschenmenge.
Wilhelm und Hilde.

Hilde läuft aufgeregt hin und her und würdigt Wilhelm keines Blickes.

Hilde: „Es ist ein Wahnsinn!“ Sie zeigt mit beiden Armen Richtung Bühne.
“Da draußen stehen 20 000 Genossen, hungrig, müde vom Arbeiten, in Angst.
Und du willst einfach von hier verschwinden …“

Wilhelm schreit: „WILL ICH NICHT! Ich will … nicht … verschwinden! Ich will ihnen die Wahrheit sagen! Es geht nicht! Wir können es nicht schaffen! Die Gegner sind zu stark.“

Hilde: „Du willst dich aus dem Staub machen.
Du willst uns im Stich lassen! Jetzt in dieser harten Zeit.“

Wilhelm: „Nein, nochmal, das will ich nicht! Aber die Kräfte, gegen die wir stehen, sind so rücksichtslos, so brutal.
Wenn es nach ihnen geht, werden wir bald überall in Europa Leichenberge haben! Sie wollen Krieg! In ganz Europa.
So etwas war noch nie da.
Und sie wollen das!“ Er bedeckte sein Gesicht mit den Händen.“

Hilde: „Dann kümmer dich drum!! Das ist doch gerade das, was du wolltest: Für den Frieden kämpfen.
Wenn du einige unserer Genossen in einer wilden Rauferei mit einer übermächtigen Horde von Monarchisten siehst und überall Blut, dann gehst du auch nicht weg und sagst: Es geht nicht!“

Wilhelm: „Dann hole ich eine Sturmtruppe der Spartakisten.
Das kann ich nicht selbst machen.
Aber gegen die imperialistischen Mächte hilft keine Sturmtruppe.
Sie haben Geld, Waffen, ganze Regierungen, Unternehmer, die Presse und jetzt auch Geheimorganisationen, die für sie spionieren … und morden!“

Hilde: „DU bist die Sturmtruppe gegen die Imperialisten! Die schärfste und mächtigste Waffe ist das Wort.
Das hast DU mir gesagt.
Und die Genossen da draußen haben dich gerufen.
Was ist eine Sturmtruppe, die nicht kommt, wenn man sie ruft?“

Wilhelm faltet seine Arme vor der Brust und schließt die Augen.
Von draußen hört man „Wilhelm, Wilhelm“-Rufe lauter werden.
Er atmet schwer.
____
