== [big-number]#2019# Endlich mal Action!

[text-caps]#Frederik saß wie# jeden Morgen an seinem Schreibtisch im 6.
Stock des Hauptquartiers des BND, des größten deutschen Geheimdienstes.
Vor ihm lag wie immer sein Vesperpaket, ihm gegenüber saß Heinz, in seine Zeitung vertieft.
Draußen vor dem Fenster rief eine Gruppe von etwa fünfzig Demonstranten Parolen wie: „Stoppt den Überwachungswahn!“ und „BND an die Kette!“ Sie trugen T-Shirts mit Aufschriften wie „I am a Torrorist“ und „Freiheit statt Angst“ Frederik und Heinz beachteten sie nicht.

Frederik biss in einen Sandwich, aber legte ihn dann plötzlich auf den Tisch, beugte sich vor und schaute kauend auf seinen Computermonitor: „Was ist denn da los?“ Er zog seine Tastatur zu sich her und tippte etwas.
„Unsere amerikanische Kollegen … die sticht wohl der Hafer.
Boah.
Na, endlich mal Action hier!“

Heinz lugte über seine Zeitung: „Was gibt’s?“

Frederik: „Die CIA plant vier Durchsuchungsaktionen mit zwölf Polizeiautos, deutschen Polizeiautos, wohl gemerkt! Alles heute, hier in Berlin.
Wenn das mal die Presse nicht mitbekommt …“

Heinz: „Heute?“

Frederik: „Jupp.“ Er schaute auf die Uhr.
„In einer halben Stunde!“

Heinz: „Na, immerhin melden sie uns das mal.
Und wo?“

Frederik: „Sagen sie nicht.
Irgendwo in Berlin.
Wir sollen uns raushalten.
Wahrscheinlich wollen sie wieder irgendwelche Aktivisten oder Hacker erschrecken.
Nach dem Motto: Wir kommen mit deutschen Polizeiautos, nehmen dich mit, befragen dich und lassen dich wieder laufen.
Warum? Nur um dir zu zeigen, dass wir das können, damit du weißt, mit wem du es zu tun hast.
Und wenn du etwas davon erzählst, dann hast du irgendwann plötzlich einen Unfall.
Oder deine Freundin.
Oder irgendetwas anderes passiert.
Wir zeigen dir einfach mal, wer der Stärkere ist.“

Heinz grinste und nahm die Beine vom Tisch: „Ja, das wirkt.
Bisschen Respekt schadet nicht.
Na, dann werde ich mal unserem Präsidenten schreiben, damit das kein Kuddelmuddel wird.
Und dem Polizeipräsidium, Kollegen vom Verfassungsschutz, Landeskriminalamt.
Hmmm … und der Bundeskanzlerin.“ Er grinste.
„Spaaaß.
Wer muss das noch wissen? Haben wir die Autokennzeichen?“

Frederik: „Jupp.
Schicke ich dir rüber …“
