== [big-number]#2021# Endlich mal Action!

[text-caps]#Frederik saß wie# jeden Morgen an seinem Schreibtisch im 6.
Stock der Zentrale des Bundesnachrichtendienstes in Berlin, des größten deutschen Geheimdienstes.
Vor ihm lag wie immer sein Vesperpaket, das ihm seine Frau gemacht hatte, ihm gegenüber saß Heinz, in seine Zeitung vertieft.
Draußen vor dem Fenster rief eine Gruppe von etwa fünfzig Demonstranten Parolen wie: „Stoppt den Überwachungswahn!“ und „BND an die Kette!“ Sie trugen T-Shirts mit Aufschriften wie „I am a Torrorist“ und „Freiheit statt Angst“. Frederik und Heinz beachteten sie nicht.

Frederik biss in einen Sandwich, aber legte ihn dann plötzlich auf den Tisch, beugte sich vor und schaute kauend auf seinen Computermonitor: „Was ist denn da los?“ Er zog seine Tastatur zu sich her und tippte etwas.
„Unsere amerikanischen Kollegen … die sticht wohl der Hafer.
Boah.
Na, endlich mal Action hier!“

Heinz lugte über seine Zeitung: „Was gibt’s?“

Frederik: „Die CIA plant vier Durchsuchungsaktionen mit zwölf Polizeiautos, deutschen Polizeiautos! Alles heute, hier in Berlin.
Wenn das mal die Presse nicht mitbekommt …“

Heinz: „Heute?“

Frederik: „Jupp.“ Er schaute auf die Uhr.
„In einer halben Stunde!“

Heinz: „Na, immerhin sagen sie uns das mal vorher.
Und wo?“

Frederik: „Sagen sie nicht.
Irgendwo in Berlin.
Wir sollen uns raushalten.
Wahrscheinlich wollen sie einfach mal wieder irgendwelche Aktivisten oder Hacker erschrecken.
Nach dem Motto: Wir kommen mit deutschen Polizeiautos, nehmen dich mit, befragen dich und lassen dich wieder laufen.
Warum? Nur um dir zu zeigen, dass wir das können, damit du weißt, mit wem du es zu tun hast.
Und wenn du etwas davon erzählst, dann wird deine Freundin irgendwann plötzlich einen Unfall haben.
Wir zeigen dir einfach mal, wer der Stärkere ist.“

Heinz grinste und nahm die Beine vom Tisch: „Bisschen Respekt schadet nicht.
Na, dann werde ich das mal intern weiterleiten, damit das kein Kuddelmuddel wird.
Und dem Polizeipräsidium melden, den werten Kollegen vom Verfassungsschutz, Landeskriminalamt.
Hmmm … und der Bundeskanzlerin.“ Er grinste.
„Spaaaß.
Wer muss das noch wissen? Haben wir die Autokennzeichen?“

Frederik: „Jupp.
Schicke ich dir rüber …“
