== [big-number]#2019# Auf dem Heimweg

[text-caps]#Marianne trottete neben# Paul her.
Er hatte seit dem Treffen im The Bird kein Wort mehr gesagt.
Er war wie in sich versunken, abwesend.

Marianne: „Wie habt ihr mich eigentlich gefunden?“

Paul antwortete ohne sie anzuschauen: „Über die Ü-Kamera-Datenbank vom BND.
Ich wusste ziemlich genau, wann du zu Hause los bist und was du an hattest und dann haben wir deinen Weg verfolgt.“

Marianne: „Mit Überwachungskameras? Du? Scheiße! Ich dachte du bist ein Cypherpunk.“

Paul drehte sich zu ihr: „Du hast keine Ahnung, um was es geht“, flüsterte er.
„Wir waren vor drei Wochen auch drin in genau der gleichen NSA-Abteilung, da, wo der Rechner steht, in dem du drin warst.
Wir haben Jahre gebraucht, um dahin zu kommen.
Da passiert gerade etwas ziemlich Spannendes.
Irgendetwas mit Spionage-Satelliten.
Ich habe bei der letzten Tour den Rechner gesehen, auf dem du warst, aber ich konnte nicht rein.
Deswegen kannte ich die Adresse, die du mir geschickt hast.
Bei der letzten Aktion sind wir wahrscheinlich aufgeflogen.
Nein, ich bin sicher, wir sind aufgeflogen.
Und jetzt sehr unter ständiger Bewachung.
Es passieren jede Menge seltsamer Dinge in den letzten Wochen.
Der einzige Rechner, dem ich noch vertraue, ist der hier in meinem Rucksack, den ich nur bei uns zu Hause im Keller benutze.“

Ein Polizeiwagen fuhr langsam an ihnen vorbei und hielt dann mitten auf der Straße.
Zwei Polizisten und ein Mann in einem schwarzen Anzug stiegen aus.
Der Anzugmann kam ruhig auf Paul zu, lächelte warm und zeigte ihm seinen Ausweis: „Paul Lasser?“

Paul nickte.
Der Mann gab ihm ein Tablet.
Paul nahm es schaute darauf.

Anzugmann: „Wir brauchen Ihre Hilfe.
Damit.“ Paul schloss sein Augen, drehte sich nach einer Weile kurz um und schaute Marie an, dann wieder den Anzugmann.

Anzugmann: „Kommen Sie mit?“ Er warf ihm einen vertrauensvollen Blick zu.
Einer der Polizisten hielt die hintere Türe auf.
Paul warf Marianne noch einen kurzen Blick zu, bedeutete ihr, dass das in Ordnung ist, und stieg ein.
Die Türen klappten zu und der Polizeiwagen fuhr davon.

Wie angewurzelt stand Marianne eine Zeit lang auf der Stelle.
„Die Nummer“, schoss es ihr durch den Kopf.
„Wie war die Auto-Nummer?“ Sie hatte versucht, sie sich zu merken, war aber dann durch Pauls Blick abgelenkt worden.
„B 4521 … 2 oder 3“ Sie setzte sich an den Straßenrand.
„Was war jetzt wichtig? Was konnte sie tun?“ Sie versuchte zu denken.

„Warum ist er eingestiegen? Wohin bringen sie ihn?” Die wichtigste Frage war ihr nicht eingefallen.
Sie hätte einfach die Polizisten fragen können.
Müssen! Nein, sie war einfach stehen geblieben und hatte nur geschaut.
Warum? Wie die Schlange vor dem Kaninchen.
Was war los? Was war mit Paul los? Was hatte er auf dem Tablet gelesen?

„Corinne!“ dachte sie.
„Ich muss mit ihr sprechen.
Vielleicht ist sie online.
Wedding, Rathaus.“ Marianne liebte die Rathäuser in Berlin, weil sie fast alle Freifunk-Internet hatten, also solches, wo man ohne Passwort hineinkam und die eigene Adresse nicht gespeichert wurde.
Ein sogenanntes Mesh-Netzwerk war ein wichtiger Baustein, um irgendwann wieder freies Internet zu bekommen.
Und alle Rathäuser hatten auch irgendwo einen Platz ohne Videoüberwachung.
Sie überlegte kurz, ob sie sich einen neuen Rechner holen sollte, aber entschied sich, direkt dorthin zu gehen.