== [big-number]#2019# Verrat

[text-caps]#Marianne saß im Schatten# an eine Mauer vor dem Weddinger Rathaus gelehnt.

„Hi Cori“, tippte sie in ihr Chatprogramm und stoppte: „Shit, Cori hat ja gar kein Handy dabei. Ich kann sie gar nicht erreichen.“ Sie lehnte sich zurück und dachte nach. Das Chatprogramm plingte, Corinne war da.

Corinne: „Hi Mari. Gut, dich zu lesen. Ich hätte auch gleich versucht, dich zu erreichen. Es ist so schlimm. Alles so schlimm!“

Marianne: „Was ist passiert?“

Corinne: „Mist, ich kann nicht wirklich sagen, was vorhin passiert ist. Aber ich muss es dir erzählen. Früh morgens haben zwei FBI-Leute geklingelt, Karli war gerade aufgestanden. Sie haben Karli gesagt, dass sie ein paar Fragen hätten und er für zwei Stunden mitkommen sollte. Und er hat es getan! Einfach so. Alles war so freundlich und ruhig. Er ist mitgefahren. Und ich stand einfach so daneben und habe zugeschaut. Jetzt weiß ich nicht einmal wo er ist. Sie haben mir nicht gesagt, wo sie ihn hinbringen. Ich habe nichts gefragt.“

Marianne fuhr ein Schauer den Rücken hinunter.

Nach einiger Zeit tippe sie: „Shit. Genauso ist es bei mir?“

Corinne: „Wie? Genauso? Das geht doch gar nicht.“

Marianne: „Sie haben Paul mitgenommen.“

Corinne: „Deinen Bruder?“

Marianne: „Sie haben mit einem Polizeiauto neben uns angehalten und ihn gebeten zu folgen. Ich bin einfach so da gestanden. Ich habe nichts gemacht, nichts gefragt. Sie haben ihm irgendetwas auf einem Tablet gezeigt. Dann ist er eingestiegen. Es war so absurd.“

Corinne: „Wow … wow.“

Corinne: „Was hat das zu bedeuten?“

Corinne: „Das ist kein Zufall.“

Corinne: „Ich glaube, …, ich will es nicht wissen …“

Marianne: „Es war koordiniert. Von Amerika nach Berlin. Scheiße!“

Corinne: „Aber wie? Paul und Karl kannten sich gar nicht, es gibt keine Berührungspunkte. Wie ist die Verbindung? Oder … oder … hast du? … Hast du Paul von Karl und mir erzählt??“

Marianne: „Nein, nein, nein. Paul weiß nichts über Karl und er weiß nichts über dich. Aber er hat mir gesagt, dass er vor ein paar Wochen in ein Computer-System bei der NSA eingedrungen ist. Ich glaube das war genau Karlis Projekt. Reiner Zufall. Und dabei wurde er wahrscheinlich erwischt.“

Corinne: „Ok. Puhh. Aber das erklärt nicht, dass sie Karli verdächtigen. Es arbeiten ein Haufen Leute an seinem Projekt. Ein Hacker aus Berlin kommt da hinein und dann wird Karli mitgenommen. Es muss irgendetwas geben, was Karli verdächtig macht. Ich meine, er hat absolut nichts gehackt seit er in dem Projekt dabei ist, hat er mir gesagt. Er meinte, das sei zu gefährlich, weil er ständig überwacht würde. Er hatte Angst. Echt Angst. Er hat sich ja nicht einmal getraut, den NSA-Schlüssel von seinem Computer zu nehmen. Und jetzt nehmen sie ihn einfach so mit …“

Marianne: „Bevor das passiert ist, war mein Bruder sehr aufgeregt. Das ist total ungewöhnlich bei ihm. Ich habe das so noch nie erlebt. Ich glaube, das ist passiert nachdem ich ihm drei Internet-Adressen geschickt habe. Die Adressen hatte ich auf Karlis Computer gefunden. Ich habe sie nur geschickt, damit er sie prüft, und mir vielleicht einen Hinweis geben kann. Ich habe ihm nicht gesagt, woher sie sind. Ich habe meinem Bruder nichts sonst erzählt, nur die Adressen, ich wollte ihn nicht dabei haben, weil ich nichts über dich erzählen wollte.“

Corinne: „Internet-Addressen von Karlis Computer?“

Marianne: „Ja. Entschuldige. Ich weiß, es war gegen unsere Abmachung.“

Corinne: „NSA-Adressen? TAO-Adressen?“

Marianne: „Wahrscheinlich. Sehr wahrscheinlich.“

Corinne und Marianne schwiegen für eine Weile.

Corinne: „Wir hatten doch ausgemacht: Wir sagen anderen nichts voneinander, nichts. Karli wusste nichts von dir. Gar nichts.“

Marianne: „Ja, ich dachte … ich wollte …“

Corinne: „Ich muss weg. Ich melde mich.“

Corinne war offline und Marianne schaute auf das Chatfenster, lange, ohne wirklich über etwas zu denken. Nach einer Weile sagte sie leise:

„Shit, shit, shit, shit.“ Sie legte die Hände ins Gesicht und fing an zu weinen.