== [big-number]#2064# Marlene Farras

[text-caps]#Marlene Farras betrat# die kleine Schulbühne des Versammlungshauses, das auf einem Hügel am Rande des Schulgeländes lag.
Draußen war ein milder Abend, leichter Wind.
Die Sonne war gerade untergegangen.
Marlene ging leicht gebeugt, ein wenig hinkend, aber schwungvoll und setzte sich auf das große Sofa in der Mitte der Bühne.
Ihre Augen leuchteten.
Sie schaute in die Runde der etwa hundert klatschenden Kinder und Jugendlichen.
Einige johlten.
Rechts neben ihr saß Lilly in einem Sessel und lächelte Marlene an.
Sie lächelte warm zurück.
Lasse und Sigur saßen in der ersten Reihe direkt vor der Bühne.

Edgar, ein Lehrer mit sportlicher Figur, hochgekrempelten Ärmeln und einer sonnigen Ausstrahlung, betrat die Bühne und nahm das Mikrofon:

„Willkommen, Marlene Farras!“ Der Beifall wurde lauter.
Er drehte sich zu Marlene und wartete bis es ruhiger wurde: „Ich freue mich, dass du hier bist.
Ich freue mich, dass du überhaupt noch auf der Erde bist.
Es war ja in deinem Leben nicht nur einmal ziemlich knapp.
Wie lebt man 14 Jahre mit einem entfesselten Geheimdienst im Nacken, dem größten Geheimdienst der Welt, auf der Liste seiner Top-Ziele?“

Er wandte sich zu den Zuschauern: „Früher, Anfang dieses Jahrhunderts, gab es viele Geheimdienste.
Und die Geschichten sind wahr.
Sie haben wirklich Menschen gesucht, überwacht, eingesperrt, verhört, manchmal sogar gefoltert und getötet.
Das waren äußerst gefährliche Einrichtungen.
Nach außen in erschienen sie als legal.
Heute gibt es sie nicht mehr.
Aus den Geheimdiensten von damals sind unsere Informationsdienste geworden, über die wir alle alles Mögliche darüber erfahren können, wie Menschen in allen Ländern der Erde zusammen arbeiten, was sie zusammen entscheiden, wer was besonders gut kann und was die Menschen überall auf der Erde zum Leben und Arbeiten brauchen.
Manchmal verwenden sie dabei sogar Nachfolger von Computerprogrammen, die früher zur Menschenjagd und zur Kontrolle des Privatlebens auf dieser Erde verwendet wurden.
Diese Menschenjagd und die Kontrolle von Allem und Jedem ist heute, Gott sei Dank, Vergangenheit.
Ihr lernt über diese alten Geheimdienste nur noch im Geschichtsunterricht, das heißt konkret in euerm Fall, im Wesentlichen durch TRON, denn dafür ist TRON ursprünglich gemacht worden: um euch den Befreiungskampf des Internets zu zeigen.“

Lasse und Sigur schauten sich an und dann zu Lilly.
Die lächelte zurück und zwinkerte mit den Augen.

Edgar trat nach vorne und setzte sich zu den Schülern gewandt an die Bühnenkante, gleichzeitig verdunkelte sich das Licht etwas.
Er wurde im Ton ruhiger: „In dieser Welt damals, die so anders war als unsere heutige, war es normal, dass Menschen versuchten, über das Leben anderer Menschen zu bestimmen, sie zu kontrollieren.
Viele meinten, dass es nicht anders ginge, weil es so viel Egoismus, so viele Verbrecher und schlechte Menschen gäbe.
Vielen war es sogar Recht, dass Staaten ihre Bürger durchleuchteten.
Die meisten hielten es für normal, dass Armeen ihre Soldaten überwachten, Unternehmen ihre Mitarbeiter, und sogar die Lehrer ihre Schüler und die Eltern ihre Kinder: ob sie zur Schule gingen, ob sie das gelernt hatten, was sie lernen sollten und ob sie etwas besser oder schlechter machten als die anderen Schüler, wie viel sie am Computer spielten, alles Mögliche.
Kontrolle und Überwachung waren damals überall verbreitet.

Es gab auch überall Streit.
Zwischen Ländern, Unternehmen, politischen Parteien, aber auch in Schulen, Familien, überall.
Das war völlig normal.
Deswegen hielten Menschen Dinge geheim, zeigten nicht wie sie wirklich waren, was sie wirklich dachten.
Entweder um einem Streit aus dem Weg zu gehen oder um einen Vorteil gegenüber anderen zu haben.
Es wurden auch immer mehr Dinge geheimgehalten, die für Menschen lebenswichtig waren, die sie hätten wissen müssen.
Das Verschweigen ging hinauf bis in die Weltpolitik und die großen Unternehmen.
Da war es sogar am schlimmsten.
Umweltkatastrophen wurden verschwiegen, Kriege, die Überwachung und am Ende kam es so weit, dass in der Welt die schlimmsten Dinge passierten konnten, und fast niemand davon erfuhr.

Das war das Arbeitsfeld der Cypherpunks.
Sie waren nicht nur Programmierer, die Verschlüsselungsprogramme schrieben und im Internet Schwachstellen suchten und ausbesserten.
Sie waren auch Hacker.
Es ging ihnen um viel mehr.
Es ging ihnen um eine neue Welt, eine neue Form des Zusammenlebens, es ging darum, einen Weg zu finden, dass alle Menschen leben können, wie sie sind, nach ihren eigenen Vorstellungen.
Es ging darum, dass sich niemand mehr für irgendjemand Anderen verbiegen muss.
Es ging um eine Welt, in der es immer weniger Angst und Zwang und Lügen gibt.

Und obwohl es lange Zeit überhaupt nicht danach aussah, wurde der Weg in diese neue Welt gefunden.
Viele Menschen hatten das damals für unmöglich gehalten, obwohl die meisten lieber in so einer Welt gelebt hätten.
Die Kräfte, die dem im Wege standen, die Kräfte, die ihr in TRON ausprobiert, nachspielt, sie schienen übermächtig zu sein.
Was hätte man gegen die Riesenarmeen, Riesenunternehmen und mächtigen Regierungen ausrichten können?
Aber alles, was man will, ist möglich.
Und so wurde auch dieser Weg gefunden.
Und zwar vor allem von Kindern und Jugendlichen wie euch.“
