== [big-number]#2019# Wir holen sie nicht!

In der Zentrale des BND in Berlin.

[text-caps]#„Wir holen sie nicht.# Basta!“ brüllte Frederik seinen Kollegen Heinz über den Schreibtisch hinweg an.

„Sie und Paul Lasser haben sich gleich nach dem Einbruch getroffen.
Das ist kein Zufall.
Sie muss etwas wissen“, antwortete Heinz etwas zornig, aber noch ruhig.

Frederik: „Vielleicht weiß sie etwas davon.
Vielleicht ahnt sie auch nur.
Verstehen tut sie auf jeden Fall, was ihr Bruder macht.
Ich habe sie im letzten Jahr hier bei einem Hackathon erlebt.
Da hat sie gezeigt, was sie kann … Vielleicht hat sie ihm sogar die Internet-Adresse gegeben.
Wer weiß.
Aber auch wenn dem so wäre: Wir holen sie nicht.“ Er schaute Heinz ernst an.
„Ich meine das ernst.
Das ist eine dienstliche Anweisung.“

Heinz schluckte.
„Wir sollten nichts unversucht lassen, wenn wir herausfinden wollen, was sie mit den Adressen vor hatten …“

Frederik: „Schluss damit! Du verstehst es nicht.
Es geht nicht immer nur darum, herauszufinden, was läuft.
Das ist genau hier sogar nebensächlich.
Es geht um mehr.
Diese Lasser hängt da mit ihrem Herz drin.
Sie ist infiziert von ihrem Bruder.
Und darum geht es hier: Um eine Infektion, einen Tumor.
Und den muss man behandeln, bevor er weiter wächst.
Einerseits muss der natürlich raus.
Aber andererseits soll er dann auch nicht mehr wieder kommen.
Und das heißt, es geht nicht nur darum, so viel herauszuschneiden, wie nötig ist.
Sondern die ganze Umgebung so zu behandeln, dass da nichts mehr wächst.
Nur dann haben wir eine Chance, dass das aufhört.
Und dafür können wir die Lasser gut einsetzen.“

Heinz: „Hey, Frederik, langsam.
Das sind Menschen, kein Krebsgeschwür.“

Frederik: „Ja, ist ja nur ein Bild.
Ich meine das nicht so hart.
Du kennst mich.
Aber was würde das Ganze bringen, wenn die Lasser da weiter macht, wo ihr Bruder aufgehört hat.
Das Talent dafür hat sie.
Auch Talent anonym zu bleiben.
Ich habe schon einmal im Tor-Netzwerk nach ihr gesucht, mit Hilfe von ein paar Jungs von der NSA.
Wir hatten damals ziemlich viele Computer im Einsatz, um ihre Spuren zu finden, einige tausend, nur für sie.
Aber wir haben nichts entdeckt.
Nichts.
Sie macht das sehr geschickt.

Und jetzt haben wir sie in der Ecke! Ihr Bruder ist weg, sie sucht nach ihm.
Es fehlt nicht viel, noch ein paar richtig schlechte Nachrichten, ein paar Aktionen in ihrem Umfeld und sie lässt das Hacken für alle Zeiten.
Und alle um sie herum werden das sehen, sie werden sie für paranoid oder für schizophren halten und irgendwann wird sie das auch wirklich sein.
Und dann erst ist wirklich Ruhe.
Ihre ganze Umgebung muss denken, dass man verrückt sein muss, wenn man sich mit uns anlegt.
Das ist mehr wert, als eine weitere Hackerin im Gefängnis, die vielleicht dort gleich neue Pläne schmiedet.
Oder schlimmer, wie Edward Snowden oder Julian Assange … Besser ein Mensch macht eine schwierige Zeit durch, als dass alles in Brand gerät.“

Heinz: „Komm mal, rüber“.
Er zeigte auf seinen Bildschirm.
„Guck, die Jungs von der NSA.
Du glaubst es nicht.
Marianne Lasser hatte gerade Chat-Kontakt … mit der Freundin von … Karl.
Karl, du weißt, der Satelliten-Mann aus Virginia.
Heiße Sache.“

Frederik nickte: „Wow.
Wie ging das? Dann müssen wir auch noch Karls Freundin auf die Liste setzen.
Oder vielleicht auch nicht.
Ich denke, die Amerikaner kümmern sich gut drum.
Aber wirklich seltsam: Wie sind die beiden zusammen gekommen?“

Heinz: „Bisher keine Spur davon.
Wir könnten Marianne Lasser fragen … Sollen wir sie nicht doch …“

Frederik: „NEIN! Sie bleibt da, wo sie ist.
Ich werde noch einmal die Tails-Aktivitäten im Internet durchsuchen lassen, auf Chat-Verbindungen zwischen New Jersey und Berlin.
Vielleicht finden wir etwas.“
