== [big-number]#2021# Allein

[text-caps]#Marlene lag auf# dem Bett im Keller-Schlafraum ihres Bruders.
Der Raum war funksicher verkleidet, das Stromnetz gefiltert.
Zudem hatte ihr Bruder einen kleinen Toilettenraum eingebaut, einen Kühlschrank und auch sonst noch einige Veränderungen vorgenommen.
Neben dem Bett stand ein Schreibtisch mit zwei großen Computermonitoren.

Marlene hatte seit drei Tagen nichts von Corinne gehört.
Drei lange Tage.
Sie hatte fast die ganze Zeit in Marwins Keller verbracht.
Corinnes Chat-Konto war stumm geblieben.
Vielleicht konnte sie es nicht mehr nutzen, vielleicht war es ihr zu gefährlich, vielleicht wollte sie einfach nicht mehr mit ihr reden.
Es war ein Verrat an ihrer Freundschaft gewesen, aber wie hätte sie wissen können, dass die Adressen so brisant waren.

Alle in ihrer Familie hatten von ihrem Bruder in der Zwischenzeit eine E-Mail bekommen.
Darin stand, dass es ihm gut ging.
Und sie war mit seinem persönlichen Schlüssel digital unterschrieben.
Keiner in Marlenes Umfeld zweifelte an seiner Echtheit.
Er schrieb, dass er für eine Weile verschwinden würde, in der Welt herumreisen, dass er Zeit bräuchte zum Nachdenken, zum Überdenken von allem, was er getan hatte.
Und er wollte einfach so gehen, ohne großen Abschiedstrara, es war ihm alles zu viel gewesen.
Einfach Abstand haben von allem Alten und vor allem vom Hacken.
Vor allem die BND-Sache war ihm zu stressig geworden.

Und tatsächlich fehlten in seinem Zimmer ein Koffer und einige seiner Sachen.
Er schrieb kein Wort von Polizei oder wer ihn auch immer in dem Auto abgeholt hatte.
Marlene hatte die E-Mail hundert Mal gelesen.
Um irgendeinen versteckten Hinweis zu finden.
Am Schluss hatte sie so sehr Bauchschmerzen gehabt, dass sie sie gelöscht hatte.
Das hatte nicht ihr Bruder geschrieben! So viel war ihr klar.
So einen Quatsch würde er nicht schreiben und auch nicht einfach so gehen.
Sein Schlüssel hing neben der Garderobe, als ob er zu Hause wäre.
Jemand anderes musste ihn wieder dort hingehängt haben, und auch die Sachen geholt.
Ihr lief ein Schauer über den Rücken.
Es war ihr vorher schon klar gewesen.
Sie kommen in die Wohnungen.
Du bist nirgends sicher.
Ihr Bruder hatte ihr das gesagt.
Aber es war etwas völlig anderes, wenn es tatsächlich passierte.

Niemand glaubte ihr.
Nicht, dass jemand den Schlüssel hingehängt und seine Sachen mitgenommen hatte und nicht das mit dem Auto, das am hellen Tag angehalten hatte.
Alle Polizeistationen Berlins meinten, dass keines ihrer Autos zu der Zeit in dieser Straße war.
Und das Auto mit dem Kennzeichen, das sich Marlene gemerkt hatte, war zur gleichen Zeit bei einem Feuerwehreinsatz in einem anderen Stadtteil.
Am Schluss glaubten sie ihr nicht einmal, dass sie an dem Tag mit ihm zusammen nach Hause gelaufen war.
Es war so gespenstisch.
In ihrem Kopf drehten sich die ganzen Fragen immer im Kreis: Wo war Marwin? Wie ging es ihm?Was hatten sie mit ihm gemacht? Was machten sie gerade mit ihm? War er überhaupt noch am Leben? Und sie hatte niemanden, mit dem sie sprechen konnte.

Alle anderen, ihre Eltern und ihr Onkel, Nachbarn, machten sich überhaupt keine Sorgen.
Sie waren sogar ein wenig sauer auf Marwin, dass er einfach so gegangen war.
Aber dass er jetzt vielleicht eine grauenhafte Zeit durchmachte? Marlene musste immer wieder weinen.
Weinen war das einzige, was sie gerade wieder losbrachte, wenn sie sich festgefahren hatte.
Weinen und die Geschichte von Hilde aus dem ersten Weltkrieg.
Warum glaubte ihr niemand? Wie gut muss man jemanden kennen, dass man ihm auch in so einer Lage vertrauen kann? Ihr Bruder hätte ihr vertraut.
Todsicher.
Aber die eigenen Eltern? Nicht? Sie hatten eine Psychologin geholt, Marlene hatte mit ihr gesprochen, ganz in der Hoffnung, dass sie merkt, dass mit ihr alles in Ordnung war.
Aber die hatte am Schluss gemeint, dass Marlene ein posttraumatisches Stresssyndrom wegen des Verlustes des Bruders hätte.
Sie würde die Realität so verändern, dass es zu ihrem Bild von ihrem Bruder passte, anstatt das wirkliche Bild von ihrem Bruder anzunehmen.

Marwin war weg.
Das war schlimm.
Aber schlimmer war noch, was jetzt mit Marwin war.
Und mit Corinne…

„Pling“, sagte ihr Chatprogramm.

„Hi Mari! Alles gut bei dir?“, erschien auf dem Bildschirm.

„Corinne!“, rief Marlene und starrte gebannt auf ihren Laptop.
