== [big-number]#2021# Eine Freundin?

[text-caps]#Marlene überlegte,# was sie Corinne schreiben sollte, was sie schreiben konnte.
War die Verbindung sicher? Von ihrer Seite aus, sehr wahrscheinlich, obwohl der Geheimdienst sicher buchstäblich draußen im Kabelverteiler saß.
Mindestens für zehn, fünfzehn Minuten war sie sicher.
Aber bei Corinne? Wie sicher war es bei ihr? Wusste sie, auf was sie schauen musste?

Corinne schrieb: „Hej Mari, ich war die letzten drei Tage abgetaucht.
Entschuldige.
Ich habe es nicht mehr ausgehalten.
Ich habe das gebraucht.
Ich habe immer noch keine Nachricht von Karli.“

Marlene: „Nichts? Gar nichts?“

Corinne: „Nein.
Ich habe keine Polizeistation gefunden, die irgendetwas über ihn wusste.
Und ich habe die ganze Stadt abgesucht.
Alle Plätze, wo er sonst war.
Er ist einfach verschwunden.
Aber das ist noch nicht einmal alles.
Ich war bei ihm an der Uni und die sagen dort, dass er auf Geschäftsreise in Europa sei.
Eine sehr dringende, geheime Mission.
Das hätte mit seinem Projekt zu tun.“

Marlene: „Was?!“

Corinne: „Ein absoluter Humbug.
Er hätte mir etwas gesagt.
Er geht doch nicht nach Europa, ohne mir ein Wort zu sagen.
Aber an der Uni haben sie mir angedeutet, dass es in unserer Beziehung ja eh kriseln würde.
Und er vielleicht deshalb nichts erzählt hatte.
Ich weiß nicht wie sie darauf kommen.
Es ist echt schlecht hier.
Niemand glaubt mir.“

Marlene: „Shit.
Wie können die Geheimdienst-Leute das machen? Wie können die alle dazu bringen, ihre Geschichte zu glauben und nicht deine? Kennst du dort wirklich niemanden gut genug, dass du ihn fragen kannst, was wirklich vor sich geht?“

Corinne: „Ich dachte, ich hätte ein oder zwei Freunde.
Aber es glauben wirklich alle die Geschichte von Karli auf Europareise.
Und ich sehe aus, als wäre ich verrückt, oder so etwas.“

Marlene: „Aber von einer Reise muss er ja irgendwann wiederkommen.“

Corinne: „Vielleicht in einem Sarg?“

Marlene schluckte: „In einem Sarg?“

Corinne: „Du weißt nie, was sie alles machen, damit die Wahrheit nicht ans Licht kommt.
Glaub mir, die tun alles, wenn sie sicher sind, dass es verborgen bleibt, wenn die Öffentlichkeit nichts davon mitbekommt.
Die Wahrheit ist die gefährlichste Sache der Welt.
Du brauchst eine Armee von Lügen, um sie zu schützen …“

„JAH!“, schrieb Marlene.

Corinne: „Was ist mit deinem Bruder? Und mit deinen Eltern?“

Marlene: „Genau wie bei dir.
Keiner glaubt mir.
Es kam eine E-Mail.
Sie glauben, dass er um die Welt reist, um sein Leben zu überdenken, um sich selbst zu finden oder einfach nur um Spaß zu haben.
Totale Scheiße.
Es fühlt sich so mies an, wenn einen niemand ernst nimmt.
Ich versuche alles, um ein wenig Logik in die Leute in meiner Umgebung zu bringen.
Das heißt, ich habe es versucht, ich habe damit aufgehört.
Es hat keinen Zweck.
Sonst werde ich wirklich langsam verrückt.“

Corinne: „Pass auf, dass das nicht passiert.
Du darfst nicht verrückt werden.
Wir kommen da durch.
Zusammen.“

Marlene: „;-)“

Corinne: „Was ist eigentlich mit den Daten von Karlis Computer? Hast du damit etwas anfangen können? Hast du den NSA-Schlüssel gefunden?“

Marlene lehnte sich zurück und atmete durch.
Was war das jetzt? Sie hatte den USB-Stick mit den NSA Daten die ganze Zeit über nicht angefasst.
Sie wusste nicht, was sie hatte oder nicht hatte.
Es war für sie jetzt einfach nicht wichtig.
Ihr Bruder war weg, ihre Eltern verdreht, der deutsche Geheimdienst hinter ihr her.
Vielleicht auch ein amerikanischer.
Sie hatte andere Probleme.
Ja, der USB-Stick.
Sie griff in ihre Hosentasche und umfasste ihn.
Was konnte sie jetzt zu Corinne sagen? Lügen ist keine Option.
Nie.
Lügen, das macht die andere Seite.
Es war, als würde Marwin neben ihr stehen und ihr das ins Ohr flüstern.

Corinne: „Es war schon ein bisschen aus heiterem Himmel.
Plötzlich werden sie so wild.
Schicken falsche Polizeiautos los und was sonst noch alles.
Es muss doch etwas passiert sein, was das ausgelöst hat? Du hast etwas gemacht? Oder nicht?“

Marlene legte ihr Gesicht in ihre Hände und dachte intensiv nach.

Corinne: „Vielleicht geht es für Karl und Marwin jetzt um ihr Leben.
Deswegen will ich jetzt wirklich wissen, was Sache ist.
Was hast du an diesem Tag gemacht, als die beiden geholt wurden?“

Marlene: „Ich bin zuerst in Karlis Computer gegangen und habe mir dort alle Schlüssel und Logs und Passwort-Dateien geholt.
Ich habe den NSA-Schlüssel gefunden, zusammen mit Adressen von drei Computern, wo er passen könnte.
Die habe ich meinem Bruder geschickt.
Das weißt du.“

Corinne: „Und was hast du dann gemacht?“

Marlenes Herz fing an zu klopfen.
Gedanken sausten durch ihren Kopf.
„War das Corinne? War sie es wirklich? Sie schrieb anders als sonst.
Es fühlte sich nicht an wie Corinne.
Gut, sie war auch in einer anderen Lage als sonst.
Was konnten sie wissen bei der NSA? Von meinem Ausflug auf den NSA-Computer wussten sie sicherlich.
Es waren nur 30 Sekunden, aber das reicht.
Vielleicht wussten sie nicht, dass ich es gewesen bin.
Ja, klar.
Sonst wäre ich nicht mehr hier und frei.
Vielleicht habe ich die Spuren auf Karls Rechner gut genug verwischt.
Der NSA-Schlüssel war nicht mehr auf dem Computer.
Vielleicht wussten sie nicht einmal von dem Schlüssel.
Es gibt nur die Kopie davon auf meinem Stick.
Vielleicht hat Corinne ihnen davon erzählt.
Shit.
Was jetzt tun? Was würde Marwin tun? Nicht aufgeben, nicht zurückziehen.
Bei Geheimdiensten würden so viele Schnarchnasen und Langweiler arbeiten.
Ihre tatsächlichen Fähigkeiten würden weit überschätzt.
Andererseits hatte er gerade an dem Tag auch furchtbar viel Angst vor ihnen gehabt.
Die TAO-Abteilung der NSA.
Sie bekam kein klaren Bild.

Marlene: „Ich war auf dem NSA-Computer.
Für eine ganz kurze Zeit.
Ich habe mich nur einmal umgeschaut, ein paar Logdateien geholt, nichts Spezielles.“

Corinne: „Wow.
Wow.
Das war es.
Dein Bruder stand unter Überwachung und dann kam ein Angriff aus Berlin, von Karlis Rechner aus.
Ja, klar.
Dann werden sie wild.“

Marlene: „Ich war anonym dort.
Ich hatte eine Tails-Verkleidung.
Niemand weiß, dass der Angriff aus Berlin kam.“

Corinne: „Du weißt, dass die NSA als einziger Geheimdienst der Welt einzelne Leute aus Tails herausholen kann.
Sie durchsuchen dafür für ein bestimmtes Ereignis fast das ganze Internet – in Minuten.
Und dann können sie sagen, der Computer, über den gerade auf den NSA-Rechner zugegriffen wurde, der steht in Berlin.“

Marlene: „Ja, ich weiß.
Deswegen hat man ja manchmal nur 10-15 Minuten.“

Corinne: „Hast du Logs von dem Besuch?“

Marlene erschrak.
Warum wollte Corinne jetzt etwas über die Logs wissen? Das war nicht ihre Art und nicht ihre Sprache.

Marlene: „Ich fühle mich nicht danach, jetzt darüber zu reden.
Ich habe die letzten Tage nicht an die Daten gedacht und habe es in der nächsten Zeit auch nicht vor.“

Corinne: „Ich will es aber wissen.
Ich will wissen, was Karli passiert ist.
Verstehst du das?“

Marlene dachte nach.

Corinne: „Ich bin hier, allein, ohne Freunde, ohne jemanden, mit dem ich reden kann.
Die einzige Freundin, die ich habe, sagt mir, dass sie nicht mit mir sprechen will.“

Marlene schaute gebannt auf das Chatfenster.

Corinne: „Sag was! Ich habe ein Recht das zu erfahren.
Du …“

Marlene klickte das Fenster weg und zog den Tails-Stick aus dem Computer.
