== [big-number]#2064# Elf Grundgedanken

[text-caps]#Marlene: „Die elf Grundgedanken# haben uns geholfen, immer besser zu verstehen, wie man sich aus der Umklammerung durch übermächtige Gegner lösen kann, wie man sich frei bewegen und kommunizieren kann, auch wenn es Leute gibt, die das verhindern wollen.
Egal, ob diese Leute für riesige Geheimdienste arbeiten, in schwer bewaffneten Armeen oder in großen und reichen Unternehmen.
Es gibt Dinge, die stärker sind als all das.
Und das haben die Cypherpunks gesucht und ausprobiert, so haben sie mitgeholfen, den Krieg vor jetzt über 30 Jahren zu beenden.

Die Grundgedanken sind wie ein Werkzeugkasten.
Ich werde die einzelnen jetzt nur andeuten.
In der Akademie könnt ihr sie genauer kennen lernen, da könnt ihr sie auch üben.
Da werdet ihr sie brauchen.
Ohne werdet ihr nicht durchkommen.

Den ersten Gedanken habe ich euch schon gesagt: Verschlüsselung, freie und offene Software, verteilte Computer.
Das hat uns immer wieder unsere persönliche Freiheit gerettet.
Das ist die Grundlage.
Noch vor 50 Jahren haben viele Menschen nicht verstanden, welche große Bedeutung diese drei Dinge haben, dass ohne sie gar nichts geht.
Dass man Bereiche im Leben braucht, wo man mit anderen allein ist, wo niemand von außen hereinschauen oder hereinkommen kann.
Die meisten gaben sich damals mehr Mühe, eine Sprache oder Autofahren zu lernen, als verschlüsseln zu lernen, freie Software zu verwenden und zu schauen, dass die eigenen persönlichen Daten nicht irgendwo herumliegen, wo sie jemand stehlen kann.
Für viele war das zu unbequem.

Den zweiten Gedanken hat Julian Assange einmal mit dem Satz ausgedrückt: Dedication wins against wealth.
Hingabe gewinnt gegen Reichtum.
In meinen Worten würde ich das so sagen: Das, was Menschen im Herzen tragen, ist stärker als jede Macht der Welt.
Die Mächtigen haben sich damals für die Cypherpunks nicht wirklich interessiert.
Sie haben sich über sie geärgert, sie wollten sie stoppen, sie weghaben, aber als Menschen waren sie für sie nicht interessant.
Deswegen haben sie es nie geschafft, sie los zu werden.
Sie waren brutal aber halbherzig und deswegen langsam, ungenau und unbeweglich.
Die Wende kam dadurch, dass jedes Jahr mehr und mehr junge Menschen ihre eigenen Ideale lebten und sie immer mehr in die Welt der großen Unternehmen, Regierungen und Geheimdienste hineintrugen, anstatt von ihnen deren Ideale zu übernehmen.
Sie wollten nicht mehr vor allem mehr Geld, mehr Macht und mehr Sicherheit, sondern sie wollten immer mehr so leben wie sie sind.
Sie wollten sich nicht mehr verbiegen, sondern ihre Ideale auch in den Firmen, überall im Leben so leben, wie sie das untereinander schon taten: dem anderen als Menschen begegnen, Ungerechtigkeiten ausgleichen, in Vertrauen, in Gemeinschaft leben, mit Blick auf die Lebensqualität jedes einzelnen Menschen.

Der dritte Gedanke ist die Überwindung des Gegeneinanders im Leben.
Im Großen ist das die Überwindung von Nationalismus und Rassismus, davon dass Menschen als besser oder schlechter, als mehr oder weniger wert angesehen werden je nachdem aus welchem Land sie kommen, welchen Titel, wie viel Geld sie haben, ob sie Mann oder Frau sind.
Im Einzelnen geht es darum, zu erkennen, dass jeder Mensch einen guten Kern hat, wirklich jeder! Jeder macht das, was er für gut und richtig hält.
Auch wenn er Bomben wirft.
Er meint dann meist, dass es notwendig ist, Bomben zu werfen, dass es nicht anders geht.
Das ist natürlich immer ein Denkfehler.
Wenn die Menschen gegeneinander gehen, dann freuen sich die Mächtigen.
Sie werden dadurch stark, dass Menschen nicht das tun, was ihr Herz ihnen sagt.
Dann können sie sie besser kontrollieren und unterdrücken.

Der vierte ist die freie Entfaltung der eigenen Initiative.
Dazu gab es schon in meiner Jugendzeit großartige Versuche.
Zum Beispiel das Linux-Projekt, das jeder von euch kennt.
Zigtausende Menschen haben da zusammengearbeitet und die meisten davon nicht um Geld zu verdienen, sondern weil sie eigene Ideen verwirklichen wollten.
Damit das gehen kann, braucht man starke und gute Regeln, und ein kräftiges Miteinander-Denken.
Zum Beispiel durfte jeder ein eigenes Projekt anfangen und kein anderer durfte ihm dabei hineinreden.
Es war einfach nicht möglich.
Und jeder durfte vom anderen alles sehen, was er machte, und sich auch alle Ideen und Pläne und Programme kopieren, die er wollte, ohne zu fragen.
Heute machen wir das nicht nur mit Computer-Programmen so, sondern überall im Leben: Wenn wir Brücken bauen, Autos produzieren oder Strom erzeugen, kann jeder nachschauen, wie das gemacht wird, bis in alle Einzelheiten.
Jeder nimmt sich davon das, was er braucht, wenn er selbst etwas bauen will, formt es um und stellt es allen anderen wieder zur Verfügung, egal wer das ist, egal wo auf der Welt.

Das Fünfte ist, nicht über andere Menschen zu urteilen, nicht zu sagen oder zu denken, dass sie etwas gut oder schlecht machen, dass sie etwas besser machen könnten, sondern versuchen zu verstehen, warum sie etwas machen, warum sie etwas denken oder sagen.
Dann passiert oft etwas sehr Seltsames: Obwohl sie manchmal schlimme Dinge machen oder sagen, fühlt man sich ihnen näher und das lässt einen selbst im Inneren ruhiger werden.
Und das wiederum merken die anderen oft, manchmal unbewusst, und werden auch ruhiger und kommen näher.
Und dann passieren manchmal überraschend sehr schöne Dinge.
Ich habe das einmal mit dem Mörder von meinem Bruder erlebt.

Das Sechste ist, dass wir Menschen immer aneinander vorbeireden, vorbeihören und vorbeidenken.
Wir hören nicht das, was der andere sagt, und er sagt nicht das, was er denkt.
Ich meine jetzt nicht lügen, sondern dann wenn jemand wirklich das sagen will, was er denkt, dann sagt er das nicht, sondern ein bisschen etwas anderes.
Da kommen sehr viele Missverständnisse her.
Was kann man tun? Ungefähr das, was ihr kennt in der Fabel mit den vier Leuten, die alle das gleiche Haus gesehen haben, aber jeder nur von einer Seite und sich später treffen und darüber sprechen.
Sie könnten jetzt darüber streiten, weil der eine eine Tür gesehen hat und die anderen nicht.
Und einer vier Fenster und eine andere zwei.
Aber sie tun es nicht, sondern hören den anderen zu und versuchen herauszufinden, wie alles zusammenpasst.
Sie versuchen, die Widersprüche aufzulösen, und alles zu bewahren, was jeder sagt.
Man muss Dinge von verschiedenen Seiten ansehen, wenn man sie kennen lernen will.

Der Siebte ist das, mit dem die Cypherpunks-Bewegung weltweit bekannt wurde.
Das ist das Recht, dass jeder Mensch erfahren darf, was die Regierungen, heute sagen wir Verwaltungen, weil sie regieren ja nicht mehr, was die Unternehmen, Armeen, die Polizei und so weiter, alles tun.
Jeder hat das Recht, alles über das zu erfahren, was einen selbst betrifft, zum Beispiel, wenn man etwas benutzt oder konsumiert.
Wenn man ein Ei isst, dann darf man erfahren, was alles getan wurde, um es zu erzeugen und zu einem zu bringen.
Genauso wenn man Strom nutzt, wenn man Straßenbahn oder Auto fährt.
Und jeder darf erfahren, was die Verwaltung des eigenen Landes alles macht, um zum Beispiel für Sicherheit zu sorgen.
Aber immer erst dann, wenn es schon getan ist, nicht vorher oder wenn es gerade getan wird, spätestens ein paar Wochen danach.
Das Tun selbst soll frei bleiben.

Jetzt fehlen noch vier.
Aber ich fühle, das wird ein bisschen abstrakt, wenn ich die hier einfach nur aufzähle.
Sie sind auch ein wenig anders als die ersten sieben.
Besonders die letzten zwei.
Also, das soll noch ein bisschen spannend bleiben.
Ihr werdet sie kennen lernen, wenn ihr in der Akademie durch die ersten sieben Gedanken durch seid.“
