== [big-number]#2019# Die Psychologin

[text-caps]#Es klopfte an# Mariannes Tür.
Sie erschrak.
„Wer war das jetzt?“ Sie atmete durch.
Corinne war noch überall in ihren Gliedern.

Ihre Mutter sagte durch die Tür: „Ich bin’s, deine Mama.“

Marianne: „Ich will jetzt nicht.“

Mutter: „Stefanie ist hier.
Sie will mit dir reden.“

Marianne: „Ich habe mit ihr geredet.“

Stefanie war die Psychologin, die bei Marianne eine posttraumatische Störung entdeckt zu haben glaubte.
Sie war 35 Jahre alt und eng mit ihrer Mutter befreundet.
Sicherlich verlangte sie von ihrer Mutter kein Geld für die Gespräche, sie tat es aus bestem Willen, nur um zu helfen.
Nichts, was Marianne jetzt im Entferntesten brauchen konnte.
Sie brauchte einen Menschen, keine Psychologin, jemand, der sie verstand und mit dem sie offen reden konnte, der nicht alles Mögliche in sie hinein interpretierte.

„Marianne, ich habe eine Idee, die ich gerne mit dir teilen würde“, sagte Stefanie durch die Tür.
“Vielleicht können wir die Situation damit verbessern.“

Marianne antwortete nicht.
Sie setzte sich auf ihr Sofa und schloss die Augen.

Stefanie: „Ich nehme mir hier einen Stuhl und warte, bis du bereit bist.
Es ist mir wichtig.
Lass dir Zeit.“

Marianne versuchte zu meditieren, zumindest das zu tun, was sie sich darunter vorstellte.
Auf jeden Fall tat es ihr gut, für eine Zeit ihre innere Balance zu suchen.
Und das funktionierte meist sogar in echten Stresssituationen, wie in der, in der sie gerade steckte.
Paul hatte ihr erzählt, was er tat, wenn bei ihm alles aus den Fugen geriet, und er nicht mehr wusste, wo er war und wohin er gehen konnte.
Daraus hatte sie sich ihre eigene Sache zusammengebastelt.
So saß sie mit geschlossenen Augen im Schneidersitz auf dem Sofa, ein Bein auf dem Boden und sagte leise: „Mein Leben ist nicht in Gefahr.
Ich brauche nichts von außen, um zufrieden zu sein.
Ich habe alles, was ich brauche.
Ich kann nichts richtig machen und auch nichts falsch machen …“

Nach etwa einer Viertelstunde stand sie auf, ging langsam zur Tür, öffnete sie und sah Stefanie an, die auf einem Stuhl an der Kellerwand saß und ein Buch las.
Stefanie schaute auf und lächelte Marianne an, wollte aufstehen, aber Marianne gab ihr ein Zeichen und setzte sich an die Wand gegenüber.

Marianne: „Was willst du mir sagen?“

Stefanie setzte sich auch auf den Boden.
„Ich habe viel über deine Situation nachgedacht.
Worin du stecken geblieben bist.
Ich hatte nicht richtig verstanden.“

Marianne fragte konzentriert: „Was hattest du nicht richtig verstanden?“

Stefanie: „Es ist real.
Vollkommen real.
Du hast keine Möglichkeit es anders zu sehen.
Es ist absolut real! Auf eine gewisse Weise.“

Marianne schaute auf den Boden.
Eine leise Wut stieg in ihr hoch.
Sie hasste Manipulationen.

Stefanie: „Dein Körper macht es real.
Wie der Körper bei einem Schock das Blut zurückhalten kann, auch dann wenn man eine große Wunde hat.
Genauso kann der Körper dein Denken fesseln, er kann bestimmen, was du denkst.
Es ist als wärst du in einem Gefängnis, nur dass du die Gitterstäbe weder sehen noch spüren kannst.
Ich hoffe so sehr, dass du vielleicht etwas davon ahnst, dass du spürst, dass mit deinem Denken etwas nicht ganz stimmt.“

Marianne antwortete ohne vom Boden aufzuschauen: „Und dann zaubert mir mein Körper ein Polizeiauto in meine Erinnerung hinein, aus dem drei Männer aussteigen, mit meinem Bruder sprechen, er mich dann anschaut und ohne auf Wiedersehen zu sagen, einsteigt?“

Stefanie nickte ernst: „Ja.
Das kann sein.“

Marianne: „Und wie erklärst du, dass ich davon schon erzählt hatte, bevor ich überhaupt den Brief von Paul bekommen habe, in dem er geschrieben hat, dass er weg ist?“

Stefanie: „Darüber habe ich auch schon nachgedacht.
Du hast vielleicht vorher geahnt, dass dein Bruder weg will oder es am Rande mitbekommen?“

Marianne: „Am Rande mitbekommen? Ich habe es am Rande mitbekommen und mir davon so einen Schock geholt, dass mein Denken gefesselt wurde.“ Marianne kochte, aber sprach weiterhin in ruhigem Ton.

Stefanie: „Ich glaube, er hat es dir vorher gesagt!“

Marianne platze: „UND DAS ERFINDEST DU EINFACH ALLES! DAS IST ALLES AUSGEDACHT! Du sagst: ‘Das kann sein’ … ‘ich glaube’ … ‘vielleicht’.
Das sind keine Tatsachen, das stimmt auch nicht, das ist rein aus deiner Fantasie.“

Stefanie antwortete mit verständnisvoller Stimme: „Es ist doch völlig unwahrscheinlich, dass dein Bruder einfach so in das Auto einsteigt.
Ohne die Polizisten etwas zu fragen, und ohne auf Wiedersehen zu sagen.
Er schaut auf ein Tablet und das war es.
Hej, er war Profihacker, er hatte Zig-Male mit Polizisten zu tun gehabt und hat sie zur Weißglut gebracht.
Ein Richter hat ihn einmal angebrüllt und dann die Verhandlung abgebrochen und er ist dabei ruhig geblieben.
Ich war da im Raum, ich sehe heute noch sein leises Lächeln.
Und macht irgendetwas, was er auf einem Tablet-Display liest, dass er einfach so in ein Polizeiauto einsteigt, ohne Frage, ohne Gegenwehr?“ Sie schaute Marianne streng an.

Marianne erstarrte.
Warum war er einfach so eingestiegen? Warum? Sie hatte sich das tausendmal gefragt.
Sie wusste es nicht.

Stefanie: „Ich glaube, und ich bin Psychologin, ich glaube, dass dein Bruder in ein Auto zu Freunden eingestiegen und mit ihnen davon gefahren ist.
Er hat dir noch einen Blick zugeworfen, aber nichts gesagt.
Aber durch den Blick hast du verstanden, dass er nicht wiederkommt.
Und da ist für dich eine Welt zusammengebrochen.
Da ist aus einem normalen Auto ein Polizeiauto geworden und aus drei Freunden, zwei Polizisten und ein Geheimdienstsmann.
Du kamst an dem Tag völlig zerheult nach Hause.
Warum? Wo warst du da gewesen?“

„In Wedding, am Rathaus“, sagte sie leise und vergrub ihr Gesicht in ihren Händen.

Stefanie legte ihre Hand auf Mariannes Schulter, aber sie schob sie zurück.

Stefanie: „Komm.
Du könntest für ein paar Wochen hier in Berlin auf die Havelhöhe gehen.
Da gibt es ein Institut, da kannst du entspannen.
Und da kannst du vielleicht die richtige Geschichte wiederfinden.
Wenn du willst.
Willst du das?“

Marianne schaute langsam mit fragendem Blick hoch zu Stefanie.
Dann erhob sie sich und verschwand in ihrem Zimmer.
