== [big-number]#2021# Unterschiedliche Strategien

[text-caps]#Im BND Hauptquartier.#

Heinz: „Schau dir das an! Fuck! Marlene Farras war auf einem TAO-Computer der NSA in Fort Meade und hat Daten mitgenommen.
Unsere Marlene.
Das ist doch ein Ding!!“

Frederik ging zu Heinz herüber und schaute auf seinen Bildschirm.

Frederik: „Sagt wer?“

Heinz: „Die werten amerikanischen Kollegen.
Ich hoffe, sie haben niemanden umgebracht, um an die Information zu kommen.
Woher wissen die das auf einmal? Auf dem Computer waren nur Spuren von Karl, dachte ich.“

Frederik: „Die Freundin von Karl.
Sie hat bestimmt geredet.
Oder musste reden.“ Er lächelte.
„Aber immerhin sagen sie uns so etwas einmal.
Einfach so … ohne Gegenleistung.
Das könnte vielleicht der Beginn einer vertrauensvollen Zusammenarbeit werden.“

Heinz schüttelte den Kopf: „Sie sagen es nicht ganz einfach so.“

Frederik beugte sich über Heinz’ Schulter und las die E-Mail.
Dann schüttelte er wild den Kopf: „Näh! Nein, nein.
Sie kriegen Marlene nicht! Nicht von mir.
Nicht jetzt.
Sie darf jetzt nicht nach Amerika.
Wir sind so knapp davor.
Ein Schritt noch und sie geht freiwillig in die Psychiatrie.
Wir können sie jetzt nicht da rausholen.
Das gibt einen Aufruhr.
Das ganze Umfeld, Familie, Freunde.
Das ist ein Wespennest.
Und wenn sie jetzt einfach so verschwindet wie ihr Bruder, kriegen wir vielleicht eine Initiative, die sich ein paar Wochen lang vor die amerikanische Botschaft stellt, oder bei uns hier, oder einen wilden Hashtag in Twitter, #woistmarianne, oder irgendeine andere von diesen Aktionen.
Und dann springt die Presse an … Viel zu viel Aufmerksamkeit.
Geht nicht.
Geht gar nicht.“

Heinz schaute Frederik skeptisch an: „Und wie willst du das machen? Ich meine: Du sagst nein zu den Amis und kannst schon die Hand auf den Telefonhörer legen für den Anruf, der dann aus dem 13.
Stock kommt, wo dir dann irgend so ein Grünschnabel mit aufgeblähter Brust einen schönen Gruß vom Präsidenten ausrichtet und dir sagt, dass du das doch machen musst.“

Frederik war zurück auf seinen Platz gegangen und ließ sich in seinen Stuhl fallen.
„Ich kann sie jetzt nicht hergeben.
In einem halben Jahr vielleicht.
Dann können sie sie haben.
Aber nicht jetzt.“

Frederik: „Wir können sie hierher bringen.
Die Amis verhören sie und wir bringen sie wieder zurück.
Im Augenblick glaubt ihr eh niemand etwas.
Wahrscheinlich würde sie es nicht einmal erzählen.
Schorsch ist ziemlich aktiv gerade.
Und der ist echt gut.
Der macht mit ihr gerade ein paar Sachen, das glaubst du nicht.
So dreist! Schau hier, das hast du noch nicht gesehen …“

Frederik zeigte Heinz einen Umzugskarton mit einem Tagebuch, einigen Kleidungsstücken und einer Uhr.

„Alles von Marlene“, grinste er.
„Hat Schorsch in den letzten Tagen aus ihrem Zimmer geholt.
Und immer während sie im Raum war.
Sie verlässt ihn ja kaum.
Nachts um drei.
Ein bisschen Gas, und sie schläft tief.
Er kommt echt überall rein.
Ein total Verrückter.
Er löscht sogar die Bilder von den zwei Überwachungskameras, die sie in ihrem Zimmer hat.
Nur an ihren Laptop ist er noch nicht heran gekommen.
Den hat sie anscheinend im Schlafsack direkt zwischen ihren Beinen.
In den nächsten Tagen kommen die Sachen dann einzeln wieder zurück an ihren Platz.“

„Zwischen ihren Beinen? Die ist ganz schön paranoid,“ lachte Heinz.
„Ich glaube auch, dass wir sie bald haben.
Das hält kein Mensch aus.“

Federik: „Ja, du legst dein Tagebuch auf den Tisch in einem kleinen Zimmer und am nächsten Morgen ist es nicht mehr da.
Du suchst es überall.
Denkst, du wirst verrückt.
Und dann zwei Tage später ist es auf einmal wieder da.
Das ist die gute alte Zersetzung.
Mein Onkel war bei der Stasi.
Die haben in der Richtung mit ihren niedlichen Mitteln ganz schön viel erreicht.
Das ganze Land hat vor ihnen gezittert, vor dem lahmfaulen Beamtenhaufen.
Echt Angst gehabt! Ich sage dir, die einfachsten Sachen wirken am besten.
Computer manipulieren.
Einfach mal aus der Ferne ab und zu den Bildschirm aus- und einschalten, das Programm abstürzen lassen, wenn derjenige gerade eine wichtige E-Mail schreibt, den Mauszeiger anhalten, eine Textpassage löschen, ein Telefongespräch beenden.
Das ist Überwachungs-Homöopathie.
Deswegen … Wir geben sie jetzt nicht raus!“

Heinz: „Dann brauchst du eine ziemlich gute Story.“

Frederik: „Wir sagen ihnen, dass sie bald in die Psychiatrie kommt.
Dort bekommen sie dann Zugriff.
Nicht jetzt.“
