== [big-number]#2064# Die Sphinx

[text-caps]#Lilly: „Es gibt# noch etwas Neues.“

Sie hob ihre flache Hand Richtung Publikum.
Auf ihr erschien eine dreidimensionale, etwa 15 cm große, gezeichnete Mosquitofliege.
Lasse und Sigur hatten im Raum einige 3D-Projektoren aufgestellt, mit denen man an beliebigen Stellen Dinge einblenden und bewegen konnte.

Lilly: „Das ist Mostafa.
Er gehört zum Personal der Akademie.“

Sie warf Mostafa in die Luft und er flatterte ziemlich aufgeregt eine Runde über die Zuschauer und dann Richtung Sofa, wo er sich neben Lilly auf der Sessellehne niederließ, noch einmal mit den Flügeln schlug und mit klarer, etwas piepsiger und aufgeregter Stimme zu sprechen anfing.

Mostafa: „Hej, hej! Mein erster Auftritt hier.
Überhaupt der erste! Ja, was soll ich sagen? Ich bin Mostafa.
Ich bin eine asiatische Tigermücke.“ Er schlug mit den Flügeln.
„Und ich weiß eine Menge über die Akademie.
Eigentlich alles.
Zumindest alles, was ihr über die Akademie wissen müsst.
Ich weiß, welches die letzten vier Grundgedanken sind.
He, he.
Und ich kenne jeden Eingang, jeden Übergang und jeden Ausgang.
Ich war schon überall.
Und … Ich kenne die Sphinx! Oh, ja.
Und meine Kollegen hier: Wim, Tin und Wunderlich.“

Ein großer Bär, eine Eule und eine Ratte erschienen hinter der Bühne.
Der Bär sprang mit einem eleganten Schwung über die Sofarücklehne und landete mit einem leichten Lächeln auf den Lippen neben Marianne auf einem großen Kissen.
Die Eule flatterte in die Höhe und landete dann ungelenk neben Bär und Lilly auf der Rücklehne.
Und die Ratte wuselte eine Zeit lang auf der Bühne herum, als würde sie ein Versteck suchen, und verschwand dann unter Lillys Sessel.
Kurz darauf lugte sie von dort etwas scheu wieder heraus.

Lilly: „Das sind die vier Spiele-Meister der Akademie.
Mostafa führt euch überall herum.
Er erklärt neue Dinge und gibt alle möglichen Kommentare, ihn könnte ihr alles fragen, was mit der Akademie zusammen hängt. Außerdem ist er der Programmierlehrer.“ Sie schaute zu Mostafa hinüber, der den Schnabel spitz nach oben verdrehte.

„Wim, der Bär, ist für die Lern-Atmosphäre zuständig, dafür, dass sich jeder frei fühlt, dass jeder seinen Weg finden kann, dass jeder das ausprobieren kann, was er probieren will.
Er wohnt im Garten des Epikur auf der elften Ebenen-Insel.
Dort müsst ihr versuchen, hinzukommen. 
Der Weg führt über alle elf Inseln.
Das ist ein bisschen wie ein Labyrinth.
Was das genau ist, werdet ihr noch erfahren.

Tin, die Eule, weiß alles, was im Befreiungskampf passiert ist.
Sie kennt die ganze Geschichte, alle Cypherpunks, alle Hacks, die 11 Grundgedanken und vor allem die allgemeinen Gedankenfehler.
Und sie lebt in einem uralten Zaubergarten, wo ihr das alles kennenlernen könnt.
Den Garten kann man verwandeln.
Zum Beispiel, indem man Gedankenfehler auflöst, etwas programmiert oder Aufgaben löst.

Und Wunderlich … Wunderlich, das ist unsere Hausratte.
Wenn ihr Mist baut, absichtlich oder unabsichtlich, dann werdet ihr ihn kennenlernen, dann bekommt ihr eine Spezial-Aufgabe mit ihm zusammen.
Und wegen dieser Aufgaben ist er auch nicht bei allen uneingeschränkt beliebt, würde ich sagen …“

Unter dem Sessel sah man ein angedeutetes Grinsen herausscheinen.

Lilly: „Die Akademie selbst müsst ihr erst einmal finden.
Sie ist eigentlich nicht zu übersehen … Wenn ihr davor steht … Die meisten Spieler sehen sie aber auch dann nicht.“ Sie fasste sich an die Nase.
„Mehr gibt es jetzt eigentlich nicht zu sagen.
Wenn jemand jetzt hier in der großen Runde etwas fragen möchte, gerne.
Ansonsten wünsche ich euch viel Spaß und wir sehen uns in TRON.
Wer noch bleiben will: Marianne wird den ganzen Abend hier sein und Geschichten erzählen und alle eure Fragen beantworten.“

Marianne: „Fehlt nicht noch etwas?“

Lilly: „Was? Ahh.
Mh mh.“

Ein dunkles Grollen war von draußen zu hören.
Es schien zuerst von der einen Seite, dann von der anderen zu kommen.
Es kam näher und wurde lauter und plötzlich, mit einem enormen Blitz und einem gewaltigen Krachen, stürzte die Wand hinter der Bühne ein, zumindest schien es so.
Steinbrocken rollten durch den Raum.
Alles füllte sich mit Nebel.
Grelles Licht blendete die Zuschauer, keiner konnte genau sehen, was vor sich ging.
Die Eule drehte sich langsam zum Licht hin, der Bär saß weiterhin ruhig auf dem Sofa und beobachtete die Zuschauer, von der Ratte war nichts zu sehen und Mostafa rollte demonstrativ die Augen.
Alle Zuschauer schauten gespannt in das Licht, wo sich eine Riesen-Vogelgestalt abzeichnete und langsam deutlicher wurde…“

„Die Sphinx!“, rief Lilly.

Mostafa grummelte neben ihr: „Sie kann nicht ein einziges Mal gesittet kommen, wie normale Menschen das tun.
Nicht einmal, wenn die Akademie eingeweiht wird.
So eine Pupsnase.“
