== [big-number]#2019# Flucht aus dem Keller

[text-caps]#Marianne schreckte# im Bett hoch.
Es war 2 Uhr 30.
Ihr Wecker hatte einen kurzen Piepston von sich gegeben.
Sie wischte sich die Augen und öffnete den Reißverschluss ihres Schlafsacks.
Ihr erster Griff galt ihren zwei Laptops, die sie immer mit in den Schlafsack nahm.
So hatte ihr das ihr Bruder gesagt: Werkzeuge immer bei sich behalten.
Sie stand auf, zog sich eine Hose an und schlüpfte in ihre Sneakers.
War das ein leises Kratzen draußen im Gang? Oder nicht? Da, noch einmal, fast unhörbar.
Sie musste wirklich hier raus jetzt, sonst würde sie wirklich noch verrückt werden.
Paul sagte immer, dass die Geheimdienste zu allem fähig seien, nichts wäre ihnen heilig, nicht einmal die eigene Wohnung.
„Irgendwann werden sie dafür zur Rechenschaft gezogen“, dachte Marianne, „und wenn ich selbst dafür sorgen muss“.

Sie schob den Schreibtisch beiseite.
Dahinter kam ein Heizkörper zum Vorschein, der auf den ersten Blick wie ein normaler Heizkörper aussah.
War er aber nicht.
Paul hatte ihn dort angebracht, um einen Geheimgang zu verdecken, den er mit einem Freund vorletzten Sommer gebaut hatte.
Ein richtiger unterirdischer Gang, durch die Hausmauer hindurch, unter dem Rasen entlang bis hin zu einem Gartenhäuschen.
Insgesamt etwa 25 Meter lang.
Vielleicht brauchen wir den einmal, hatte er Marianne gesagt.
Vielleicht müssen wir einmal aus dem Haus, ohne dass das jemand mitbekommt.
Ein kleines Hebelchen löste eine Sperre, dann ließ sich die Heizung über zwei Scharniere wegschwingen.
Marianne schaute in den dunklen Gang, es roch ein wenig modrig, aber sah sonst okay aus.
Dann suchte sie ein paar Kleidungsstücke zusammen und steckte sie zusammen mit einem Waschbeutel und ihren Laptops in einen Rucksack.
Sie verschwand im Gang und zog den Heizkörper hinter sich zu, der mit einem satten Klack einschnappte.
Leicht gebückt, aber relativ bequem ging sie den Gang entlang und stieg im Gartenhäuschen über eine kleine Leiter hinaus.
Dann verschwand sie über das angrenzende Maisfeld in der Dunkelheit.

Sie lief lange, zwei Stunden, drei Stunden, in Richtung Innenstadt, zur Jannowitzbrücke und dort zur c-base, dem bekannten Hackerspace.
Sie folgte auf ihrem Weg so gut es ging der Kamerakarte ihres Bruders.
Auf dieser Karte waren die meisten Überwachungskameras der Stadt mit Reichweite und Richtung eingezeichnet.
Es gab zu Fuß immer noch relative gute Wege in die Stadt hinein.
Die Aktionen gegen Überwachungskameras in Berlin hatten eine Wirkung gehabt.
Manchmal musste sie ein wenig komische Wege laufen und aufpassen, dass es für Menschen, die sie unterwegs traf, nicht zu seltsam aussah.

Ihr Ziel war ein Projekt in der c-base, der so genannte Dead Space, der so abgeschirmt war, dass keine Funksignale von außen eindringen oder herausgehen konnten.
Gleichzeitig wurde jede fremde elektromagnetische Strahlung von mitgebrachten Computern, Handys und anderen Geräten erkannt.
Das Spiel bestand darin, drinnen Fotos, Filme oder Tonaufnahmen zu machen und rauszubringen, oder von draußen einen der Computer anzugreifen, ohne dass das Sicherheitssystem das bemerkte.
Immer wenn das System einen Versuch erkannte, sprang ein großer Bildschirm an der Decke an und eine animierte Guy-Fawkes-Maske warnte in dramatisch-lustiger Weise vor dem Eindringling.
Mit der Zeit waren die Versuche immer ausgefeilter geworden, Hacker kamen von weit her, um zu versuchen, das System auszutricksen.
Jeder erfolgreiche Angriff führte zu neuen Gegenmaßnahmen, so wurde das System immer besser und besser.
Inzwischen musste man einen Riesenaufwand treiben, wenn man etwas mitschneiden oder hineinschmuggeln wollte.

Marianne hatte seit einem Hackathon-Wettbewerb vor zwei Jahren einen Gutschein, einen eigenen Rechner dort unterzubringen.
Und das wollte sie jetzt tun.
Sie wollte sich zumindest für einige Zeit in der Öffentlichkeit verstecken, in der viele Menschen um sie herum waren.
Sie ging davon aus, dass welcher Geheimdienst auch immer hinter ihr her war, er sie irgendwo bei Freunden oder Bekannten versteckt vermuten würde.
Sie würden alle Plätze bewachen, wo sie in den letzten Jahren gewesen war, wo sie Kontakt hatte, die irgendwie privat waren.
Auf diese Ahnung setzte sie nun alles.
Ihr Bruder hatte gesagt, dass man solche Dinge mit dem Gefühl entscheiden sollte und manchmal müsste man Dinge tun, die unsinnig erscheinen.
Schlafen wollte sie jeden Tag von 9 bis um 3 Uhr Nachmittags in einem der Schlafkojen im Keller der c-base.
Den Rest der Zeit wollte sie mit Pudelmütze vor ihrem Rechner im Dead Space sitzen und an irgendetwas arbeiten … ja, woran? Woran sollte sie arbeiten? „Genau!“, dachte sie und umfasste mit der Hand den USB-Stick in ihrer Tasche.
Das wollte sie tun.
Den wollte sie sich jetzt ganz genau anschauen.

Es war etwa 5 Uhr morgens, als sie bei der c-base an ein Seitenfenster klopfte, wo sie noch eine Gruppe von Hackern um einige Laptops herum sah.
Einer stand auf, warf einen flüchtigen Blick auf ihre Mitgliedskarte und ließ sie hinein.
Drinnen ließ sich Marianne auf ein Sofa fallen, und atmete erst einmal durch.
Einer der Jungs brachte ihr eine Mate.
