== [big-number]#2019# Night-Raid

[text-caps]#Das Schlafzimmer von# Mariannes Eltern lag im ersten Stock des Hauses.
Beide schliefen tief, als es plötzlich im Erdgeschoss laut krachte und ein greller Blitz durch das Schlafzimmerfenster hineinleuchtete.
Mariannes Eltern schreckten hoch.
Stimmen brüllten durcheinander.
Lautes Trampeln im Treppenhaus, dann nach kurzer Zeit wieder ein Rumms.
Sie schauten sich an.
Die Uhr zeigte vier Uhr morgens.

Mutter: „Um Gottes Willen! Was ist das?“

Sie griff nach seiner Hand.

Vater, aufgeregt: „Ein Sonderkommando! Scheiße.
Jetzt müssen wir ruhig bleiben.
Gott sei Dank ist Paul weg.
Sonst würden sie ihn jetzt mitnehmen.“

Mutter: „Aber Marianne, was ist mit Marianne?“

Sie wollte aus dem Bett aufstehen.
Der Vater hielt sie zurück.

Vater: „Ist ok, ist ok.
Mach dir jetzt keine Sorgen.
Sie suchen Paul.
Sie werden ihr nichts tun.
Sie wird einen gehörigen Schreck bekommen, aber das kriegen wir wieder hin.
Ich habe so etwas erwartet.“

„Marianne !!!“, schrie die Mutter, sie versuchte sich loszumachen, aber ihr Mann hielt sie fest.

Vater: „Wir dürfen jetzt nichts falsch machen.
Und gleich die Hände hoch, wenn sie reinkommen.
Dann passiert nichts.“ Seine Stimme zitterte.

Das Trampeln kam näher, die Treppe hinauf.
Mit einem Krach flog die Türe auf, grelles Licht.
Vater und Mutter hoben beide ihre Arme.

Vater: „Nicht schießen! Wir sind unbewaffnet.“

Der vorderste Soldat kam mit angeschlagener Waffe zu ihnen vor und brüllte mit amerikanischem Akzent: „Marianne Lasser.
Wo?“ Zwei weitere rissen derweil die Kleiderschränke auf.
Einer kroch mit dem Kopf unter das Bett.

Mutter und Vater schauten sich überrascht an.

„Down in her room!“, antwortete der Vater aufgeregt.

Soldat: „No!“ Er hielt seine Waffe gegen den Kopf des Vaters.

Vater, hektisch: „Then I don’t know.
I don’t know.
I don’t know.“

Der Soldat drehte sich um und verschwand im nächsten Zimmer.
Die anderen ihm hinterher.
Nach etwa zehn Minuten verließen sie das Haus.
Der Mannschaftswagen, mit dem sie gekommen waren, brauste mit quietschenden Reifen davon.

Lange schauten sich Mutter und Vater stumm an.
Plötzlich stutzte der Vater: „Warum haben sie englisch gesprochen?“

Mutter: „Und was ist mit Marianne? Wo ist Marianne?“
