== [big-number]#2021# Zwei Jahre später

[text-caps]#Pauls Gefängniszelle war# drei mal zwei Meter groß.
Sie hatte kein Fenster.
Es gab nur ein Bett, einen Eimer und ein Handtuch.
Beißender Gestand erfüllte den Raum.
Paul lag mit geschlossen Augen auf dem Bett.
Er wusste nicht welche Tageszeit gerade war.
Es war stockfinster.
Aber es war fast immer stockfinster.

„Shit“, sagte Paul leise und richtete sich auf.
Er atmete kurz durch und rief dann gegen die Türe: „Hej! Ich brauche ein neues Handtuch!“

Keine Antwort von draußen.
Er sank zurück und sagte leise zu ich selbst: „Ich darf nicht wieder in die Scheiß-Wut zurückfallen.
Die frisst mein Gehirn auf.
Die Jungs und Mädels da draußen vor der Tür sind meine Feinde, gut, … aber ich bin nicht ihrer! Shit.“ Er atmete.
„Ich bin nicht ihrer.
Ich bin nicht ihrer.“ Er richtete sich wieder auf, legte seine Hände auf seine Beine und atmete tief und langsam.
„Kein Dagegen!“ Er presste seine Hände auf seine Beine und atmete tief aus und ein.
„Kein Dagegen“, murmelte er wieder und eine Träne drückte in sein Auge.
„Ich will nicht verrückt werden.“ Seine Hände strichen über seinen Hinterkopf, zu der Stelle hin, wo eine Menge Schorf die Haare verklebte.

Er stöhnte und biss auf seine Lippen.
Es tat immer noch verdammt weh.
Er wusste nicht einmal sicher, wie es passiert war.
Aber wahrscheinlich war es der Vierkantstock, der bei der letzten Befragung in der Ecke hinter ihm stand.
An den Schlag konnte er sich nicht erinnern.

Was zum Teufel konnten sie nach zwei Jahren noch von ihm wollen? Er war rauß aus seinen Kreisen, zwei Jahre ohne Hacks, ohne Kommunikation.
Zwei Jahre, das war endlos lange. Ein Schauer fuhr ihm den Rücken herunter: „Ja … und was dann, wenn sie nichts mehr von mir wollen?
Was dann? … Shit.“

Er atmete wieder tief und langsam, rieb die Hände über seine Beine.
Seine Wut stieg wieder in ihm hoch.
Er konnte nichts dagegen tun.
Sie wurde stärker … plötzlich er schlug mit voller Wut auf seine Beine.
Im gleichen Augenblick öffnete sich die Türe mit einem satten Klack und das Licht ging an.
Gleißendes Licht.
Er riss die Hände hoch, um seine Augen zu verdecken.
Zu spät.
Er fühlte wieder diesen stechenden Schmerz.
Jedes Mal, wenn er ein paar Tage ohne Licht war und es dann plötzlich hell wurde.
Er dachte nur „Scheiße, solche Arschlöcher!“

Das letzte Buch, das er vor seiner Verhaftung gelesen hatte, war von Marshall Rosenberg: Gewaltfreie Kommunikation, wie man Konflikte lösen kann, in dem man sich in andere Menschen einfühlt.
So eine Ironie des Schicksals: Rosenberg meinte, dass man jeden anderen Menschen verstehen kann.
Er hatte sich ungefähr in seinem Alter zum Lebensziel gesetzt, so viel Empathiekraft zu entwickeln, dass er sich in Adolf Hitler würde einfühlen können, um verstehen zu können, warum er tat, was er tat.
Nein, das war keine Ironie des Schicksals, das war blanker Zynismus des Lebens.
„Rosenberg, Hitler.
Und ich?“, dachte Paul.
„Ich scheitere an ein paar amerikanischen Soldaten, ziemlich normalen Soldaten, die in ihrer Freizeit bestimmt mit Freunden grillen, mit Frau und Kindern ins Disneyland gehen und einmal im Jahr mit viel Liebe zusammen einen Truthahn zubereiten und essen…“

Er hätte diesen Marshall Rosenberg jetzt gerne hier, um ihn zu fragen: „Hey, Marshall, guck, so machen die das hier.
Das ist doch völlig sinnfrei.
Sie sagen mir zwei Jahre lang nicht was sie von mir wollen, klagen mich nicht an, lassen mich tagelang alleine im Dunkeln und hauen mich mit einem Vierkantholz bewusstlos.“

Drei Soldaten hatten inzwischen das Bett umringt.
Einer fasste ihn an der Schulter: „Auf! Jemand will mit dir sprechen.“

„Keine Handschellen, keinen Schlag, etwas war neu“, dachte Paul.
Er richtete sich langsam auf, schaute ein wenig scheu in die drei Gesichter und stand dann auf.

Rumms, bekam er einen Schlag von hinten auf den Rücken.

Soldat: „Auf! Beeilung.
Zuerst unter die Dusche.
Du stinkst zum Himmel.“
