== [big-number]#2019# Strandcafé in Dahab

[text-caps]#Marianne saß auf# einigen Sitzkissen in einem Strandcafé in Dahab, einem kleinen Touristennest am Roten Meer.
Sie lehnte sich zurück und dachte an die Reise von Berlin hierher.
Drei Monate hatte sie gedauert.
Sie hatte den größten Teil der Strecke per Anhalter zurückgelegt.
Einmal konnte sie in einem winzig kleinen Privatflugzeug mitfliegen.
Auf der Reise trug sie ausschließlich Hippi-Kleidung.
Sie lächelte bei dem Gedanken.

Auf dem niedrigen Tischchen vor ihr lag ein Laptop und ein weiterer auf ihrem Schoß.
Sie schaute über das Meer, auf die Kite-Surfer, die direkt vor dem Café ihre Runden zogen und dann dahinter auf die leicht verschwommene Küstenlinie von Saudi-Arabien auf der anderen Seite des Meeres.
Sie war allein im Café.
Nur Achmed, der Barkeeper, war hinter dem Tresen gerade dabei, einen Milchshake zurecht zu machen.
Achmed war Mitte Zwanzig, mit wuscheligem schwarzen Haar und immer einem unscheinbaren Lächeln auf den Lippen.

Mit einigen eleganten Schritten kam er mit dem Milchshake auf Marianne zu und stellte es vor sie auf das Tischchen.
Sie war inzwischen wieder versunken in ihren Laptop und schien ihn nicht zu bemerken.
Er schaute sie eine Weile an und setzte sich dann neben sie, worauf sie sich überrascht zu ihm hindrehte.
Er lächelte warm.

Achmed: „Achmed!“ Er streckte ihr die Hand entgegen.
Sie nahm sie ein wenig zögernd.

Marianne: „Waltraut.“

Achmed: „Woldraud?“

Marianne: „Wal-t-rau-t.“

Er nickte ihr freundlich zu.

Barkeeper zeigte auf den Milchshake: „Der geht auf mich!“

„Warum?“ fragte sie und schaute ihn an.
Er wurde ein wenig unsicher.

Barkeeper: „Du bist heute zwei Wochen hier.
Das muss man feiern! Und ich feiere, dass ich nach zwei Wochen endlich deinen Namen weiß.“

Marianne lächelte: „Danke!“

Achmed: „Du bist aus Deutschland?“

Marianne schaute ihn überrascht an, zuckte mit den Schultern.
Dann lächelte sie ihn an und drehte sich wieder zu ihrem Laptop.

Er saß eine Weile stumm neben ihr und meinte dann: „Hej, du hast die ganze Zeit hier niemanden getroffen und kaum etwas gesprochen, außer, wenn du etwas zu trinken und zu essen willst, oder um zu sagen, dass dich niemand stören soll.“

Sie schaute ihn wieder an.

Achmed: „Und das geht hier nicht so! Das ist das Eel Garden Café.
Hier sprechen die Menschen miteinander.
Das ist nicht gut, wenn man nicht miteinander spricht.
Allein sein ist nicht gut.
Ich wüsste zum Beispiel gerne, was du da machst.
Du benutzt seltsame Programme.
Nur bunter Text und so.
Keine Filme, kein Facebook.
Ein Freund von mir macht das auch so.
Er ist Hacker.
Du weißt sicher, was Hacker sind? Er ist ein richtiger Hacker!“

Marianne: „Mohammed.“

Achmed nickte überrascht.

Marianne: „Wegen ihm bin ich hier.
Er hat mir gesagt, dass du ok bist.
Der beste Platz für mich hier in Dahab.“

Achmed schaute sie verblüfft an: „Er, er hat mir nichts gesagt.“

Marianne: „Ich wollte das nicht.“

Achmed: „Dann bist du auch ein Hacker?“

Marianne: „Eine Hackerin.“

Achmed schaute sie mit leicht geöffnetem Mund an.
Pling! Klang es von der Bar.

Achmed: „Oh, ein Gast.
Ich komme gleich wieder.
Bleib hier!“

Marianne drehte sich wieder zu ihrem Laptop.
Es war gerade so spannend.
Sie war in den letzten Tagen einige große Schritte weitergekommen.
Sie konnte eine Karte von einem Computernetz innerhalb der TAO, der Elite-Hackergruppe in der NSA, zeichnen.
Zwei weitere Rechner hatte sie heute Morgen dazubekommen.
Sie war dort an einer ganz, ganz zentralen Stelle.
Diese Stelle war unglaublich abgesichert, wie Fort Knox.
Nichts konnte da einfach so unbemerkt herein- oder herausgeschmuggelt werden.
Da musste etwas Wertvolles sein, etwas, was sie mit allen Mitteln schützen wollten.

Seit sie auf der Flucht war, bekam sie viel besseren Zugang zu allem: Passworte, Schlüssel, Programme, erfolgreiche Hacks.
Es war unglaublich.
Von überall kam Hilfe.
Es gab es tatsächlich, das verborgene Netzwerk der Hacker.
Das wusste sie jetzt.
Und sie wusste auch, dass sie dort inzwischen bekannt war.
Sie hatte einen guten Ruf, man traute ihr.
Und seit das so war, musste sie nur Fragen stellen, und ein paar Stunden oder Tage später hatte sie eine Antwort oder gleich ein Programm.
Das Einzige, was sie unbedingt wissen wollte, was sie noch nicht herausbekommen hatte, war, wie es ihrem Bruder Paul ging.
Nur dass er am Leben war, wusste sie inzwischen, irgendwo in den USA.
Aber dass sie da noch nicht mehr herausgefunden hatte, spornte sie jetzt eher an, als dass es sie niederdrückte.
Sie spürte die Kraft dieser dunklen Gemeinschaft, Menschen, die anonym lebten, die ihr Leben riskierten, für … ja, für was? Für eine bessere, menschlichere Art miteinander umzugehen, besser zusammenzuarbeiten, für weniger Ungerechtigkeit, mehr Offenheit.
Ja, für eine neue Art zusammen zu leben.
Und sie waren unfassbar schlagkräftig.

Achmed, den Barkeeper, hatte sie von Anfang an gemocht, aber sie hatte entschieden, Abstand zu halten.
Er hatte mit alldem nichts zu tun, er würde es kaum verstehen.
Aber Mohammed meinte, dass sie ihm mit allem vertrauen könne, mit allem! Es war seltsam, dass Mohammed das sagte.
Aber das hatte für sie eine große Bedeutung.

Mit Mohammed tauschte sie sich mehrmals am Tag aus, viel Persönliches.
Es tat gut, über Gefühle zu sprechen, auch über Achmed, über seine lustigen schwarzen Locken und seine warmen Augen, wie unsicher er ihr gegenüber war und wie er ständig mit Gästen schummelte.
Am besten war er, wenn sie es merkten.
Er schaffte es immer irgendwie raus.
Und die meisten kamen dann auch wieder.

Um Mohammed zu schreiben verwendete sie Pond, ein E-Mail-Programm, das wie gemacht war für Tails.
Sie hatte nicht mehr viel Auswahl, wie sie kommunizieren konnte, sie war ziemlich weit oben auf der weltweiten Fahndungsliste der Geheimdienste.
Aber Pond vertraute sie.
Pond sendete sobald es gestartet wurde, in unregelmäßigen Abständen immer gleichgroße Nachrichtenpakete in das Tor-Netzwerk.
Egal, ob sie gerade eine Nachricht geschrieben hatte oder nicht.
Wenn nicht, dann wurden leere Nachrichten weggesendet.
Niemand konnte von außen herausfinden, ob jemand gerade etwas schickte oder nicht, auch nicht an wen oder wie viel.
Und im Netz sausten die von außen nicht unterscheidbaren Pakete von allen Pond-Nutzern kreuz und quer zwischen den Tor-Knoten herum, es war unmöglich sie einzelnen Pond-Nutzern zuzuordnen.
Ein heiloses Chaos – aus der Sicht von Geheimdiensten.

„Jetzt!“, Achmed plumpste neben ihr auf ein Kissen.
„Erzähl.
Was machst du so? Hilfst du Mohammed?“

Marianne: „Manchmal“.
Sie lächelte ihn an und dachte, dass sie doch gerne mit Achmed redete.
Ihr Bruder hatte ihr gesagt, dass das, was „die“ wollen, damit meinte er meistens die Geheimdienste, ist, dass wir weniger miteinander kommunizieren, vorsichtiger oder sogar überhaupt nicht mehr.
Was wir hingegen wollen, meinte er, ist, dass wir frei kommunizieren können, so viel wir wollen.

Marianne: „Ich programmiere ein bisschen, halte meinen Computer von Eindringlingen frei und gerade versuche ich herauszufinden, welche Computer in einem bestimmten Computernetz sind und was die so machen.
Und vielleicht wie ich da hineinkomme.“

Achmed: „Klingt spannend.
Hab ich keine Ahnung davon.
Aber ich kann kochen und tauchen, ich war letzte Woche einmal auf 65 Meter Tiefe, nachts.
Das ist super.
Da fühlst du dich wie im Weltall.
Du schwebst völlig schwerelos in der Dunkelheit.
Es ist eine ganz andere Welt dort unten.“

„Pling“, klang es von der Bar.

Achmed: „Mist.
Viel los heute.
Programmierst du mir was?“ Er sprang auf und beeilte sich an die Bar.
Sie lächelte ihm nach.
