== [big-number]#1915# Kampf am Brandenburger Tor

=== SZENE 4
____
Hilde und Wilhelm in inniger Umarmung mitten auf dem Paradeplatz vor dem Brandenburger Tor.
Um sie herum geschäftiges Treiben, Wagen, Menschen mit Plakaten, Fahnen, Knüppeln, viel Aufregung, Geschrei.

Adolf tritt von hinten an Wilhelm heran und klopft ihm auf die Schulter.
Der löst nach kurzer Zeit die Umarmung und wendet sich ihm zu.

Wilhelm: „Adolf! Was gibt es?“

Adolf: „Es geht los.“

Wilhelm nickte.
Er küsste Hilde auf die Wange und sie schauten sich noch einmal tief in die Augen.
Dann folgte er Adolf durch die dichter werdende Menschenmenge in Richtung eines kleinen Rednerpodestes.
Adolf sprang hinauf, nahm das riesiges Megaphon, was dort auf einem Tisch lag und fing an damit laut „Heja, heja, heja“ zu rufen.

Die Menschenmenge wandte sich langsam zu ihm hin und stimmte in das „Heja“ ein.
Nach einer Zeit hatten sich alle zum Rednerpodest hingewendet.
„F R E I H E I T“ brüllte Adolf so laut er konnte.
„F R E I H E I T“ brüllte die Menge zurück.
„F R I E D E N“, wieder ein mächtiges Echo.
Es schallte von allen Seiten des Platzes zurück.
„S O Z I A L I S M U S“.
Alle Fäuste gingen hoch.
Der ganze Platz war ein brüllendes Meer aus wogenden Schildern, Fahnen und Fäusten.
Wilhelm nahm das Megaphon.

„Genossen!“ Die Menge brüllte weiter.
„Genossen! Heute ist der Tag …“ Ein Mann stürzte auf die Bühne, atemlos, fasste Wilhelm an der Schulter, beugte sich keuchend nach vorne: „Die, die Deutschnationalen … dort …“ Er zeigte die lange Promenade entlang in Richtung Alexanderplatz.
„Sie kommen!“ Wilhelm versuchte in der Ferne etwas zu erkennen.
Er erschrak, nahm das Megaphon und brüllte „SPARTAKISTEN! SPARTAKISTEN! Die Deutschnationalen kommen.
Holt eure Knüppel raus.
Sie kommen nicht in Frieden.“ Mit einer großen Geste zeigte er in die Richtung, wo etwa einen halben Kilometer entfernt eine Menschenmenge zu erkennen war.
„Sie sind unsere Feinde! Aber wir nicht die ihren.
Aber wir müssen sie stoppen.
Mit aller unserer Kraft.
Sie wollen uns vernichten.
Das wird ihnen nicht gelingen.
VOLLE KRAFT …“

„VORAUS“ antwortete die Menge.
Knüppel erschienen, Fahnen wurden zusammengerollt, die Menge setzte sich in Bewegung.
Wilhelm drehte sich zu einigen Männern hin, die um das Podest standen, um es zu beschützen: „Geht ihr auch! Ich komme hier zurecht.“
____