== [big-number]#2064# Eine neue Aufgabe

[text-caps]#Lasse und Sigur# liefen den Grasweg hoch auf eine Rundhütte zu, die auf einem großen Felsen stand.
Die Abendsonne leuchtete die Hütte vollständig aus.
Sie bestand aus einem Kreis von mannshohen Steinen und einem geschindelten Holzdach auf Holzstelzen.
Zur Sonnenseite hin war sie offen.
Dort brannte in der Mitte ein Lagerfeuer.
Lilly saß vor der Hütte auf dem Felsen und blickte in eine weitläufige Landschaft aus Äckern, Gärten, Häusern und einem See.

Lilly: „Hej, Lasse, hej, Sigur, geht nur rein.
Sie wartet schon.“

Lasse und Sigur gingen links und rechts am Lagerfeuer vorbei in die Hütte.
Drinnen saß Marianne auf einem großen Kissen, vor sich ein kleines Tischchen mit Tee.
Sie begrüßte sie mit einem warmen Lächeln.

Marianne: „Setzt euch.
Nehmt euch Tee.“

Sie musterte die beiden, wie sie ihren Tee einschenkten.
Lasse mochte es, hier in dieser Hütte zu sein.
Sie hatte eine besondere Atmosphäre.
Vielleicht waren es die großen Steine, oder das schöne, sehr asymmetrische Holzdach, vielleicht auch einfach das Lächeln von Marianne.
Er konnte hier ruhig werden.
Sigur war zum ersten Mal hier.
Er fühlte sich nicht wirklich wohl, verstand nicht, wozu das alles da war und warum er hierher kommen sollte.
Er hätte viel lieber einfach im Spielbericht gelesen, was passiert war und was das für Folgen hatte.
Einfach, sachlich, nicht so ein Brimborium drumherum.
Was soll das für einen Unterschied machen, wenn man sich in so eine virtuelle Hütte setzte.
Mehr als im Spielbericht konnte ja hier auch nicht passieren.

Lasse: „Marianne …“

Sie unterbrach: „Ich weiß, Lasse.“

Sie nahm einen Bleistift und zeichnet damit auf ein Blatt Papier vor ihr einen Fünfstern, bei dem ein Sternzacken offen war.

Marianne: „Wisst ihr, was das hier ist.“

Sigur zuckte mit den Schultern: „Ein Fünfstern“.

Marianne wies auf die offene Stelle.

Lasse: „Das Zeichen hatten die Kampfroboter vorne auf der Spitze.
Aber du musst es umdrehen.
Die offene Stelle muss oben sein.“

Marianne nickte: „Genau! Das ist das Zeichen der Sorat Rangers.
Es sind immer fünf.“

Lasse: „Die Sorat Rangers.
Fünf.
Soll das heißen, dass das eben … das eben waren die Sorat Rangers? Fuck.
Nein.“

Sigur: „Nee.
Auf keinen Fall.
Das waren sie nicht.“

Marianne fasste sich an die Nase: „Warum nicht?“

Sigur: „Die Sorat Rangers sind eine Eliteeinheit der CIA, sie sind die Elite-Kampfroboter-Einheit der CIA.
Sie kommen dann, wenn irgendein großes Ding läuft.
Und wenn sie kommen, dann räumen sie auf.
Sie haben eine Effizienz von 100%.
Alle Einsätze erfolgreich beendet, nie einen Roboter verloren.
Die holen wir nicht so einfach vom Himmel, ohne Vorbereitung.
Das sind die Besten der Besten.
Da bräuchten wir zwanzig fliegende Kampfroboter, und dann noch gut programmierte Formationen, eine gute Taktik.
Aber nicht ich und Lasse einfach so, aus dem Stand.
Vergiss es.
TRON ist realistisch.“

Marianne: „Wenn die Sorat Rangers das wären, für was sie gehalten werden, dann hättest du Recht.
Dann wäre das für euch wahrscheinlich böse geendet.
Sie sind es aber nicht.
Du bist da leider auf die CIA-Einschüchterungs-Propaganda hereingefallen.
Die Sorat Rangers sind eine Gruppe, die für gestellte Attentate zuständig sind, nicht für echte.
Sie müssen nicht die Besten der Besten sein, weil ihre Aufträge allesamt gestellt sind.
Sie sind gute Piloten, aber nicht absolute Elite.
Das ist in TRON so und das war auch in Wirklichkeit so.“

Lasse: „Sie waren echt? Es gab sie in echt?“

Marianne nickte: „Mhmh.
Und als ihr sie heute erwischt habt, war die Formation gerade unterwegs zu einer Mission, die in Wirklichkeit im Jahr 2025 stattgefunden hat.
Ein Treffen von Staatspräsidenten und Armeeführern des Nahen Ostens, in Khandahar.
Die wurden in dem Augenblick gerade von anderen Kampfrobotern angegriffen, von russischen, die in Wirklichkeit aber auch von der CIA, bzw.
einem befreundeten Geheimdienst geflogen werden.
Wahrscheinlich war es der Mossad.
Wir wissen das nicht sicher.
Auf jeden Fall geht das gründlich schief.
In TRON und auch in Wirklichkeit.
Weil der Fünfstern nicht kommt.
Sie werden kurz vorher abgeschossen.
Ein paar Minuten vorher.
Wir wissen nicht, warum das in Wirklichkeit so war … in TRON wissen wir es.
In TRON ward ihr das.
Was jetzt gerade im weiteren Verlauf passiert, ist, dass durch einige Missverständnisse in der Leitstelle und zwei falsche Kommandos die gesamte Versammlung dort in die Luft gebombt wird.
Alles wird dem Erdboden gleich gemacht.
Es gab 122 Tote.
Darunter sieben Staatspräsidenten.“

Lasse: „Der Mittelost-Krieg! Dann kam der Mittel-Ost-Krieg!“

Sigur: „Mit der Atombombe auf Salina.
Scheiße.“

Marianne: „Noch nicht gleich.
Es fehlt noch etwas.“

Lasse und Sigur schauten Marianne an.

Marianne: „Die Drahtzieher dieses Scheinangriffs dürfen nicht im Verborgenen bleiben.
Es muss klar sein, dass das alles gestellt war und in die Hose gegangen ist.
Dann, dann erst kommt der Krieg.
Sonst kommt etwas anderes.
Und ihr sollt …“

Lasse: „..
wir sollen das aufgedecken.
Wir sollen herausfinden, wer das bei der CIA gemacht hat.“

Sigur: „Was anderes kommt sonst, wenn nicht der Mittelost-Krieg?“

Marianne: „Nein, nicht bei der CIA.
Es gibt einen bislang unbekannten Geheimdienst in den USA, der für das hier verantwortlich ist.
Die CIA ist in diesem Fall nur Tarnung.
Die Sorat-Rangers fliegen für den unbekannten Geheimdienst.
Und den müsst ihr finden.
Das ist die Aufgabe.
Geht in drei Tagen zu dieser Konferenz in Caracas und trefft genau um diese Uhrzeit an diesem Ort einen Frederick Peterson.
Dann werdet ihr eine Chance haben.“

Sie gab Lasse einen Zettel.

Lasse schaute sie an: „Venezuela?“

Sigur: „Wenn es anders kommt … wird dann die Atombombe nicht geworfen?“

Marianne: „Ich weiß, was du denkst.
Ihr sollt dafür sorgen, dass es zu einem Krieg kommt, bei dem eine Atombombe gezündet wird und viele Menschen sterben.
Du musst das nicht tun.
Du musst selber denken und entscheiden, was du für richtig hältst.
Ich sage nur, dass ihr herausfinden und bekannt machen sollt, dass es diesen geheimen Geheimdienst gibt.
Und wie er arbeitet.“

Lilly stand im Eingang und gab Marianne ein Zeichen.

Marianne: „Ok.
Ich muss gehen.
Viel Glück euch, ihr Cypherpunks.“

Sie stand auf ging hinaus.

„Ich bin kein Cypherpunk“, murmelte Sigur und trottete hinter Lasse aus der Hütte.
