== [big-number]#2064# Die Kommandozentrale

[text-caps]#Marianne lief mit Lilly# den Felsen hinunter. Am der dunkelgrünen Hyper-Tür, die am Fuß des Felsens stand, gingen sie vorbei. Lasse und Sigur hinter ihnen verschwanden mit einem leichten blauen Lichtzucken darin.

Marianne: »Was gibt's? Warum hast du mich geholt?«

Lilly: »Einer der Raben kam angeflogen und sagte, dass es im KCT ein Problem gäbe und du gebraucht würdest. Das ist so süß wie die Raben vor einem landen, sich verneigen und dann warten bis man das volle Bewusstsein bei ihnen hat.«

Marianne: »Ein Rabe landet vor dir?«
Sie schüttelte den Kopf.
Dann bist du jetzt wohl Teil der Spielleitung.
Sie haben dich akzeptiert.
Ganz schön schnell.«

Lilly: »Was ist das KCT?«

Marianne: »Das Kommando Center Taurus.
Aber das ist noch nichts für dich.«

Lilly bekam glänzende Augen und schaute Marianne an.

Marianne: »Nein! Nein. Nein ...
Du bist 12.
Das geht nicht.
Das ist Ernst.
Das ist nicht mehr Teil des Spiel.
Das ist Teil der Verteidigung.
Der echten Verteidigung.«

Lilly nahm ihre Augen nicht von Marianne.
Lilly: »Ich weiß. Taurus, die Verschwörung, Saruman.«

Marianne schaute sie erstaunt an: »Woher weißt du das?«

Lilly: »Du schreibst davon in deiner Biographie.«

Marianne: »Das ist kein Wort über eine Verschwörung und kein Wort über Saruman und überhaupt nichts über Taurus.
Das ist nur eine Beschreibung, was passieren könnte, wenn es Hacker gäbe, die eindringen wollten.«

Lilly schaute Marianne aus den Augenwinkeln an: »Komm. Das war doch klar, dass das nicht nur Theorie war.
Das war viel zu konkret.
Das habe ich beim ersten Mal Lesen verstanden.
Und im Archiv zu deiner Biografie habe ich dann den Rest dazu gefunden.«

Marianne: »Du hast mein Archiv gehackt? Fuck.«

Lilly schaute kurz zu Boden: »Habe ich was Böses gemacht?
Das war nicht soooo gut geschützt.
Wenn du wirklich gewollt hättest, dass das niemand bekommt, dann...«

Marianne: »... es war ein privates Archiv, keine Schwachstellendatenbank ...«

Lilly: »Informationen, die für alle sind.«

Marianne: »Für alle Erwachsenen!«

Sie schauten sich in die Augen.

Marianne schaute kurz zu Boden und nickte dann: »Gut.
Ok.
Du bist selbstständig hineingekommen, du hast keine persönlichen Informationen gesehen.
Ist ok.
Hat dich davon etwas durcheinander gebracht?
Hast du Fragen zu dem, was du dort gesehen hast?«

Lilly bekam wieder ihre leuchtenden Augen: »Tausende.«
Sie lächelte vorsichtig.

Marianne: »Lilly! Ich meine das ernst.
Da sind Sachen dabei, die verstören können.
Es gibt Menschen, die haben deswegen Albträume.«

Lilly: »Ich will das wissen.
Im Ernst.
Ich weiß, dass die Akademie ständig angegriffen wird.«

Marianne strich sich mit der Hand über den Mund und schloss die Augen.
Sie stand eine Weile mit geschlossenen Augen, öffnete sie wieder und schaute Lilly ernst an:
»Gut, dann komm mit ins KCT.«

Lilly riss die Arme in die Höhe: »Japp!«

Marianne berührte das Amulett, das um ihren Hals hing, murmelte etwas und sagte dann deutlich: »Promote Lilly Browdowin to apprentice defence admin.«

Rechts von Lilly erschien eine rote Hyper-Tür.
Sie erschrak leicht.

Lilly: »Wow! So, schnell. Keine Fee als Rückmeldung?«

Marianne: »Alte Linux-Regel: No news is good news. Wenn es klappt, dann kommt keine Meldung.
Willkommen bei der Verteidigung der Akademie!«

Lilly atmete durch: »Wow!«

Marianne deutete auf die Tür und Lilly schritt hindurch.
Marianne folgte ihr.
s
