== [big-number]#2021# Nach Hause?

[text-caps]#Paul saß in# einem fensterlosen Besprechungsraum an einem Tisch.
Ihm gegenüber ein Mann und eine Frau in Geschäftskleidung.
Zwei Soldaten standen in den beiden Ecken hinter ihm, ein weiterer breitbeinig, mit verschränkten Armen vor der Tür.

Frau: „Paul Lasser!“ Sie nickte ihm zu.

Paul war sprachlos.
Er hatte seinen Namen zwei Jahre lang nicht mehr gehört.
Und jetzt hier.
Er schüttelte den Kopf.
Schüttelte noch einmal, nickte dann aber.

Frau: „Was jetzt? Sind Sie Paul Lasser?“

Paul: „Ja, das bin ich.“ Er verkniff sich „Woher kennen Sie meinen Namen?“ zu fragen, oder „Haben Sie meine Karteikarte nach zwei Jahren endlich wiedergefunden?“ Früher wäre das für ihn unwiderstehlich gewesen.
Jetzt passte es für ihn nicht mehr.
Er hatte den Geschmack an solchem Humor verloren.
Er schaute beide an und versuchte sich so gut wie möglich hineinzufühlen, warum sie hierher gekommen waren und ihm Fragen stellen wollten.
Die beiden schienen wirklich etwas zu wollen.
Das war neu.
Vieles war neu heute.

Frau: „Wie geht es Ihnen gesundheitlich?“

Paul drehte den Kopf und deutete auf die Stelle mit der Blutkruste.
Dann schob er seine Unterlippe nach unten und zeigte eine Lücke mit drei fehlenden Zähnen.

Paul: „Ausgeschlagen.“ Er schaute sie etwas abwesend an.

Die Frau stöhnte leise: „Können Sie laufen?“

Paul: „Laufen, sitzen, pinkeln, springen, auf einem Bein stehen.
Tanzen habe ich schon lange nicht mehr probiert.
Schreien! Darf ich? Warum werde ich hier festgehalten? Was wollen Sie von mir?“

Mann: „Wir wollen ihren Gesundheitszustand feststellen, um eine eventuelle Freilassung vorzubereiten.“

Paul drehte sich zu ihm und schaute ihn erstaunt an.
Das ist das Letzte, was für ihn Sinn machen würde.
Ihn freilassen? Mit all dem, was er hier erlebt hatte? Mit all den Kontakten, die er von früher hatte, die ihm immer noch vertrauten, und denen er einiges Neues über die Realität der Hackerverfolgung des 21.
Jahrhunderts erzählen könnte.
Inklusive Folter.
Nein! Das war das Letzte, was sie wollen konnten.
Ein Trick? Vielleicht.
Nein, wahrscheinlich.
Er beschloss nichts zu sagen.

Mann: „Wollen Sie hier raus? Wollen Sie nach Hause?“

Paul schaute den Mann abwesend an und schwieg.
„Nach Hause … zu Marianne … zu den Eltern … nach Berlin“, dachte er.
Eine Träne drückte von innen hervor und begann das rechte Augenlid zu füllen.
„Nichts anmerken lassen“.
Er faltete die Hände vor sich auf dem Tisch und schloss die Augen.

Frau: „Wir wissen, Sie haben Schlimmes erlebt.
Aber es kann jetzt vorbei sein.
Ich habe ihre Akte gelesen.
Ich weiß, was Sie durchgemacht haben.
Lichtentzug, Schlafentzug, ungerechtes Schlagen, nackt in der Kälte im Schlamm stehen.
Sie hatten eine Lungenentzündung.“ Paul schlug seine Augen auf und schaute sie an.
Sie fuhr fort: „Falsche Nachrichten: Verhaftung und Tod ihrer Schwester …“

„Mari!“, platzte es aus ihm heraus.
Er schaute der Frau in die Augen.
Er schaute noch einmal.
„Die Nachricht war gar nicht echt! Er hatte ihr vertraut.
Es war eine Lüge.“, dachte er.
„Shit, ich habe nicht daran gedacht, dass die Nachricht falsch sein könnte.“ Er schaute wild um sich.
„Marianne ist nicht tot?“, fragte er leise in Richtung der Frau.
Sein Herz fing an zu klopfen.
Wie hatte er das glauben können? Warum in aller Welt hatte er diesen Arschlöchern das geglaubt? Warum? Er sprang auf, riss an den Handfesseln, die klirrten wie in einem mittelalterlichen Kerkerverließ.
Dann schrie er so laut er konnte: „Schweine! Schweine! Arschlöscher!“ Die zwei Männer hinter ihm packten ihn und drückten ihn auf den Tisch.
Einer holte mit einer Handbewegung ein schwarzes Klebeband heraus und riss ein Stück ab.
Der andere hielt derweil Pauls Kopf bereit.

Frau: „Stopp! Stopp! Kein Klebeband.
Es stirbt doch niemand, wenn er schreit.
Gehen Sie zurück in ihre Ecken!“

Paul lag heulend auf dem Tisch.
Er wimmerte: „Schweine, Schweine, Schweine.“

Der Mann und die Frau blickten eine Weile auf Paul, wie er mit den Händen über dem Kopf auf dem Tisch lag, und sahen sich dann an.
Der Mann zuckte mit den Schultern, griff nach seinem Ordner auf dem Tisch und wollte aufstehen.
Die Frau hielt ihn am Arm.

Frau: „Warte noch.“

Er setzte sich wieder.

Nach einer Weile schaute Paul hoch und wischte sich die Tränen aus den Augen.
Die Frau schob ihm eine Packung Papiertaschentücher zu.
Er ignorierte sie.

Paul schaute sie an: „Wo ist Marianne?“

Die Frau blickte kurz nach unten: „Ich weiß, dass das unendlich schwer zu ertragen ist.
Aber wir müssen da jetzt durch.
Es sind Fehler passiert.
Schlimme Fehler.
Es wird eine Untersuchung geben …“

Paul unterbrach: „Wo man niemals erfährt, was dabei herausgekommen ist, wer was warum gemacht hat und warum er oder sie das jetzt nicht mehr tun soll.“

Frau: „Es wird eine Untersuchung geben.
Ich weiß, das Strafverfolgungssystem der Vereinigten Staaten ist weit davon entfernt, perfekt zu sein.
Aber es ist das Beste, was wir haben.
Und wir haben schon viele Fehler korrigiert.
Heute können wir vielleicht einen weiteren korrigieren.“

In Paul stieg wieder die Wut hoch, unendliche Wut.
Aber diesmal konnte sie er halten.
Sie übermannte ihn nicht.
Marianne war am Leben.
Das gab ihm neue Kraft.
Er hatte nach der Frage, wo Marianne sei, in den Augen der Frau gesehen, dass sie sie kannte und wahrscheinlich wusste, wo sie war.
„Gott!“, durchfuhr ihn ein Gedanke.
Ihm stockte der Atem.
„Sie wollen Mari.
Und sie brauchen mich dafür … Nein! Nein.
Nein, das werden sie nicht bekommen.
Lieber sterbe ich.
Ich bleibe hier! Wenn Mari es bis jetzt geschafft hat, dann hat sie die Welt durchgepflügt, dann steht an einigen Stellen kein Stein mehr so wie er war.“
Er kannte sie gut.
Er lächelte leicht und dachte: „Ihr habt euch mit Mari angelegt … jetzt müsst ihr allein sehen, wie ihr da wieder herauskommt.“
