== [big-number]#2019# The Boatly Hackerspace

[text-caps]#Achmed kam von# der Strandseite aus in das Cafe und schlich sich von hinten an Marianne an. Er fasste sie an beiden Schultern und küsste sie auf die Wange. Marianne drehte sich erschreckt um, aber lächelte, als sie Achmed sah. Sie küssten sich. Achmed sprang über die Kissen, an die sich Marianne anlehnte, und landete mit einem breiten, warmen Lächeln neben ihr. Seine Augen funkelten. Er nahm ihre Hand.

Achmed: „Du bist so schön, ich kann es nicht glauben. Ich könnte dich die ganze Zeit nur anschauen. Komm! Ich muss dir etwas zeigen. Wirklich toll. Eine Überraschung. Dafür müssen wir ein wenig tauchen. Bist du schon mal getaucht?“

Marianne schaute skeptisch: „Ja. Aber nur mit Schnorchel, ohne Flasche.“

Achmed: „Macht nichts. Es ist nicht so tief und ich bin der beste Tauchlehrer hier am Strand.“

Marianne: „Ich kann jetzt nicht tauchen gehen.“

Achmed: „Komm. Es wird dir gefallen. Ganz sicher. Mohammed meint auch, dass es dir gefallen wird.“

Marianne stutze: „Ok. Hat er das gesagt? … dann, gut.“ Sie zögerte wieder. „Nein, es geht nicht.“

Achmed hob den Zeigefinger: „Ah, klar. Ich weiß.“ 

Er sprang auf, hinter die Bar und kam wieder mit einem schwarzen Aktenkoffer aus Gummi.

Achmed: „Hier für deine Laptops. Der ist wasserdicht. Darin kannst du sie mitnehmen.“

Marianne schaute ihn erstaunt an, nahm den Koffer und tatsächlich, er war groß genug für beide Laptops.

Achmed: „Ich kann ihn umschnallen. Ist besser, wenn du beim ersten Mal nicht so viel Gewicht an dir hast. Warte hier, ich bin gleich zurück.“

Er sprang auf und kam Minuten später vollbeladen mit Tauchausrüstung zurück. 

Sie zogen die Ausrüstung an und gingen zum Strand, wo ein kleines Fischerboot mit Außenbordmotor lag. Marianne stieg ins Boot, Achmed schob es heraus und sprang hinein. Er startete den Motor und das Boot machte einen Satz nach vorne. Marianne, die sich noch nicht richtig gesetzt hatte, verlor das Gleichgewicht und fiel Achmed auf den Schoß. Er legte den Arm um sie.

Achmed grinste: „Das ist meine Spezialität! Habe ich lange dafür geübt.“ Beide lächelten und küssten sich. Achmed gab Gas.

„So schön!“, dachte Marianne, lehnte sich an und ließ sich den Wind durch die Haare wehen. „So könnte das immer sein.“

Etwa 500 Meter weiter stoppte Achmed das Boot. Er stand auf und schaute ins Wasser, er schient etwas zu suchen. Er schaut wieder zum Strand hin, der noch gut zu sehen war. Dann schien er etwas zu entdecken und warf den Anker.

Achmed: „Hier können wir rein. Da, schnall die Sauerstoffflasche um, setz deine Brille auf und dann, schau, hier, du lässt dich hier so rückwärts reinfallen, dann passiert nichts.“

Beide nahmen ihre Flaschen, setzten die Brillen auf und Marianne ließ sich ins Wasser fallen. Achmed sprang hinterher. Unter Wasser gab er ihr Zeichen, ihm zu folgen. Es ging tiefer und auch ein ganzes Stück weg vom Boot. Sie schwammen etwa fünf Minuten, bevor Achmed in eine Schlucht hinuntertauchte und aus dem Schatten ein graues, metallenes Etwas auftauchte.

„Was ist das? So groß! Riesengroß. Bestimmt 30 Meter lang“, dachte Marianne. „Hmm? Ein Schiff? Ja, ein Schiff.“ Es lag ein wenig gekippt an der unteren Kante der Schlucht in etwa 20 Metern Tiefe und war augenscheinlich noch ziemlich vollständig erhalten. Aber alt, sehr alt. Mohammed machte sich an einem Drehrad einer Metalltüre zu schaffen und nach ein paar Versuchen öffnete sie sich. Er gab Marianne ein Zeichen ihm zu folgen und verschwand hinein. Drinnen war ein Gang, der auf eine Treppe zulief. Sie schwammen hinunter, wieder ein Gang, einmal rechts und dann eine kleine Metallleiter hinauf wieder durch eine Luke. Und dahinter war es anders, seltsames Licht. Achmed schwamm nach oben und sein Kopf verschwand. Sie hinterher und: Luft. Eine Wasseroberfläche und Luft. In einem ziemlich großen Raum. Sie zogen ihre Tauchmasken ab.

Marianne: „Wow! Das ist ja ein Ding. Woher kommt denn die Luft? Das ist gute Luft.“

Achmed: „Vom Strand. Wir haben einen Schlauch gelegt, damit man hier an der Wasseroberfläche nichts sieht.“ Er formte mit Daumen und Zeigefinger einen Kreis. „So dick. Da pumpen wir ab und zu Luft durch. Und schau da!“ Er zeigte ans Ende des Zimmers: Da stand auf einem großen Gitterpodest, vollständig außerhalb des Wassers, ein Tisch, eine Bank, Stühle, ein Kühlschrank, eine Lampe und weiter hinten, ein Bett. Rechts neben der Leiter, die dort aus dem Wasser führte, hing ein Schild:

„Dahab Boatly Hackerspace“

Marianne lachte laut: „Wie geil!“ Sie schwamm hin und kletterte aus dem Wasser.

Marianne: „Geil! Ein Hackerspace! Aber dann muss es hier auch Internet geben....“

Achmed: „Klar. 10 Megabit Internet. Nicht schnell, aber immerhin“ Er deutete auf ein Kabel, das von der Decke baumelte. „Und Licht!“ Er knipste das Licht an.

Marianne zog ihre Tauchausrüstung aus und fläzte sich auf die Bank. 

Marianne: „Wie geil! Hier will ich bleiben.“

Achmed: „Klar, das kannst du. Das ist jetzt für dich.“

Marianne: „Ich meine das ernst. Das passt jetzt gerade so gut. Ich bin gerade bei einer Sache, die ich am liebsten von hier aus machen würde.“

Achmed: „Ich weiß.“ Er lächelte.

Marianne schaute ihn fragend an.

Achmed: „Ich weiß nicht viel. Mohammed hat gesagt: Bring Marianne ins Boatly. Sie wird es mögen und sie wird da bleiben wollen. Und wenn Mohammed das sagt, dann stimmt das. Und ich bringe dir Essen. So Essen wie vorgestern. Dann kannst du ganz hier bleiben.“

Marianne: „Wow. Ein 5 Sterne-Restaurant ist das hier auch noch.“

Sie packte einen der Laptops aus und steckte Strom- und Netzwerkkabel ein.