== [big-number]#2019# Wo ist Marianne Lasser?

[text-caps]#Im Hauptquartier der CIA# in Langley/Virginia/USA, ein großräumiges Büro mit breiter Fensterfront.
Eine Frau und zwei Männer in Geschäftskleidung sitzen sich am ovalen Besprechungstisch gegenüber.
In der Mitte ein Kaffee-Service, Kekse, eine Metalldose für Mobiltelefone.

Frau: „Dahab und Hurghada! Ägypten.“

Erster Mann: „Ist die Information gut?“

Frau: „Definitiv.
Die Audioscanner haben angeschlagen.
Wir haben ihre Stimme von einem Smartphone in Dahab und von einem in Hurghada, jeweils weniger als 10 Meter entfernt.
Allerdings nur diese zweimal, aber ohne Zweifel.“

Zweiter Mann unzufrieden: „Nur zwei Aufzeichnungen?“ 

Frau: „Wir wissen, dass sie da ist.“

Erster Mann: „Gibt es Videodaten?“ Er hielt der Frau eine Kanne entgegen.
„Kaffee?“

Frau: „Danke.
Nein.
Sie ist vorsichtig.
Wir haben die lokalen Überwachungskameras und die Smartphone-Kameras plus minus zwei Stunden und eine halbe Meile im Umkreis durchgeschaut.
Da war nichts.“

Zweiter Mann: „Nicht einmal etwas Verdächtiges.
Eine Frau in Burka, allein, mit westlichem Gang?“ 

Frau: „Nichts Brauchbares.
Es gibt Tor- und I2P-Verkehr an beiden Plätzen.
Aber nicht viel mehr als üblich.
Und nichts, was sich zuordnen ließe.“

Zweiter Mann: „Sie geht nicht auf den üblichen Wegen ins Tornetz.
Da kriegt ihr sie nicht.
Sonst habt ihr nichts? Das ist alles? Was ist mit Jabber? Ricochet? Pond? Onion Services?“

Frau: „Jabber macht sie nicht.
Onion Services haben wir keinen Hinweis und Ricochet und Pond wissen wir nicht.
Die sind problematisch.“

Zweiter Mann lacht laut auf: „Ihr seid die NSA! Ihr kommt nach so vielen Jahren nicht in Programme rein, die ein Schulabbrecher und ein Google-Programmierer in ihrer Freizeit geschrieben haben? Warum habt ihr die nicht längst abgeschaltet?“

Die Frau schloss die Augen und kämpfte mit ihrer Wut: „Können wir bitte sachlich bleiben? Ricochet und Pond laufen verteilt im Tornetz.
Ricochet hat überhaupt keinen zentralen Server und bei Pond sind die Server dezentral.
Wenn wir einen Server abschalten, zum Beispiel den von Langley, dann bekommen wir einen WikiLeaks-Effekt: dann poppen woanders drei neue Server auf.
Jeder poplige Informatik-Student kann in 20 Minuten einen Pond-Server einrichten.

Erster Mann: „Und Tor selbst? Ihr könntet es abschalten, oder zumindest stören.“

Die Frau stöhnte: „Wir können Tor nicht abschalten.
Nicht auf absehbare Zeit.
Da hängt zu viel dran.“

Zweiter Mann: „Ihr habt RAPTOR verloren, ihr habt Hacker in eurer Feld-Kommunikation und deswegen ist Tor das Sicherste, was ihr draußen im Feld habt! Ihr braucht es selbst.
Ihr habt nichts Besseres.
Das ist die Wahrheit.
Und das ist shit! Das ist peinlich! Die NSA braucht ein Open-Source-Programm.“

Erster Mann: „Hej, stopp! Es geht hier nicht darum, dass wir uns gegenseitig Schuld zuschieben.
Wir jagen Terroristen.
Gemeinsam!“

Zweiter Mann wütend, lauter werdend: „Ich brauche gute Informationen für meine Arbeit! Mein Auftrag ist es, Marianne Lasser zu fangen, und ich werde mich nicht von irgendwelchen pupsigen Anfängern davon abhalten lassen.
Nicht einmal wenn sie bei der NSA arbeiten.“

Frau: „Keine Klarnamen!“

Der zweite Mann stand auf, voll Wut: „Ich habe genug von dem Gekusche.
Wir treffen uns hier persönlich im CIA-Hauptquartier! E-Mail, Telefon ist euch zu unsicher.
Mein Smartphone liegt in einem Blechkasten, ich soll keine Klarnamen verwenden.
Und ich bin verdammt nochmal in der Zentrale des schlagkräftigsten Geheimdienstes der Vereinigten Staaten.
Vor wem haben wir eigentlich Angst? Vor ein paar pubertierenden Jungs und Mädels in Schlabberpullis.
Wir hier bei der CIA stehen an der Front, wir kramen nicht in irgendwelchen Netzen rum und schieben Bits von einer Ecke in die andere.
Wir machen die echte Arbeit, die schmutzige Arbeit.
Wenn ich einem CIA-Feld-Offizier sage: Er soll sein Smartphone in eine Blechdose tun, dann wirft er es auf den Boden und tritt es kaputt.
Und dann sagt er mir, dass er ein besseres braucht.“

Der erste Mann fasste ihn am Arm, aber er machte sich los.

Zweiter Mann: „Ich habe echt genug von dem Pillepalle, das wir hier veranstalten.
Ich bin kurz davor Academi anzurufen.
Und die werden mir sicherlich nicht eine halbe Stunde lang alle Probleme aufzählen.“

Frau: “Academi ist eine Söldnerfirma, kein Nachrichtendienst.
Sie schicken Kampftruppen, Spezialeinheiten.
Die kannst du hinschicken, wenn wir genau wissen, wo sie ist.“ 

Zweiter Mann: „Nee, nee.
Da irrst du dich.
Die nehmen inzwischen auch Suchaufträge.
Die haben jetzt eigene Hacker.
Die können nicht immer warten, bis sie von irgendwo gute Informationen bekommen.
Wenn ich denen sage, dass Marianne Lasser in Hurghada oder Dahab ist, dann dauert es keine zwei Tage und sie haben sie.“

Erster Mann: „Und dann ist sie tot, und ein paar andere Leute gleich mit.
Wir verwenden Academi nicht für Hacker! Die machen zu viele Probleme.
Zu unsauber.
Die Lage ist aufgeheizt genug.“

Der zweite Mann machte eine Bewegung zu antworten, lehnte sich dann aber zurück in seinem Sessel, kniff die Lippen zusammen und verschränkte die Arme.

Frau: „Ich denke, das war es für heute.
Mir wäre auch lieber wir hätten mehr.
Der XKeyScore-Code für die relevanten Daten ist hier.“ Sie schob zwei handgeschriebene Zettel zu den beiden rüber.
