== [big-number]#2023# Ich will hier bleiben

[text-caps]#Die Frau schaute# Marwin vertrauensvoll an: „Wir wollen Ihnen ein Angebot machen, dem Sie nicht widerstehen können.“

Marwin verzog keine Miene.

Frau: „Sie kommen hier heute noch raus und dürfen nach Berlin fliegen.
Mit offizieller Einreiseerlaubnis von Deutschland.
Sie bekommen €50 000 in bar für einen Neuanfang und keine Einschränkungen bezüglich Ihrer Internet-Aktivitäten.“

Mann: „Und das ist sehr unüblich.
Normalerweise hieße das: Mindestens fünf Jahre kein Internet.“

Marwin stöhnte leicht.

Frau: „Und Sicherheit vor Verfolgung durch deutsche Strafbehörden.
Volle Amnestie.
Sie kriegen einen Neuanfang.
Sie können ein normales Leben leben, noch einmal neu beginnen.“

Marwin schaute sie eine Weile an und fragte: „Und was muss ich tun?“

Die Frau atmete ein: „Nicht viel.
Wir machen eine gemeinsame Story, was in den zwei Jahren passiert ist.
Warten Sie! Nicht gleich ablehnen.
Wir können Sie hier nicht einfach so rauslassen.
Das würde nicht funktionieren.
Selbst wenn ich Sie einfach freilassen wollte, könnte ich das nicht tun.
Da draußen sind sehr, sehr mächtige Leute, die genau schauen, was hier passiert, und die haben schon jetzt ungewöhnlich viel Zugeständnisse gemacht.
Sonst würden wir beide gar nicht hier sitzen.
Ein wenig müssen wir ihnen geben.
Die Welt ist nicht perfekt.
Ich halte Sie für unschuldig.
Mit dem, weswegen Sie verhaftet wurden, haben Sie nichts zu tun.
Ich würde Sie direkt freilassen.
Aber so ist die Realität nicht.“

Mann in leicht drohendem Ton: „Wenn Sie nicht mit uns kooperieren, dann werden andere kommen und mit Ihnen reden, die andere Dinge wollen.
Oder auch niemand mehr.
Das liegt nicht in unserer Macht.
Wir sind jetzt hier.
Das öffnet Ihnen das Fenster für einige Möglichkeiten.
Aber auch nicht lange.“

Marwin zur Frau gerichtet: „Warum kommen Sie jetzt? Und erzählen Sie mir keine Scheiße.
Es ist etwas passiert.
Deswegen sind Sie hier.
Sie versprechen sich Vorteile davon, mich rauszulassen.
Welche sind das?“

Mann ungeduldig: „Sie bekommen eine Chance.
Wir haben wirklich nicht viel Zeit.
Wenn wir beide hier ohne Ergebnis rausgehen, kommen wir vielleicht nicht wieder ...“

Die Frau unterbrach ihn: „Warte.
Herr Farras, Sie haben Recht.
Ich verstehe, dass Sie denken, dass das eine Falle ist, nach allem, was Sie durchgemacht haben.
Aber es ist keine.
Und es gibt tatsächlich einen Auslöser für dieses Gespräch.
Aber wiederum, ich kann Ihnen nicht alles sagen, das darf ich nicht.
So gern ich wollte.
Nur so viel: Es gab ein Umdenken auf höchster Ebene, in der Regierung, bei der Präsidentin, in Bezug auf alles, was mit Überwachung zu tun hat.
Es wird darüber gesprochen, die NSA aufzulösen.“ Sie schaute ihn eindringlich an.
Marwin schaute leicht abwesend zurück.

Frau: „Sie können sich vorstellen, dass da bei uns einiges in Bewegung ist.
Und im Zuge dessen werden auch Gefangene entlassen.
Vor allem die Unschuldigen.“ Sie senkte ihren Blick auf den Tisch.

Marwin: „Wo ist Marlene?“ Er schaute die Frau eindringlich an.
Sie schreckte leicht auf, schaute Marwin an, aber fasste sich schnell wieder: „Es geht ihr gut, soweit ich weiß.
Sie ist in Freiheit.“

Marwin verschränkte die Arme: „Ich will hier bleiben.“

Der Mann stöhnte.
Er griff nach seiner Tasche.
Die Frau schaute ihn an.

Frau: „Das glaube ich Ihnen nicht.“

Marwin: „Sie lügen mich an.
Sie sind auf meine Frage hin gerade erschrocken und haben sie dann nicht beantwortet.
Ich will hier bleiben!“ Seine Stimme vibrierte leicht.

Der Mann fasste die Frau am Arm: „Komm! Ich habe dir gesagt, das hat keinen Zweck.
Der ist vernunftresistent.
Wir sagen, sie sollen die anderen reinschicken.
Wir machen derweil mit Sudo weiter.“

„Sudo ist hier!“, schreckte Marwin auf, um dann aber sofort wieder abzuwiegeln.
„Interessiert mich nicht, interessiert mich nicht.“ Der Mann hatte schon angesetzt etwas zu sagen.

Marwin: „Ich will nichts über Sudo wissen.“

Mann: „Sudo hat ein Bein verloren.“

Marwin erstarrte.
„Scheiß Manipulationen“, dachte er.
„Wie soll ich das jetzt wieder aus dem Kopf bekommen: Sudo hat kein Bein verloren.
Sudo hat kein Bein verloren.
Sudo hat kein Bein verloren.“ Er legte seinen Kopf auf den Tisch und vergrub ihn unter seinen Händen.
Der Mann und die Frau schauten auf ihn.
Nach einer Weile richtete er sich auf, schaute teilnahmslos in den Raum und fing an leise „Allways on the bright side of life“ zu summen.

Der Mann packte seinen Ordner und verließ den Raum.
Die Frau schaute eine Weile vor sich auf den Tisch, dann noch einmal auf Marwin, und folgte ihm dann.
