== [big-number]#1915# Nach der Bombe

=== SZENE 5: Brandenburger Tor, nach einer Bombenexplosion
____
Dichter Rauch über dem Platz, blutende Menschenkörper liegen herum, Steinbrocken, Holzteile.
Menschen irren über den Platz.
Manche blutend, verstört, taub.

Hilde läuft aufgeregt suchend auf die Stelle zu, wo Wilhelm vor einer halben Stunde noch zu den Menschen geredet hat.
Das Rednerpult ist verschwunden.
Im Gewühl rund um die Stelle erblickt sie Adolf, der knieend über eine bewusstlose Frau gebeugt ist und verzweifelt bemüht ist, eine Wunde an ihrem Bauch mit einem Stofffetzen abzudrücken.

Hilde: „Adolf!“ Sie rennt zu ihm, schaut auf die Frau, dann wieder auf ihn: „Adolf! Hej!“ Adolf schaut sie hektisch an: „Wir brauchen Sanitäter.“

Hilde: „Komm, lass mich machen.
Ich brauche dein Messer und die Schur da drüben.“
Sie zeigt Richtung Bühne.
Adolf springt auf und kommt wenige Augenblicke später mit der Schnur zurück.
Hilde hat die Kleidung der Frau inzwischen aufgeschnitten und ist dabei mit ihrem eigenen Tuch die Wunde notdürftig zu säubern.
Sie blutet stark.
Mit dem Seil bindet sie den Arm der Frau ab, der ebenfalls verletzt war.
Dann presst sie das Tuch auf den Bauch.
„Da ist noch etwas drin.
Sie muss ins Spital.
Geh einen Sanitäter holen.“ Adolf verschwindet in der Menge.
Marianne prüft mit ihrem Ohr am Mund den Atem der Frau.
Sie erschrickt.
Mit einem Arm zieht sie einen vorbeitorkelnden Mann zu sich heran, drückt ihm das Tuch in die Hand und weist ihn an, es auf die Wunde zu drücken.
Dann fängt sie an mit beiden Händen kräftig gegen den Brustkorb zu stoßen.
Dreimal, viermal, dann hört  sie wieder an der Brust.
Nochmal dreimal, viermal.
Hören.
Immer wieder.
Die Zeit verstreicht.
Wo war Adolf? Nach endlosen Minuten kommt er.
Im Schlepptau einen Sanitäter.
Der kniet sich sofort neben die Frau.
Fühlt Puls und prüft den Atem.

Sanitäter: „Wie lange?“

Hilde: „5 bis 6 Minuten“

Der Sanitäter steht auf: „Sie ist tot.“ Er dreht sich um und verschwindet in der Menge.

Hilde schaut Adolf an: „Weißt du, wo er ist?“ Adolf schaut verstört auf die Frau, dann auf Hilde, dann wieder auf die Frau.

Hilde: „Adolf! Wilhelm.
Weißt du wo Wilhelm ist?“

Adolf verwirrt: „Ich weiß nicht.
Wo? Wilhelm?
Die Frau ist tot.
Wilhelm? 
Der ist darüber gegangen.“ 
Er zeigt mit seinem Arm über den Platz.

Hilde nimmt Adolf in den Arm und drückt ihn.
Nach einer Weile macht sie sich los und geht in die Richtung, in die er gezeigt hat.
Adolf setzt sich neben die tote Frau, beugt sich nach vorne und legt sein Gesicht in seine Hände.

„Klar!“, ruft Hilde nach den ersten Schritten und änderte leicht ihre Richtung.
Sie eilt über den Platz auf ein Renaissance-Gebäude zu, vor dem eine öffentliche Telefonzelle steht.
Dort findet sie Wilhelm, Telefonhörer in der Hand, sein Mantel über die Schulter gehängt, wild gestikulierend.

„Gott sei Dank!“ Hilde atmet erleichtert aus.
Sie geht zu ihm und legt ihm ihre Hand auf den Rücken.
Er schaut kurz über die Schulter, lächelt sie an und dreht sich wieder zum Telefon.

Wilhelm brüllt: „Wir brauchen mehr Krankenwagen! Herr Professor! Es sind hier bestimmt noch 50 Menschen nicht versorgt, in meinem Blickfeld allein.
--- Brandenburger Tor.
Westseite.
--- Schicken Sie, was Sie haben.“

Er knallt den Hörer auf die Gabel und dreht sich zu Hilde.
Sie umarmen sich.
Aber Hilde macht sich plötzlich los und fasst an seinen Arm.

Hilde: „Du bist verletzt!“ Sie berührt seinen blutigen Verband am rechten Oberarm.
Ein wenig Blut war daraus Richtung Ellbogen geflossen.

Wilhelm: „Ja.
Messerstich.“

Hilde: „WAS?“ Sie schaut ihn ungläubig an.

Wilhelm: „Ja, die Feiglinge kamen kurz nach der Bombe und wollten mich kriegen.
Aber, PA!, es waren noch drei Spartakisten um die Bühne.
Und das hat gereicht.
Für sieben Angreifer.
Einer ist tot.“

Hilde umarmte Wilhelm fest.
„Du musst aufpassen.
Sie wollen dich.
Du brauchst ab jetzt einen Spartakistenverband nur für dich.
Und hier stehst du jetzt allein herum ...
Das geht nicht mehr! Das darfst du nicht mehr! Komm wir gehen irgendwo in Sicherheit.“

Wilhelm: „Nein, es ist nicht mehr gefährlich.
Sie machen nichts spontan.
Sie planen solche Dinge, sie führen Befehle aus, sie gehorchen ihren Oberen.
Und die Oberen sind nicht hier.
Nichts von dem, was jetzt gerade passiert, ist geplant.
Und damit können sie nicht umgehen.
Aber bei Reden, Märschen, Versammlungen, Verhandlungen, da müssen wir ab jetzt vorsichtig sein.
Du auch! Deine Arbeit in den Waisenhäusern, den Suppenküchen, den Arbeiterschulen, die schafft Bewusstsein bei den Menschen.
Die Menschen mögen dich.
Sie sind hinter denen her, die selbstständig denken, die sich nicht unterordnen wollen.
Hinter denen, die die Wahrheit lieben.“

Hilde: "Komm, Wilhelm. Ich will hier jetzt nicht bleiben. Wir gehen nach Hause. Heute Abend ist Treffen, da könnt ihr reden, was ihr daraus machen wollt."
____
