== [big-number]#2019# Überraschende Nachricht

[text-caps]#Mariane saß allein# vor ihrem Laptop, neben sich einen Teller mit Hühnchen und Reis.
Sie aß mit einer Hand und tippte mit der anderen in ihren Laptop.
Sie war in einem Chat mit einer Gruppe von Hackern.

Torrorist: „Das war eine Show! Habt ihr die Logs von Marianne gelesen? Geile Sache.“

Mohammed: „Ja, vor allem das QR-Ding, die Idee, Daten mit einem QR-Film rauszuschaffen, dass ist super.
7 Stunden 53 Minuten würden der TAO-Rechner brauchen, auf dem die Datei liegt, um das Terabyte als QR-Film auf dem Bildschirm anzuzeigen.
Aber was nimmst du für die andere Seite? Eine gute Kamera, klein, mit Akku, mehr als 1TB Speicher, schnell genug?“

Totaot: „Ein normaler Raspberry Pi reicht voll.
Das Programm, um den QR-Film in Daten zu wandeln, schreibe ich dir in einer halben Stunde.
Du hast immer den gleichen Blickwinkel auf den QR-Code.
Das geht dann wahnsinnig schnell.
Einen USB-Stick mit zwei Terabyte rein, HD-Kamera, normaler Akku-Satz.“

Julian: „Und das Ganze in ein Taschenbuch einbauen und ins Regal gegenüber vom Rechner stellen.
Fertig.
Wie starten wir das Programm?“

Marianne: „Du musst PAUL in Großbuchstaben auf der Konsole eintippen.“

Julian: „Geil.
Klingt gut.“

Totaot: „Ich baue das Ding.
Wer bringt es rein und drückt die Tasten?“

Eine Weile lang antwortete niemand im Chatraum.

Marianne: „Scheiße! Das ist nicht witzig.“

Julian: „Hej, Marianne, das war super gut.
Wir hatten Spaß.
Du hast es probiert.
Sie haben jetzt noch mehr Schiss vor uns, und jede Menge Arbeit.
Wir brauchen jetzt alle neue Computer.
Einige ziehen ganz um.
Wir haben viele Zugänge verloren.
Du vor allem den in die TAO rein.
Aber, was soll's.
Der Hack war geil.
Die Idee groß.“

Mohammed: „Eine poplige Traffic-Schranke.
Pffff.“

Torrorist: „Wer weiß.
Vielleicht waren da noch mehr.
Aber Marianne ist wieder raus gekommen.
Und keinen von uns hat's erwischt, keinen einzigen.
Das ist das Allerbeste.
Aber du Marianne, du musst jetzt wirklich da weg, wo du bist.
Die suchen wie verrückt nach dir.“

Mohammed: „Allerdings.
Hier in Dahab schwirren seit zwei Tagen einige schräge Gestalten rum.
Wir beobachten die.
Das sieht gar nicht gut aus.
Sie waren sogar schon im Hotel.“

Torrorist: „Wo die Abzweigung liegt?“

Mohammed: „Yupp.“

Julian: „Shit, Marianne, du musst da sofort weg.
Das sind sicher Academi-Leute.
Ich habe einen Tipp bekommen, dass zwei Gruppen nach Dahab und Hurghada geschickt worden sind.“

Mohammed: „Ok.
Machen wir dicht hier.
Bis bald, ich bin weg.“

Totaot: „Marianne! Guck gleich mal in dein Pond.“

Marianne: „Bis bald! Ich bin so froh, dass es euch gibt.“

Sie klickte das Chat-Fenster weg und wechselte die Tails-Identität.
Auf ihrem Bildschirm erschien:

****
....
„New message received from Totaot.“ 
....
****

Sie schrieb: „Show“

****
....
Ich bin gerade über Jabber kontaktiert worden. Jemand,
der dich über Pond sprechen will. Keine Ahnung, wo der
meine Adresse her hat. Ist ein bisschen scary. Er hat
ein Pond-Secret für dich und gesagt, dass es 30 Minuten
gültig ist. Scheiße. Könnte eine Falle sein. Pass echt
auf! Er hat gesagt, er weiß, was mit Corinne passiert
ist. Keine Ahnung welche Corinne er meint.

LG, Fred

Pond-Secret: DECD !E02 (0E6 !82C B9E9
....
****

Marianne atmete ein.
„Corinne“, dachte sie.
„Sie hatte vier Monate nichts von ihr gehört.
Shit.
Ein Honeypot? Speziell um sie anzulocken? Niemand kannte Corinne in ihrem Umkreis.
Nicht einmal Paul.“

Sie schloss die Augen.
In 20 Minuten würde Achmed hierher kommen und sie würde für immer von hier verschwinden.
Er hatte gesagt, dass er sie rüber bringen bringen würde ans andere Ufer, nach Saudi-Arabien, das waren nur 35 km.
Achmed war Beduine, er hatte eine große Familie, mit vielen Verbindungen, auch in Saudi-Arabien.
Wir helfen uns, hatte er gesagt, das machen wir seit Jahrhunderten.
Das war jetzt ihre beste Option.
Die Saudische Küstenwache war zwar brutal, aber sie war auch langsam und nicht sonderlich motiviert.
Der Saudische Geheimdienst? Klang für sie nicht mehr sehr furchteinflößend.
20 Minuten Zeit.
Konnte sie es wagen?

Alle ihre Gedanken verschwanden und sie begann zu tippen:

****
....
new-contact boatly_unknown_contact DECD !E02 (0E6 !82C B9E9
....
****

Mit diesem Befehl sagte man Pond, dass man Kontakt zu jemandem aufnehmen wollte: Man gab einen Namen ein und ein Geheimnis.
Der andere tat mit demselben Geheimnis genau dasselbe.
Und wenn sich die beiden Geheimnisse irgendwo im dunklen Teil des Internets trafen, dann wurde eine sichere Verbindung zwischen beiden Seiten eingerichtet.

****
....
Key exchange with boatly_unknown_contact complete.
....
****

„Wow!“, dachte Marianne.
Das ging schnell.
Fast ein bisschen zu schnell.

****
....
Message received from boatly_unknown_contact.
....
****

Marianne stutzte: „Und gleich eine Nachricht.
Da will wirklich jemand mit mir reden.“

Normalerweise brauchten Nachrichten über Pond einige Minuten.
Aber es war möglich, die Zeit abzukürzen.

Sie tippte: show.

****
....
„Hallo Marianne,

du kennst mich nicht, aber ich weiß einiges über
dich. Dein Bruder Paul sitzt in einem CIA-Gefängnis
irgendwo in den USA. Es geht ihm wohl den Umständen
entsprechend gut. Über dich gibt es Vermutungen, dass
du in Dahab oder in Hurghada bist und du bist vor drei
Stunden in die zentrale Datenbank der TAO eingebrochen.“
....
****

Marinne stockte der Atem: „Wow.“ Sie las weiter.

****
....
„Corinne ist tot. Sie war im gleichen Gefängnis wie
dein Bruder und hat es nicht geschafft. Ich weiß nicht
genau, wie es passiert ist. Aber sie wollten Dinge über
ihren Freund wissen, die sie nicht wusste, nicht wissen
konnte. Das habe ich vor ein paar Tagen erfahren. Ich
selbst war beim Tod ihres Freundes dabei. Ich saß im
Raum als es passiert ist. Ein Schlag gegen den Kopf. Brutal!
Er lag da. Er ist nicht wieder aufgestanden. Ich musste
mich damals übergeben als mir klar wurde, dass er wirklich
tot war. Das war für mich ein Wendepunkt. Ich wollte schon
einige Zeit davor aussteigen, aber das ist nicht so einfach,
da wo ich arbeite. Ich bin hier in der Zentrale der TAO,
in der NSA. Ich bin Verbindungsoffizier zur CIA. Ich leite
Daten weiter, die die CIA nutzt, um Hacker aufzuspüren, zu
verhaften, zu befragen und zu töten. Ich habe keinen Willen
mehr, da mitzumachen. Ich habe deine Geschichte verfolgt und
ich will dir helfen.

Ich schreibe dir jetzt, um dir zu sagen, dass die CIA
die Söldnerfirma Academi beauftragt hat, sie hieß früher
einmal Blackwater, dich zu fangen oder zu töten und ihnen
die beiden Städte Dahab und Hurghada genannt.

An beiden Orten sind gerade mindestens 20 Leute unterwegs,
um dich zu finden. Wenn du Möglichkeiten hast wegzukommen,
dann versuche es. Sie suchen derzeit nur dort und an den
Orten, wo du Freunde und Familie hast. Wenn du Fragen hast,
schreib. Ich bin jetzt hier.

Lieber Gruß, Anita
....
****

„Reply“, tippte Marianne:

****
....
Woher weiß du, dass ich in der Datenbank war?
....
****

„Send“.

Kaum eine Minute später:

****
....
Die Reihenfolge, wie du die Logdateien der zwölf Rechner
geholt hast, war dieselbe wie die, als du beim ersten 
Mal vor einigen Monaten in einem TAO-Rechner warst. Und
noch einige andere Dinge haben übereingestimmt. Wir haben
hier Hacker-Profile, die erfassen das.
....
****

Marianne drückte sich mit der Hand auf ihre Brust.
„Oh Gott“, dachte sie, „das kann echt sein.“ Sie sprang auf.
Ging ein paar Mal um den Tisch herum, setzte sich wieder.
In solchen Situationen vertraute sie nur ihrem Gefühl.
Nach zwei weiteren Minuten schrieb sie:

****
....
Kannst du heute noch einen aktuellen Raspberry PI kaufen,
eine HD-Kamera, einen 2TB-Memory-Stick? Und hast du Zugang
zu Serverraum der 07-Maschine? 
....
****

„Send“.


Marianne schaute gebannt auf den Monitor.
Es tat sich nichts.
Wenn Anita fragen würde, warum, dann würde sie nicht mehr antworten.
Sie muss direkt verstehen, dass sie es ernst meinte.
Direkt mit hineinkommen.
Sonst würde es nicht gehen.
Sie wusste nichts von Anita.
War sie Frau oder Mann, wie alt, oder vielleicht sogar eine Gruppe, die jetzt gerade alle vor einem NSA-Monitor standen und sich berieten, was sie als nächstes schreiben sollten.

****
....
Message received from boatly_unknown_contact.
....
****

erschien auf dem Bildschirm.
„Show“ tippte Marianne.

****
....
Ja.
....
****

Marianne schloss die Augen.
Es war ein Risiko.
Aber alles war jetzt riskant.
Sie schrieb:

****
....
Anita,

du bekommst in ein paar Stunden ein Programm für den
Raspberry von 5!50 F%87 1(37 AC56 3%EE

Du musst es nur auf eine SD-Karte kopieren und dann den
Raspberry damit starten. Du platzierst es nicht weiter als
3 Meter vom Monitor von der 07-Maschine weg. Du tippst P A U L
ein. Alles Weitere passiert automatisch. Es wird ca. 8 Stunden
dauern. Schreib ihm, wenn du den Stick fertig hast.
....
****

„Send“.
Sie schickte die gleiche Nachricht auch an Totaot.

„Klonck“, tönte die Tür dumpf unter dem Wasser.
Sekunden später erschien Achmed, riss die Taucherbrille ab und rief: „Schnell, Marianne.
Sie kommen.
Boote und ein Hubschrauber.“

Marianne schaute umher.
Sie packte ihre Laptops in die Gummitasche und wollte den Taucheranzug anziehen.
„Hubschrauber“, dachte sie.
„Shit.“

„Keine Zeit.
Nur die Flasche“, rief Achmed.
Sie zog sich die Sauerstoffflasche über, setzte die Maske auf und band sich den Koffer um.
Achmed verschwand im Wasser.
Sie sprang ihm nach.
Außerhalb des Bootes schwamm er in eine andere Richtung als sonst.
Marianne folgte.
Es ging tiefer, dem Grabens entlang.
Und nach etwa 50 Metern erkannte Marianne auf dem Meeresboden ein kleines U-Boot, das normalerweise wohl Touristen zu Tauchgängen brachte.
Achmed griff nach einem Haken und machte ihn vorne am Brustgürtel von Marianne fest.
Dann einen für sich.
Er gab dem Fahrer im U-Boot ein Zeichen und es ging los.