== [big-number]#2064# Fortunato

[text-caps]#Lasse und Sigur# liefen durch die Straßen von Caracas in Venezuela.
Es war früher Nachmittag, drückend heiß.
Am Ende der Straße erschien ein Gerichtsgebäude.

Sigur: „J u z g a d o? – Das ist das Haus, wo wir hinsollen.“
Er schaute Lasse erstaunt an.
„Was sollen wir in einem Gericht?“

Lasse: „Mal sehen.“
Er schaute auf einen Zettel.
„Zweiter Stock.
Zimmer 433.
Auf.“

Sie zeigten ihre Ausweise am Eingang, liefen die Treppe hinauf und setzten sich in einem tristen Gang auf eine Bank.
Die massive Holztür zu Zimmer 433 war geschlossen.
Drinnen waren sehr leise Stimmen zu hören.

Lasse schaute auf seine Uhr: „15:31 Uhr.
Jetzt sollen wir ihn treffen.“ 

Sigur stand auf und ging Richtung Türe.
Er setzte an zu klopfen.

Lasse: „HALT! Wir sollen warten, hieß es.“

Sigur: „Nee, hieß es nicht.
Es hieß: Trefft Frederick Petterson um 15:31 Uhr an der Avenida Oeste 13, Caracas, Venezuela, Zweiter Stock, Zimmer 433.
Wir sind im Augenblick nicht in Zimmer 433.“ Er setzte wieder an zu klopfen.

Lasse: „Warte, wir ...“ 

Die Türe schwang auf und ein kleiner, sympathisch aussehender, offensichtlich einheimischer Mann stürzte heraus.
Er stieß fast mit Sigur zusammen.
Beide schauten sich kurz in die Augen.
Der Mann machte einen Schritt zur Seite und eilte an Lasse vorbei in Richtung Aufzug.

Sigur schaute ihm perplex nach.

Lasse rief: „Herr Petterson“, obwohl der Mann nicht ein bisschen nach „Petterson“ aussah, viel eher nach „Rodriguez“.

Der Mann blieb stehen, wartete kurz, drehte sich dann zu Lasse und kam auf ihn zu.
Er flüsterte: „Fortunato, nicht Petterson, nicht hier“.
Er schaute beide wild an.
„Kommt mit! Wir müssen an einen Ort, wo wir frei sprechen können.“
Auf dem Parkplatz vor dem Gerichtsgebäude stiegen sie in einen riesigen Toyota Pickup ein, ein älteres Modell, mit Beulen und Schrammen an allen Seiten.
Fortunato fuhr los.
Nachdem sie vom Gerichtsparkplatz auf die Hauptstraße gebogen waren, drehte er sich zu ihnen und fragte: „Ihr seid Hacker, nicht?“

Lasse und Sigur schauten sich an.

Lasse: „Vielleicht.“

Frederick: „Ihr seid Hacker.
Ich bin immer sehr gut informiert.
Muss ich sein.
Das ist mein Job.“

Sigur: „Was tun Sie?“

Frederick: „Ich handle mit Drogen.
Aber kein Straßenverkauf, keine Softdrogen.
Nur Großhandel, nur echte Sachen, nur per Internet.
Braucht ihr ein Schiff mit Kokain? 500 Kilo? Aus Kolumbien, wunderbarer Stoff.
In zwei Wochen habt ihr es ...“

Sigur trocken: „Ja.
Ich hätte gerne ein Schiff voll.
Was kostet das?“

Das Lächeln verschwand auf Fortunatos Mund, er antwortete genauso trocken wie Sigur:
„Du bist nicht hier für Drogen.
Du hättest auch nicht genug Geld dafür.
Du hast nur ein Konto mit 6500 Euro darauf, die Wohnung, in der du wohnst, gehört deinen Eltern und deine Bitcoins sind derzeit“, er tippte mit einer Hand auf einem etwas klobig aussehenden Smartphone, “27.
Wow! Das ist viel für einen 19-Jährigen White-Hat-Hacker.
27 Bitcoins.
Natürlich könntest du bei mir in Bitcoins bezahlen, aber das wären eher 2700.
Aber wie schon gesagt: Deswegen seid ihr nicht hier.“

Sigur drückte sich mit leicht offenem Mund in die Rückbank.

Lasse: „Weswegen sind wir hier?“

Fortunato: „Hmmm.
Das ist seltsam.
Das sollte ich eigentlich wissen.
Es ist mein Job, Dinge zu wissen.
Aber, ehrlich gesagt, ich weiß es nicht.“

Lasse: „Woher weißt du wie alt Sigur ist und wie viel Geld er hat? Und dass wir Hacker sind?“

Fortunato: „Ich weiß auch, dass ihr illegal CIA-Flugkampfroboter fliegt und dass ihr die Sorat Rangers vom Himmel geholt habt.
Das wiederum hat mein Interesse an euch wirklich geweckt. Die Sorat Rangers sind Geschichte.“ Er lächelte warm.
Fortunato war einer der Menschen, denen man absolut nichts übel nehmen konnte.
Er strahlte Wärme und Leichtigkeit aus.
Man wollte instinktiv zu ihm Vertrauen haben.

Lasse dachte: „Stopp. Hier stimmt etwas nicht.
Das kann er gar nicht alles wissen.
Das geht nicht.
Niemand kann so einfach die Verbindung machen zwischen uns und den Kampfrobotern.
Und überhaupt wissen, wer wir waren.“ 

Lasse schaute Sigur an dann wieder Fortunato und fragte ärgerlich: „Woher weißt du das alles?“

Fortunato lächelte wieder: „Ich bin nicht nur Drogenhändler.
Wisst ihr, das lohnt sich nicht mehr richtig.
Das Geld stimmt, aber es macht zu wenig Spaß.
Es ist so industriell geworden.
Sie schmeißen dir Tonnen von dem Zeug hinterher, du kannst das im Internet direkt vom Feld bestellen, du hast kein Risiko mehr, aber es gibt keine echte Freundschaft mehr, ist nicht mehr nötig, alles ist professionell.
Und das ist langweilig.
Nein, ich handle jetzt mehr und mehr mit noch wertvolleren Gütern: Informationen. Big data.
Super Sache, sage ich euch.
Ich mache in Einzel-Personen und Firmen, und da alles: Aufenthaltsorte, Bankdaten, Korrespondenz, Bilder, Filme.
In Echtzeit und die ganze Historie.
Außerdem Vorschläge für Erpressungs- und Bestechungsmöglichkeiten.
Egal wer.
Ich habe 230 Millionen Einzelpersonen in meiner Datenbank.
Wollt ihr die privaten E-Mails von der nächsten Präsidentin der Vereinigten Staaten? Kein Problem.

Eure Daten habe ich schon im Gerichtszimmer gekannt.
Ein Sensor hat mir gesagt, dass ihr draußen vor den Tür seid. Ihr seid in meiner Datenbank … Aber ihr wundert euch, wie ich euren Aufenthaltsort kenne. Ihr habt keine Smartphones. Komisch, nicht? Für mich kein Problem. Bei Aufenthaltsorten, da habe ich eine Spezialität, fast ein Monopol: Ich habe nicht nur GPS, sondern auch RFID.“

Sigur: „RFID? Das wird zum Bezahlen und als Zugangskontrolle verwendet.
Ich habe nicht einen RFID-Chip an mir, weder zum Bezahlen, noch um irgendwo hineinzukommen.
Wie willst du mich damit orten?“ 

Fortunato zog ein kleines Papierblättchen mit einem QR-Code heraus.
„Seht ihr hier auf der anderen Seite des Codes diesen winzigen hautfarbenen Punkt? Das ist der kleinste RFID-Chip der Welt, 78 Mikrometer lang und breit.“

Lasse und Sigur beugten sich zu ihm hin, konnten aber nichts erkennen.

Fortunato: „Erinnert ihr euch an die süßen Mädels am Eingang eurer Konferenz.
Die, die euch jeden Morgen den Tagespass umhängen, was Nettes sagen und euch ein Begrüßungküsschen geben?
Super süß, nicht?
Das sind meine Mädels.
Und die sind super geschickt.
Die nehmen so ein Blättchen, wischen das bei euch irgendwo gegen Kleidung oder Haare und registrieren dann den zugehörigen QR-Code.
Und schon kann man verfolgen, wo ihr hingeht.
Haare sind am besten.
Die legt man nicht an der Garderobe ab oder wechselt sie irgendwann.
Und sie kriegen ein akustisches Signal ins Ohr, wenn der Chip von gestern noch da ist.
Und dann kriegt ihr keinen neuen.“
Fortunato lächelte stolz.

„Arschloch!“, murmelte Sigur gerade so laut, dass Fortunato es hören konnte.
Er strich sich mit den Fingern durch die Haare.

Fortunato schaute ihn mit großen, offenen Augen an: „Komm, hej, das ist ein Super-System.
Und denkt nach: Ich erzähle euch das.
Ihr wisst jetzt davon.
Da könnt ihr nicht auf mich sauer sein.
Ich bin offen mit euch.“

Lasse: „Und wo stehen die ganzen Scanner?“

Fortunato: „In Caracas? Überall in der Stadt.
Wir haben Zehntausende hier.
Die kosten ja nichts.
Ein Scanner ist ein Plättchen, 15 mal 15 Millimeter groß und sendet per GSM.
Sie funken über zwanzig Meter weit und halten etwa ein Jahr.“ Er holte ein Tablett-Computer heraus, der wie ein iPad aussah und grinste: „Ist kein iPad, keine Sorge.
Ist was Eigenes ...
Schaut!“ Er zeigte ihnen eine Karte von Caracas, auf dem eine Unmenge von roten, grünen und blauen Punkten zu sehen waren.
Einige schienen sich zu bewegen, einzeln, in Gruppen.
Um das Konferenzzentrum herum war eine große Wolke aus Punkten zu erkennen.

Fortunato: „Das sind exakt 3243 Teilnehmer von eurer Konferenz.
Davon haben derzeit 2230 kein GPS-Telefon dabei.
Aber ich habe die Daten! In Echtzeit!“

Lasse und Sigur schauten ungläubig auf das Tablett.

Fortunato: „Die meisten davon sind Aktivisten und Hacker.
Wertvolle Zielgruppe.
Und ich füge noch Informationen hinzu, wer sich mit wem trifft, mit wem isst, mit wem spazieren geht, nach Hause geht.
Was meint ihr, was ich für die Daten bekomme? Schaut, ich habe derzeit 24 Echtzeitabbonenten.“ Er tippte auf das Tablett und streckte es ihnen entgegen.
„Die NSA ist auch dabei.
Aber von denen nehme ich grundsätzlich kein Geld.
Die haben so viele super Sachen im Angebot.
Mit denen tausche ich nur, obwohl sie immer wieder fragen, ob sie nicht auch bezahlen dürfen.“

Sigur etwas lauter: „Mir wird übel.“

Lasse: „Mit dem System kommst du nicht lange durch, Fortunato.
Bei der Konferenz gibt es so viele RFID-Scanner, das fällt auf, wenn plötzlich ein paar Tausend Chips mehr da sind.“

Fortunato: „Meine Chips arbeiten nicht mit der normalen Frequenz.
In China gibt es eine komplette Fabrik, die nur meine Chips macht.
Hej Jungs, wacht auf.
Heute muss man etwas tun, wenn man Erfolg haben will.
Die Welt ist nicht nett.
Da ist Krieg da draußen.
Den hab nicht ich gemacht.
Aber wenn man diese Welt kennt, wenn man weiß, was alles geht und was nicht, dann kann man es sich auch heute noch ganz nett einrichten.
Man kann eine Menge machen, vor allem wenn man nicht für den Staat arbeitet, sondern als freier Unternehmer.
Die staatlichen Geheimdienste und sonst alle Dienste, die in staatlicher Hand sind, die sind wirklich langsam und träge, auch fantasielos: NSA, CIA, LBI, FBI, GCHQ.
Alles Lahmärsche.
Allerdings manchmal verdammt gefährliche Lahmärsche … Sie kaufen sich halt, was sie brauchen.
Aber mein RFID-System kriegen sie nicht.
Das ist unverkäuflich.“

Lasse hielt den Atem an.
Sigur schaute ihn mit leicht panischem Blick an, deutete an, auszusteigen.

Fortunato: „Hej Jungs.
Wir sind in dem, was wir machen, nicht so weit voneinander entfernt, wie das jetzt vielleicht scheint.
Die Dinge technisch im Griff zu haben, darum geht es, erfindungsreich mit den Gegebenheiten umzugehen.
Das Konzept kennt ihr doch: Hacken, Technik umfunktionieren, etwas anders nutzen, als es die Erfinder vorgesehen haben.
Genau das mache ich.
Hej, es ist auch nicht sehr moralisch, experimentelle Flugkampfroboter zu klauen und damit Elite-Einheiten vom Himmel zu schießen.
Da habt ihr fast eine halbe Milliarde Dollar Schaden verursacht.“

Lasse brummte: „Ich mache keine Geschäfte mit der NSA.“

Sigur zischte Lasse zu: „Lass uns abhauen.“

Lasse leise zurück: „Warte noch.
Marianne hat uns hier hingeschickt.“

Sigur sehr leise: „Ich mache mit dem Arschloch keinen Deal.
Der ist andere Seite.
Der lügt dich voll, wenn es sein muss.“

Fortunato unbeeindruckt von dem Flüstern der beiden: „Aber jetzt sagt mir: Warum seid ihr gekommen?“ 

Lasse: „Wir suchen einen noch unbekannten U.S. Geheimdienst.
Einen, der für Attentate zuständig ist, besonders für gestellte Attentate.“

Fortunato überlegte kurz.

Fortunato: „LBI.
Lubricious Bureau of Intelligence.
Home of the Sorat Rangers.
Eigentlich Localized Bureau of Intelligence.
Aber die sind wirklich schmierig.
Wenn es in dem Business Arschlöcher gibt, dann sind sie es.
Da müsst ihr wirklich nicht auf mir herumhacken.
Gegen die bin ich ein reiner Menschenfreund.“

Lasse: „Die Sorat Rangers sind von der CIA!“

Fortunato: „Falsch.
Sind sie nicht.
Nur ihre Plaketten sind von der CIA.
Beim LBI ist alles Schein.
Das existiert offiziell ja nicht.
Es hat nicht einmal ein eigenes Gebäude.
Nirgendwo.
Kein einziges.
Alle Mitarbeiter haben eine Tarnidentität, 100%, sogar der Boss.
Die gibt es nicht, überhaupt nicht, die sind überall verteilt: CIA, NSA, Regierung, sogar ausländische Geheimdienste, Ölfirmen, Google, Apple hat einige … Und die wollt ihr? Lasst mich raten, was ihr von denen wollt: Ihr wollt einen Kampfroboter-Satelliten klauen, damit ihr eine eigene Flotte steuern könnt.
So was könnt ihr nur dort bekommen.
Überall anders würde das auffliegen.
Aber das LBI hat ein paar, von denen niemand weiß.
Na, habe ich Recht?“
Er grinste und drehte sich zu Lasse.

Lasse: „Nein.“

Fortunato: „Nein.
Hmmm.
Dann wollt ihr die nächsten Sorat Rangers werden? Dafür habt ihr gerade eure Visitenkarte abgegeben.
Aber ich sage euch, dass wäre ein gefährliches Spiel ...“

Sigur stöhnte.

Fortunato: „Ok, ok, ich weiß, ihr arbeitet nicht mit denen zusammen.
Habe ich schon gelernt.
Ich weiß noch nicht, warum ihr euch da selbst beschränkt, aber ok, ihr macht so etwas nicht.
Moral? Moral kann ganz schön teuer sein heutzutage.
Die kann das Leben kosten.
Aber dann sagt, was wollt ihr machen?“

Lasse: „Wir wollen das LBI aufdecken.
Wir wollen öffentlich machen, was sie tun.“

Fortunato bremste das Auto abrupt ab, fuhr nach rechts und hielt an, leicht aufgeregt: „Jungs! Das ist keine gute Idee.“ Er drehte sich zu ihnen hin.
„Ihr habt gesehen, was die Veröffentlichung der NSA-Schwachstellendatenbank vor ein paar Jahren für ein Aufruhr war.
Heilloses Chaos.
Große Firmen sind pleite gegangen.
Viele Menschen haben das Vertrauen ins Internet komplett verloren.
Regierungschefs haben gewechselt.
Menschen sind gestorben.“

„Nee“, unterbrach Sigur.
„Niemand ist deswegen gestorben!“

Fortunato: „Bei den Geheimdiensten, doch, doch, einige.
Egal.
Es war ein Erdbeben.
Aber das hier, LBI, das wäre noch ein Tick drüber.
Das ist nicht nur NSA, nicht nur eine introvertierte Hackerfirma, die sich nur in alle Computer und Smartphones der Welt hineinsickern lässt und alle Daten speichert, die sie in die Finger bekommen.
Nein, nein.
Das ist heftiger.
LBI, das sind gestellte Weltereignisse, Attentate, gesprengte Gebäude, erfundene Rebellengruppen, erfundene Kriege, erfundene Revolutionen.
Ihr habt keine Ahnung, was alles LBI ist.
Wenn ihr das aufdeckt, dann sterben viele Menschen.
Todsicher.
Überlegt doch mal:
Allein, was passieren würde, wenn ihr Khandahar aufdeckt!
Das, was wegen euch gerade schief gelaufen ist.
Sieben Präsidenten tot.
Wenn herauskommt, dass das gestellt war, dann gibt es Krieg.
Todsicher.
Einen Krieg mit vielen Toten.
Und das ward ihr dann.
Das ist nicht besonders moralisch.
Ihr arbeitet nicht mit der NSA zusammen?
Aber Menschen umbringen, das ist ok, oder?“

Sigur: „Jetzt kriegst du Angst, nicht?
Man kann alles kontrollieren, aber nur wenn es nicht ans Licht kommt.
Wistleblowing ist der eigentliche Feind! Was ihr braucht ist ein dunkles Gleichgewicht: Jeder spielt seine Rolle, alles bleibt geheim, dann können die schlimmsten Dinge passieren und keiner ist wirklich verantwortlich.
Bist du verantwortlich für die Kampfroboter-Toten, die aufgrund deiner Positionsdaten sterben? Oder wegen der Freundeslisten, die du berechnest und an die NSA weitergibst? Nein.

Aber wenn wir etwas aufdecken, dann sollen wir verantwortlich sein.
Der Überbringer der Nachricht ist schuld.
Aufdecken, Wistleblowing muss man verantwortungsvoll machen, alles andere nicht.
Wer übernimmt die Verantwortung dafür, dass wir erst in die Lage gekommen sind, dass Menschen ihr Leben verlieren, wenn Dinge öffentlich werden? Wer übernimmt die Verantwortung für die Dinge, die im Geheimen passieren? Niemand.“

Lasse: „Sigur, wir alle haben für alles Verantwortung.
Ob wir Schuld an dem Schlamassel sind oder nicht.
Wir haben nur eine Erde, nur eine Luft, nur eine Menschheit.
Verantwortung kann man nicht teilen.“

Es wurde still im Auto.
Ein, zwei, drei lange Minuten.
Dann lächelte Fortunato Lasse und Sigur aufmunternd zu: „Kommt.
Wir gehen erst einmal zu mir nach Hause.
Es ist gleich hier um die Ecke.
Dann essen wir was Gutes und schauen weiter.“
Er startete das Auto und fuhr zurück auf die Straße.
