== [big-number]#2064# Im Strand-Appartment 

[text-caps]#Sigur und Lasse saßen# im Wohnzimmer des Strand-Apartments in zwei riesigen Sesseln.
Von dort hatten sie einen 270-Grad-Rundumblick über das Meer.
Auf der anderen Seite im Raum stand ein überdimensionierter Fernseher, links dahinter ein offener Kamin.

Sigur: „Was meinst du, wann wird er wiederkommen?“

Lasse: „Keine Ahnung.
Vielleicht kommt er gar nicht wieder.“

Sigur: „Auf jeden Fall sieht er uns gerade auf irgendeinem Monitor oder hört uns durch irgendein Mikrofon.
Und meinen RFID-Chip habe ich auch noch nicht gefunden.“
Er strich sich wieder durch die Haare.
„Das ist kein guter Platz hier.
Lass uns gehen.“

Lasse: „Hier gibt es irgendetwas zu tun.
Sonst hätte Marianne uns nicht hierher geschickt.“
Er schaute sich um.

Sigur: „Klar.
Hier steht sicher irgendwo sein Cloud-Rechner rum.
Und da sind ziemlich sicher super interessante Sachen drauf.
Und da hacken wir uns jetzt einfach rein und schauen zum Beispiel, was er Interessantes über das LBI hat.“
Er zog die Augenbrauen hoch und lächelte gestellt.
„Und da er weiß, dass wir Hacker sind, lässt er uns hier in Ruhe allein unser Ding machen.“

Lasse: „Mh mh.
Er sieht und hört uns zu.
Auf jeden Fall.
Aber dann können wir ihn ja um Hilfe fragen, wenn wir nicht weiterkommen.“
Er lächelte gestellt zurück.

Plötzlich schaute Sigur Lasse erstaunt an.
Dann schien er intensiv zu denken, er schloss die Augen.
Dann griff er in seinen Rucksack, holte seinen Laptop heraus und legte ein Tuch über seine Hände, während er das Passwort eingab.
Er begann darauf herumzutippen.
Lasse beobachtete ihn eine Weile, Sigur war vertieft in sein Gerät, unansprechbar, „plugged in“, wie sie das nannten.
Nach einer Weile holte er auch seinen Rechner heraus, schaltete ihn an, gab sein Passwort ein und ging ins Internet.

„Pling“, sagte das Chat-Programm und zeigte eine Nachricht von Sigur.

Sigur: „Endlich.
Das bist du ja! Pass auf, dass dir nichts von hinten auf den Monitor schaut.“ Lasse klappte den Bildschirm leicht zu sich.

Sigur: „Neben deinem linken Fuß unter dem Tisch ist eine Steckdose.
Ich habe unter meinem linken Bein einen kabellosen Stecker.
Nimm ihn unauffällig und stecke ihn dort ein.“
Lasse tat so als würde er sich die Schuhe binden und drückte den Stecker dabei in die Dose.

Sigur: „Gut.
Ich habe Kontakt.
Das Gerät meldet mir ultrakleine Schwankungen im Stromnetz, zum Beispiel von Computer-Aktivität, von allen Computern, die hier so im Netz hängen.
Ich werde jetzt einen Portscan über alle Computer in Caracas laufen lassen und schauen, wann sich hier etwas tut.
Vielleicht erwischen wir ja etwas.“

Lasse: „Komm, wenn er überhaupt Rechner hier hat, dann ist er sicher so paranoid, dass sie an einem eigenen Netz hängen.
Wahrscheinlich geht er auch direkt über Satelliten raus ins Internet.“
Sigur saß eine Weile vertieft vor seinem Rechner und tippte ab und zu.
Lasse bearbeite derweil seine Pond-Nachrichten.

„Got it!“, schrieb Sigur plötzlich, „drei Rechner sind direkt hier im Stromnetz.
Wahrscheinlich im Keller.
Tief im Keller.
Einer scheint ein Tor-Hidden-Service zu sein, wahrscheinlich auf einem Cubes-System.
Da gucke ich mal rein.“

Lasse schickte ihm eine Datei: „Hier sind die Sachen von Lilly, mit denen sie in Cubes hineingeht.
Da ist zwar nichts für die neueste Version dabei, aber vielleicht kannst du es brauchen.“

Sigur: „Keine Zero-Days für die neueste Version?
Gutes Zeichen.
Ich liebe Cubes.
He he.
Er hat hier nicht die neueste Version.
Super.
Ich probiere die Sachen gerade mal durch.
Lilly ist ein Schatz.“

Wenige Minuten später: Sigur verzog auf seinem Sessel keine Miene und schrieb: „YESS!!! Bin drin! Super einfach.
Er hat zwar einen ganz guten Schutz gehabt, aber eben nicht die neueste Version. Ich sage immer: Updaten, updaten, updaten.
Einen kleinen Moment. Hier: Die Onion-Adresse ist idtAIrLBI0KJ6gjyro8uTkHa.onion.
Was hat er denn da?
Aha, einen Shop.
Wow!
Er ist wirklich ein Informationshändler.
Nicht gelogen.
Schön übersichtlich.
Und hier: Das Such-Programm, von dem er gesprochen hat.
Da kann man Telefonnummern eingeben, E-Mail-Adressen.
Wie bei XKeyScore von der NSA.
Mal gucken, was das so kann.
Gib mal … nein, nicht deine! Um Gottes Willen.
Die von Edward Snowden ein.“

****
....
Edward Snowden

Tätigkeitsschwerpunkt: Hacker, Internetaktivist, Internet-Sicherheit

Letzter bestätigter Aufenthaltsort: 2 Tage alt 

Bewegungsprofil: 2% Abdeckung

E-Mails gesamt: 12234 (alle Adressdaten, Betreffzeile)

E-Mails ohne PGP: 335 (voller Inhalt, alle Adressdaten, Betreffzeile)

Jabber-Kontakte: 71

Finanzdaten: 12334

Portrait-Fotos: 72

Kommunikationskontakte: 781
....
****

Sigur: „Shit, der hat im Bewegungsprofil nur 2% Abdeckung.
Wie macht der das?
Und schau mal, was das kostet: Volle Daten $ 65.000, Metadaten $38.000.
Das ist ja geschenkt.
Mal sehen wie viel Abdeckung Marc Zuckerberg hat und was der kostet … Ahhh. Der hat 99,3%.
Wow.
Aber klar.
Und seine Daten kosten: $ 81.000.
Warum ist der teurer als Edward?“

Lasse: „Hmmm.
Die Leute, die das interessiert haben mehr Geld?“

Sigur: „Egal.
Ich schau mal weiter. Da liegt sicherlich noch mehr auf dem Rechner rum.“
