== [big-number]#2064# Ein Plan

[text-caps]#Fortunato saß in# einem Strandcafé an einem Tisch und löffelte eine Suppe.
Neben ihm saß Jonny, braungebrannt, muskulöser Oberkörper, Mitte 30, europäisches Aussehen, mit Bermudashirt und Strohhut, das Gesicht komplett im Schatten des Hutes.
Vor ihm stand ein großer Cocktail.

Fortunato: „Die beiden sitzen jetzt in diesem Augenblick bei mir zu Hause im Wohnzimmer und hacken an ihren Computern.“

Jonny: „Na, dann, hacken sie wohl gerade deine Server … Super Plan!“

Fortunato: „Nee.
Kein Problem.
Die sind im Keller, zweites Untergeschoss, mit einer Stahltresortüre gesichert.
Da kommen sie nicht ran.
Und von da aus geht es direkt hoch zu einem TAO-Satelliten.
Also von außen auch nicht.
Hat mir alles die TAO eingerichtet.
Die sind gut die Jungs.“
Er zeigte ihm sein Tablett.
„Schau.
Alles ruhig da unten.“

Jonny: „Trotzdem.
Die beiden sind brandgefährlich.
Schau lieber genau, was sie machen.“

Fortunato: „Meinst du ich vergeude meine Zeit mit ungefährlichen Leuten?
Ungefährliche Leute kann ich nicht brauchen.
Die kannst du in irgendeinem Staats-Geheimdienst einsetzen.
Die beiden sind junge Wildpferde.
Du musst sie nur zähmen.
Besonders Sigur finde ich interessant.
Wie er sich seinen ersten Kampfroboter gehackt hat, unglaublich.
Und vor allem: Er ist empfindlich, er wird sich demnächst seine Haare rasieren und seine Kleider verbrennen, um die RFID-Chips herauszubekommen.
Er kommt in Stress wegen solcher Dinge.
Da können wir ansetzen ...“

Jonny: „Was willst du tun?“

Fortunato: „Ein Zyankali-Implantat.
Etwas, was starke Gefühle auslöst: Angst, Wut.
Du hast so ein Ding in dir und irgendjemand kann mit Satelliten-Fernzünder die Kapsel brechen und du stirbst.
Du kannst es nicht rausholen.
Du musst ständig gucken, dass es Verbindung hat, sonst geht es auch auf.
Da wirst du verrückt.
Wir brauchen ihn abhängig, kontrollierbar.
Er kriegt es mit lokaler Betäubung.
Er soll alles mitbekommen.“

Jonny: „Und der andere?“

Fortunato: „Lasse?
Wir trennen die beiden.
Er kriegt nur einen Lokalisierungs-Chip, aber unter Vollnarkose.
Dann kommt er frei.
Sie werden sich suchen, da kannst du drauf gehen.
Und Lasse wird Freunde kontaktieren.
Da bekomme ich ein paar Daten für meine Darknet-Sammlung.“

Jonny: „Böse, böse.“

Fortunato: „Kannst du das alles organisieren?
Ein Team mit Arzt?
Morgen 5:45 Uhr?
Bei mir zu Hause.
Das Zyankali aber nicht echt.
Traubenzucker oder so etwas.
Ich will ihn ja nicht aus Versehen umbringen.“

Jonny trocken: „Okay.“
