== [big-number]#1915# In einer Suppenküche 

=== SZENE 6
____
Hilde in einer Suppenküche hinter einem riesigen Topf, einen Schöpflöffel in der Hand.
Menschen, die mit Teller und Löffel anstehen.
Am Eingang eine Gruppe Spartakisten mit Sturmgewehren.

Ein älterer Bettler betritt den Raum, nimmt sich einen Teller und schaut eine Weile auf das Ende der Schlange.
Dann hält er den Teller vor sich und geht direkt auf Hilde zu, aber niemand in der Schlange macht ihm Platz.
Hilde und er schauen sich an.
Sie macht ein Zeichen zu der Frau, die als nächste dran wäre und winkt den Bettler herbei.
Der Mann hinter der Frau murrt etwas laut in seinen Bart.
Hilde schaut kurz mit sachlichem Blick hin und füllt dann den Teller des Bettlers.

Hilde: „Lass es dir schmecken, Bruder.“ 

Der lächelt sie mit einer tiefen Wärme an und trottet dann in Richtung einer dunklen Ecke.
Hilde füllt den Teller der Frau.

Hilde: „Das ist Albert.
Er ist als Waise aufgewachsen und hat vorgestern erfahren, wer seine Eltern waren.
Sie haben 50 Jahre lang nicht weit von ihm gewohnt.
Er kommt gerade vom Friedhof.“

Die Frau nickt und schaut dem Bettler nach.

Hilde: „Außerdem bekommt er schlimme Wutausbrüche, wenn er zu wenig im Magen hat.
Deswegen habe ich ihn vorgelassen.
Da kann er nichts machen.
Das ist angeboren.“ Sie lächelt die Frau an und wendet sich dann dem Mann zu, der hinter ihr steht.

Wilhelm sitzt in einer Ecke des Raumes an einem Tisch mit drei anderen und redet mit wilden Gesten.
Die drei hören ihm gebannt zu und ziehen ab und zu Mienen als Reaktion auf das, was Wilhelm sagt.
Am Nachbartisch schläft eine Frau mit dem Kopf auf dem Tisch, drei Kinder neben ihr, die ein Fingerspiel spielen.
Um sie herum stehen eine Menge Beutel mit allerlei Dingen gefüllt.
Ihr gegenüber liest ein Mann anderen ein Flugblatt vor, das immer wieder lebhaft kommentiert wird.
Einen Tisch weiter sitzen zwei dunkle Gestalten, der eine eine Suppe löffelnd, der andere vor sich ein Glas Bier.

Der Bettler sitzt auf dem Boden an eine Wand gelehnt und löffelt seine Suppe sehr konzentriert mit leicht zitternder Hand.
Als der Teller leer ist, setzt er ihn vorsichtig auf seinem Schoß ab und wendet seinen Blick zu Hilde.
Er schaut sie lange mit sanftem Blick an.

Plötzlich brennt am Eingang eine laute Diskussion auf.
Im Raum wird es still.
Der Spartakisten-Gruppenführer stellt sich einem Polizei-Hauptmann in den Weg.
Beide haben schnell jeder eine Gruppe von uniformierten und bewaffneten Männern hinter sich.
Der Hauptmann hält dem Gruppenführer ein Blatt Papier ins Gesicht und verlangt lautstark den Zutritt.
Widerwillig nimmt der das Papier und liest es langsam.
Dann macht er einen Schritt zu Seite.
Der Hauptmann schnappt sich das Papier zurück und betritt den Raum.
Hinter ihm etwa sechs oder sieben Polizisten.
Er geht direkt auf Hilde zu, während die anderen sich im Raum verteilen und beginnen, auf den Tischen, in Taschen und unter den Bänken nach etwas zu suchen.

Hauptmann streng: „Gnä Frau! Die Konzession für Essensausgabe bitte!“ 

Hilde schaut ihn an: „Ich weiß.
Wir brauchen hier eine Konzession.
Wir haben das hier ganz spontan eingerichtet.
Schauen Sie die Menschen an.
Die waren bis vorgestern noch manchmal zwei, drei Tage ohne Essen.“

Der Hauptmann schaut kurz durch den Raum.

Hauptmann: „Sie brauchen eine Konzession.
So sind die Vorschriften.“

Hilde: „Ich weiß.
Wir müssen auch eine Strafe bezahlen, wenn wir keine haben, nicht?
30 Reichsmark waren das, glaube ich.
Ich verstehe das, Gesetz ist Gesetz.
Und es gab schon einige Infektionen wegen schlechter Küchen.
Unsere Gruppe hier hat viel Erfahrung.
Wir haben schon Hunderte Mittagssuppen gemacht.
Sie können gerne einmal in die Küche schauen.
Ich gehe gleich hin und sage den Leuten dort, dass sie mit dem Kochen aufhören.
Sie bereiten gerade den zweiten Topf vor.
Es kommen heute mehr Menschen als sonst.“

Der Hauptmann schaut Hilde an und kratzt sich am Kopf.

Hauptmann: „Machen Sie das hier heute normal fertig.
Alles gut aufräumen.
Dann ist das in Ordnung.“

Hilde: „Das machen wir, gut.“

Hauptmann: „Und gehen Sie morgen in die Motzstraße 17.
Da ist ein Stadtkommissar Geimer im zweiten Stock.
Der stellt Konzessionen aus.
Sagen Sie ihm einen Gruß von Hauptmann Schlöndorf.“

Der Hauptmann nickte Hilde kurz zu und drehte sich in den Raum, um sich ein Bild von der Lage zu machen.
Vier Polizisten haben inzwischen den Bettler umringt.
Der scheint zu schlafen.
Einer kickt ihn mit dem Fuß.

Erster Polizist: „Hej! Aufstehen! Wir haben dir gesagt, dass du hier nicht mehr in die Gegend kommen sollst.“

Der Bettler reagiert nicht.
Wilhelm springt auf und geht in drohender Haltung auf den Polizisten zu.
„Wilhelm!“, ruft Hilde und gibt ihm ein Zeichen, dass er wieder zurückgehen soll.
Ein anderer Polizist tippt den Bettler mit dem Fuß an.
Der drückt seine Tasche, die er vor die Brust genommen hat, näher an sich, aber öffnet die Augen nicht.

Zweiter Polizist: „HEY!“

Der Bettler blinzelt und sagt ruhig und mit langsamer Aussprache: „Ich will hier nur ein bisschen ausruhen.“

Erster Polizist: „So, du kommst jetzt mit uns.“
Er greift unter seine Arme.
Der zweite hilft mit.
Der Bettler macht sich schwer und blinzelt wieder.

Bettler: „Ich will mich hier ein bisschen ausruhen.“

Mit Kraft heben sie ihn auf, so dass er mehr schlecht als recht steht.
Er wankt.
Als sie ihn ein wenig locker lassen, knickt er wieder weg und sinkt zurück an die Wand.
Er schaut beide ruhig an.

Bettler: „Nur ein bisschen schlafen und dann gehe ich auf den Friedhof.“

Der erste Polizist beugt sich wieder über ihn.
Der Bettler schaut ihn mit großen Augen an, blinzelt fast kindlich.

Polizist: „Kommt.
Wir tragen ihn raus.“

Vier Polizisten setzen an, ihn hoch zu heben.
Der Bettler kommt ihnen zuvor, indem er selbst aufsteht.
Er schaut in die Runde.

Bettler: „Ich habe hier gegessen.
Bin jetzt satt.
Es ist warm hier.
Ich will mich nur ein wenig ausruhen.“

Er sinkt zurück an die Wand.
Die vier Polizisten stehen einen Moment lang ratlos um ihn herum.
Der Hauptmann kommt von hinten heran, schaut auf den Bettler und meint dann: „Kommt, lasst ihn.
Wir gehen!“ 

Sie verlassen die Halle.
Hilde fängt wieder an, Suppe zu schöpfen und meint lächelnd zu dem Mann, der gerade an der Reihe war: 
„Er weiß genau, wie er das macht. Von ihm kannst du einiges lernen.“
____
