== [big-number]#2064# Tresoreinbruch 

[text-caps]#Sigur schloss die Augen# und grinste in sich hinein.
Er schrieb in sein Chatfenster: „Lasse! Wow! Wow! Wowowow! Schau, hier!“

Lasse drehte sich instinktiv zu ihm, um sich dann aber sofort wieder ruhig zurück zu seinem Monitor zu wenden, auf dem gerade ein Videofilm lief.
Über den Videofilm hatte er, kaum zu bemerken, sein Chatfenster gelegt.
Dort scrollten jetzt seitenweise Daten durch.

Lasse: „Was ist das???“

Sigur streckte sich auf seinem Sessel und tippte: „Bitcoins! Da gehen alle Bitcoins aus den Shop hin.
Das sind Massen.“

Lasse: „Echt? Super!“

Sigur: „Aber leider in einer Veracrypt-Datei verschlüsselt.
Es ist eindeutig: Die ganzen Einnahmen des Shops gehen da hinein.
Ich habe die Bitcoin-Blockchain durchgeschaut: Da müssen Hunderttausende oder vielleicht sogar Millionen von Bitcoins drin sein.“

Lasse: „Milliarden Euro.
Super! … Scary … Aber was haben wir davon? An eine Veracrypt-Datei kommen wir nicht ran.
Oder meinst du, er hat ein schwaches Passwort drauf?“

Sigur: „:-)“

Sigur: „:-D“

Sigur: „:-P“

Sigur: „Nee.
Ich glaube nicht, dass er ein schwaches Passwort hat.
Ich kann mal nebenher einen Passwort-Cracker laufen lassen, aber ich glaube nicht, dass dabei etwas herauskommt.
Das hier ist alles sehr professionell gemacht.
Sieht nach Geheimdienstarbeit aus, vielleicht sogar direkt die TAO.
Aber ich, ich habe hier zu meinen Füßen liegen, das Go-Programm, das die Bitcoins vom Shop in den Tresor bringt.
Die Logfiles sagen, dass er das Programm normalerweise einmal am Tag startet, Vormittags, und dann gibt das Passwort für den Bitcoin-Tresor ein.
Und ich, ich starte dann automatisch ein kleines Programm, was die neu verdienten Coins nicht in den Tresor schreibt, sondern sie zusammen mit allen anderen Bitcoins aus dem Tresor nimmt und in meine kleine Höhle zu mir nach Hause schickt, in meinen kleinen Raspberry Pi, meinen treuen Helfer über die Jahre.
Du kennst ihn.
:-)“

Lasse: „Du bist verrückt!
Du willst sie komplett klauen?
Du willst an der Stelle ein eigenes Programm unterbringen?
Das fällt auf.“

Sigur: „Nee.
Dateien verstecken ist meine Spezialität.
Mein Programm wird zunächst einmal schlafen.
Ich schicke ihm jeden Tag ein Ping, als Weiterschlafen-Zeichen: Wenn das kommt, dann wacht es nicht auf.
Erst, wenn es einmal ausbleibt, dann schlägt es zu: Wumms!“

„RUMMS“, hörten sie draußen eine Autotüre zuschlagen.
Beide erschraken und schauten zu erst in die Richtung des Autos und sich dann an.
Es war der Pickup von Fortunato.

Lasse: „Scheiße! Ausgerechnet jetzt.“

Sigur sagte kein Wort.
Er zog seinen Kopfhörer auf und vertiefte sich in seinen Laptop.

Fortunato schloss die Haustür auf und kam mit einer großen Tüte unter dem Arm hinein.

Fortunato: „Hi Jungs! So spät noch auf? Wollt ihr nicht ins Bett?“ Er lachte.
„Nee, klar: Hacker sind Nachtarbeiter.“ Ich habe euch ein paar einheimische Sachen besorgt.
Er legte die Tüte auf den Wohnzimmertisch vor Sigur und Lasse ab.

„Danke!“, sagte Lasse und griff danach.
Sie war voll mit Nüssen, Schokolade, Bananen, Orangen, einer Papaja und einigen Tüten Chips.

Fortunato: „Sigur? Na?“
Sigur rührte sich nicht und tippte weiter auf seiner Tastatur.

Lasse schaute Fortunato an und meinte: „Plugged in! Da kannst du nichts machen“.
Er stopfte seinen Mund mit Nüssen voll und grinste Fortunato an.

Fortunato nickte und lies sich in den dritten Sessel fallen, der an der anderen Seite des Tisches stand.

Fortunato: „Und? Wie ist das Arbeiten hier?
Karibikstrand, Rundum-Sicht, eigene Bootsanlegestelle.
Da lässt es sich aushalten, nicht?
Ihr könnt gerne noch ein paar Tage hier bleiben.“

Lasse: „Nee.
Wir brechen morgen früh auf.
Unsere Flüge gehen so um 12.“

Fortunato: „Ok.
Ich kümmere mich um euer Taxi.
Ihr braucht auch nicht so viel früher da zu sein, wie normal.
Ich habe dort meinen extra Eingang.
Keine Wartezeiten, keine Kofferkontrolle.
Also, wenn ihr noch ein bisschen Koks mitnehmen wollt, gerne ...“

Lasse lächelte: „Taxi gerne.
Koks danke nein.“

Fortunato: „Was macht eigentlich Sigur?“

Lasse: „Er programmiert.
Bestimmt wieder irgend so ein Wächterprogramm, dass auf einem Computer auf ein bestimmtes Ereignis wartet und dann aktiv wird.
Und bis es aktiv wird, ist es so gut versteckt, dass es nicht einmal die TAO findet.
Und nachdem es gelaufen ist, löschte es sich selbst vom Computer, und du findest keine Spuren.
Das ist Sigurs Spezialität.
Keiner kann das besser als er.
Sie hassen ihn dafür.
Es ist reine Zauberei.“

Fortunato lächelte etwas gequält.

Fortunato: „Mh mh.
Meint ihr nicht, wir könnten ein kleines Projekt zusammen machen?
Irgendetwas Spannendes.
Zum Spaß haben.
Ich habe einige Projekte, wo ich so etwas gut brauchen könnte.
Und ihr könnt nebenbei jede Menge Geld verdienen.“

Lasse lächelte zurück: „Vielleicht. Wenn du auf deine Zusammenarbeit mit der NSA verzichtest und mit anderen Geheimdiensten, uns alles sagst, was du über das LBI weißt, dann gerne.“

Fortunato: „Warum wollt ihr unbedingt den brutalen Weg gehen, wenn ihr Dinge verändern wollt?
Mir stinkt auch viel, was in der Welt passiert, auch in den Geheimdiensten.
Glaubt mir, ich habe einiges an Brutalität rausgenommen, da wo ich aktiv bin.
Die Menschen gehen da respektvoller miteinander um.
Der Kokainhandel war vor zehn Jahren noch viel brutaler.
Ich will auch eine friedlichere Welt, in der so viele Menschen wie möglich Party haben und das arbeiten können, was sie wollen.
Aber trotzdem, gerade dann, wenn ich etwas verändern will, gehe ich in das Haus zur Türe hinein und grüße den Gastgeber, bin freundlich.
Ich gehe nicht durchs Fenster im zweiten Stock, oder breche gleich durch die Wand und zerre alles nach draußen, was ich da drinnen finde.
In jedem Haus ist ein bisschen Unordnung.
Das lässt sich nicht vermeiden.
Aber ist meistens kein böser Wille.
Das Einzige, was ihr mit dem ganzen Öffentlichmachen erreicht, ist, dass alle aufwachen und dann wird es brutaler.
Warum macht ihr das?
Man ändert die Dinge doch besser von innen.
Das „Nicht-Dagegen“ gehört doch zu den Cypherpunk-Idealen?
Mir gefällt jede Menge nicht, was da abgeht, zum Beispiel, dass immer noch einige ohne Zögern Menschen töten oder das in Auftrag geben.
Das ist bescheuert, das ist krank.
Das LBI nimmt den Tod von Tausenden Menschen in Kauf, jedes Jahr.
Und sie sagen: Sonst würden mehr Menschen sterben. Sie sagen: Sonst würden Amerikaner sterben.
Und dann sage ich ihnen: Hej, und wenn ich sterbe, dann ist das nicht so schlimm.
Ich bin zwar Amerikaner, aber Südamerikaner und die sind für euch weniger wert.
Was ist das?
Aber sie meinen, das würde mein Land genauso sehen.
Jedes Land hat die Aufgabe für seine eigenen Bürger zu sorgen.
Das ist der Preis dafür, dass es ein freies Land ist.“

Lasse: „Du hast Kontakt zum … LBI?“

Fortunato: „Klar hab ich das.
Sonst wäre ich schlecht in meinem Job.
He.
Ich bin kein kleines Licht.
Genauso wenig wie ihr kleine Lichter auf eurem Gebiet seid.
Das LBI kauft bei mir Aufenthaltsorte von Leuten.
Vieles mache ich genauer als die NSA.
Auf jedem Fall unkomplizierter und schneller.
Sie schicken mir eine E-Mail-Adresse oder eine Handy-Nummer und sie bekommen einen Link zu einem Tor-Hidden-Service, wo sie den aktuellen Aufenthaltsort und alle anderen in den letzten acht bis neun Jahren abrufen können.
Ich arbeite gerade daran, dass auch die ganzen Überwachungskameras dazu kommen.
Es gibt da inzwischen tolle Händler, die bieten dir 30 bis 40 Prozent aller Überwachungskameras in einer Stadt wie Caracas: Ort, Richtung, Reichweite und komplette Aufnahmen.
Wenn du weißt, wo genau jemand ist, dann kannst du die passenden Überwachungskamerabilder einblenden.
Live.
Dann kannst du verfolgen, wo der Kerl oder das Mädel gerade steckt und was es tut.
Echt geile Technik, sage ich dir.“

Lasse schaute Fortunato an: „Kann ich mal sehen, wie das aussieht?“

Der atmete kurz durch.
„Wie meinst du?
Eine Überwachungsseite?
Ok.
Hast du eine E-Mail-Adresse oder eine Telefonnummer?“

Lasse überlegte, fasste sich an die Nase und meinte dann in leicht hastigem Ton: „strider4@posteo.de“.
Er schaute Fortunato an.

„Einen kleinen Moment“, meinte Fortunato, „es dauert ein, zwei Minuten.“

Lasse schüttelte den Kopf: „Nur ein, zwei Minuten, scheiße ...“

Sigur schrieb: „Ich bekomme voll die Wut.
Ich dreh ihm den Hals zu.
Der hat null Respekt vor Privatsphäre.
Null komma null.“

Fortunato stöhnte leise: „Uh.
Er ist tot.
Gestorben am 17. Mai 2022.
Das ist Amonium, das ist sein Hackername.“

Er schaute Lasse fragen an.

Lasse: „Genau.
Ich würde gerne die Überwachungskameras vom 17. Mai 2022 sehen.
So gegen 16:30 Uhr.“

Fortunato stöhnte laut: „Du wolltest sehen wie das System funktioniert.
Und jetzt sind wir schon wieder beim Enthüllen.
Das ist nicht mein Ding.
Ich reiße keine Wände ein.
Ich kann dir gerne die Bilder vom 16. Mai zeigen.“

Lasse aufgeregter: „Du hast die Bilder.
Nicht wahr?
Du weißt, was da passiert ist.“

Fortunato: „Nein, ich habe sie nicht.
Ich habe sie gelöscht.
Der ganze 17. Mai ist gelöscht.
Alle haben ihn gelöscht.“

Lasses Gesicht wurde rot.
Laut: „UND DAS IST OK?
Geschichte löschen?
Lügen?
Manipulieren?
Das war ein Freund von mir, von uns beiden.
Und ich meine Freund.
Wir konnten uns komplett auf ihn verlassen.
Er hat manchmal auf meinen Laptop aufgepasst.
Ich hätte ihm mein Leben anvertraut.
Und dann wird er vor eine Straßenbahn gestoßen und stirbt, und alle Bilder davon sind weg, nichts da.
Wir haben überall danach gesucht.
Stadtverwaltung, Geschäfte, Bahn, alles war weg.
Einfach weg.
Das ist Scheiße.
Und du machst da mit!
Das ist Scheiße!“

Fortunato: „Ich habe ihn nicht gestoßen.
Und wenn ich sie nicht gelöscht hätte, dann wären meine Kontakte zu den Auftraggebern eingefroren.
Sie sind da knallhart.
Wenn sie etwas löschen wollen, dann musst du das tun, sonst bis du draußen.
Und nicht nur eine Zeit lang, sondern gleich für immer.“

Sigur schrieb: „Hosenpisser.“

Lasse: „Aber du hast die Bilder gesehen?“

Fortunato: „Ja.“

Lasse: „Er wurde gestoßen.“

Fortunato: „Ja.“

Lasse vergrub sein Gesicht in seinen Händen.
Amonium, Sigur und er.
Sie waren immer zu dritt unterwegs gewesen.
Sie hatten die Welt aufgemischt.
Sie hatten zu dritt alles gelernt, was sie jetzt konnten.
Und dann, von einem Tag auf den anderen war er weg.
Und keine Möglichkeit mehr im Spiel zusammen zu kommen.

Lasse: „LBI?“

Fortunato: „Nein, nicht LBI.“

Er holte einen Zettel und einen Bleistift aus der Tasche, kritzelte „Doch LBI“ drauf und schob ihn Lasse hin.
Dann zuckte er mit den Schultern, als wollte er sich bei Lasse entschuldigen.

Sigur klappte seinen Laptop zu und nahm seinen Kopfhörer ab: „Fertig! Lass uns schlafen gehen.“

Lasse und Fortunato drehten sich zu Sigur.
Der schaute völlig ungerührt zurück, ein bisschen gelangweilt.

„Du cooler Hund“, dachte Lasse und seine Wut ließ nach.

„Ja ...
ok“, meinte er und nickte, „lass uns ins Bett gehen.“

Er schaute Fortunato an: „Wenn dir irgendwann wieder Bilder vom 17. Mai über den Weg laufen, dann schicke sie mir bitte.“

Fortunato: „Eure Zimmer sind auf der Empore, die Treppe da rauf und dann links.
Ich schaue noch ein bisschen Fernsehen.
Gute Nacht euch.“

„Nacht“, gab Sigur zurück und beide stiegen die Treppe hinauf.
