== [big-number]#2021# Night-Owl

[text-caps]#Paul saß im# Besprechungszimmer an seinem Tisch.
Vor ihm lagen fünf Papierflieger und zwei Schiffe.
Er summte leise „Don't worry, be happy“ vor sich hin.

Die Türklinke bewegte sich langsam nach unten und die Tür öffnete sich.
Herein kam ein schmächtiger junger Mann in Sträflingskleidung, Anfang 20, ein wenig vorsichtig schauend, schlich an Paul vorbei und setzte sich auf den Stuhl gegenüber.
Er hatte weder Hand- noch Fußfesseln, aber Druckstellen waren sichtbar.
Beide schauten sich an, aber sprachen lange Zeit nicht.
Irgendwann streckte ihm Paul seine Hand entgegen.

Paul: „Paul.“

Er nahm Pauls Hand.

Amon: „Night-Owl.“

Paul erschrak: „Nicht die Hacker-Namen, nicht hier.
Sie hören zu, sie nehmen alles auf.“

Amon: „Sie wissen das schon.“

Paul: „Du bist wirklich Night-Owl? Der Night-Owl? Der Überwachungskamera-Hack?“

Amon nickte langsam.

Paul: „Wow.
Ich habe so viel von dir gelernt.
Wie lange bist du schon hier?“

Amon: „Zwei Jahre, zehn Tage, fünf Stunden.“

Paul: „Shit.
Dann haben sie dich am gleichen Tag wie mich geholt.
Berlin?“

Amon nickte wieder.

Paul: „Boah.
Berlin ist eine große Stadt.
Wenn ich gewusst hätte, dass Night-Owl in Berlin ist … Wow.“

Amon: „Damals dachte ich das auch so, wow, Berlin.
Aber das ist jetzt anders ...“

Paul: „Anders?“

Amon: „Ich will das hier nicht mehr, ich will das da draußen auch nicht mehr.
Es ist alles so scheiße.“

Paul: „Sie wollen mich rauslassen!
Ich glaube heute.
Dich nicht?“

Amon: „Vergiss es.
Das sind Tricks.
Mich haben sie schon dreimal rausgelassen.
Ich habe Papiere unterschrieben, versprochen, dass ich nichts sage – bis an mein Lebensende nichts sage, sonst würden sie eben dieses Lebensende vorverlegen.
Genauso haben sie das gesagt.
Und ich wollte nur noch raus.
Ich hätte alles unterschrieben … Und dann stand ich dreimal schon draußen an der Bushaltestelle, mit allen meinen Sachen und dann kam kein Bus sondern ein Jeep und sie haben mich wieder geholt.
Ich sage inzwischen alles, was sie hören wollen … Es ist eh egal.“

Paul: „Du musst dir etwas behalten.
Etwas, was sie nicht haben.
Die Wahrheit.
Du darfst nicht lügen!
Dann gehst du auf ihre Seite ...“

Amon hielt sich die Hände vors Gesicht: „Das schaffe ich nicht mehr.
Ich werde hier verrückt.
Natürlich gehe ich auf ihre Seite, wenn ich dann hier raus komme.“

Paul nahm seine Hand: „Nicht lügen!
Sonst wirst du wirklich verrückt.
Sie sind verrückt, weil sie so viel lügen.
Zu lügen macht verrückt.“

Tränen kullerten von Amons Backen.
Er ließ sie einfach laufen, wischte sie nicht ab.

Paul: „Was haben sie dir gesagt, das du hier tun sollst?
Mit mir?“

Amon reagierte nicht.

Paul: „Du weißt, dass das ein Spiel ist.
Sie spielen immer Spiele.
Komm, schreib es hier auf den Zettel und verdeck es mit deiner Hand.“

Amon schaute kurz in Richtung der Überwachungskamera vor ihm und nahm dann den Zettel.

Amon schrieb: „Ich weiß nicht.
Sie haben gesagt, du wärst verrückt geworden und wolltest hier nicht raus.
Und du brauchst jemanden zum Reden.“

Paul las den Zettel und schaute ihn verwirrt an.
Amon zuckte mit den Schultern.

Amon schrieb: „Willst du denn nicht raus?“

Paul: „Natürlich will ich hier raus.
Aber da ist irgendein faules Spiel im Gang.
Sie handeln völlig verdreht.
Wahrscheinlich wegen Marianne.“

„Marianne? Marianne Lasser?“, schrieb Amon.

Paul nickte und schrieb: „Meine Schwester.“

Amon: „Was?? Marianne ... ist deine Schwester?
Geil.
Ich habe einmal bei einem Hackaton mit ihr gespielt.
Sie ist so sauschnell.“

Paul: „Sie hat vor zwei Jahren einen TAO-Rechner gehackt.
Deswegen bin ich wohl hier.“

Amon: „Sie ist auch hier?“

Paul: „Nein.
Sie ist in Freiheit.
Immer noch.
Nach zwei Jahren!
Geil, nicht?“

Amon: „Woher weißt du das?“

Paul sagte laut: „Ich weiß es.“

Dann nahm er das Papier und stopfte es sich in den Mund.

Paul schluckte es hinunter und grinste: „Es ist nicht einmal schlimm für den Magen.
Jetzt haben sie zwei, drei Stunden Zeit es rauszuholen, wenn sie noch etwas davon lesen wollen.“

Amon musste lachten.
„Es tut so gut, einen Menschen vor sich zu haben“, dachte er.
„Ich hatte fast vergessen wie das war.“ 

Paul sagte in normaler Lautstärke: „Night-Owl, wenn wir hier rauskommen, dann machen wir einen Hack zusammen – Nein, nein, Spaß … Wir werden ganz brav sein.“ 

Paul schrieb auf das nächste Blatt: „Wir haben schon einen zusammen gemacht.
Deine 'Bachelorarbeit', so hast du ihn damals einmal genannt.
Aber bitte, schreib nicht meinen richtigen Namen.“

Amon lachte über das ganze Gesicht.
„Du?
Du warst das?
Wow.
Ich wollte dich immer einmal in echt treffen.
Das war so geil da drin.
Sie hatten überhaupt keine Chance gegen uns.
Nicht eine Spur.“

Paul: „Kein bisschen!“
Ihm traten Tränen in die Augen.

Amon: „Geil!“ 

Amon schob das Papier weg und sagte: „Warum machen sie so etwas? Warum sperren sie uns weg? Warum brüllen sie uns an, hauen uns Vierkanthölzer gegen den Kopf, entziehen uns das Licht, erzählen uns, dass unsere Familie ermordet wird? Warum lassen sie uns scheinbar frei, lassen uns nicht schlafen und geben uns kaputte Computer mit Scheininternet? Warum? Warum gibt es solche Arschlöcher?“

Paul: „Sie wissen nichts von unserer Welt.
Sie wissen nichts davon, was es heißt, nach eigenen Ideen zu leben und nicht nach dem, was andere ihnen befehlen oder vorgaukeln oder eingeredet haben.
Sie halten das für naiv, wenn Menschen auf ihrem eigenen Boden stehen wollen.
Sie meinen, dass es naiv ist, wenn sie sich nicht an das System anpassen, dass sie nichts mehr machen können, wenn sie einen schlechten Lebenslauf bekommen, in dem steht, dass man sich nicht auf sie verlassen kann oder dass sie nicht gut arbeiten.
Ohne so einen Lebenslauf könnten sie nicht leben, meinen sie.
Sie könnten sich kein Haus mehr leisten oder kein Auto, keine Familie ernähren, wenn sie nicht einen Job machen, wo ihnen jemand sagt, was sie zu tun haben.
Es ist so krank.
Das sind erwachsene Menschen und sie glauben, sie müssten sich beugen, sonst klappt das mit ihrem Leben nicht.“

Amon: „Das ist wirklich krank!
Und wir haben doch niemandem geschadet.
Nicht wirklich.
Es ist doch kein Schaden, wenn wir ein paar tausend Überwachungskameras abschalten oder umfunktionieren, oder wenn wir die Riesenwerbedisplays mal für ein paar Tage für uns benutzen, um Tetris zu spielen.
Müssen sie uns dafür einsperren?
Okay, ich habe die V-Leute-Datenbank beim BND gehackt.
Das war dumm.
Da sind sie wild geworden.
Aber ich hatte so eine Scheiß-Wut, weil so viele Leute um mich herum Geld dafür bekommen, mich auszuhorchen.
Und es wäre doch besser für die Menschheit, wenn die ganzen V-Leute öffentlich werden würden.
Und für sie auch.
Das ist doch ein Scheiß-Job.“

Paul: „Du hattest die V-Leute-Datenbank?
Scheiße.
Warum hast du sie nicht weitergegeben?
Die hätte ich auch gerne gehabt.“

Amon: „Ich hatte nur die Datei, mit VeraCrypt verschlüsselt.
Aber ich hatte auf dem BND-Computer schon ein kleines Wächterprogramm installiert, das mir das Passwort schickt, sobald sie einer geöffnet hätte.
Hat aber keiner, in zwei Monaten nicht.“

Paul: „Ich hätte da in Berlin wirklich ein paar Fragen an diese Datenbank gehabt ...“

Amon: „Hatte ich auch.
Jetzt ist mir das egal.
Und du bist wirklich nicht wegen einem eigenen Hack hier?“

Paul nahm das Blatt und schrieb: „Ich glaube nicht.
Ich habe keinerlei Fragen in Richtung der Sachen bekommen, bei denen ich dabei war.“

Amon sagte laut: „Scheiße! Die sind einfach nur Scheiße.“

Eine Tür öffnete sich und ein Soldat erschien.

Soldat: „Night-Owl, austreten!“

Amon erhob sich und folgte ihm nach draußen.
Paul schloss die Augen und sagte leise: „Shit! Das war ein Trick.“
Er verzog sein Gesicht, wischte sich die Tränen aus den Augen und stopfte dann das Blatt in seinen Mund.
