== [big-number]#2064# Spezial-Kommando

[text-caps]#5:45 Uhr.#
Fortunato saß allein im Wohnzimmer und drehte an einem Rubiks Cube.
Bei einem leisen Geräusch eines anhaltenden Fahrzeugs, schaute er auf und horchte.
Er stand auf, ging zur Eingangstür und öffnete sie leise.
Sieben Mann eines Einsatzkommandos betraten das Apartment in voller Ausrüstung mit Sturmgewehren im Anschlag.
Der letzte trug zwei große Medizinkoffer.
Fortunato führte sie leise die Treppe nach oben.

Fortunato zum Gruppenführer: „Rechts ist Lasse.
Links Sigur.
Lasse ist im Tiefschlaf, ich habe ihm Gas gegeben.
Sigur normal.“

Der Gruppenführer öffnete leise die rechte Türe und machte ein Zeichen zum letzten Soldaten. Der trug die Medizinkoffer ins Zimmer.
Er kniete sich neben Lasse und prüfte Atem und Puls.
Dann drehte er Lasses Kopf zur Seite und setzte eine Art von Impf-Pistole an seinen Hinterkopf.
Er schloss die Augen und drückte ab.
Noch einem kurzen, gefährlich klingenden „Plick“, legte er die Pistole zu Seite, wischte mit einem kleinen Tuch das Blut weg, das aus der winzigen Wunde austrat. Er verklebte die Stelle mit Wundkleber.
Dann griff er in den Koffer und holte ein handgroßes Gerät mit Bildschirm heraus.
Er knipste es an, zog zwei Antennen heraus und beobachtete kurz die pulsierenden Signale, die auf dem Bildschirm erschienen.
Er gab dem Gruppenführer ein Zeichen, dass alles ok war.

Der Gruppenführer drehte sich zu Sigurs Türe und zählte mit den Fingern von drei herunter.
Bei null trat der erste Soldat die Türe ein und vier weitere stürmten mit lautem Geschrei ins Zimmer.
Zwei Soldaten drehten Sigur brutal auf den Bauch und fixierten seine Arme hinter dem Rücken mit Plastikfesseln.
Ein Soldat hielt ihm seine Waffe direkt neben Sigurs Kop, ein anderer hielt eine starke Lampe auf ihn.
Sigur blinzelte mit den Augen.
Er hatte ein taubes Gefühl im Kopf, das Licht, die Schreie, die brutalen Hände an seinen Armen und Beinen, die vielen Soldaten um ihn herum, das alles war für ihn noch nicht ganz da.
Dann hörte er von weit eine Stimme rufen:

Gruppenführer: „Herr Alvas!
Herr Alvas!
Hören Sie mich?“

Sigur drehte seine Kopf zu ihm und schaute ihn mit einem Auge an.

„Herr Alvas!“, der Gruppenführer nahm sich einen Stuhl und setzte sich neben ihn.
„Hören Sie mir zu!
Hören Sie?
Nicken Sie, wenn Sie mich hören!“

Sigur reagierte nicht.
Einer der beiden Soldaten, die ihn festhielten, drehte seinen Arm.
Sigur stöhnte laut und versuchte zu nicken.

Gruppenführer: „Ok.
Herr Alvas, Sie haben ein paar sehr dumme Dinge getan.
Sie müssten eigentlich wissen, dass Sie damit Leuten auf die Füße treten, die das nicht durchgehen lassen.
Vielleicht haben Sie das einfach ignoriert, vielleicht auch nicht.
Egal.
Falls Sie geglaubt haben, dass Sie uns ungestraft ficken können, dass Sie ungestraft in sicherheitsrelevante Systeme eindringen und sie übernehmen können, dann haben Sie sich geirrt.
Ganz offensichtlich.
Und deswegen bin ich jetzt hier.“

Sigur mit Schmerzen: „Wer ist wir?“

Der Gruppenführer gab einem Soldaten neben ihm ein Zeichen und der schlug Sigur mit der Hand fest auf den Kopf.
Sigur schrie auf.

Gruppenführer: „_ICH_ stelle die Fragen.
Sie warten und geben Antworten.
– Ich könnte Ihnen jetzt ein paar Fragen stellen, um ein wenig mehr über das herauszufinden, was Sie alles gemacht haben.
Unglücklicherweise haben wir aber keine bekannten Wissenslücken über Sie.
Wir wissen, was wir über Sie wissen wollen.
Und das ist eine Menge.
Ich bin nicht hier um Fragen zu stellen.
Ich bin hier, um mit Ihnen einen Deal zu machen.
Naturgemäß, in der Situation, in der wir uns befinden, wird der Deal eher etwas einseitig sein.
Es wird nicht sehr viele Vorteile auf Ihrer Seite geben, aber doch einen zumindest:
Sie werden das überleben.
Ansonsten sind es eher Verpflichtungen.
Aber Sie werden trotzdem unterschreiben.
Nicht mit einem Stift, nicht auf Papier, und auch nicht selbst.
Das machen wir für Sie.
Und zwar in Ihrem Körper mit so einem kleinen Kügelchen.
Sehen Sie?“

Er hielt ein Kügelchen mit etwa fünf Millimetern Durchmesser vor Sigurs Gesicht.
Der hatte sich abgewandt und reagierte nicht.
Er bekam einen weiteren Schlag gegen den Kopf und drehte sich dann zum Gruppenführer hin.

Gruppenführer: „So ein Kügelchen, ein Wunderwerk der Technik und eine nette Erfindung aus unseren Folterkammern, entschuldigen Sie, aus unseren Räumen für fortgeschrittene Verhörtechniken.
Da ist ein Funkcontroller eingebaut und ein Multifunktionsprozessor.
Und den haben wir so programmiert, dass er vor allem zwei Dinge tut.
Erstens meldet er auf Bedarf Ihren Aufenthaltsort und weitere Körperdaten wie Herzschlag, Blutdruck etc.
und zum zweiten kann er jederzeit die Kapsel platzen lassen, und dann tritt etwa ein halbes Gramm Kaliumcyanid, das ist Blausäure, in ihren Körper.
Daraufhin erleben Sie einen etwa ein bis zwei Stunden dauernden Todeskampf.
Ist einer der unangenehmsten, die es gibt.
Ach ja, und falls Sie auf die Idee kommen sollten, ab jetzt in einen funkabgeschirmten Raum zu gehen: Nach etwa zwanzig Minuten dort öffnet sich die Kapsel auch.
Sie braucht den Kontakt zu uns.
Wir wollen nämlich immer wissen, wo Sie sind und wie es Ihnen geht.“

Sigur versuchte sich zu befreien, riss seine Schultern hin und her, strampelte mit den Beinen.
Die Soldaten drückten ihn mit Gewalt auf das Bett.
Er verlor vor Schmerzen fast das Bewusstsein.

Gruppenführer: „Wir können das mit Schmerzen machen, oder relativ unspektakulär.
Ihre Entscheidung.
Was wollen Sie?
Hmm?“ Er gab ein weiteres Zeichen und die Soldaten drehten Sigur mit Gewalt auf den Rücken.
Sie fixierten seinen Körper mit breiten Klebestreifen ans Bett.
Der Soldat mit den Medizinkoffern kam, stellte sie vor Sigur ab und öffnete sie.
Dann nahm er sich einen Stuhl, setzte sich und holte eine Spritze heraus.
Er stach sie seitlich in den Bauch von Sigur.

Soldat: „Das ist eine örtliche Betäubung.
Sie werden keine Schmerzen spüren.“

Er öffnete Sigurs Hose und zog sein Hemd hoch, so dass der Bauch freilag.
Sigur zappelte.
Dann sah er den Medizinsoldaten mit einem langen, schlanken Skalpell einmal in seinen Bauch stechen und danach mit einer Pinzette ein Kügelchen in den blutenden Spalt drücken.
Sigur schätzte etwa vier bis fünf Zentimeter tief.
Dann verödete der Medizinsoldat die Wunde mit einem Stift und wischte das Blut weg.

Medizinsoldat: „Sie werden ein paar Tage lang Schmerzen haben, einen blauen Fleck, aber es wird nicht lebensbedrohlich sein.
Die Kapsel hat kleine Widerhaken, die es unmöglich machen, sie herauszuziehen ohne die Häkchen abzubrechen.
Wenn sie abbrechen, tritt das Zyankali auch aus.
Also seien Sie vorsichtig damit.
Ein Schlag in den Magen oder Sport reicht dafür allerdings nicht aus.
Die Häkchen sind auf Druck sehr flexibel.
Nur Ziehen geht nicht.
Joga machen sie besser nicht.“

Sigur wurde übel.
Er wollte sich erbrechen.
Sein Körper zuckte hin und her.
Er hatte eigentlich schon aufgegeben.
Aber der Körper wehrte sich noch.
Er konnte den Kopf gerade noch zur Seite drehen, bevor der Schwall Erbrochenes aus seinem Mund spritzte und vor allem den Boden vor dem Bett und den Gruppenführer traf.
Der sprang auf.

Gruppenführer: „Teufel!
Passen Sie auf!“ Ein Soldat haute Sigur wieder gegen den Kopf.

Gruppenführer: „Das ist ja ekelhaft!
Uah.“ Er sah sich von oben bis unten an und nahm dann das Handtuch, das ihm der Medizinsoldat reichte.
Er begann sich damit abzuwischen.
„Sauerei.“

Der Medizinsoldat holte wieder das Messgerät heraus, kontrollierte die Messdaten des Kügelchens in Sigurs Bauch und packte es dann wieder ein.

Medizinsoldat: „Fertig!“ Er schmiss die restlichen Sachen in die Koffer, klappte sie zu und verließ damit den Raum.
Die anderen Soldaten folgten ihm.
Der Gruppenführer stand als letzter alleine im Zimmer und schaute auf Sigur: „Machen Sie keinen Scheiß, wir beobachten Sie.
Drei Mann werden rund um die Uhr auf Ihren Monitor schauen.“

Dann verklebte er Sigurs Mund mit einem Klebeband und verließ das Zimmer.

Einige Stunden danach wachte Lasse auf.
Er hört seltsame Geräusche aus dem Nachbarzimmer.
Sein Kopf dröhnte wie nach einem exzessiven Bierabend, zumindest stellte er sich das so vor, weil er noch nie wirklich betrunken gewesen war.
Er stand auf und spürte einen ziehenden Schmerz im Kopf.
Er wankte.

„Was ist los?“, dachte er und richtete sich auf.
Er ging zu Sigurs Türe, öffnete sie und fand Sigur gefesselt am Bett, mit hochrotem Kopf, zappelnd.
Lasse sprang zu ihm, riss ihm das Klebeband vom Mund und öffnete die Plastikfesseln mit einem Messer, das er in Sigurs Rucksack fand.

Sigur richtete sich auf und setzte sich auf die Bettkante.
Er atmete schwer.
„Sie haben mich gebugged.
Ich habe eine Kapsel im Bauch.
Sie haben gesagt, es wäre Zyankali drin.“

Lasse: „Oh, shit.
Gott, nein.
Er setzte sich neben ihn.
Nein, nein, nein.
Wer war das?“

Sigur: „Ein Swat-Team mit Mediziner: fünf bis acht Leute.
Ich weiß nicht mehr.
Es war wie im Film.“

Lasse: „Aber sie haben dich nicht mitgenommen!“

Sigur: „Nein, anscheinend nicht.“

Sie hörten ein leises Wimmern vom unteren Stockwerk.
Beide horchten auf.

Lasse: „Wo ist eigentlich Fortunato?
War der dabei?“

Sigur: „Sicher.
Aber ich habe ihn nicht gesehen.“

Lasse schaute vorsichtig um die Ecke, die Treppe hinunter ins Wohnzimmer.
Auf einem der Sessel lag Fortunato, gefesselt an Händen und Füßen, mit Klebeband über dem Mund und ähnlich rotem Kopf wie Sigur.
Lasse lief hin und befreite ihn.
Fortunato ließ sich in den Sessel sinken und rieb sich sein Arme.
Sigur kam auch und so saß die Runde wie am Abend zuvor um den Wohnzimmertisch.

Fortunato schwer atmend: „Mit euch erlebt man Sachen!“

Lasse und Sigur schauten sich an.
Sigur schloss die Augen, schüttelte leicht den Kopf und zischte zu Lasse: „Ich will nur raus hier.“
Lasse nickte.

Fortunato: „Ich hatte fünf Jahre keine Razzia!
Ich kenne Leute hier.
Niemand macht eine Razzia bei mir.
Das waren US-Amerikaner.“

Lasse: „Das war keine Razzia.
Das war eine Geheimdienstaktion.“ Er und Fortunato schauten sich an.
Lasse blickte auf die Wohnzimmeruhr.
„12:15 Uhr.
Shit.
Unser Flieger ist weg.“

Fortunato: „Wann ist er gegangen?“

Lasse: „Er geht 12:35 Uhr raus.“

Fortunato: „Wollt ihr noch fliegen?
Wollt ihr raus hier?
Das ginge noch.“

„Ja, raus hier“, meinte Sigur mit dunklem Gesicht.

Lasse: „Aber es reicht eh nicht.
Wir müssen hinfahren und einchecken und ...“

Fortunato: „Der Flughafen ist hier gleich um die Ecke, 30 Minuten.
Ich verschiebe den Abflug um eine Stunde.
Dann müsst ihr euch nicht beeilen.“

Lasse schaute ihn an.
Sigur nickte und Fortuanto griff zum Telefon.

Fortunato: „Taxi kommt in 10 Minuten.
Jungs, ist mit euch alles in Ordnung?
Du siehst fertig aus, Sigur.“

Sigur: „Alles ok.
Ich hole meine Sachen.“

10 Minuten später hupte das Taxi vor der Türe, Lasse und Sigur verließen das Apartment mit ihren Rucksäcken auf dem Rücken.
Lasse drehte sich um und winkte kurz.

Fortunato ließ sich in einen Sessel fallen und atmete durch: „So eine Aufregung!
Das ist immer so mit den Gringos.“
Er schüttelte den Kopf.
„Jetzt erst einmal eine Mate und dann im Shop nachschauen, was inzwischen passiert ist.“ Er schnappte sich sein Tablett und rief erstaunt: “Hej!
622 Bitcoins!
Seit gestern Nachmittag.
Wow!
Das Ding läuft.“

Er atmete noch einmal tief durch und gab das Passwort für seinen Bitcoin-Tresor ein.