== [big-number]#2064# Nichts wie weg hier!

Im Taxi.

[text-caps]#„Halt an!“ schrie# Lasse zum Fahrer.
Sigur neben ihm würgte.
Er öffnete die Tür, stolperte hinaus und erbrach sich.
Dann kauerte er für einige Augenblicke an der Stelle.
Lasse kam von hinten und hob ihn auf: „Komm, denk irgendetwas, wenn wir wirklich hier rauskommen, im Flieger sitzen, heim … komm, noch ein bisschen ...“ Er zog ihn ins Taxi.

Sigur war kreidebleich, seine Augen schwarz unterlaufen.
Er ballte immer wieder seine Fäuste und schüttelte den Kopf.

Lasse: „Komm, halt durch, noch zehn Minuten.“

Der Fahrer fuhr nicht zum Haupteingang des Flughafens, sondern durch eine Service-Schleuße.
Ein Mann mit Gepäckwagen wartete dahinter auf sie.
Lasse und Sigur nahmen ihre Rucksäcke und kletterten auf den Wagen.
Der Mann reichte ihnen wortlos einen Flasche Wasser, die Sigur gerne nahm, nickte ihnen zu und fuhr sie direkt zu ihrem Gate, wo an der Treppe ein Steward wartete.

Steward: „Keine Koffer?
Umso einfacher.
Folgen Sie mir.“

Sie gingen zusammen die Treppe hinauf, niemand schien sich für sie zu interessieren.
Lasse und Sigur fanden einen Platz auf einer Bank vor dem Gate-Schalter und ließen sich auf die Bank fallen.
Zurück in der normalen Welt.
Menschen, die auf einen Flug warteten, in Smartphones vertieft, einer ein Laptop mit Facebook.
Auf dem Display über dem Flugschalter stand: 

Erwartete Abflugzeit: 13:35 Uhr.

Lasses schüttelte den Kopf und sagte leise: „Fortunato“.

Sigur lehnte seinen Kopf gegen Lasses Schulter und schloss die Augen.

„Das hat Sigur noch nie getan“, dachte Lasse und legte seinen Arm um ihn.

Nach etwa einer Dreiviertelstunde wurde der Flug aufgerufen.
Sie stellten sich in die Schlange vor dem Gate-Schalter.
Lasse zeigte Ausweis und Ticket, wurde durchgewunken.
Sigur wollte gerade das Gleiche tun, da griff ihm von hinten ein Mann in Anzug an die Schulter.
Sigur drehte sich in Panik um.
Zwei riesige Sicherheitbeamte standen vor ihm, Bodybuilder mit Knopf und Ringelschur am Ohr.
Ein weiterer ging mit großen Schritten auf Lasse zu, der sich umgedreht hatte.

Sicherheitsmann zu Sigur: „Wir haben noch ein paar Fragen.“

Sigur hielt den Atem an, er dachte panisch: „Wo ist ein Fluchtweg?“ Er schaute links und rechts.
Aber der zweite Sicherheitsmann stand schon hinter ihm und fasste ihn fest an der Schulter.

Zweiter Sicherheitsmann: „Kommen Sie bitte mit!“

Lasse stürmte Richtung Sigur los, aber der Sicherheitsmann  vor ihm fing ihn ab.
In den Armen des Sicherheitsmannes starrte er panisch in die Richtung, in die Sigur gerade fortgebracht wurde, aber er kam nicht los.

Dritter Sicherheitsmann: „Ruhig!
Seien Sie ruhig!
Es hat sowieso keinen Zweck.
Gehen Sie ins Flugzeug!
Hier gibt es für Sie nichts.“
Lasse versuchte alles, um loszukommen.
Er schrie ihn an, aber der Mann hielt ihn fest.
Erst als die beiden anderen Männer mit Sigur hinter einer Tür verschwunden waren, ließ er ihn los.
Lasse rannte auf die Tür zu und rüttelte an der Klinke.
Niemand schien ihn zu beachten.
Nur einige Passagiere schauten im Vorbeigehen verwundert.
