== [big-number]#2020# An einem See in Tasmanien

[text-caps]#Marianne saß auf# einem Bootssteg an einem Seestrand in Tasmanien.
Ihre Füße ließ sie im Wasser baumeln.
Sie trug einen großen Sonnenhut.
Die Abendsonne tauchte alles in ein warmes Licht.
Vor ihr schaukelte ein am Steg festgebundenes Boot auf den Wellen.
Vom Hügel hinter ihr kamen zwei Männer auf sie zu.

„Hier, entlang … Fred? War das Fred?“

Hans zeigte den kleinen Hügel hinunter Richtung See, wo Marianne saß.
Ein Trampelpfad führte genau dort hin.

Fred: „Fred, ja!
– Das da ist Marina?“

Hans nickte.


Fred: „Kann ich sie allein überraschen?
Wir haben uns lange nicht gesehen.“

„Klar“, meinte Hans.
„Dann fange ich schon einmal mit dem Abendessen an.
Heute machen wir … lass mal überlegen ...
Auflauf mit Auberginen, Zucchini, Süßkartoffeln und Käse.
Alles eigener Anbau.
Es wird dir schmecken.“

Er drehte sich um und verschwand den Hügel hinauf.

Fred schlich leise den Trampelpfad nach unten.
Er blickte die ganze Zeit auf Marianne und wollte auf keinen Fall irgendeinen Geräusch machen.
Als er drei Meter hinter ihr war blieb er stehen.
Sie drehte sich plötzlich um, aber erschrak nicht, wie Fred vermutet hatte, sondern lächelte, schluckte, lächelte wieder und hielt die Hand vor ihren Mund.

Marianne: „Fred!!!“ Sie sprang auf und fiel ihm um den Hals.
„Fred!
Du bist da, du bist da!
Super!“ Sie umarmten sich lange und setzten sich dann zusammen auf den Steg.

Fred: „Und, erzähl … wie ist es bei dir gerade?“

Marianne: „Total schön hier.
Hans ist so super.
Er lebt seit vierzig Jahren hier auf diesem Fleck.
Er ist aus Deutschland.
Sein Vater dachte in den 70er Jahren, dass in Europa eine Katastrophe kurz bevorsteht und ist damals mit der ganzen Familie hierher gezogen.
Er hat hier ein Minihostel und baut mit seiner Frau zusammen fast alles selbst an, was sie essen.
Natürlich alles Bio.
Und ich helfe ihm jetzt.
Ich bin eine Austauschstudentin.
Ich habe schon jede Menge gelernt: Richtig hacken, so mit einer echten Hacke, du weißt schon?“
Sie machte eine Handbewegung.
“Ich kann hier bleiben, so lange ich will.
Ich arbeite hier, bekomme Essen, ein Bett, Internet und ein bisschen Taschengeld.
Das machen viele hier in Tasmanien.
Sie kommen aus der ganzen Welt und verbringen hier ein paar Wochen, ein paar Monate oder ein Jahr.“

Fred: „Du hast keine Angst?“

Marianne schüttelte den Kopf.
„Überhaupt nicht.
Ich bin als Zweit-Ehefrau in Burka auf einem Schiff super aus Saudi-Arabien rausgekommen.
Ein entfernter Verwandter von Achmed, im 18.
Jahrhundert haben sie einen gemeinsamen Urururururgroßvater, hat mich zusammen mit seiner richtigen Frau nach Indonesien mitgenommen.
Dort bin ich Rucksacktouristin geworden, mit einem Ausweis, den ich noch von Paul hatte, und bin dann nach Tasmanien getrampt.
Hans hier ist ein Onkel um eine Ecke von einem Darknet-Hacker, der in seinem normalen Leben einen Büro-Job hat, überhaupt nichts mit Computerprogrammierung.
Sie haben sich in den letzten vierzig Jahren einmal gesehen.
Aber das Beste von allem ist Tasmanien.
Die Insel ist etwa so groß wie Bayern, gleiches Klima, hat aber nur eine halbe Million Einwohner, 7 Einwohner pro Quadratkilometer.
Hier kennt echt jeder jeden.
Und hier passiert nicht viel.
Wenn hier irgendjemand nach irgendjemandem sucht, dann wissen das sofort alle.
So etwas ist für die Leute hier spannend.
Also wenn CIA-Leute in der Gegend auftauchen, dann weiß ich das, bevor sie überhaupt hier ans Haus kommen.
Und ich habe Hans gesagt, dass mich ein eifersüchtiger Freund verfolgt, der auf keinen Fall herausfinden darf, dass ich hier bin.
Er meinte, kein Problem, er sagt mir sofort alles, was er hört.“

Fred schüttelte langsam den Kopf: „Typisch Marianne.
Du versteckst dich in der Öffentlichkeit, wo dich jeder sehen kann.
Das ist dein Ding.
Ich hätte ja an eine Großstadt gedacht, Mexico City, anonyme Hochhaussiedlung.
Aber du gehst dahin, wo dich alle sehen.
Super!“

Marianne: „Hey, und einmal die Woche gehen Hans und ich mit dem Boot da raus und holen Austern.
Frische Austern mit Zitrone, weiß du wie das schmeckt?
Hmmmm.
Das musst du probieren ...
Aber sag du jetzt.
Ich bin so gespannt, mich zerreißt es gleich.
Hast du etwas mitgebracht?
Du wolltest in der letzten Pond-Nachricht nur meine Adresse.“

Fred: „Ich wollte nur deine Adresse, weil ich über alles Weitere mit dir direkt sprechen wollte.“

Marianne schaute ihn voller Erwartung an: „Also hast du es?“

Fred nickte und zog einen USB-Stick aus seiner Tasche.

Marianne hielt die Hände vors Gesicht und quietschte „Jiiiiiiiiiihhhhhhaaaa.“ Sie sprang auf und tanzte um Fred herum, ließ sich neben ihn fallen, küsste ihn auf die Backe und nahm den Stick: „Hier drauf?“ Sie schaute ihn an.

Fred nickte wieder.

Marianne umschloss den Stick mit der Hand und drückte ihn gegen die Brust: „Wie viel?“

Fred: „Ein Terabyte, wie du gesagt hast.“

Marianne kullerte eine Träne die Backen herunter: „Geil.
So geil.
Hast du schon geschaut, was drin ist?“

Fred nickte.

Marianne: „Und?“

Fred: „Ich habe schon viel sortiert.
Ein Katastrophe.
Unfassbar.
MacOSX hat siebzehn verschiedene Hintertüren in allen aktuellen Versionen.
Es ist ein Kinderspiel, damit überall reinzukommen.
Perfekt für Script-Kiddies.
Jeder Schüler kann mit den Codes in die größten Firmen hineinhacken und alles lesen und löschen und klauen und ändern.
Für alle Betriebssysteme sind Dinge da: Windows, Linux, für alle Programme, für alle Computer.
Sie haben eine eigene Abteilung für Festplattenhintertüren, die kommen da schon beim Hersteller drauf, bei jedem großen Hersteller.
Fast jede Festplatte, die du neu kaufen kannst, kommt mit einer Hintertür, die funktioniert, egal welches Betriebssystem du installierst.
Es ist ein bisschen so wie AMT von Intel, nur für Festplatten und eben geheim.
Ich sage dir: Das Internet ist ein riesiger Schweizer Käse, und die Ratten klettern da überall herum.“

Marianne: „Tails?
Tor?“

Fred nickte.

Marianne: „Shit.
Schlimm?“ 

Fred nickte wieder: „Nicht so schlimm wie Windows- und MacOS-Verschlüsselung, aber es gibt was zu tun ...“

Marianne: „Pond, Ricochet, VeraCrypt?“

Fred: „Pond und ricochet scheinen tatsächlich schwierig zu sein für sie, VeraCrypt ein paar kleine Dinge, aber nichts wirklich Kritisches.
Es ist klar, dass die NSA den Vorgänger Truecrypt abschalten wollte.
Es ist wirklich gut.“

Marianne: „Okay.
Ich habe viel darüber nachgedacht.
Als erstes schicken wir die relevanten Schwachstellen an das Tails-, an das Tor-Team, an das GPG-Projekt, OTR.
Wir brauchen sichere Kanäle für die weiteren Dinge.
Die werden dann, wenn nötig, auch einiges an die Linux-Teams weiterreichen.
Also, erst machen wir unsere Software dicht, dann können wir anfangen größere Kreise einzuweihen, damit sie die Lücken flicken können.
Als nächstes dann alles in der Linux- und der BSD-Welt.
Es wird wahnsinnig viel Arbeit werden, aber immerhin wissen jetzt alle, worauf sie schauen müssen.
Wenn du eine Vorlage hast, dann ist es huntertmal einfacher eine Lücke zu schließen.
Wir müssen überlegen, wie viel Zeit wir ihnen geben.
Zu lange dürfen wir nicht warten.“

Fred: „Und MacOSX und Windows?
Smartphones?
IOS, Android?“

Marianne: „Keine Vorwarnung!
Die sehen die Lücken, wenn wir das Ganze veröffentlichen.
Das ist keine freie Software.
Die haben viele Hintertüren selbst eingebaut.“

Fred: „Keine Vorwarnung?
Das kannst du nicht machen.
Die meisten Computer und Smartphones benutzen diese Betriebssysteme.
Milliarden von Menschen.
Wenn du den Entwicklern keine Zeit lässt, die Löcher zu beheben, dann bekommst du ein Chaos, dann … Puhhh.
Nee!
Echt!
Dann kann jeder 12-Jährige mit einem kleinen Programm beim BND rein und Dateien löschen.
Stell dir das vor.
Jeder Exfreund kann bei der Exfreundin auf ihr Smartphone schauen, alles lesen, löschen, verändern, in ihrem Namen Nachrichten schicken … Und umgekehrt.
Du kannst alle Facebook- und WhatsApp-Konten hacken, fremd Online-Banking machen, fremd einkaufen gehen … Und da draußen sind genug Leute, die das machen werden.“

Marianne schüttelte den Kopf: „Ich hatte viel Zeit, um darüber nachzudenken.
So, wie sie die Snowden-Veröffentlichungen kassiert haben.
Die meisten Daten sind immer noch nicht veröffentlicht.
Und da sind Hämmer dabei.
Ne.
Keine Vorwarnung!
Nicht eine Minute.
Nur wenn sie vorher eine Liste mit allen Hintertüren veröffentlichen, die sie selbst eingebaut haben, sie rausmachen und den kompletten Quelltext von ihren Programmen veröffentlichen.“

Fred schüttelte den Kopf: „Das machen sie niemals!
Du hast keine Ahnung, was ...“

Marianne unterbrach: „Wir brauchen das Chaos.
Sonst geht es nicht.
Wir kommen nicht durch, wenn wir ihnen den Faden in die Hand geben.
Nicht mal ein Stückchen davon.
Sie hassen Chaos.“

Fred setzte an, etwas zu sagen, aber zog zurück.

Marianne: „Ich werde dir erzählen, welchen Plan ich seit Saudi-Arabien entwickelt habe.
Es ist ein Risiko, aber es wird gehen.
Aber vorher brauchen wir erst einmal Ruhe.
Wir werden genug Fehler machen, also brauchen wir ruhiges, klares Denken.
Der Plan muss super werden.
Aber damit fangen wir nicht heute an.
Heute bist du hier angekommen, heute gibt es Auflauf, schätze ich, heute ist ein schöner Sonnenuntergang, zum ersten Mal mit dir.
Und überhaupt ich weiß noch gar nicht, wie es gelaufen ist, wie du den Stick bekommen hast, wie es Anita geht, wie sie die Daten herausbekommen hat.“

Fred setzte wieder an, etwas zu sagen, hob seinen Finger, stockte und lachte dann: „Du bist unglaublich!
Wir haben hier das größte Ding seit Snowden, und viel gefährlicher noch als das und gefährlicher als das Collateral-Murder-Video und die War-Logs von Chelsea Manning, und du denkst an Auflauf.“

„Ja“, nickte sie.
„Das ist auch wichtig.
Und Nachtisch.
Hans macht eine tolle Tiramisu.
Komm, wir gehen, dann zeige ich dir noch den Garten, aus dem die Sachen sind, die wir essen werden.“
