== [big-number]#2023# Linda

[text-caps]#Marwin saß allein# mit finsterer Miene im Besprechungsraum.
Alle Papierschiffe und -flieger lagen zusammengeknüllt auf einem Haufen vor ihm.
Die Tür öffnete sich.
Die Frau, die schon einmal im Raum war, kam herein und setzte sich dahin, wo vorher Night-Owl gesessen hatte.
Marwin ignorierte sie so gut es ging.
Sie schwieg auch und schaute ihn an.

Nach einer Weile fragte Marwin: „Habt ihr Night-Owl jetzt auch ein Bein abgesägt?“

Die Frau atmete durch.

„Linda“, sagte sie, „ich bin Linda.“
Sie streckte ihm die Hand entgegen.

Er schaute ungläubig auf ihre Hand, dann auf sie.

Marwin: „Wissen Sie, das ist hier jetzt schon eine seltsame Geste.
Und ich meine das gar nicht sarkastisch.
Seit wann behandeln Sie jemanden wie mich als Menschen?“

Sie zog ihre Hand zurück, weil Marwin kein Anzeichen machte, sie zu nehmen.

Linda: „Ich behandele Menschen immer als Menschen.
Für mich sind alle Menschen auf der gleichen Ebene.“

Marwin schluckte.

Linda: „Das steht so in der amerikanischen Verfassung.
Und die bedeutet mir viel.
Deswegen mache ich hier meinen Job.
Ich bin mit der Verfassung aufgewachsen.
Mein Vater ist Senator.“

Marwin: „Als die amerikanische Verfassung geschrieben wurde, galt sie für alle Menschen – außer für Sklaven, Ureinwohner und ... Frauen.
Frauen waren mit der Verfassung gar nicht gemeint.
Die ist für weiße Männer geschrieben.
Also vielleicht für mich, aber nicht für Sie.
Frauen durften damals noch nicht einmal wählen, geschweige denn studieren oder entscheiden, wo sie wohnen wollen.“

Linda: „Dinge entwickeln sich weiter, auch in der Gesellschaft.
Und ohne die Verfassung hätte sich unsere Gesellschaft nicht so entwickelt.
Es war eine gute Grundlage.
Wir Menschen machen Fehler und lernen aus ihnen.
Und wer weiß, es war eine andere Zeit.
Vielleicht wäre ich als Hausfrau damals ganz glücklich gewesen, auch ohne wählen zu können.
Das weiß ich nicht.
Mit Kindern um mich herum, und ohne diesen täglichen Kampf im Büro, ohne Konkurrenz, ohne ständigen Druck.
Und ohne mit bornierten Offizieren streiten zu müssen ...“

Marwin: „Sie haben sich mit dem Oberst gestritten.
Nicht wahr?“

Linda: „Ja.
Habe ich.
Wir sind uns nicht immer einig.
Sogar eher selten.“

Marwin: „Bei euch in der Verwaltung gibt es überall Streit, ihr seid euch meistens nicht einig, ihr spioniert euch gegenseitig aus, verdächtigt euch, kämpft um Posten, macht andere schlecht, intrigiert ...“

Linda: „Nicht alle machen das.
Aber es gibt solche Menschen.
So sind große Verwaltungen und auch große Firmen eben.
Ich habe auch ein paar Firmen von innen gesehen.
Irgendwie läuft es überall ähnlich.
Die schlechte Nachricht ist: Wir haben nur eine Welt und die ist eben nicht perfekt.
Wir können die Welt so nehmen wie sie ist, unser Bestes versuchen, oder wir können uns eine bessere Welt erträumen und gegen die einzige, die wir wirklich haben, rebellieren, sie verachten und zerstören wollen.“

Marwin: „Oder wir können die Welt so nehmen wie sie ist, sie nicht verachten, nicht zerstören wollen und uns gleichzeitig eine bessere erträumen.
Wir können alle die Dinge ändern, die wir ändern können und alle übrigen so stark träumen wie wir nur können.
Mit all unserer Macht.
Bis diese Dinge sich dann schließlich auch verändern.
Oder wir können aufgeben und uns der derzeitigen Weltordnung beugen, weil man an der eh nichts ändern kann.
Auf die Knie fallen, sich fügen, alles das machen, was sie uns machen lassen will, alles das sagen, was sie uns sagen lassen will und uns selbst das damit erklären, dass wir eben nur eine Welt haben.“

Linda: „Marwin, du hast vorhin gesagt, dass wir von eurer Welt keine Ahnung haben, dass wir nicht wissen, was es heißt, nach eigenen Ideen zu leben.
Wie hast du das gemeint?
Was ist eure Welt?
Was meinst du damit?“

Marwin, gespielt erstaunt: „Ohh!
Du hast uns zugehört?“

Linda wurde leicht rot im Gesicht.

Linda: „Das ist ein Verhörraum. War dir das nicht klar?“

Marwin stöhnte: „Es geht doch nicht darum, ob mir das klar ist, oder nicht.
Natürlich war mir das klar.
Es ist ein guter Umgang zwischen Menschen, wenn man nicht mithört, wenn andere ein privates Gespräch führen.
Das ist für dich bei dir zu Hause doch normal.
Du siehst deine Tochter, wenn du eine hast, auf dem Sofa mit einer Freundin sprechen, beide sind konzentriert, es geht augenscheinlich um etwas Wichtiges, dann gehst du nicht hin und setzt dich daneben oder stellst ein Mikrofon auf und hörst mit.
Das machst du nicht.“

Linda: „Wir sind hier in einem Gefängnis.“

Marwin: „Das ist mir egal!
Ich bin trotzdem Mensch.
Es ist mir egal, ob wir in einem Gefängnis sind oder in einer Sauna oder in einem Hackerspace nachts um 3 Uhr.
Wenn jemand bei einem anderen mitlauscht, wenn der mit jemandem persönlich spricht, dann behandelt er ihn nicht als Menschen, dann verletzt er seine Privatsphäre.
Und das ist ein Grundrecht, ein Menschenrecht.
Dann scheißt er auch auf seine eigene Verfassung.“

Linda: „Es gibt Regeln, die haben wir uns als Gesellschaft gegeben.
Und die erlauben, dass die Grundrechte in bestimmten Situationen eingeschränkt werden.
Jemand muss den Job machen, zu schauen, dass sich Menschen an die Regeln halten.
Es ist eine Tatsache, dass es Menschen gibt, die sich daran nicht halten.
Und ich mache hier meinen Job.
Ich habe mir die Regeln nicht ausgesucht.
Du kannst nicht in eine Gemeinschaft kommen und alle Regeln missachten.
Dann gibt es bald keine Gemeinschaft mehr.
Ich kann versuchen, auf die Regeln einzuwirken, sie menschlicher zu machen.
Aber solange sie gelten, halte ich mich daran.“

Marwin: „Du darfst dich nicht an sie halten, wenn sie gegen die Verfassung verstoßen.
Das sagt die Verfassung.“

Linda: „Was verstößt gegen die Verfassung?“

Marwin: „Mithören.
Das verstößt gegen die Redefreiheit.
Wenn jemand mithört, dann schränkt das die Redefreiheit ein.
Menschen sprechen anders, wenn sie wissen, dass jemand mithört.
Ein Verstoß gegen den ersten Anhang eurer Verfassung.“

Linda: „Nicht in einem Gefängnis.
Und außerdem bist du kein Amerikaner.
Da ist die Lage nochmal anders.
Die Verfassung gilt für amerikanische Staatsbürger.“

Marwin schwieg.
Linda schaute ihn prüfend an.

Linda: „Du kannst nicht allen Ernstes erwarten, dass du in einem Gefängnis ...“

Marwin unterbrach sie: „Du hast vorhin gesagt, dass du alle Menschen immer als Menschen behandelst.“

Linda: „Hey.
Du meinst, ich behandle dich nicht als Menschen, wenn ich hier so mit dir spreche und dann etwas erwähne, was ich vorhin mitgehört habe?“

Marwin: „Genau.“

Linda: „Fuck!“

Marwin: „Du behandelst mich nicht als Menschen, wenn du einen Unterschied machst zwischen Amerikanern und Nicht-Amerikanern, in Bezug auf ihre Menschenrechte.
Ob früher die Sklaven, Ureinwohner und Frauen in der Verfassung nicht gemeint waren, oder ob heute alle Nichtamerikaner nicht gemeint sind, ist genau das gleiche.
Du kannst mich nicht gleichzeitig als Ausländer und als Menschen behandeln.
Das geht nicht.
Das ist rassistisch oder nationalistisch, es ist nicht menschlich, ich werde nicht als Mensch behandelt.“

Linda: „So wie ich jetzt mit dir spreche, so offen, so frei, hat noch überhaupt niemand hier mit dir gesprochen, oder?
Die ganzen zwei Jahre nicht.
Siehst du da keinen Unterschied?
Ich bin offen zu dir.
Ich will wirklich von dir etwas wissen.
Die da draußen denken, dass du dumm bist, oder verrückt oder sonst was.
Ich weiß, dass du das nicht bist.
Meinst du nicht, du könntest das würdigen?
Ich meine, ich strenge mich hier an ...“

Marwin: „Wir sind nicht auf der gleichen Ebene.
Du hast das Recht, jederzeit hier rauszugehen.
Ich nicht.“

Er stand auf und ging mit normalen Schritten Richtung Tür.
Der Soldat an der Tür kam ihm entgegen und stellte sich in den Weg.
Marwin versuchte an ihm vorbeizuschlüpfen, aber der packte ihn und schaute ihn drohend an.
Marwin schlenderte zurück zu seinem Sitz.

Marwin: „Und jetzt du.
Schau mal, ob er bei dir einen Unterschied macht.“

Linda lief im Gesicht rot an.

Marwin: „Und denk dran, du hältst mich für unschuldig.
Du meinst, ich habe nichts gemacht dafür, dass ich hier bin.
Also, ich bin unschuldig und werde anders behandelt als du.
Und du machst nichts dagegen, du hältst das für normal.
So sind die Regeln, an die du dich hältst.“

Linda lauter: „Ich bin hierher gekommen, damit wir einen Weg finden, wie du hier rauskommen kannst.
Verstehst du?
Ich will die Regeln ändern.
Aber du willst ja offensichtlich nicht raus.
Und ich will endlich verstehen, warum nicht.
Und ich will das verstehen, was du vorhin mit eurer Welt gemeint hast.“

Marwin: „Du willst einen Weg finden?
Ich kenne den Weg raus.“ Er stand wieder auf und ging Richtung Tür.
Linda fasste ihn am Arm und wies ihn zurück auf seinen Platz.

Linda: „Es gibt Regeln und wenn wir auf die nicht schauen, dann kommst du hier nie raus.“ 

Marwin: „Kannst du das Mikrofon ausschalten?
Oder ist das auch eine von den Regeln, die man nicht brechen darf?“

Linda überlegte kurz, stand auf, verließ den Raum und kam eine Minute später wieder.

Linda: „Es ist aus.“

Marwin atmete durch.
„Das fühlt sich gut an.
Und die drei hier noch?“ Er zeigte im Raum herum.

Linda: „Okay!“ Sie wies die Soldaten an, den Raum zu verlassen.

Linda: „Okay.
Sie sind draußen.
Wir sind allein.
Jetzt sag mir: Warum willst du hier nicht raus?“

Marwin: „Ich will hier nicht raus, weil ihr über mich Marlene finden wollt.
Ich will hier nicht raus, weil ich nichts lieber will, als sie wiederzusehen, sie zu umarmen, ihr dann auf die Schulter zu klopfen, dass sie es geschafft hat, zu überleben.
Der Scheiß-NSA und der CIA zu entkommen, und sie fragen, was sie in der Zwischenzeit auf die Beine gestellt hat, um sie zu ficken.
Und dann würde ich mir die ganzen Geschichten anhören und mich darüber freuen wie ein Schneekönig.
Dann würden wir zusammen auf irgendeinem Berliner Dach sitzen, eine Mate trinken und den Sonnenuntergang anschauen.
Scheiße.
Aber ich kann nicht zu ihr gehen, weil ihr mir dann folgt und ich sie damit in Gefahr bringe.
Und das halte ich nicht aus, rauszugehen und Marlene nicht zu sehen.
Deswegen will ich nicht raus.
Ansonsten würde ich schon ganz gerne hinfahren, wohin ich will, Leute treffen, mit ihnen spannende Sachen machen, die uns gerade in den Sinn kommen, vielleicht zusammen kochen, mal wieder ein Spiel programmieren oder irgendetwas anderes hacken.“

Linda: „Wir wollen über dich nicht Marlene finden.
Das kann ich dir garantieren.
Wir wollen ...“ Sie stockte.
„Marlene, sie ist … wir wollen ...“ Linda stockte wieder, packte ihre Papiere zusammen und verließ den Raum.

Marwin schaute ihr mit offenem Mund nach.
