== [big-number]#2020# Und los …  

[text-caps]#Drei Wochen später.#

Marianne: „Es fühlt sich gut an, das neue Tor.
Auch Cubes OS.
So frei.
Und Tails.
Viel weniger Ungeziefer … Wahnsinn, was sich in den letzten drei Wochen getan hat.“

Fred: „Du fühlst das?“

Marianne: „Ich glaube schon.
Vielleicht ist es Einbildung, aber irgendwie, wenn ich meine Finger über die Tastatur lege – es ist anders.
Es fühlt sich frisch an.
Doch, definitiv, es fühlt sich offener an.“
Sie kicherte.

Fred: „Marianne!“ Er schaute sie mit ernster Miene an.
„Marianne!“

Marianne schaute ernst zurück: „Ja.“

Fred: „Ich glaube, es ist Zeit.“

Marianne: „Ja, das glaube ich auch.“

Fred: „Und du bist dir sicher, es so zu machen?
Ich meine, echt konsequent.“

Marianne: „Es geht nicht anders.
Die gröbsten Löcher in den freien Programmen sind gestopft.
Die Linuxe und die BSDs laufen einigermaßen stabil.
Alle wichtigen Anwendungen auch.
Nicht perfekt, für viele Kleinigkeiten werden sie noch Monate brauchen, aber es ist okay.“

Fred: „Das sind nicht einmal fünf Prozent aller Computer auf der Welt.“

Marianne atmete durch.

Fred: „Microsoft, Apple und Google haben nicht auf deine Fragen geantwortet?“

Marianne: „Nein, nichts.“

Fred: „Aber sie ahnen etwas?“

Marianne: „Klar.
Sie sehen, was im Linux-Bereich gerade los ist.
Außerdem machen sie überall bei der Entwicklung der freien Software mit.
Sie finanzieren ja komplette Projekte.
Also haben sie die Dokumente der Schwachstellendatenbank dafür auch bekommen.
Nur eben nicht die für ihre eigenen Systeme.
Und das sind Riesen-Lücken, die da plötzlich überall gefunden werden.
Schwachstellen, die zum Teil zwanzig Jahre drin waren und von allen möglichen Leuten ausgenutzt wurden.
Jetzt sind sie weg.
Und dazu haben sie noch unser Angebot bekommen, ihnen ihre Schwachstellen zu geben, wenn sie mitmachen.
Sie machen nicht mit, sie wollen nicht mitmachen, aber sie haben bestimmt schon Notfall-Teams zusammengestellt.“

Fred: „Ja, das war wohl zu viel für sie: alle Hintertüren bekannt zu geben, die sie im Auftrag oder aus eigenem Antrieb in ihre Programme eingebaut haben.
Und den gesamten Quelltext ihrer Programme zu veröffentlichen und öffentlich aktuell halten, damit jeder endlich sehen kann, was sie machen.
Das war wohl echt zu viel.
Sie haben sicherlich unterschrieben, dass sie nichts über die Hintertüren sagen dürfen.“

Marianne: „Das haben sie auf jeden Fall unterschrieben.
Aber was soll das?
Es war genauso illegal sie einzubauen.“

Fred: „Fuck.“

Marianne: „Na dann, gehen wir ran.
Wie viele Webseiten haben inzwischen das ganze Terabyte verschlüsselt zum Downloaden bereit?“

Fred: „253.“

Marianne: „Das reicht.
Wir haben es ja auch noch auf der WikiLeaks-Webseite.
Okay, dann geben wir jetzt den Schlüssel dazu frei.
Über Twitter: The Intercept, Chaos Computer Club, netzpolitik.org, Ed Snowden.
WikiLeaks wird es eh retweeten.
Und alle unsere Kanäle auch.
Alle sollen den Schlüssel gleich weitergeben, Dateien herunterladen, entschlüsseln.“

Fred schaute über seine Schulter: „In jedem guten Krimi wäre jetzt der Augenblick, wo die Tür eingetreten wird und ein Swat-Team schreiend hereinkommt.“
Er grinste und lauschte.
Alles war ruhig.
Marianne stand auf und schloss das Fenster.

Marianne: „Es gibt andere, die den Schlüssel für solche Fälle hätten.“

Fred: „Ich weiß, es sollte ein Scherz sein.“

Marianne: „So, ich drücke … jetzt! … Weg!!“

Fred: „Weg!“

Marianne: „Weg!“
Sie atmete aus und beobachtete ihren Laptop.
„The Intercept hat es schon retweeted, netzpolitik.org, WikiLeaks auch … Okay.
Dann hat es die Welt. Ed Snowden auch.“
Sie nickte Fred zu und beide schauten sich lange in die Augen.

Nach einer Weile zwinkerte Fred ihr zu: „Und jetzt den Brief.“

Marianne: „Ach ja, klar, den Brief.
Okay.
An den Guardian, New York Times, Der Spiegel, Washington Post, etc.“

****
....
AUFRUF AN DIE INTERNET-WELT

Mit den heutigen Tag beginnt ein neuer Zeitabschnitt in der
Geschichte des Internets. Der zurückliegende war geprägt
durch eine immer größere Anzahl von Schwachstellen und
entsprechender Exploits, über die sich jeder, der sie kennt und
das nötige technische Wissen besitzt, unerlaubterweise Zugriff
auf fremde Computer und Smartphones verschaffen kann. Und das
können inzwischen viele Menschen weltweit. Nicht nur Menschen
bei Geheimdiensten, Regierungen und Unternehmen, sondern auch
bei kriminellen Organisationen und auch kriminelle Einzelne.

Wir sehen jeden unerlaubten Zugriff auf persönliche Daten als
Unrecht an. Die einzige Ausnahme hiervon ist, wenn eine
unmittelbare Gefahr für die Freiheit von Menschen besteht,
die durch einen unerlaubten Zugriff möglicherweise abgewendet
werden kann. In solchen Fällen muss kurze Zeit später jeder
einzelne Zugriff lückenlos und vollständig veröffentlicht
werden. Ansonsten ist unserer Ansicht nach insbesondere das
Geheimhalten von Schwachstellen ein Unrecht. Jeder Mensch hat
ein Grundrecht zu erfahren, welche Schwachstellen die Geräte
haben, die er verwendet.

Heute haben wir die umfangreichste Datenbank von geheim-
gehaltenen Schwachstellen veröffentlicht, die je veröffentlicht
wurde. Möglicherweise die größte, die es gibt: die Schwachstellen-
Datenbank der TAO, einer Abteilung der NSA. Dies wird zum ersten
Mal transparent machen, wie sehr alle Computer und Smartphones,
Tablets und andere Geräte mit solchen Schwachstellen durchsetzt
sind. In der Datenbank nicht enthalten sind Schwachstellen in
den Computersystemen von Flugzeugen, Satelliten, Kraftwerken,
Verkehrssystemen und Krankenhäusern, Flughäfen und Industrieanla-
gen. Für sie existiert eine andere Datenbank, die wir nicht hacken
konnten.

Solange die jetzt bekannt gewordenen Schwachstellen von den
Programmierern nicht behoben sind, ist es sehr einfach, in fast
alle Computer und Smartphones einzudringen und an alles heranzu-
kommen, was dort gespeichert ist. Wenn ihr Computer und Smartphones
benutzt, auf denen die Betriebssysteme Windows, MacOS, Android, iOS
laufen oder andere, die nicht freie Software sind, dann empfehlen
wir diese Geräte für einige Wochen nicht zu verwenden. Einzige
Ausnahme bei Android ist, wenn ihr den Android-Quelltext und den
von allen Apps, die ihr verwendet, selbst heruntergeladen und
kompiliert habt. Nehmt die Batterie heraus oder legt sie sie in
eine Metallschachtel.

Alle Menschen, die Systeme, Anwendungsprogramme und andere Software
programmieren, die auf Linux, BSD oder anderer freier Software
beruhen, haben von uns schon vor Wochen eine Liste der Schwach-
stellen erhalten und sie haben seitdem daran gearbeitet, die Lücken
zu schließen. Wir empfehlen auf eines dieser Systeme umzusteigen.

Unserer Auffassung nach darf Software nicht geheim gehalten wer-
den. Jeder Mensch hat ein Recht darauf zu erfahren, was der Computer
oder das Smartphone, das er verwendet, tatsächlich macht.

@Anonymous 
....
****

Marianne schaute Fred mit einem dramatischen Blick an: „Na?
Soll ich das jetzt abschicken?“

„NEIN!“, rief Fred mit gespielter Panik.
„BLOSS NICHT … Das bringt die Mächtigen der Welt durcheinander!!“
Er riss die Augen auf und schaute sie an.

„Zu spät“ grinste Marianne zurück.

Hans rief von unten: „Hey! Marianne! Wenn ihr noch rechtzeitig zum Schiff wollt, dann müssen wir jetzt gehen.“ 

Fred und Marianne klappten ihre Laptops zu, steckten sie in ihre gepackten Koffer und verließen das Zimmer.
Eine Stunde später saßen Sie auf einem kleinen Frachter, der Richtung Festland fuhr.
