== [big-number]#1915# Deutsch-National!

=== SZENE 7
____
Eine Gruppe von Offizieren in einer Bierwirtschaft, viel Qualm, laute Gespräche überall.

Erster Offizier: „Wilhelm und Hilde Papenburg, sie besudeln die Ehre des deutschen Volkes.
Sie wollen uns in den Arm fallen, wenn wir die Waffen gegen unsere feigen Feinde erheben, um wieder die Vorherrschaft über Europa zu erringen.
Sie wollen unsere Kraft schwächen, sie machen Gemeinschaft mit unseren Feinden: mit Franzosen, mit Engländern, mit Russen.
Sie sind die wahren Feinde auf unserem Weg, Deutschland zu dem zu machen, was es seinem inneren Wesen nach ist: Die erste Führungsmacht.“

Zweiter Offizier: „Jawoll!“

Erster Offizier: „Und wir müssen lernen, dass eine neue Zeit angebrochen ist: die Maschinenzeit.
Auf den Schlachtfeldern werden die siegen, die die besseren Maschinen haben.
Gepanzerte Fahrzeuge, gepanzerte Flugzeuge, Maschinengewehre.
Aber auch die Maschinen, die Maschinen produzieren, auch die Maschinen, die Land beackern, Straßen und Häuser bauen.
Unsere Industrie ist das Entscheidende auf unserem Weg an die Weltspitze.
Und die großartigen Menschen, die die Unternehmen führen: Sie sind Führer von Arbeitereinheiten, genauso wie wir Führer sind von Armeeeinheiten sind.“

Zweiter Offizier: „Ein Hoch auf die deutsche Wirtschaft.“

Dritter Offizier: „Die stärkste der Welt!“

Vierter Offizier: „Nach den Amerikanern.
Noch … Die Engländer haben wir überholt, in diesem Jahr.
Amerika ist die große Gefahr.
Wer die Industrie anführt, führt die Welt an.
Wir brauchen schlagkräftige, wachsende und agile Unternehmen.
Unsere Unternehmen lassen schon jetzt Arbeiter rund um die Welt für sich arbeiten.
Wir müssen nicht Länder kolonisieren, das ist von gestern.
Wir müssen Länder befreien, sie öffnen, damit unsere Unternehmen dort die Arbeiter für sich arbeiten lassen können.
Und die Menschen dort unsere Waren kaufen.
Das ist der neue Wettlauf.
Nicht die Kolonisierung.
Und da ist Amerika noch einen Schritt voraus.“

Dritter Offizier: „Sie bauen die höchsten Gebäude der Welt.
Die längsten Eisenbahnstrecken.“

Erster Offizier: „Wir werden die Waffen sprechen lassen, wir werden die Weltordnung verschieben, wir werden unseren Unternehmen überall Raum verschaffen, in dem sie sich ausbreiten können.
Und dafür müssen wir aufs Schlachtfeld.
Dafür brauchen wir Achtung, Respekt.
Das bekommen wir dort.
Und deswegen, deswegen habe ich euch hier heute eingeladen, um mit euch darüber zu sprechen, was wir gegen die machen können, die diesen Weg von innen stören.“

Zweiter Offizier: „Wilhelm und Hilde Papenburg ...“

Erster Offizier: „... und ihre korrupte Bewegung.
Die Spartakisten.
Und auch andere.
Aber zunächst sie.
Sie vergiften die Herzen der deutschen Arbeiterschaft.
Sie wollen nicht mehr fleißig für die Sache arbeiten, sie wollen weniger arbeiten, mitbestimmen, sie wollen Regeln ändern.
Sie wollen die Firmen besitzen, in denen sie arbeiten.
Überall, wo ich hinsehe, sehe ich Verrat.
Verrat an der deutschen Sache.
Verrat am deutschen Volk.
An den deutschen Unternehmern.
Das deutsche Volk soll stark sein, nicht schwach.
Es soll sich gegen die anderen Länder durchsetzen, nicht sich beugen.
Die sozialistische Utopie wird uns in die Sklaverei treiben.
Amerika, England, Frankreich, Russland, sie haben Respekt vor Stärke, nicht vor Schwäche.
Auch unsere Freunde: Österreich und Italien, respektieren den Starken nicht den Schwachen.“

Dritter Offizier: „Lass uns die beiden beseitigen.
Endgültig.
Keine Warnungen mehr, keine Einschüchterungen.
Sie müssen weg, bevor die Krankheit noch weitere Arbeiterkreise befällt.“

Zweiter Offizier: „Jawoll!“

Vierter Offizier: „Ich lasse sie rund um die Uhr beobachten.
Wir haben einige unserer Leute in ihrer Bewegung.
Es wird immer jemand in der Nähe sein.
Und dann finden wir einen Plan, wie wir es machen.“

Erster Offizier laut: „Einer für alle.“

Alle zusammen: „Und alle für einen!“ 
____
