== [big-number]#2064# Wo ist das LBI?

[text-caps]#Lasse und Sigur# saßen wieder in der Küche des Spiele-Labors.
Jeder wieder mit einem großen Kakao in der Hand.

Sigur: „Und wo bist du gerade?“

Lasse: „Bei Spielende saß ich im Flugzeug heim nach San Diego.“

Sigur: „Du bist eingestiegen?“

Lasse: „Ja.
In Caracas wird alles von Fortunato kontrolliert.
Er hat eine Wahnsinns-Übersicht.
Und ich traue ihm keinen Zentimeter mehr.
Und dann kann ich dort nicht viel machen.
Lieber von zu Hause, von unserem Strand-Appartment aus.
Ich traue ihm nicht einmal mehr, dass er von dem Überfall nichts gewusst hat.“

Sigur: „Neee.
Natürlich steckt er da voll mit drin.
Das war gespielt von ihm.
Aber echt, schau, dass es solche Arschlöcher gibt: Die schneiden dir den Bauch auf und machen eine fernsteuerbare Zyankalikapsel hinein.
Ich wüsste zu gerne, ob das vor 50 Jahren in echt so vorgekommen ist.
Ich hab wirklich Wut bekommen.“

Lasse: „Unfassbar, wenn es tatsächlich so wäre.
Wo bist du jetzt eigentlich?“

Sigur: „Immer noch in dem Raum, wo die Wachleute mich hingebracht haben.
Sie ignorieren mich schon seit ein paar Stunden.
Einfach nur doof.
Mir dröhnt auch noch der Schädel und übel ist mir.
Ich spüre den Druck im Magen, Würgereiz.
Mir ist in echt ein wenig übel … selbst hier noch.“

Lasse: „Aber was jetzt?
Was machen wir mit dem LBI?
Wie suchen wir da weiter?
Haben wir etwas übersehen?
Viel Neues wissen wir nicht.“

Sigur: „Wir verkleiden uns als TAO-Hacker und brechen bei ihnen ein.“

Lasse: „Ja, nur schade, dass wir nicht wissen, wo sie sind, sie haben nicht einmal Gebäude, keine zentralen Server, überhaupt keinen Platz, wo wir hinein könnten.“

Sigur: „Die verstecken sich sicher im Tor-Netz, die haben ihre Daten über Hashes im Internet verteilt und benutzen Tails oder Cubes OS als Betriebssystem.
Die haben ja nichts Besseres eigenes.
Die brauchen freie Software.
Und dann bauen wir irgendwie eine Hintertüre in Tails ein und darüber gehen wir auf ihre Rechner.“

Lasse: „Hast du sie noch alle?
In Tails eine Hintertüre?
Ich glaube, du spinnst.
Erstens ist das gegen Cypherpunk-Ethik, in Standard-Programme Hintertüren einzubauen.
Und abgesehen davon: Das würdest du gar nicht schaffen.
Das Projekt ist hochaktiv, die schauen sich alles Neue zwei, dreimal an bevor sie es nehmen.
Und du bist dort nicht bekannt.“

Sigur: „Hej, das war Spaß!
Du weißt doch, wo ich gerade bin.
Wie soll ich denn da überhaupt etwas machen?
Unter Drogen gesetzt, ohne Computer, mit Blausäure im Bauch...
Das wird jetzt eher langweilig für mich.“

Lasse: „Ja, das wird wie bei Tim.
Der hat mal zwei ganze Spieltage lang in der Psychatrie verbracht, in einem Minizimmer ohne Fenster, in einer Zwangsjacke.
Konnte nichts machen … Scheiße.
Aber ich verstehe die Logik nicht.
Warum schickt uns Marianne zu Fortunato, um das LBI zu finden.
Und alles, was dort passiert, ist, dass wir davon erfahren und dann ...“

Sigur sprang auf: „Moment mal!
Ja, klar!
Fortunato, er ist beim LBI.
Er arbeitet für die.
Er ist LBI.
Natürlich.
Wir waren in einem LBI-Haus.
Wie macht er so einen Wandel vom Drogenbaron zum Informationshändler?
Ohne Hilfe?
Sein System hat die TAO gebaut, da bin ich mir sicher.
Und er ist nicht TAO.
Er hat ein Haus für sich, alle Computer laufen bei ihm privat.
Das ist ein LBI-Haus.
Ganz sicher.
Ich glaube, wir haben sie gefunden.“

Lasse: „Shit. Ja. 
Das macht Sinn.
Und wir haben sie gleich beklaut ...“

Sigur: „Ja ... gleich beklaut.
Geil!
Die Bitcoins sollten jetzt schon unterwegs sein.
Er hat bestimmt nachgeschaut, was in seinem Shop passiert ist.
Wenn du zu Hause bist, dann bekommst du von mir nach drei Tagen eine Pond-Nachricht mit dem Schlüssel zu meiner Raspberry-Höhle.
Die wird automatisch losgeschickt, wenn ich drei Tage nichts von mir hören lasse.
Und so wie es aussieht, wird das wohl so sein.“

Lasse: „Und dann?“

Sigur: „Dann?“

Lasse: „Was machen wir dann?“

Sigur: „Das ist richtig viel Geld.
Ich denke nicht, dass sie so einfach darauf verzichten können.
Das sind Bitcoins.
Die müssen bestimmt viele Leute an den normalen Bezahlwegen vorbei bezahlen.
Und das können sie jetzt nicht mehr, oder zumindest sehr viel weniger gut.
Sie werden hinter dem Geld her sein.
Bitcoins sind nicht anonym.
Du musst aufpassen, wie du sie ausgibst.“

Lasse: „Keine Angst, ich gebe sie nicht aus.
Die gebrauchen wir als Köder.
So können wir das LBI zu uns locken ...“

Sigur: „Cool.“
