== [big-number]#2064# Einschüchtern!

[text-caps]#Marianne und Lilly# saßen zusammen bei einer Tasse Tee in der Steinhütte.
Vor ihnen brannte eine Lagerfeuer.

Lilly: “Ist das in Wirklichkeit passiert mit der Zyankalikapsel?“

Marianne: „Ich habe das selber nicht miterlebt.
Als Ali Steffens und Eduardo Lampresa den LBI-Bitcoin-Tresor geknackt haben, war ich gerade im Gefängnis.
Davon habe ich nichts mitbekommen.
Aber es kann gut sein, dass das so war, es ist schon sehr brutal zugegangen damals.
Ich selbst hatte aber nie eine Kapsel in meinem Körper.
Nur eine Laser-Tätowierung auf der Stirn, die man von Satelliten aus lesen kann.
Aber es gab zum Beispiel richtige Folterzentren, wo viele Menschen gestorben sind.
Zuerst in Ost-Afrika und im Mittleren Osten, aber später immer mehr auch in den zentralen Städten wie Berlin, Moskau, San Francisco, Quito und Paris.
Die waren vor allem zur Einschüchterung da.
Es ging nicht so sehr darum, Menschen zu bestrafen oder Informationen zu bekommen, es ging um die Botschaft: Verhalt dich ruhig und dir passiert nichts.
Und wenn du nicht ruhig bist, dann wird es schlimm...

Und das hat funktioniert.
Viele haben sich gebeugt, viele hatten Angst, manche panische Angst.
Aber nicht alle.
Manche Hacker können sich nicht beugen.
Eigentlich hörst du auf, ein Hacker zu sein, wenn du dich beugst.
Und die Geheimdienste haben gemeint, dass sich alle beugen werden, wenn sie nur genug ihre Übermacht zeigen.
Sie haben sich geirrt.“

Lilly: „Wie bei deinem Bruder...“

Marianne nickte: „Ja, wie bei meinem Bruder Paul.
Mh mh.“
Sie schüttelte leicht den Kopf.
„Das war so ungerecht.
… Mir läuft jetzt noch ein Schauer über den Rücken, wenn ich an ihn denke.
Er hat sich nicht gebeugt.
Er hat sie durchschaut.
Ich habe ihn so gemocht.
Und er musste so früh sterben.“

Lilly: „Ja, das war für dich der Beginn, nicht?
Irgendwie.
So verstehe ich dein Buch.“

Marianne: „Ja, das war schon ein Beginn.
Das war da, wo es ernst geworden ist.
Vorher habe ich viel gespielt.
Ich habe einfach gemacht, was dran war.
Auch die NSA-Datenbank.
Danach ist das schwerer geworden und dunkler.
Deswegen hat es mich ja auch einmal erwischt.
Und seitdem humple ich immer ein bisschen.“

Lilly schaute überrascht auf Mariannes Bein: „Deswegen?“

Marianne: „Das war im Gefängnis.
Sie sind echt Unmenschen, keine Menschen, zumindest wenn sie Soldaten sind.
Sie sind vielleicht Menschen im Privatleben.
Das ist richtig schizophren.
Absolut eiskalt und brutal bei der Arbeit und weich und nett zu Hause zu Partner und Kindern.
Auch bei vielen Menschen in den Unternehmen war das damals so.

Aber selbst das kann man verstehen.
Wenn man ihre Geschichte kennt.
Einen Soldaten habe ich im Gefängnis genauer kennen gelernt.
Ziemlich genau.
Das war für mich ein Wendepunkt.
Seine Geschichte hat mich beeindruckt.
Da habe ich gelernt, wie wichtig es ist, niemals gegen jemanden zu sein, sondern immer seinen eigenen Weg im Auge zu haben und den anderen so gut wie möglich zu verstehen.
Selbst dann, wenn er einen umbringen will.
Paul hat das gekonnt.
Er konnte immer unter die Oberfläche schauen.
Er hat es im Augenblick gewusst, einfach so gewusst.
Und er hat es mir immer wieder gesagt.
Aber ich habe nicht gleich verstanden.
Es ist ja in den elf Grundgedanken drin, die Paul im Gefängnis aufgeschrieben hat.
Ich habe sie gelesen, immer wieder, aber richtig verstanden habe ich sie erst, als ich selbst im Gefängnis war.
Genau im gleichen wie er übrigens.
Das ist vielleicht eine Ironie des Schicksals, dass ich dort gelandet bin.
Oder es war einfach wiederum Einschüchterung.
Es geht so viel um Einschüchterung, sie wollen allmächtig dastehen.

Ali und Eduardo waren da spitze.
Es war völlig unmöglich, sie einzuschüchtern.
Sie hatten einfach irgendwie beschlossen, sich nicht einschüchtern zu lassen und sie haben das durchgezogen.
Und jetzt spielen Lasse und Sigur das nach.
Wer weiß, vielleicht schaffen sie ja die ganze Mission und dann wird es ein Treffen geben zwischen Ali und Eduardo und Lasse und Sigur.
Das will ich erleben.
Das wird spannend.

Fortunato hieß ja in Wirklichkeit so.
Ich habe ihn sogar einmal getroffen.
Aber es war keine große Begegnung.
Nett ist er.
Lustig.
Und immer mindestens zwei Frauen um ihn herum.
Aber ich konnte nicht gut mit ihm reden.
Er ist echt so wie im Spiel.
Ein sympathisches Arschloch.“

Lilly: „Wie geht das weiter mit den Bitcoins?
Sind die beiden auf der richtigen Spur.“

Marianne: „Absolut.
Und wie es weitergeht?
Hmm.
Das kommt darauf an, was sie jetzt machen.“

Sie lächelte Lilly an.
