== [big-number]#1918# Festnahme

=== SZENE 7
____
Wilhelm in seiner Wohnung in einem Berliner Mietshaus.
Morgens, beim Rasieren 
// BLENDE //
Hilde in ihrer Wohnung am Küchentisch beim Frühstücken.

Wilhelm wäscht die Rasierseife ab und trocknet sich sein Gesicht.
Er schaut auf die Uhr und ruft: „Herrgott!“
Er eilt aus dem Badezimmer, zieht sich ein Hemd, dann Jackett und Schuhe an, schnappt sich seinen Mantel und verlässt die Wohnung.
Vor seiner Wohnungstüre warten zwei Spartakisten.
Er nickt ihnen zu und eilt vor ihnen die Treppen hinunter.
Sie folgen.

Hilde stellt ihren Teller in die Spüle, macht sich kurz im Spiegel zurecht, zieht ihren Mantel an.
Da klingelt es an der Türe.
Sie öffnet und lächelt Adolf an.

Hilde: „Hej, pünktlich wie die Eisenbahn.“

Adolf lächelte: „Ich habe drei Minuten im Flur gewartet ...“

Hilde: „Komm, heute gibt es viel zu tun.
Ich habe ein gutes Gefühl, dass wir mit den Suppenküchen einen Schritt vorankommen.“

Sie läuft vorneweg die Treppen herunter, Adolf folgt kurz hinter ihr.

Wilhelm drückt die Klinke der Haustüre und öffnet sie mit Schwung.
Ein breitschultriger Mann steht vor ihm, packt ihn an der Brust und reißt ihn auf den Gehweg.
Ein anderer stülpt einen Kartoffelsack über seinen Kopf, tritt ihm mit dem Knie in den Bauch und zerrt ihn in ein bereitstehendes Auto, das sofort davon rast.
Zwei weitere Männer sind unterdessen mit Gewehren im Anschlag in Richtung Haustüre gestürzt und brüllen die beiden Spartakisten an, ihre Waffen fallen zu lassen.
Der breitschultrige Mann kickt die Waffen auf die Straße, durchsucht die beiden, schubst sie dann, einen mit der linken, einen mit rechten Hand, zurück in den Hausgang und schlägt die Türe zu.
Dann springen alle auf einen bereitstehenden Pritschenwagen und rasen ebenfalls davon.

Hilde öffnet die Haustüre und bekommt einen Schlag auf den Kopf.
Sie sinkt bewusstlos zusammen.
Zwei Männer schleifen sie in ein bereitstehendes Auto.
Ein Mann mit Gewehr zielt auf Adolf, der sofort die Hände hebt.
Mit panischen Augen schaut er den Mann an, der nichts sagt.

Adolf: „NEIN! NICHT ...“

Der Mann drückt ab.
Ein gewaltiger Knall erschüttert den Treppenaufgang.
Er drückt noch einmal ab.
Adolf fasst sich an die Brust, spürt warmes Blut.
Er bricht auf dem kalten Steinboden zusammen, unter ihm bildet sich eine große Blutlache.
____
