== [big-number]#2021# Ein Blutstropfen

[text-caps]#Paul schaute zur Tür# und dachte: „Immer noch keine Wachen … Es ist mindestens schon eine halbe Stunde her, seit Linda aus dem Raum geflüchtet ist.
Ja, sie ist geflüchtet.
Aber wovor?
Sicherlich davor, etwas über Marianne zu sagen … Shit.
Shit.
Shit … Was ist mit Marianne? … Linda weiß, wo sie ist … Ja.
Sie will sie nicht finden.
Sie braucht mich nicht, um sie zu finden, weil sie weiß, wo sie ist.
Aber was will sie dann?
Warum mich freilassen?
Es macht keinen Sinn.“

„Verdammt!“, sagte er laut.
„Verdammte Scheiße!“

Er legte seinen Kopf auf den Tisch.
Seine Nase fing an zu bluten.
Er knüllte ein Stückchen Taschentuch zusammen und drückte es ins Nasenloch.

„Marianne zwingt sie gerade, mich freizulassen“, dachte er und lächelte, „Ja, das würde zu ihr passen.“ Er nickte. „Schöner Gedanke, aber, scheiße, nein.
Sie lassen sich nicht erpressen.
Aus Prinzip nicht.
Sie sind die größte Weltmacht, das großartigste Land, das es je gegeben hat.
Sie alle sind Teil eines Wundertraums, die Elitenation der Welt.
Nein, da kann nicht ein 18-jähriges Mädchen kommen und sie zu irgendetwas zwingen.“

Er vergrub seinen Kopf unter seinen Händen.
„Oder war es tatsächlich ein Gesinnungswandel?
Linda hatte etwas angedeutet: Sie wollen die NSA auflösen … Nein, so ein Quatsch.
Allenfalls, weil sie etwas Besseres haben und sie sie nicht mehr brauchen.
Bestimmt nicht, weil sie sich sich auf ihre Ideale besinnen: Auf Freiheit, Selbstentfaltung, den anderen leben lassen.

Oder fangen sie wirklich an, ihre eigenen Ideale ernst zu nehmen?
Sich selbst ernst zu nehmen?
Die Ideale nicht nur auf ihr Land zu beziehen?
Nein.
Ihr Ziel ist es, die Welt zu erobern.
Das ist das einzige, was für sie in einer verrückten Welt Sinn macht.
Ordnung durch Macht.
Der Starke kann seine Güte walten lassen, der Schwache nicht.
Das bekommen sie mit der Muttermilch: Wenn es mit der Welt gut weitergehen soll, dann müssen wir sie steuern, mit unseren Armeen, mit unserer Finanzindustrie, Rüstungsindustrie, mit der Internet-Industrie, Google, Apple, Microsoft, mit Fast Food, Coca Cola und mit den Massenmedien.
Jeden Aspekt des Lebens kontrollieren.
Das ist das großes Ziel.
Und wenn man das erreicht hat, dann kann man die Freiheit der Menschen garantieren – zumindest von einem Teil der Menschen.
Das maximale Glück für die maximale Anzahl von Menschen.“

Er schlug mit der Faust auf den Tisch: "Fuck". Er dachte: „Das ist der dämonischste Spruch, den es gibt, weil er vernünftig klingt, und damit so schwer zu durchschauen ist.
Menschen ausschließen: Wenn das großartigste Land, das es je gegeben hat, herrscht, dann gibt es Freiheit für alle diejenigen, die sich seiner Kultur unterwerfen, seinen Lebensvorstellungen.
Und jeder Feind seiner Art zu leben, ist ein Freiheitsfeind und wird unschädlich gemacht.
Zum Beispiel Hacker, vor allem Cypherpunks.“

Er fasste sich mit beiden Händen an den Kopf.
„Mit Gewalt zur Harmonie … Mit Unterdrückung zur Freiheit.
Was bringt Menschen dazu, so etwas Idiotisches zu denken?
Was bringt hunderte von Millionen von Menschen, in Regierungen, in Staatsapparaten, in Unternehmen dazu, so einen Quatsch zu denken?
Wieso können sie denken, dass Macht Probleme lösen kann, Konzentration von Macht, in unserer Zeit?
Macht muss in die Hände der Menschen, die tatsächlich machen: programmieren, bauen, pflanzen, putzen ...
Macht muss sich verteilen, wie Wasser über eine Gießkanne.
Nicht wie bei einem Stauseebruch.“

Er atmete schwer.

„Und wegen diesem Denkfehler sitze ich jetzt seit zwei Jahren hier, völlig sinnlos, ohne Anklage, nicht einmal ein Vorwurf, nicht einmal ein falscher Vorwurf.
Wenn nur zehn, zwanzig Prozent der Bevölkerung echte Hacker wären, Cypherpunks, Menschen mit Cypherpunkherz, dann sähe es anders aus.“

Er schaute im Raum herum und blieb auf dem Tisch an einem kleinen Büchlein und einem Stift hängen, die Linda dort vergessen hatte.
Er sah sie an und rief dann plötzlich: „Jah!
Genau!
Ein Manifest!
Wie Eric Hughes 1993.
Ich schreibe ein Hacker-Manifest, ein neues Cypherpunk-Manifest.
Das ist es.
Und wenn es niemals jemand lesen wird ...“
Er zog das Büchlein zu sich hin, riss alle schon beschriebenen Seiten heraus und ordnete sie in einem Stapel auf dem Tisch an.
Dann schlug er die erste Seite auf und nahm den Stift.
Er dachte: "Eric Hughes ... Verschlüsselung"  und begann zu schreiben:

****
....
Alles beginnt mit Verschlüsselung.
....
****

Er schaute auf den ersten Satz, nickte und schrieb weiter.

****
....
Verschlüsselung ist die Grundlage unserer persönlichen Frei-
heit. Wir müssen wählen können, wer unsere Informationen bekommt
und wer nicht. Wir müssen uns verstecken können, uns den Blicken 
derer entziehen, die zerstören wollen, was wir schaffen. Jeder 
Anfang braucht Schutz.
....
****

Ein Blutstropfen fiel von seiner Nase auf das Papier.
Es schaue ihn fasziniert an und achtete darauf, dass er nicht verlief, sondern so trocknete wie er war.

