== [big-number]#2064# Bombendrohung

[text-caps]#Lasse saß in# einem Restaurant im 10.
Stockwerk eines Einkaufszentrums in San Diego, USA, mit einem herrlichen Blick über den Ozean.
Gegenüber von ihm saßen zwei Männer in schwarzen Anzügen.
Die Stimmung war aufgeheizt, beide Seiten bemühten sich gelassen zu wirken.

Lasse: „Ich habe vier Bitcoin-Bomben.“
Er zeigte vier Finger.
„Und ab morgen wird jeden Tag um 8:31 Uhr eine hochgehen.
Dann verteilen sich eure Bitcoins im Bruchteil einer Sekunde über tausende von Bitcoin-Wallets.
Über dreißig Milliarden Dollar.“

Erster Mann: „Das ist kein Problem für uns.
Das können wir verhindern.
Wir haben so viele Computer und Hacker zur Verfügung wie wir wollen.
Wir holen in der Zeit einfach alle Server herunter, über die die Transaktionen laufen können.“

Lasse lachte laut.
„Alle 700 000?
Macht keine Witze!
Und selbst wenn, das würde alles nur ein paar Minuten, höchstens eine halbe Stunde verzögern.
Die meisten Server haben eine Auto-Sicherung:
Die tauchen vollautomatisch woanders im Internet wieder auf und machen da weiter, wo sie als letztes aufgehört haben.
Manche machen dann sogar gleich mehrere Server auf: wie bei der Hydra im alten Griechenland.
Du schlägst einen Kopf ab und es wachsen drei neue.
Die haben alle von Wikileaks und Piratebay gelernt, und die habt ihr ja nie wirklich in den Griff bekommen.
Vielleicht mal ein paar Tage.
Und jetzt wollt ihr Bitcoin insgesamt lahmlegen.
Kommt Jungs, im Ernst …“

Erster Mann: „Anderes Szenario.
Die Bomben sind explodiert.
Das Geld ist weg.
Und dann?
Was dann?
Wenn Sie alle Bitcoins in die Luft gejagt haben und dann nichts mehr haben, was wir wollen, gar nichts.
Was dann?
Was machen Sie dann?“

Lasse: „Ich versuche hier wegzukommen.
Und wenn ich es nicht schaffe, dann bringt ihr mich um.“

Erster Mann: „Erst erwischt es Sigur.
Und für Sie haben wir einen Haufen Agenten hier in San Diego.
Flucht ist keine Option.“

Lasse schaute ihm in die Augen: „Okay.
Dann bringt ihr mich um.
Und was dann?“

Zweiter Mann lachte: „Was dann?
Dann sind Sie tot!“

Lasse dreht sich zum zweiten Mann: „Ja, gut, und dann?“

Der lief im Gesicht leicht rot an, griff in seine Jacke und zog eine Pistole soweit heraus, dass Lasse sie sehen konnte.

Zweiter Mann kalt: „Wir können das jetzt auch gleich machen.
Ist schallgedämpft und hat Uranmunition.
Ein Streifschuss würde reichen.
Ich schieße immer drei Mal.
Zuerst zweimal ins Herz und dann ins Gesicht.
Deine Leiche kommt ins Meer, 5000 Meter tief.
Und wir machen dir eine gute Story, wie die übrige Welt dich sehen wird.
Zum Beispiel: Lasse Brodowin, der Überläufer, abgetaucht, führt in Wirklichkeit ein luxuriöses Leben.
Für deine Freunde lassen wir dich nicht sterben.
Für die wirst du ein ganz normaler Verräter sein.“

Lasse: „Aber die Bitcoins sind dann weg.
Und das ist für euch keine Option.“

Der erste Mann drückte die Pistole des ersten zurück in seine Anzugtasche: „Guy, lass das.“

Er drehte sich zu Lasse: „Wir sind hier für eine Einigung, die für beide passt, womit beide Seiten leben können.
Also, nochmal: Sigur kommt frei.
Wie geht es weiter?
Wie kommen wir an die Bitcoins?
Wie können wir sicher sein, dass wir sie bekommen?
Wie können wir sicher sein, dass du sie hast?
Wir brauchen eine Garantie.
Die Bitcoins müssen vor Sigurs Freilassung irgendwo deponiert sein, wir müssen prüfen können, dass sie da sind.“

Lasse schüttelte den Kopf.
„Das wird nicht passieren.
Ich warte, bis ich von Sigur das Signal bekomme, dass er in Freiheit ist.
Dann schicke ich die Bitcoins.
Ich gebe keine Garantien vorher.“

Erster Mann: „Das läuft nicht.“

Zweiter Mann mit rotem Kopf zum ersten: „Wir können ihn auch gleich mitnehmen.
Die Nacht ist lang bis morgen früh um 8:31 Uhr.
Wenn ich machen darf, dann erzählt er uns vor Mitternacht, wie wir an die Bitcoins kommen.
Und ich mache da nicht so Pillepalle wie Waterboarding oder nackt in einer kalten, schmutzigen Ecke stehen lassen.
Das geht bei mir schneller.
Da sieht man danach auch noch etwas davon.“

Er trat Lasse unter dem Tisch fest mit seinem Stiefel.

Lasse fasste an sein Bein: „Ahhh.
Arschloch!
Scheiße!
Warum gibt es bei euch so viele Arschlöcher?“

Erster Mann kühl: „Er hatte eine schwere Kindheit.
Seine Mutter hat ihn ein paar Mal ins Krankenhaus geprügelt.
Sie war drogenabhängig und hysterisch.
Alleinerziehend.
Das hat ihn geformt.“

Lasse und er schauten sich eine Weile in die Augen.

Erster Mann: „Es wird nicht so passieren wie Sie sagen.
Wir brauchen Sicherheit.“

Lasse: „Ich kann jetzt hier mit einem Knopfdruck dafür sorgen, dass ich keine Möglichkeit mehr habe, die Bomben zu stoppen.
Keiner kann das dann mehr.“

Erster Mann: „Die halbe TAO sucht nach den Rechnern, auf denen die Bitcoins sind.
Sie sind irgendwo im Tor-Netz.
Vielleicht finden wir sie.“

Lasse: „Du weißt, dass ihr sie da nicht finden könnt.
700 000 Rechner, Tor-Rechner.
Nee.
Ihr hattet ja früher schon mit 4000, 5000 jede Menge Probleme, so 2010, 2011.
Außerdem braucht ihr das Tor-Netz selbst für alles Mögliche.
Ihr habt ja nichts, was so brauchbar ist.
Ihr könnt es nicht einfach abschalten.“

Sie schauten sich wieder eine Weile stumm an, Auge in Auge.
Lasse mit ruhigem Blick.

Erster Mann: „Du musst mir etwas geben.
Wenn ich mit dem Ergebnis zurückkomme, dann bin ich von dem Auftrag weg und dann geben sie dich zum Beispiel allein in die Hände von ihm hier.
Auch nachdem die Bitcoins weg sind.
Das machen sie dann einfach aus purer Rache, sie sind keine guten Verlierer.
Das nennen sie Prävention.
Komm.
Nochmal: Wir sehen die Bitcoins vorher ...“

Der zweite Mann biss auf die Zähne und atmete durch, eindringlich, zischend: „Ich habe eine spezielle Schere.
Damit schneide ich dir zuerst den Zeigefinger ab.
Ohne, dass ich Kraft aufwenden müsste.
Ab.
Eine normale Haushaltsschere, speziell geschärft.
Und dann den Ringfinger.
Ab.
Dann den kleinen.
Mal sehen, ob du uns dann immer noch den Mittelfinger zeigst.“

Lasse schaute über den Ozean.
Er schloss die Augen und atmete aus.
„Nicht dagegen gehen“, dachte er.
„Sonst ist es vorbei.
Sonst habe ich keine Chance ...
So ein Arschloch.
Solche Arschlöcher.
Was ist aus denen später geworden?
Wo sind sie in unserer Zeit?
Was haben die in ihrem Leben gemacht?“ Er umklammerte in der Hosentasche den Druckknopf, der irgendwo im Tor-Netz die Passworte für die Bomben ändern würde.
Ein langer Druck und er könnte nicht mehr an sie herankommen, und sonst auch niemand mehr.

Er lehnte sich zurück und schaute zum ersten Mann: „Dann drücke ich den Knopf jetzt!!“

„Nein! Stop!“, riefen beide etwa gleichzeitig.

Lasse schüttelte den Kopf und schaute wieder aufs Meer.
Am Horizont, weit draußen, schwebte ein riesiger weißer Ballon.
Lasse schaute ihm verträumt nach.

