== [big-number]#2021# Der Haftbefehl

[text-caps]#Anni lief mit# ihrem Smartphone in der Hand hinter die letzte Tischreihe im Klassenzimmer.
Sophie folgte ihr, legte ihr eine Hand auf ihre Schulter.
Anni machte sich los.

Anni: „So ein ARSCH!!“
Sie stampfte mit dem Fuß auf den Boden.
„Ich glaub es einfach nicht!
Er hat es wieder gemacht!
Ich dachte, das wäre vorbei.
Ich dachte, sie hätten die Löcher jetzt gestopft.
Ich habe die neueste iOS-Version.“
Sie streckte Sophie ihr Smartphone entgegen.

Sophie nahm es und schaute auf das Display: „Scheiße!
Er postet wieder über dein Facebook-Konto.
Shit.
An alle deine Freunde.
Und so einen Schwachsinn.
Der hat so viel Scheiße im Hirn.
Du hättest dich wirklich niemals mit ihm einlassen sollen.
Er war ja vorher schon ein Arschloch.
Immerhin sind es diesmal keine Fotos … Oh shit …
Nee.“

Anni: „Was??“ 

Sophie: „Ein Foto.
Gerade jetzt.“

Anni: „Gib mir!!“

Sophie hielt das Smartphone weg: 
„Nee.
Besser du schaust dir das nicht an.“

Anni: „Aber nicht wieder nackt?“
Sie riss Sophie das Smartphone aus der Hand.
„Oh, nein …
Nein …
Nein.“
Sie schrie das Smartphone an: „Du Ficker, Arsch, Spatzenhirn.“ 

Sie ließ sich auf einen Stuhl fallen, legte den Kopf in ihre Hände und heulte.
Sophie legte vorsichtig die Hand auf ihren Rücken: „Komm, jetzt machen wir es wirklich.
Wir zeigen ihn an!
So richtig mit Polizei und so.
Jeder weiß, dass er das war.
Er hat es schon einmal getan und damit geprahlt.
Wir kriegen ihn dran.“ 

Anni schluchzte: „Nein, es kann jeder gewesen sein.
Das ist wieder irgendso eine Schwachstelle aus irgendeiner Scheiß-Anleitung in YouTube.
Und selbst wenn wir ihn drankriegen würden, die Fotos sind draußen.
Die holt mir keiner mehr zurück.“
Sophie streichelte ihren Rücken.
Anni schluchzte: “Warum?
Warum wieder ich?
Warum immer noch?
Ich dachte, es wäre vorbei.
Ich habe mein Smartphone letztes Jahr drei Monate nicht in die Hand genommen.
Bis alle gesagt haben, dass jetzt keine Hintertüren mehr drin sind.“

Kevin trat von hinten zu den beiden hinzu: „Ja, ja, das haben sie gesagt:
Das privateste und sicherste  iPhone aller Zeiten, transparente und sichere Android Phones, wie noch nie vorher.
Zum ersten Mal keine Hintertüren mehr.
Überhaupt keine.
Nie mehr.
Apple und Google feiern ihre Befreiung von den Geheimdiensten.
Große Show.
Alle Daumen hoch.
Aber dann haben sie doch wieder neue Hintertüren eingebaut.
Sie können es nicht lassen.
Vielleicht werden sie auch gezwungen.
Schmeiß dein iPhone weg.
Solange das nicht Open-Source ist, kannst du das vergessen.“

Sophie stieß ihn mit dem Ellbogen: „Hey, du Depp, siehst du nicht: Ihr geht’s schlecht.
Sie braucht jetzt keinen Vortrag.“

Anni wischte sich die Tränen aus den Augen: „Er hat Recht.
Das mache ich jetzt auch.
Marianne hat das schon vor ein paar Jahren gesagt.
Sie hat immer gesagt, dass da Hintertüren und alles Mögliche drin sind und dass sie uns damit überwachen.
Oh, wir könnten sie jetzt so gut gebrauchen.
Sie wüsste, was wir jetzt machen können.“

Kevin: „Ja.
Sie würde den Stinker hacken.
Der würde sein Bild ständig auf jedem Bildschirm in der Schule sehen, über Wochen, und nirgends in sein eigenes Facebook-Konto hineinkommen.
Der hätte kein schönes Leben mehr.“

Sophie lachte: „Ja!
Marianne.
Das wäre jetzt cool!
...
Echt komisch.
Sie hat sich nie mehr gemeldet.
Wir waren doch eigentlich gut mit ihr, oder?
Ist sie immer noch auf Weltreise mit ihrem Bruder?“

Kevin: „Keine Ahnung.
Die letzten Twitter-Meldungen sind mehr als ein Jahr alt.
Und die waren ziemlich komisch.
Nur noch Strand und Sonne, keine Laptops …“

Sophie: „Die Eltern haben gesagt, dass sie Probleme mit Geheimdiensten bekommen haben und sich daraufhin das Hacken abgewöhnen wollten.“

Kevin: „Glaubst du das?
Marianne Hacken abgewöhnen?
Eine Katze wird vegan.
Marianne sieht reuig ein, dass Hacken nicht gut ist, dass man das in unserer Welt nicht macht und wird „vernünftig“.
Da müssten sie sie erst foltern oder so was, Gehirnwäsche ...“

Sophie: „Mhmh.
Du hast Recht.
Aber was macht sie dann?
Wo ist dann?
Was ist mit ihr?“

Kevin zuckte mit den Schultern: „Keine Ahnung.“

Die Tür flog auf.
Lukas stürmte ins Klassenzimmer und stellte sich in der Mitte auf: „HEY!!
HAMMER!
HAMMER!
Habt ihr schon gehört?
Marianne wird international gesucht, mit Haftbefehl.
Sie soll die Schwachstellen-Datenbank gehackt haben!!
Sie war das!“
Er winkte mit seinem Tablett.

Die drei stürmten auf Lukas zu: „Zeig!
Zeig!“ Sie beugten sich über das Tablett und lasen:

____

*Deutsche Hackerin im NSA-Spionage-Skandal enttarnt*

Hinter den folgenschweren Enthüllungen über Schwachstellen in Computersystemen aus dem letzten Jahr soll maßgeblich die Berliner Hackerin Marianne Lasser (18) stehen.
Sie ist bereits wegen anderer Vergehen seit über zwei Jahren auf der Flucht.
Gestern Abend wurde von der Regierung der Vereinigten Staaten ein internationaler Haftbefehl gegen sie erlassen.
Die USA werfen ihr vor, militärische Geheimnisse verraten zu haben, die zu millionenfachem Diebstahl, Betrug, Verletzung von Urheberrechts- und Persönlichkeitsrechten und in drei nachgewiesenen Fällen zu Mord geführt haben.
Sie soll nach dem Spionage-Gesetz von 1917 angeklagt werden.
Sollte sie verurteilt werden, erwartet sie in den USA eine lebenslange Haftstrafe oder die Todesstrafe.

Dazu der Bundesjustizminister Lamprecht: "Wir sind gegen die Todesstrafe, und werden sie nur ausliefern, wenn wir eine Garantie der USA bekommen.
Aber leider ist ansonsten in diesem Fall die Rechtslage eindeutig.
Sie hat nicht bei der NSA gearbeitet, sie ist also keine Wistleblowerin.
Sie hat sich offenbar, unterstützt von einer größeren Gruppe von Hackern, in die NSA hineingehackt und die Schwachstellen-Datenbank entwendet.
Das ist Computergewalt, ein eindeutiger Fall von Spionage.
Nachdem, was wir wissen, wollte sie damit zunächst Geld erpressen und als das nicht geklappt hat, hat sie die Datenbank auf völlig unverantwortliche Weise veröffentlicht.
Die Folgen kennen wir alle.
Unendlich viele Verstöße gegen Persönlichkeits-, Eigentumsrecht, Wirtschaftsspionage, einige Firmen mussten Konkurs anmelden. Es gab nachweislich drei Tote."
____

Anni: „Woah.
Woah.
Was sind das für Deppen?
Sie wollen Marianne Morde in die Schuhe schieben.
Sie die völlig durchgedreht?
Was ist das?
Klar, ich habe auch daran gedacht, das Arschloch umzubringen, das meine Bilder gepostet hat.
Aber da wäre doch nicht Marianne Schuld daran … Haben sie die noch alle?
Ich fasse es nicht.
Was ist das für ein Scheiß?“

Kevin: „Voll ins Hirn geschissen.
Marianne Hacken für Geld?
Das geht doch gar nicht.
Die schreiben das einfach, die wissen nichts von ihr.
Die sind so blöd … Marianne bringt sich doch nicht für Geld in Gefahr?
Marianne, für Geld!
Die sind so blind.“ 

Sophie: „Das ist reine Propaganda.
Die schießen sich auf sie ein.
Ich kann mir gut vorstellen, dass sie das war.
Sie hat es wahrscheinlich gemacht, um denen mal richtig eine reinzudrücken.
Denen, die die ganzen Schwachstellen da erst hineingebaut haben: Geheimdienste, Firmen.
Und die Botschaft ist anscheinend angekommen.
Sie hat sie voll erwischt.
Und dafür soll sie jetzt lebenslang ins Gefängnis?
Oder schlimmer.
Die Geheimdienstchefs, die Unternehmensbosse, die amerikanische Präsidentin ja, das wäre gerecht.
Aber Marianne?“

Kevin: „Kill the Messenger!“

Anni ballte eine Faust: „Hej, wir müssen da was tun.
Wir können das nicht einfach hinnehmen.
Das braucht eine Antwort.
Und zwar eine laute.
Das darf so nicht stehen bleiben!
Marianne ist in unserer Klasse.“

Kevin entschlossen: „Die dürfen damit nicht durchkommen.
Auf keinen Fall.“

Sophie: „Wir müssen den Wichsern mal richtig ans Bein treten.“

Anni und Kevin schauten Sophie ein wenig überrascht an und nickten dann.
