== [big-number]#2021# Krisensitzung

[text-caps]#Heinz und Frederik# saßen in Freizeitkleidung an einem großen, vollbesetzten Besprechungstisch im Hauptquartier des BND. Einige hatten Anzüge an, andere waren auch leger gekleidet.
Vier Teilnehmer saßen auf Stühlen an einer Wand, am Kopfende saß der Präsident des BND.

Präsident: „Ok, was wissen wir?“

Ein Mann in grauem Anzug stand auf und ging zum Projektor, der ein Bild von Marianne und einige persönliche Daten an die Wand warf: „Marianne Lasser, 18 Jahre, Eckener-Gymnasium hier in Mariendorf bis vor zwei Jahren, bis dahin neun Monate unter Intensivüberwachung von uns, ab dann weltweite Fahndung, initiiert durch die CIA.
Kurz aufgetaucht in Dahab, Ägypten vor zwei Jahren, dann vermutlich Saudi Arabien, im letzten Jahr wahrscheinlich Tasmanien ...“

Präsident: „Vermutlich?
Wahrscheinlich?
Ist das hier noch ein Geheimdienst?
Oder sind wir hier bei 'Wer wird Millionär?' ?
Brauchen Sie einen Zuschauerjoker?
Marianne Lasser war fast drei Jahre in unserem Fokus, und wir haben ein Krümelchen Nichts.
Und selbst das ist von den Amerikanern.“

Mann:  „Tasmanien ist von uns.
Wir haben eine Verhaftung, die das behauptet.
Ein Darknet-Hacker.“

Präsident: „Wer ist es?“

Mann: „Kann ich nicht sagen, es haben nicht alle hier im Raum die dafür nötige Sicherheitsstufe.
Er wird wohl Kronzeuge werden.
Wir haben ihn bald soweit.“
Er kritzelte etwas auf ein Blatt Papier und schob es dem Präsidenten zu.

Der Präsident las es: „Ok.
Ich verstehe ...
Also, sie hatte keinen Kontakt zur Familie?
Zu Freunden?
Keine gewohnten Plätze?
Hackerspaces?“

Frederik: „Negativ.
Wir prüfen alles regelmäßig.
Hackerspaces können wir nicht sicher sagen.
Da gibt es zu viele, das geht von der Zahl her in Richtung Bahnhöfe … Und wegen dem Schlamassel im letzten Jahr hatten wir zeitweise an einigen Stellen den Überblick verloren.
Smartphones waren vielfach nicht erreichbar, Facebook-, WhatsApp-Konten stillgelegt, es gab viel mehr verschlüsselte Kommunikation, es wurde viel mehr mit Bargeld und Bitcoins gekauft.
Aber inzwischen haben wir wieder kompletten Zugang zur Familie, zur Klasse, zu uns bekannten Freunden.
Im Hackerumfeld ist es traditionell schwerer: Pond verbreitet sich, Ricochet, GPG ist sehr stark, wird immer mehr auf der Kommandozeile genutzt, Tor, OTR … Die üblichen Verdächtigen.“

Ein anderer Mann: „Seit letzter Woche gibt es wieder neue Leaks!
iPhone könnte wieder schwieriger werden in der nächsten Zeit.“

Frederik: „Android genauso.
Bei beiden Firmen sind Wistleblower aktiv.
Immer noch.
Die kriegen das dort nicht in den Griff.
Wahrscheinlich sind es 15, 16 Wistleblower alleine bei Apple, Google, Microsoft, Facebook und Yahoo.
Die von der Öffentlichkeit weg zu halten ist ganz schön Arbeit.
Wir haben einiges abgefangen, bevor das letzte Woche passiert ist.
Unsere Medienleute machen fast nichts anderes mehr ...“

Präsident: „Welche Kanäle nutzen die Pfeifen, ähh, Wistleblower?“

Frederik lächelte kurz gequält, und fuhr fort: „SecureDrop, GlobalLeaks, WikiLeaks, eigene Sachen … Es wird unübersichtlich.
Man kann mit ein wenig Linux-Knowhow einen ziemlich guten Drop aufmachen.
Spiegel Online hat so einen.“

Präsident: „Wir müssen aufpassen.
Es gibt viel Aufmerksamkeit in der Bevölkerung.
Die Bundeskanzlerin macht sich Sorgen.
Sie hat mich persönlich darauf angesprochen.
Der Haftbefehl jetzt kommt zur Unzeit.
Damit steigt die Aufmerksamkeit noch einmal sprunghaft.
Die Menschen fangen an, der Sache über längere Zeit Bedeutung zuzumessen.
Der Haftbefehl mag in Amerika funktionieren, aber hier in Deutschland ist er eine Katastrophe.
Vorschläge?“

Heinz: „Mariannes Bruder sitzt drüben in USA in einem NSA-Gefängnis.
Vielleicht können wir ihn nutzen.“

Präsident: „Wie?“

Heinz: „Freilassen, verfolgen.
Er wird sie sicherlich suchen.“

Frederik lachte: „Aber das musst du gut machen.
Paul Lasser ist nicht irgendwer.
Der riecht die Lunte.
Er war über Monate bei uns im System, und wir haben ihn nicht entdeckt.“

Präsident: „Aber jetzt war er fast zwei Jahre bei den Amerikanern.
Solche CIA-Gefängnisse sind keine Erholungsheime.
Das prägt.
Vielleicht hat er sich geändert ...“

Frederik: „Ich rufe da mal an.“

Heinz: „Und wir nehmen ihre Schulklasse noch genauer ins Visier.
Wir nehmen noch den nächsten Hop in die Intensiv-Überwachung: deren Freunde und Verwandte, genauso die Familie. Im Hackerumfeld können wir vom Aufwand her nicht mehr tun als jetzt.
Da sind wir am Anschlag.“

Mann: „Und ich werde den Druck auf unseren Darknet-Hacker noch ein wenig erhöhen.“

Präsident: „Ok, gehen wir an die Arbeit!
Dass das hier wieder ein richtiger Geheimdienst wird.“

