== [big-number]#1918, 2021#	Verhör (1) 

=== SZENE 8

____
Hilde gefesselt auf einem Stuhl in einem großen Gewölbekeller.
Sie hat einen Knebel im Mund.
Vereinzelt flackernde Leuchten an der Wand.
Um sie herum eine Gruppe von verschieden uniformierten jungen Männern.
Ein Hauptmann.

Ein Mann der Gruppe macht zwei Schritte auf Hilde zu und schlägt ihr mit Hand ins Gesicht.
Sie versucht ausweichen, aber der Schlag trifft sie trotzdem so hart, dass sie mit dem Stuhl zur Seite kippt und auf den Boden fällt.
Sie schlägt mit dem Kopf auf und bleibt liegen.
Ihr Lippe blutet.
Das Gesicht ist schmutzig vom feuchten Boden.

Hauptmann: „Aufheben!“

Zwei der Männer greifen sie und richteten sie auf.
Der Hauptmann nimmt sich einen Stuhl setzt sich vor ihr verkehrt herum darauf.
Er legt beide Arme auf den Stuhlrücken und grinst sie an.

Hauptmann: „Dirne, wir haben dich gewarnt.
Du hast dich mit uns angelegt.
Jetzt bekommst du die Rechnung dafür.“

Hilde stammelt etwas durch den Knebel.

Hauptmann: „Still!
Du bist jetzt nicht dran.
Ich bin jetzt dran: Wir haben dich gewarnt, mehrmals.
Du hast einfach weitergemacht.
Das alles hier wäre nicht nötig, wenn du dich zurückgenommen hättest, wenn du Vernunft angenommen hättest.
Aber du lässt uns keine Wahl.“

Hilde stammelt wieder.

Hauptmann: „Wenn wir jetzt mit offenen Armen den Franzosen entgegenlaufen würden, wie ihr Spartakisten das wollt, dann bekämen wir alle eine Kugel in die Brust.
Und auf die Weise wollt ihr alle umarmen: Engländer, Amerikaner, Russen, Chinesen, Neger, die ganze Welt.
Es ist pure Blödheit, allen zu vertrauen.
Das ist Selbstmord.
Wir können nur auf unsere eigene Stärke vertrauen und auf sonst nichts.
Der Schwache hat keine Freunde.
Der Schwache wird Sklave.“

Er schaute ihr eindringlich in die Augen.

„Du hilfst den Schwachen.
Das hast du schon immer gemacht.
Schon damals in der Schule.
Du hast denen geholfen, die nichts zustande kriegen, weil sie nicht arbeiten wollten.
Und das machst du immer noch.
Gibst ihnen zu essen, einen Platz zum Schlafen.
Nimmst ihnen den letzten Grund, warum sie überhaupt arbeiten würden.
Sie wollen am liebsten nur von denen klauen, die hart und ehrlich arbeiten.
Und du hilfst ihnen dabei.
Die deutsche Natur arbeitet hart und ehrlich.
Deswegen kaufen alle unser Waren, überall auf der Welt.
„Made in Germany“, das hat Klang.
Das ist die Zukunft.
Wir sind besser als alle anderen, wir können besser arbeiten, wir können besser organisieren.
Wir haben die besten Erfinder.
Wenn wir unsere Kultur mit anderen vermischen, dann schwächen wir sie.
Kulturen können nicht gleichberechtigt nebeneinander leben.
Es muss ein Leitbild, eine Leitkultur geben.
Und die ist deutsch.“

Er holte seine Pistole heraus, betrachtete sie.
Wog sie in der Hand.
Dann hielt er sie ihr plötzlich an die Stirn und spannte den Abzug:
„Wir brauchen eine deutsche Leitkultur.
Wir müssen die minderwertigen Elemente aus unserer Gesellschaft entfernen.
Würdest du das nicht auch so sehen?
Ich wette, du siehst das auch so.
Wir haben eine Erklärung vorbereitet, die du nur unterschreiben musst.
Bist du bereit?“
Sie stammelte etwas Unverständliches.
„Ahh? So? Aha!
Du kannst nicht reden.
BERTHOLD!“

Ein Mann tritt von hinten heran und öffnet den Knebel.
Hilde hustet.
Der Hauptmann nimmt seine Pistole von ihrer Stirn und schaut sie an: „Na, bist du bereit, Hilde?“

Hilde mit rauher Stimme: „Niemals!“

Der Hauptmann grinst: „Ich habe irgendwie gehofft, dass du das sagst.
Deine Schöntuerei mit dem Abschaum war mir immer zu wider.
Es hat seinen Reiz, jemanden zu töten.
Vor allem, wenn es ein Auftrag ist, wenn es Pflicht ist.
Das ist ein ziemliches Erlebnis.
Töten können nicht viele.
Mir wird es ein Vergnügen sein.
Und ich bekomme sogar ein Abzeichen dafür.“
Er zielt mit der Waffe wieder gegen Hildes Stirn:
„Letzte Chance, Dirne.
Ah.
Berthold, die Wanne.
Ich will nicht, dass das wieder so eine Sauerei wird.“
Bertold kommt wieder und schiebt mit dem Fuß eine Metallwanne hinter Hildes Stuhl.

Hilde sah den Hauptmann ernst an: „Was du machst, dafür bist du verantwortlich.
Du persönlich.
Du bist erwachsen.
Du kannst dich nicht hinter einem Befehl oder irgendeiner Gruppe oder einem Führer verstecken.
Was du machst, das machst du selbst.“

Der Hauptmann lachte: „Ja, das mache ich.
Ich alleine.
Aus voller Überzeugung.“
Er grinste.
„Zusammen mit Bertold.“
Er presste die Pistole stärker an Hildes Stirn und rief leicht aufgeregt: „Denk deinen letzten Gedanken!“ Dann drückte er den Abzug.
Hildes Gesicht fror ein, ihr Genick zuckte.
„Klick!“ 

Der Hauptmann lacht: „BUMM! Du lebst noch.
Hast du gedacht, ich erschieße dich hier so einfach?
Nein, nein.
Wir brauchen dich noch.
Du weißt ein paar Dinge, die wir wissen wollen.
So schnell kommst du hier nicht weg.“

Hilde schließt ihre Augen und atmet hastig.
Sie ist vollkommen bleich geworden.

Hauptmann: “Als erstes will ich von dir alle Namen des Spartakisten-Komitees, und zwar jetzt sofort.
Einen sag ich dir schon mal: Wilhelm Papenburg.
Den haben wir schon.
Jetzt brauche ich noch neun.
Drei davon wissen wir sicher.
Wenn die nicht auf deiner Liste sind, dann schieß ich dir in den Fuß, einmal für jeden, der fehlt.“ Er drehte sich um.
“Bertold, hast du das Verbandszeug da?“

Bertold: „Jawoll! Hier.“

Hauptmann: „Oder, hmm, ich sag einem von den Jungs hier, er soll dich mal richtig hart rannehmen, richtig wie ein Mann.
Siehst ja auch gar nicht so übel aus.
Na?
Wie wäre das?
Gibt es Freiwillige?“

Aus der Gruppe: „Ja!“, „Ja!“, „Hier!“

Hauptmann kam nah an ihr Gesicht: „Na?
Was wäre dir lieber?
Einer von denen oder dein Fuß?“
Hilde spukt ihm einen dicken Batzen Speichel ins Gesicht.
Der Hauptmann richtet sich auf, erzittert und wischt sich das Gesicht ab.
Er atmet tief ein und schlägt Hilde dann mit der Hand ins Gesicht.

Hauptmann: „Du Luder! Wir können auch anders! Luder!“
Er läuft aufgeregt im Raum herum.
„Luder! Bertold!!“

Bertold: „Jawoll!“ 

Hauptmann: „Hol ihn rein.
Wir machen gleich mit Stufe zwei weiter.“

Bertold: „Jawoll, Herr Hauptmann!“ 

/// BLENDE /// 2021, Marianne.

Marianne legte das Buch weg und atmete ein paar Mal kräftig aus.

Marianne: „Fuck!“

Neben ihr lag eine äthiopische Zeitung mit ihrem Bild auf der Titelseite.
Sie legte sich auf das Hotelbett in einem winzigen Zimmer irgendwo mitten in Addis Abeba in Äthiopien.
