== [big-number]#2023# Das Manifest (1)

[text-caps]#Marwin lief mit# einem Stift im Mund im Besprechungsraum auf und ab.
Auf einmal machte er einen großen Schritt in Richtung Wand, blieb davor stehen und wippte auf seinen Füßen: „Verschlüsselung, Verschlüsselung … Hmm.
Und dann … Ja!“ Er schnippte mit den Fingern.
„Ja, genau!“ Er setzte sich an den Tisch, blätterte um und schrieb:

„2 -- Die großen Ideale unserer Zeit, Wirtschaftswachstum, Geldgewinn und Sicherheit, gelten nicht mehr.
Wir können sie nicht mehr im Herzen tragen.
Sie schaffen überall Gegeneinander, Misstrauen und Angst.
Wir brauchen neue Ideale, stärkere Ideale, Ideale, die alles aus den Angeln heben können, was alt und verkrustet ist.
Und wir haben diese Ideale schon, jeder hat sie.
Zum Beispiel: Gerechtigkeit, Transparenz des öffentlichen Lebens, Überwindung von Unterdrückung (keine Chefs mehr!), kreatives Miteinander, Vertrauen, Mut ...“

Er blätterte um.

„3 -- Wir müssen das Gegeneinander überwinden.
Es gibt nur eine Menschheit.
Gegeneinander sein trennt, was in Wirklichkeit zusammen gehört.
Es gibt keine Terroristen, keine Anarchisten und keine Nazis.
Es gib nur Menschen, die geblendet sind vom Gegeneinander, die andere Menschen töten, vergewaltigen, einschüchtern, missbrauchen, unterdrücken, heruntermachen oder Shitstorms in Gang setzen, weil sie selbst Angst haben, weil sie blind sind, vor Angst.
Angst ist heilbar.“

Er blätterte um.

„4 -- Wir müssen die Initiativkraft in jedem Menschen heilig halten, auch die in uns selbst.
Räume dafür schaffen, Räume, in denen wir uns begegnen, anderen begegnen, miteinander Dinge erfinden, schöpferisch sein können, frei unseren eigenen Impulsen folgen.
Wir müssen lernen, wo die Grenzen zum Anderen sind, ab wann ich den Impuls des Anderen verletze, und lernen, mich da zurückzuziehen und ihn leben zu lassen.“

Marwin nahm den Stift zwischen die Zähne, stand auf und begann wieder im Raum herum zu laufen.
Ab und zu blieb er stehen, wippte mit den Füßen.
Nach einer Weile schaute er zur Spiegelwand, hinter der vermutlich auch jetzt Menschen saßen und ihn beobachteten.
Er lächelte warm in ihre Richtung.

„Was mag in ihnen jetzt vorgehen?“ dachte er.
„Warum machen sie so einen langweiligen Job, ihn zu beobachten, obwohl sie an ihm als Menschen überhaupt kein Interesse haben?
Sie schauen Stunden und Stunden auf etwas, was sie nicht interessiert.
Das ist doch reine Zeitverschwendung.
Fünf Tage die Woche so eine Arbeit?
Nein, das könnte ich nicht.
Und sie denken sich sicherlich auf der besseren, angenehmeren Seite der Geschichte, auf der freieren Seite.
Aber das ist eine Illusion.
Victor Frankl erlebte die größten Momente seiner eigenen Freiheit in einem deutschen Konzentrationslager als Gefangener, nicht als Wachmann.
Ja, das kann ich jetzt verstehen“, dachte Marwin und reckte die Arme in die Luft.
„Ja ... den Anderen verstehen.
Sich in ihn hineindenken.
Das ist es.“

Er nahm den Stift aus dem Mund, setzte sich wieder, blätterte um und schrieb.

„5 -- Empathie ist die Kunst, sich so weit in einen anderen hinein zu denken und zu fühlen, dass man versteht, warum er das macht, was er macht.
Soweit, dass man sich sagt, dass man genauso handeln würde, wenn man an an seiner Stelle wäre und seine Geschichte hätte.
Kein Kind kommt mit einem Drang auf die Welt, einen anderen Menschen zu töten.
Wir erwerben ihn.
Kinder kennen keine überlegene Rasse, keine überlegenes Volk, keine bedeutendere Nation oder wichtigeres Unternehmen, in denen einige Menschen mehr wert sind als andere.
Solche Unterschiede zwischen Menschen zu machen, ist uns als Kind fremd.
Wir lernen das später.
Deswegen können wir es auch wieder verlernen.“

Er legte den Stift auf den Tisch und richtete sich auf und sagte laut: „Ja, das können wir auch wieder verlernen!“
Dann stutzte er: „Aber wie?
Wie verlernen wir das?“
