== [big-number]#2064# Ein fliegender Kampfroboter 

[text-caps]#Lasse saß auf# der Rückbank eines Vans und arbeitete an seinem Laptop.
Sie fuhren auf irgendeinem Highway durch Arizona, mitten durch die Wüste.
Fahrer und Beifahrer waren in ein Gespräch vertieft.

Lasse startete Pond.
Er schaute gebannt auf den Bildschirm.
Zunächst die übliche Nachricht:

****
....
>>> There are no messages waiting to be transmitted.
....
****

Er tippte „log“.

****
....
- Jan 14 10:32:08 | Next network transaction in 5m23.029s seconds
....
****

„Fünf Minuten warten. Ok!“, dachte er.
Pond holte und sendete Nachrichten nicht sofort, sondern nach zufällig bestimmten Zeiten.
Dadurch konnten sich Geheimdienste schwerer ausrechnen, ob jemand gerade Pond nutzte.

Lasse: „Nee, nicht ok.“
Er tippte „transact now“.
Nach wenigen Augenblicken erschien:

****
....
(Jan 14 10:40) Message received from sig
....
****

„Shit. Shit!
Sie ist da: Die Nachricht von Sig“, dachte er, „Jetzt wird es spannend.
Ist er frei?“
Er tippte „show“.

****
....
Hi Lasse,

ich bin bei Tim!!! Ja! Ich bin raus! Alles hat geklappt. Das ist
so ein Super-Scheißhaufen dort. Ich kann's echt nicht glauben. Ich
habe eine Scheißwut. Wenn mir Fortunato mal im Dunkeln begegnet,
dann stecke ich ihm eine Zyankalikapsel in den Arsch. Aber eine mit
wasserlöslicher Hülle. Und in den letzten 30 Minuten seines Lebens
erzähle ich ihm dann Monty-Python-Sketche, einen nach dem ande-
ren. So ein Super-Arschloch.


Aber ich bin erst einmal draußen. Das ist gut. Und ohne Verfol-
ger. Ich sitze hier in einem 60 Jahre alten Atomschutzbunker unter
Tims Haus. Den hat seine Oma gebaut. Die hatten damals wirklich
Angst vor einem Atomkrieg. Glaubst du das? So wie später vor Terro-
risten. Aber jetzt hilft uns das. Hier kommen keine Signale raus
oder rein. Alles dicht.


Joe hat mir einen kleinen Taktgeber für meine Blausäurekapsel ge-
baut, damit sie immer meint, mit der Außenwelt verbunden zu sein
und nicht irgendwann die Säure freilässt ... meine liebe Klei-
ne. War gar nicht so schwer zu machen, Joe hat das Systemprogramm
der Kapsel modifiziert. Und es funktioniert tatsächlich, weil: Ich
lebe noch. Es sind schon mehr als 5 Stunden vorbei. Nur wenn ich
rausgehe von hier muss ich unter meiner Kleidung ein superlustiges
Alu-Kostüm anziehen: Damit die liebe Kleine nicht doch irgendwie
nach Hause funkt.


Langsam wache ich auch auf und mein Kopf dreht sich nicht mehr in
Wellen herum. Es ist verrückt, was sie einem da alles geben, damit
man nicht denken kann. Lieber Handschellen als solche Pillen. Ich
glaube, ich brauche eine echte Entziehungskur, oder besser Lillys
Chilli-Ingwer-Knoblauch-Diät: zwei Wochen lang: Weißt du noch? Mor-
gens nach dem Aufwachen: zwei frisch gepflückte und geschälte
Knoblauchzehen langsam zerkauen, dabei Haltung bewahren und
immer sanft lächeln ...


Hergekommen bin ich mit dem Anhaltertrick, den du wohl auch gerade
verwendest. Ich hatte erst drei zufällige Fahrer, dann Joe, Luis
und zuletzt Tim. Sechs Stationen. Das packen sie nicht, nicht wenn
Joe, Luis und Tim fahren. Und seit Joe hatte ich ja das Kostüm an und
den Taktgeber.


Jetzt werde ich erst einmal chillen. Mate steht hier vor mir. Wann
kommst du?


Sig
....
****

Lasse schrieb: „reply“

****
....
Hi Sig!

Wow, super! Ich bin mit dem Hitchhiking gerade auf der dritten
Station. Ich denke, der Fahrer ist nicht vom LBI. Ist ein Kurier-
fahrer und hat offensichtlich einen Kollegen dabei. Er bringt mich
nach Phoenix. Dort wartet Trevor. Ich sehe dich morgen früh,
denke ich.
....
****

Er speicherte die Nachricht und gab „send“ ein.
Pond antwortete:

****
....
>>> There is one message waiting to be transmitted.
....
****

Lasse atmete aus.
Zwei Stunden noch bis Phoenix.
„Ok“, dachte er, „Zeit, die erste Bombe zu entschärfen und ihre Bitcoins zurückzuschicken.“

Er öffnete das Terminal-Programm und stellte eine Verbindung zu dem Computer im Tor-Netzwerk her, auf dem die erste Bombe lag.
Er schaute sie an: Noch 25 Minuten bis zur Detonation.
Dann tippte er:

****
....
bbomb --disarm
....
****

Das Programm antwortete:

****
....
Passphrase:
....
****

Er atmete durch.

****
....
KvTsS#Fwf+w/~pOIet19

Bitcoin bomb disarmed.
....
****

„So einfach ist das“, dachte er. „Ok, jetzt noch zurücküberweisen.“

****
....
bbomb --transfer-all 3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy
....
****

In dem Augenblick, als er mit dem Finger die Eingabe-Taste drücken wollte, fuhr das Auto über eine Bodenwelle.
Lasse machte zusammen mit dem Laptop einen Satz nach oben.

„Sorry!“ meinte der Fahrer von vorne.
„Die habe ich nicht gesehen.“

Der Befehl im Terminal-Programm war verschwunden.
Lasse drückt die Pfeil-nach-oben-Taste, um ihn wieder zu holen.
Er war nicht mehr da.
Lasse schaute irritiert im Auto herum.
Er tippte noch einige Male die Pfeiltaste: nichts.
Er verstand nicht.
Befehle konnten nicht so einfach verschwinden.
Er schaute sich um, sein Blick ging nach draußen, dann nach vorne.
Sie fuhren auf eine Kurve zu, mit einem Hügel dahinter.

„OOOHH SHIT!“, rief er laut.
Hinter dem Hügel, direkt vor ihnen, schwebte ein fliegender Kampfroboter, der sich langsam zu ihnen hindrehte.
Er erkannte sofort das Modell, Reaper MQ-11, brandneu, er konnte in der Luft stehen.
Lasse kannte ihn sehr gut, er war einer seiner Lieblingsroboter, nicht der Schnellste, aber dafür irrwitzig wendig.
Sein Herz begann zu rasen.
Zweimal kurz zuckte ein Feuerball am Kampfroboter.
Lasse riss instinktiv die Arme hoch um sein Gesicht zu verdecken.
Ein halbe Sekunde später zischten zwei Raketen links und rechts neben dem Auto vorbei, trafen 50 Meter hinter ihnen zwei Autos, die in einem Feuerball verschwanden.
Lasse und sein Laptop wurden wieder hochgeschleudert, der Fahrer brachte den Wagen irgendwie zum Stoppen.

„Fuck!“ schrie Lasse, „Fuck! Fuck!“ Er sprang aus dem Auto und schaut nach hinten auf die lodernden Wracks.
Sein Herz raste.
„Das macht keinen Sinn!“, rief er.
Er dachte: “Sie stoppen mich, bevor sie das Geld haben. Fuck! Nein!
Das macht keinen Sinn!“

Er schaute in Richtung Kampfroboter.
Der hatte keine Raketen mehr und drehte ab.
Dann sah er nach links in den Himmel.
„OH!“, dachte er.
Er riss seine Augen auf.
Ein weißer Riesen-Ballon schwebte über der Steppe neben der Autobahn, der gleiche wie in San Diego über dem Meer.
Nur diesmal viel näher.
Er war bestimmt zwanzigmal größer als normale Heißluft-Ballons.
Und auf ihm stand über die ganze Fläche geschrieben:

****
....
AK768-X5P

sZEf\~ofUA+
....
****

Lasse starrte ihn an und nickte langsam.
Er kannte den Ballon gut.
Er kam von TRON.
Aber was machte er hier? Jetzt?
Es war ein Hinweis für ihn.
Die Bodenwelle hatte ihn am Abschicken der Bitcoins gehindert.
Der Kampfroboter war eine Einschüchterung vom LBI, sie waren wohl nervös geworden.
Es war ein kleiner Gruß: „Wir sind bei dir und zu allem bereit.“

„Scheiße!“, dachte er, "dafür bringen sie Menschen um ...“
Er fasste sich an den Bauch.
„Aber was will mir TRON sagen?
sZEf\~ofUA+ ist ein Passwort, klar.
Aber AK768-X5P? Was war das? Ich kenne das irgendwo her.“
Er dachte nach.
Er lief auf der Autobahn einige Male im Kreis herum.
„Ja! Klar! Das ist ein Satellit.“

Er sprang ins Auto und tippe etwas auf seinem Laptop.

Lasse zu sich selbst: „Das muss der Satellit sein, über den das LBI die Kampfroboter steuert.“
Er dachte: „Wir haben ihn gefunden. Endlich!
Und gleich einen Zugang dazu.
Sigur muss das wissen.
Jetzt sofort.
Dann können wir sie jagen.
Das wird ein Ding.
Ja, sie haben sich gezeigt.
Jetzt finden wir ihre Kampfroboter.
Das wird ein Spaß.“

Er lächelte und tippte.

****
....
Hi Sig,

Vom AK768-X5P aus werden die LBI-Kampfroboter gesteuert. Einer
war eben bei 34.513079 / -113.4173765, ein neuer Reaper
MQ-11. Kannst du ihn finden? Ich komme dazu, wenn ich in
Phoenix das Auto gewechselt habe. Das Passwort ist sZEf\~ofUA+

Lasse.
....
****

Er wartete, bis Pond die Nachricht verschickt hatte, und klappte seinen Laptop zu.
