== [big-number]#2021, 1918# Verhör (2)

[text-caps]#Ein schmutziges Straßen-Café# in einer Geschäftsstraße irgendwo in Addis-Abbeba. Marianne saß in einer Ecke, halb hinter einer Säule und trank einen Tee.
Zwei einheimische junge Männer mit schwarzen Sonnenbrillen schauten von einem Nachbartisch zu ihr herüber. Sie schaute weg, griff in ihren Rucksack und holte das Taschenbuch heraus. Sie wollte gerade anfangen zu lesen, als plötzlich ein Pritschenwagen anhielt und Männer in Uniform und Sonnebrille herunter sprangen. Drei von ihnen stellten sich mit vorgehaltenen Maschinenpistolen vor das Café. Auf der anderen Straßenseite schien Ähnliches vorzugehen.

Marianne stutze. Sie beobachtete genau, was weiter passierte, legte eine Hand auf ihren Rucksack.

"Kein Problem!", rief einer der jungen Männer vom Nachbartisch. "Das ist nur der Innenminister, der will da drüben einen Kaffee trinken."

Marianne nickte ihm zu und vertiefte sich dann wieder in ihr Buch.


=== SZENE 9: Gewölbekeller.

____
Hilde wieder geknebelt, immer noch auf dem selben Stuhl.
Der Hauptmann steht neben ihr.

Er beugt sich zu Hilde herunter, geht mit seinem Mund ganz nah an ihr Ohr und flüstert halblaut:
„Na?
Du weißt schon, was jetzt kommt, nicht?
Willst du dir das nicht ersparen?
Und Wilhelm auch?
Ich nenne dir den Preis dafür: Du suchst dir einen von den Jungs hier aus, der dich richtig rannehmen darf.
Die sind ganz hungrig.
Danach schreibst du mir die Namen auf.
Wenn die Namen stimmen, kannst du nach Hause gehen und dir einen Teller Nudeln kochen.
Vielleicht vorher duschen … Hmm?
Wie ist das?
...
Ja, ich weiß, das ist ein bisschen teurer als vorhin.
Aber so ist das im Leben, je länger man wartet, umso teurer wird es.“

Hilde zeigt keine Regung.

„Klock!“, die Türe springt auf und zwei der Soldaten schleifen einen Mann herein, der kraftlos mit den Beinen strampelt.
Sie setzen ihn auf einen Stuhl etwa zehn Meter von Hilde entfernt, sodass sie ihn gerade so aus den Augenwinkeln sehen kann.
Er kann sich kaum aufrecht auf dem Stuhl halten.

Hilde lugt herüber und denkt: „Oh nein.
Wilhelm!
Was haben sie mit dir gemacht?“

Wilhelm nimmt von ihr keine Notiz.
Sie atmet durch: „Was wird jetzt kommen?“

Der Hauptmann beugt sich wieder zu ihr herunter: „Dein Bruder ist da.“
Er grinst sie breit an.

„Ich sehe euch noch, wie ihr früher so lustig Hand in Hand die Allee herunterspaziert seid …
Dann hat er dich auf die Schulter genommen.
Jetzt ist es nicht ganz so romantisch.
Ich verstehe.
Aber egal.

Ich habe jetzt ein anderes Problem.
Ich muss entscheiden, wie herum ich die Sache aufziehe.
Ich will die Liste mit den Namen.
Die kennt ihr beide.
Also muss ich entscheiden: Wer bekommt die Sonderbehandlung und wer soll mir die Namen sagen?
Hmm.
Hilde oder Wilhelm?
Wilhelm oder Hilde?“
Er wiegt seine Hand hin und her.

“Wilhelm!
Wilhelm wird behandelt und du sagst mir die Namen.
Okay?“
Er rief laut: „Phase 1.“

Ein Soldat tritt von hinten an Wilhelm heran und schlägt ihm mit einem abgebrochenen Besenstiel an den Kopf.
Der stöhnt laut auf.
„Rumms“, noch einmal.
Der Soldat nimmt den Stock auf die andere Seite des Kopfes und schlägt wieder zu.
Wilhelm stöhnt wieder laut und wimmert dann leise.

Hauptmann: „Na?
Abbrechen?
Ich meine, du weißt, dass wir noch mehr können.
Da habt ihr Spartakisten doch sicher vorher drüber geredet.
Ach so, du kannst gar nicht reden.
Bertold!“

Bertold kommt und nimmt ihr den Knebel ab. Hilde hustet und spuckt auf den Boden, aber antwortet nicht.

Hauptmann: „Hmm.
Nicht?
Okay, dann kommt Phase 2.
Und du wählst dir zwei Jungs aus.
Es wird teurer.
Ich sagte das schon.“

„Warten Sie, Herr Hauptmann.
Ich habe eine Zwischeneinlage“, ruft Bertold.

Hauptmann: „Zwischeneinlage?
Gut!
Du hast immer gute Zwischeneinlagen.“

Bertold schreitet langsam von hinten an Wilhelm heran.
Dann öffnet er seine Hose, greift seinen Penis und pinkelt Wilhelm mit breitem Strahl über Rücken und Schulter, begleitet von lautem Gelächter aller anderen Soldaten.

Hauptmann: „Joah.
Gute Einlage!
Das wird helfen.
Aber das stinkt furchtbar, bis hier rüber!
Mach das nicht zu oft.
Jetzt aber: Phase 2.
Alle verlassen den Raum, außer Bertold.“

Der Raum leert sich.
Bertold geht zu einem Regal an der Wand, in dem einige Zangen und Messer liegen.
Er sucht eine Weile und nimmt dann eine dicke, kleine Beißzange.

Bertold: „Die Zehen- und Fingerzange.“ Er hält sie Richtung des Hauptmanns.
Hilde lugt zu ihm herüber, schließt wieder die Augen und atmet schwer.

Hauptmann laut: „Zuerst die Finger, erst der Daumen“, dann schaut er auf Hilde: „Na?“ Hilde atmet stärker.
Sie beginnt zu schwitzen.

Bertold: „Daumen?
Das ist gut.“
Er nimmt Wilhelms Hand.
Der wehrt sich.
Bertold packt fester zu.
Wilhelm entreißt ihm die Hand mit letzter Kraft.

Bertold: „Na, du willst nicht?
Kein Problem.“

Bertold setzt sich mit einem Schwung so auf seinen Schoß, dass er dabei Wilhelms Arm unter sich einklemmt.
Er nimmt die Hand mit Gewalt.
Wilhelm kann nichts mehr tun, er versucht sie wegzuziehen, aber es geht nicht.
Bertold setzt die Zange an.

Hilde: „STOPP!“

Der Hauptmann stellt sich vor sie: „Stopp?
Okay, wen willst du vögeln?
Soll ich die Jungs wieder reinrufen, damit du auswählen kannst?“

Hilde: „Gib mir ein Blatt Papier und einen Tisch.
Ich schreibe dir die Namen auf.“

Hauptmann: „Eins nach dem anderen.
Die Jungs hier freuen sich schon so darauf.“

Hilde bestimmt: „Ich brauche einen Tisch, ein Blatt Papier und einen Stift.“

Der Hauptmann überlegt kurz.
„Okay.
Dann ändern wir die Reihenfolge.
Erst die Namen.
Ist eh besser diese Reihenfolge.
Dann bist du noch frischer beim Schreiben.
Los, Tisch hier herüber.“

Bertold trägt den Tisch zu Hilde, sie bekommt einen Stift und das Blatt, auf dem oben schon „Wilhelm Papenburg“ mit seiner Adresse draufstand.
Bertold öffnet ihre Handfesseln.
Sie atmet durch und beginnt zu schreiben.
____

Marianne klappte das Taschenbuch zu und schaute auf die drei Maschinenpistolen-Männer.
Dann zog sie einen Laptop aus ihrem Rucksack und schaltete ihn an.

„Pling!“, kam es aus dem Lautsprecher. Marianne tippt auf die Tastatur und lächelte.

Marianne leise: "Lago Maggiore? Jah."
