== [big-number]#2064# Mein Kampfroboter, dein Kampfroboter

[text-caps]#Ein Polizeiauto# in normaler Geschwindigkeit auf dem Highway.
Der Fahrer in Uniform mit schwarzer Sonnenbrille schaute in den Rückspiegel.
Phoenix verschwand langsam am Horizont.
Er lächelte und sagte dann laut: „Die Luft ist rein! Du kannst rauskommen.“

Von hinter der Rückbank des Autos kam ein lautes Klopfen: „Wumm“ Dann noch einmal: „Wumm … wumm!“
Der Fahrer pfiff leise eine Melodie.
Er lugte über den Rückspiegel zur Rückbank und lächelte.
„WUMM!“, die Rückbank klappte nach vorne und Lasse steckte seinen Kopf durch die Öffnung.
Er schaute den Fahrer an.
Der drehte sich um und grinste: „Wir sind draußen!“
Lasse: „Geil!
Mensch, Trevor!
Super Sache!
Und das hier.“
Er schaute sich im Wagen um.

Trevor: „Was ist?“

Lasse: „Ein Bullenauto?
Das ist Bullenauto.
Wie bei den Blues Brothers.“

Trevor: „Klar!
Mit Bullenmotor und Bullenreifen.
Magst du es?“

Lasse: „Ich liebe es.
Hey, und auch noch mit einem Satellitenfunker.“
Er legte die Hand auf ein großes Gerät mit Antennen neben ihm auf der Rückbank.
„Das ist sehr gut.
Dann müssen wir gleich keine Umwege gehen … Hej, LBI, das sind echt Schnarchnasen.
Das ist genauso Großbürokratie wie die anderen Geheimläden.
Die haben nichts dazu gelernt.
Ich dachte früher, die amerikanischen Geheimdienste sind die besten der Welt … Pah.
So ein einfacher Trick.
Mit Ansage.
Und klappt doch.“

Trevor: „Nee, die sind nicht die besten.
Die haben nur das meiste Geld.
Wir sind die besten.
Geld und Geheimhaltung machen müde und dumm.
Vor allem in ultrageheimen Geheimdiensten, die niemand kennt.
Das ist so schlimm wie ein ultrageheimes Verschlüsselungsprogramm, bei dem niemand jemals kontrolliert, was es wirklich tut.“

Lasse: „Und sie haben Schiss, sie haben so einen Riesenschiss bei allem, was sie machen.
Es darf ja nichts schief laufen.
Sie brauchen überall eine Übermacht an Leuten.
Nicht zehnmal mehr Leute, nein, fünfzigmal mehr.
Ich habe nicht gedacht, dass das so krass ist.
Sie sind auf alles eingegangen, was ich ihnen angeboten habe.
Sie denken wahrscheinlich, sie würden sterben, wenn sie ihre Bitcoins nicht mehr haben.
Ohne Geld sind sie tot.
Es ist so krass.“

Trevor: „Und wo müssen wir gleich keine Umwege gehen?“

Lasse: „Wir werden den Spieß ein bisschen umdrehen, denke ich.
Sie haben einen Fehler gemacht.
Sie haben uns einen ihrer Kampfroboter gezeigt.
Und Sigur hat ihn vielleicht schon gefunden.
Wir haben einen Zugangscode – Spielgeschenk von TRON.“

Trever blinzelte mit den Augen: „Was ist denn das da vorne?“
Er deutete auf einen kleinen Punkt im Himmel etwa zwei Kilometer vor ihnen.

Lasse: „Was?
Ah, ja.
Ich sehe es.
Keine Ahnung … Oh … Nein ...Shiiiiit!“

Trevor: „Was?“

Lasse aufgeregt: „Das ist eine Reaper.
Wieder eine Reaper MQ-11.
Oh, shit.
ABFAHRT!
Sofort Abfahrt!
Ich habe die Bitcoins nicht überwiesen.
Wir haben nur ein paar Sekunden.
Runter vom Highway.“

Trever: „Hier?“

Lasse: „Fahr!
Schnell!
Schnell!
Oder nein!
Fahr hinter den Lastwagen dort.
Schnell.“
Lasse fasste mit dem Arm nach vorne, konnte aber das Lenkrad nicht ganz erreichen.

Trevor: „Ist gut, ist gut, ist gut.
Ich fahr schon.“
Er lenkte das Auto hinter den Lastwagen.
Einige Augenblicke später zischte in unmittelbarer Nähe ein fliegender Kampfroboter an ihnen vorbei.
Beide zogen die Köpfe ein.

Lasse warf sich nach hinten und schaute aus dem Rückfenster: „Scheiße!
Die fliegt in der Geschwindigkeit in zehn Metern Höhe.
Ist der bescheuert?
Das ist vollkommener Irrsinn.
Die haben neue Piloten.“

Der Kampfroboter wendete mit einem atemberaubenden Manöver und schaute direkt auf ihr Auto, vielleicht 200 Meter entfernt.
Man konnte deutlich vier Raketen erkennen.

Lasse aufgeregt: „GOTT!
Vier Hellfire-Raketen.
Was tun wir??
Mir fällt nix ein.
Ich weiß nix.
Halt an!
Raus aus dem Auto, Seitengraben.“

Trevor machte eine Vollbremsung zum Standstreifen hin.
Beide hechten aus dem Auto und stürzten sich über die Leitplanken in einen Graben.
Der Kampfroboter flog über sie weg, deutlich langsamer diesmal, wendete noch einmal und blieb dann zu ihnen gewendet in der Luft stehen.
Lasse und Trevor vergruben ihre Köpfe unter den Armen und bissen auf die Zähne.
Sie zitterten am ganzen Leib.
Aber nichts passierte.
Der Kampfroboter stand da und schwebte.
Fast so laut wie ein Hubschrauber.

„SCHEISSE!!“, rief Lasse ins Ohr von Trevor.
„Was ist das?
Warum schießt er nicht?“

Trevor schrie zurück: „Vielleicht ist das Sigur!
Du hast doch gesagt, ihr habt einen Code.“

„Quatsch!“, rief Lasse, „das ist eine Reaper MQ-11, das ist nicht Sigur ...
Das ist nicht Sigur … das ist … Hej, vielleicht ist das Sigur!“
Er sprang auf und hechtete zurück zum Auto, nahm den Laptop und startete das Jabber-Chat-Programm.
„Pling!“, kam eine Nachricht herein.

Sigur: „Hej, erkennst du mich nicht?
Wer macht solche Wendungen mit einer Reaper MQ-11?
Ein CIA-Pilot?
Vergiss es.“

Lasse: „Das ist dein Kampfroboter?
Du hast ihn geklaut?“

Sigur: „Ausgeliehen!
Er war auf einem Übungsflug, mit voller Bewaffnung.
Quasi eine Gelegenheit.
Und dann habe ich ihn gleich versteckt, sodass sie nicht verfolgen können, wo ich bin.
Ich denke, sie suchen schon irgendwo nach dem Wrack.“

Lasse: „Voll geil!
Was hast du damit vor?“

Sigur: „Weiß ich noch nicht.
Es war so geil, ihn zu nehmen und so einfach.
Ich musste nur zugreifen.
Hej, ich hab vollen Zugriff auf den Satelliten, root.
Der kontrolliert 29 Kampfroboter als versteckte Seitenfunktion.
Sonst überträgt er Fernsehsender und Telefongespräche.
Die Flugzeuge sind gerade alle im Hangar, außer zweien.
Die müssen nur rauskommen, dann kann ich sie übernehmen.
Ich flieg meine jetzt erst einmal hinter den Hügel, es ist vielleicht nicht so gut hier direkt an der Autobahn.“

Der Kampfroboter flog von der Autobahn weg.
Trevor kam ins Auto gestürzt: „Polizei.
Dahinten kommt Polizei.“

Lasse zog seine Tür zu und schaute nach hinten.
Das Polizeiauto kam näher.
Dann gingen die Blaulichter an und es fuhr rechts heraus und blieb hinter ihnen in etwa 20 Meter Abstand stehen.
Zwei Polizisten stiegen aus und liefen mit gezogenen Waffen auf Lasse und Trevor zu.

Trever: „Oh, ja.
Ich habe den Polizeifunk ausgemacht, damit wir darüber nicht verfolgt werden können.
Das ist verdächtig.“

Lasse: „Shit!
Es sieht nicht so aus, als könnten wir mit ihnen reden.
Zu gefährlich.
Gib Gas!“
Trevor startete den Motor und fuhr mit quietschenden Reifen davon.
Die Polizisten rannten zurück, sprangen ins Auto und fuhren hinterher.

Lasse aktivierte die Spracherkennung von Jabber, so dass Sigur auch das mitbekam, was im Auto gesprochen wurde.
Er sagte: „Sigur, Polizei.
Sie wollten uns anhalten.
Wir sind weggefahren.“

Sigur antwortete: „Ok.
Ich schaue mir die Sache an.“ Nach kurzer Zeit tauchte der Kampfroboter wieder am Himmel auf.
Er flog etwa hundert Meter rechts hinter dem Polizeiwagen, der mit Blaulicht in hoher Geschwindigkeit über den Highway raste.

Trevor: „Noch 30 Meilen bis Cornville.
Da ist die Übergabe geplant, Roger kommt gegen 1 Uhr nachts dorthin und du kannst solange in einem leeren Haus warten.“

Lasse: „Aber da fahren wir nicht hin, solange uns die Polizei verfolgt.“

Trevor: „Ich komme nicht weg von ihnen.
Ich kann nicht schneller fahren.
Und vielleicht kommt gleich eine Straßensperre.
Soll ich wenden?“

Lasse: „Keine Ahnung.
Shit!“

Sigur: „Tim hier hat den Polizeifunk angemacht.
Sie bauen schon an der Straßensperre.
Sie ist 25 Meilen entfernt.
Ihr müsst von da verschwinden.“

Lasse: „Aber wie kriegen wir den hinter uns los?“

Trevor: „Sigur, kannst du sie nicht einfach abknallen?“
Lasse und Trevor lachten.

Sigur: „Ok.
Ihr seid gerade ziemlich alleine auf der Autobahn.“

Lasse schrie: „SIGUR! NICHT!!“
Er blickte zum Kampfroboter und sah Sekunden später einen Feuerball aufzucken und das Polizeiauto hinter ihnen verschwand in einer gewaltigen Explosion.

Lasse und Trevor zuckten zusammen und sahen beide auf das brennende Wrack und dann zueinander.

Lasse, Trevor: „Scheiße! Sigur!“

Sigur: „Hej, ihr seid alleine.
Ihr seid frei!“

Lasse: „Runter von der Autobahn.
Hier gleich.“
Trevor fuhr auf der Stelle von der Autobahn ab in Richtung einer Straße, die in einiger Entfernung vorbeiführte.
Der Wagen holperte über das Gras und kam ohne sich festzufahren auf der anderen Seite an.

Lasse: „Halt an! Halt an!
Was tun wir jetzt?“

Trevor hielt nicht an und meinte: „Ich fahr dich etwa 20 Kilometer von hier irgendwo in die Pampa, wir finden einen satellitengeschützten Platz, du nimmst mein Klapprad, das ist im Kofferraum, wartest ein, zwei Stunden und fährst dann in der Dämmerung rüber nach Cornville.
Das ist am sichersten.
Sie werden nicht gleich mit Wärmebildkameras kommen.
Sie sind nicht vorbereitet.
Und ich versuche dann zu dem Auto zu kommen, mit dem ich sowieso zurückfahren wollte.
Wir sind vorbereitet.
Sie nicht.“

Lasse: „Und, Sigur, lass den Kampfroboter irgendwo kontrolliert abstürzen.
Wenn sie rauskriegen, dass wir ihn entführt haben, dann ist das ganze Wespennest hinter uns her.“

Sigur: „Die sind eh schon hinter uns her.
Und wissen tun sie es auch bald.
Ich meine, dort auf dem Highway liegen überall Raketenteile.“

Lasse: „Sie brauchen eine Zeit lang, um herauszukriegen, dass es eine Reaper MQ-11 war, dass im Armee- und im CIA-Arsenal keine fehlt, in der Zeit gar keine dort unterwegs war und dann sagt ihnen irgendwann jemand vom LBI, dass ihnen just in der Zeit eine abhanden gekommen ist.
Das ist alles oberhalb von top secret.
Da fließen die Informationen nicht so schnell.
Wir haben mindestens ein paar Stunden Ruhe.
Also knall das Ding jetzt irgendwo in der Wüste auf den Boden!“
