== [big-number]#2023# Das Manifest (2)

[text-caps]#Marwin blätterte um# und schrieb weiter: „6 -- Wir hören einander nicht zu.
Wir hören die Worte, die ein anderer sagt, und machen uns eigene Gedanken daraus.
Dann haben wir nicht mehr das, was der andere gedacht hat.
Nicht mehr das, was er gesagt hat.
Nicht einmal das, was wir gehört haben.
Dann haben wir das, was wir über das denken, was wir gehört haben von dem, was der andere gesagt hat, über das, was er gedacht hat.
Es sind immer diese vier Stufen, wenn wir kommunizieren.
Denken – Sagen – Hören – Denken.
Und meistens unterscheiden sich alle vier, manchmal in grotesker Weise, manchmal in lebensentscheidenden Details.
Kriege werden geführt, Morde begangen, Menschen ausgeschlossen – nur, weil wir das nicht unterscheiden.
Diese vier Dinge müssen zusammenwachsen, eins werden.
Aber das ist unmöglich.
Sie können nicht eins werden.
Trotzdem müssen wir es versuchen!
Es kommt auf den Versuch an.
Wir müssen lernen, die Dinge von mehr als einer Seite zu betrachten, beweglich bleiben in unseren Worten und Gedanken.“

Er blätterte um.

„7 -- Wir brauchen Transparenz, Offenheit von allem Öffentlichen, von allem, das uns etwas angeht, von allem, was nicht privat ist.
Wenn ich etwas verwende oder konsumiere, habe ich ein Menschenrecht darauf, zu wissen, was vorher damit passiert ist:
Wer hat meinen Strom produziert, den ich aus der Steckdose nehme, wie wurde er produziert?
Wer hat an meinem Computer mitgebaut, wer hat meine Software geschrieben und was hat er oder sie gemacht?
Was machen Unternehmen, um ein Produkt zu entwickeln, es zu bauen, zu verkaufen?
Wie sorgt der Staat für meine Sicherheit?
Was tut er dafür?
Bringt er andere Menschen dafür um?
Wie viele? Wen?
Foltert er dafür?
Unterdrückt er?“

Er blätterte um.

„8 -- Wir brauchen Mut, viel Mut, um die Angst zu überwinden.
Angst ist eines der beiden großen Unterdrückungsinstrumente.
Je mehr Angst Menschen haben, umso einfacher sind sie manipulierbar, kontrollierbar.
Einschüchterung macht Sklaven.
Mut ist die Kraft, die Angst zu überwinden.
Mut ist genauso ansteckend wie Angst.

Und Wut, sie ist die warme, machtvolle Kraft in unserem Körper.
Wut ist nicht Aggression.
Wir brauchen viel Wut, um lähmende Hoffnung zu überwinden.
Hoffnung, die einem von außen gemacht wird, lähmt.
Wir brauchen das nicht.
Wir haben immer genug eigene Hoffnung in uns.
Wir verlieren sie nur manchmal aus den Augen.
Die Hoffnung stirbt zuletzt.“

Er blätterte um.

„9 -- Menschen dürfen keine Zahlen mehr sein.
Ein Mensch kann nicht statistisch erfasst werden.
Er wird dadurch getötet.
Der Satz „Elf Menschen bei Feuergefecht gestorben“ tötet die Menschen ein zweites Mal.
Denn in Wirklichkeit waren es Anke, Helmut, Tim, Trevor, Silke, Antje, Lisa, Jochen, Leon, Aischa und Finn.
Sie sind alle auf unterschiedliche Weise gestorben, sie hatten alle individuelle Lebenswege.
Sie waren nur gerade zusammen, als sie starben.
Menschen dürfen keine Zahlen mehr sein, Menschen sind Menschen.“

Er legte den Stift auf den Tisch und schaute auf den Text.

„Okay: 'Menschen sind Menschen'.
Das ist ein schönes letztes Wort.
Ich glaube, das ist alles“, dachte er.
„Mehr muss nicht sein.“

Er nahm den Stift und schrieb zusammenfassend:

„Verschlüsseln,

wirkliche Ideale,

das Gegeneinander überwinden,

freie Entfaltung,

hineinfühlen können,

Gedanken statt Worte,

Offenheit,

Mut und Wut,

der Mensch als Mensch“.

Er legte den Stift wieder auf den Tisch und streckte sich.

Marwin: „Und wem gebe ich das jetzt?
… Shit … Linda? … Nein! …

Marlene!
Oskar!
Julian!
… Aber wie?“ Er schloss die Augen.
Dann hob er die Hände, schlug die Augen auf und rief: „Ich brauche Magie!“
Er schaute das Büchlein intensiv an, rollte die Augen, spreizte seine Finger darüber in seltsamen Formen und sagte geheimnisvoll, während er die Hände auf- und niederbewegte: „Abara kadabara, finde deinen Weg zu … Marlene … Oskar … Julian … Tobi“.

Er schaute erstaunt seine Finger an und sagte zu ihnen: „Hmm?
Was wollt ihr?
Was wollt ihr denn jetzt?“
Er nickte.
„Ja, das kann ich mir vorstellen.
Ich würde sterben für eine Tastatur.
Und wenn es nur eine Hosentastatur an einem Raspberry Pi oder einem Olimex Board wäre.
Es fehlt mir so!
Scheiße!
Das wäre jetzt besser als eine Mate zum Sonnenuntergang auf einem Berliner Dach.“ Er nahm den Stift und schrieb:

„Liebe zur Technik“

Er schaute auf die Liste und nickte.
„Jetzt ist es schön.
Genau, wir müssen in der Breite eine Liebe zur Technik entwickeln …“

Er formte seine Finger wieder in der absurdesten Weise und bewegte sie über dem vollgeschriebenen Blatt: „Abrakadubrabra“, sagte er laut, „flieg zu Marlene, flieg zu Oskar, flieg zu Julian und Tobi.“
