== [big-number]#2021# Am Lago Maggiore

[text-caps]#Marianne saß mit# einem großen, runden Hut auf der Terrasse einer Ferienwohnung am Lago Maggiore, im Norden von Italien.
Sie blickte über den See, auf die Berge auf der gegenüberliegenden Seite.
Die Terrasse war von links und rechts blickdicht mit Agaven zugewachsen, und auch auf der Terrasse selbst standen überall Töpfe mit großen Pflanzen.
Sie saß im Schatten im Schneidersitz auf einem Korbsessel, die Hände in einer Meditationsgeste, die Augen geschlossen.
Nach einer Weile öffnete sie die Augen und setzte ihr Headset auf, legte ihre Beine auf ein kleines Tischchen, nahm den Laptop auf den Schoß und fing an zu tippen.

Marianne mit halber Lautstärke in ihr Headset: „Hej!“

Sie hörte zu.

Marianne: „Es ist alles ganz ruhig hier.
Ich kann arbeiten.
Von der anderen Uferseite aus ist die Terrasse theoretisch einsehbar, aber das sind viereinhalb Kilometer.
Es ist ok.“

Sie hörte zu.

Marianne: „Ja, klar habe ich von den neuen Leaks bei Google gehört.
Ich kenne die beiden Jungs persönlich.
Es ist wirklich unfassbar: Die Android-Leute haben es tatsächlich geschafft, die Hintertüren zum dritten Mal wieder reinzubauen.
Zum dritten Mal!
Und vorher zweimal geschworen, es es nie wieder zu tun.
Was machen die da?
Die verlieren doch komplett ihre Glaubwürdigkeit.
Ich kenne ein paar ganz normale Leute, die jetzt durch die Decke gehen.“

Sie hörte zu.

„Nein, das ist Quatsch, sie haben die beiden nicht gefunden.
Sie sind noch da und aktiv.“

Sie hörte zu.

„Klar bin ich sicher.
Ich habe eben gerade eine Ricochet-Nachricht bekommen.
Sie haben andere gefunden, vielleicht brauchen sie irgendwelche Sündenböcke.
Vielleicht ist es auch nicht ganz sauber gelaufen, vielleicht haben sich die beiden intern in andere Konten gehackt und die Leaks über die rausgeschickt.
Aber definitiv, sie sind noch da, nicht aufgeflogen und wild entschlossen, so lange neue Schwachstellen zu melden, wie sie eingebaut werden.“

Sie hörte zu.

„Ja, genau.
Das sehe ich auch so.
Das sind Helden.
Das sind die Helden der Neuzeit.
Die brauchen wir.
Das sind die Revolutionäre, von denen später einmal Bilder an der Wand hängen werden.
Zuerst will man sie selbst aufhängen, später ihre Bilder.
Das war schon immer so: Jesus, Ghandi, Martin Luther King, Mandela.“

Sie hörte zu.

„Ja, ja, klar.
Ich weiß auch nicht, was mir lieber wäre.
Ich will auch nicht als Bild an irgendeiner Wand enden.
Aber es wird so sein.
Die Menschen lieben es, andere zu bewundern.
Das ist bequemer als selbst etwas zu tun.“

Marianne hörte einen Schlag gegen das Metalltor am Eingang und drehte sich erschrocken um.
Sie schaute.

Marianne: „Warte kurz.“

Sie sah Luigi mit einer großen Tüte hereinkommen.

Marianne: „Ich rufe dich zurück.
Bis gleich.“
Sie drehte sich um.
„Luigi!
Ich wusste nicht, dass du jetzt kommst.“

Er lächelte sie an, legte die Tüte auf den Tisch und gab Marianne rechts und links einen Kuss die Wangen.
Sie lächelte und griff nach der Tüte.

Marianne: „Ahhh, italienische Kekse!
Mmmhhh.
Benissima.“

Luigi war Mitte Dreißig, wohnte seit 20 Jahren hier in Luino, im italienischen Teil des Lago Maggiore, nahe der Grenze zur Schweiz.
Er hatte einen örtlichen Hackerspace gegründet, nicht den größten, es waren nur 5 oder 6 Mitglieder, aber sie hatten den ein oder anderen guten Hack hinter sich.
Zum Beispiel hatten sie die Kaffeemaschine gebaut, die man per verschlüsseltem Jabber-Chat erst einmal davon überzeugen musste, dass man jetzt Kaffee braucht.
Die Kaffeemaschine analysierte, wie aktiv man gerade in OpenSource-Projekten auf Github war.
Wenn es ihr nicht genug war, dann musste man einen der Tricks finden, sie doch zum Kochen zu bewegen.
Sie hatten das vor zwei Jahren beim Chaos Communication Congress in Berlin vorgestellt.

Die Anfrage, Marianne unterzubringen, war von einem alten Freund gekommen, und er hatte sofort zugesagt: Wie konnte er anders, als der Frau zu helfen, die die Grundlage dazu gelegt hatte, das Internet von Grund auf zu reparieren, der Frau, die ihnen alle Schlaglöcher in den Daten-Autobahnen gezeigt hatte?

Luigi: „Hast du gesehen?
Deine Klasse hat über WikiLeaks einen Brief an dich geschickt.“

Marianne: „Nein.
Echt?
Meine alte Klasse?
Jetzt?
Was schreiben sie denn?
Dass ich zurückkommen und mich einem fairen Prozess stellen soll?“

Luigi: „Nein, überhaupt nicht.
Ich finde es super cool, was sie schreiben.
Sie wollen streiken, bis dein Bild in der Öffentlichkeit wieder korrigiert ist.
Sie streiken gegen die Propaganda in Deutschland.“

„Was???“, Marianne nahm ihr Beine vom Tischchen und fing an, etwas in ihren Laptop zu tippen.
Dann las sie.
Luigi stand neben ihr und legte die Hand auf ihre Schulter.
Er lächelte.

Luigi: „Das tut gut, so etwas zu lesen, nicht?“

Marianne schaute Luigi kurz aus dem Augenwinkel an und las weiter.
Nach einer Weile stand sie auf und ging zum Terrassengeländer.

„Nicht dahin!“, rief Luigi, „nicht zum Geländer.
„Das ist einsehbar.“

Marianne blieb stehen.
Tränen kullerten ihr über die Backen.
Sie griff mit beiden Händen das Geländer und schloss die Augen.
Luigi kam und legte von hinten seine Arme um sie.
So standen sie einige Minuten.
Dann zog er sie sanft nach hinten.

Luigi: „Komm! Zurück aus dem Sichtfeld.“ 

Marianne löste sich von ihm und setzte sich zurück in ihren Korbsessel, nahm sich den Laptop und las den Brief noch einmal.

Marianne: „Hast du ein Blatt Papier und einen Stift?“

Luigi: „Was?“

Marianne: „Papier, Stift, ganz normal, wie in der Schule.“

Luigi: „Ja, ich glaube“, ging weg und kam mit einem Block und einem Kugelschreiber wieder.
Marianne legte den Block auf ihren Laptop und begann zu schreiben:

****
....
Liebe Sophie, Anni, Kevin, Aischa, Lukas, Janis, Lisa, Leonie,
Felix, Berem, Jannik, Jannick, Philip, Moritz, Antonia, Aylin,
Johanna, Tom, Jonas, Devin, Marie, Lena, Nils, Paul, Emilie,
Viviane, Tatjana,

ich sitze hier mit Tränen in den Augen, weil ich gerade euren
Brief gelesen habe. Es tut so gut, von euch zu hören. Ich wusste
wirklich nicht, ob ich euch verloren hatte oder nicht. Und ihr
scheint die einzigen zu sein, die mich wirklich kennen – bis auf
einige Hackerfreunde, die mir geblieben sind. Auch da haben sich
einige abgewendet. Wir haben mächtige Gegner.


Euren Brief wird die Öffentlichkeit wahrnehmen. Ich glaube, ihr
wisst, dass ihr deswegen eine Menge Gegenwind bekommen werdet. Im
Internet tobt ein voll ausgeprägter Krieg, mit Toten, Verwundeten,
Gefangenen und Gefolterten. Ihr werdet alle schon seit zwei Jahren
überwacht. Alle eure Handys, alle Konten, Facebook, Whatsapp,
E-Mail, auch Threema, Telegram, sogar Signal und Xabber. Das macht
ein kleines Programm direkt auf den Smartphones. Auf Smartphones
ist nichts sicher, wenn man unter direkter Überwachung eines großen
Geheimdienstes steht. Und das tut ihr. Am besten ihr stellt alle
auf sichere Laptops um. Ich werde jemanden fragen, ob er zu euch
kommt und euch hilft, eine sichere Kommunikation einzurichten.


Macht euch auf viel, viel Gegenwind gefasst. Das, was ihr tut, ist
super, aber es ist für einige mächtige Leute eine echte Gefahr, die
sie auf alle Fälle beseitigen wollen werden. Ihr seid gefährlich,
weil ihr Aufmerksamkeit schafft, Interesse weckt. Das ist ihr größtes
Problem. Aber ihr könnt euch auch sicher sein, dass ab jetzt eine
Menge Augen aus dem Internet auf euch schauen werden, die euch
schützen wollen und Dinge tun werden, dass ihr eine größere Chance
habt, da heil wieder herauszukommen. Eure Gegner, unsere Gegner,
schrecken auch nicht vor Mord zurück. Deswegen: Geht an die Öffent-
lichkeit, macht Lärm, dass euch die Leute sehen. Ihr braucht Fern-
sehen, Presse, Twitter … Vor der Öffentlichkeit fliehen sie in Panik,
sie haben eine höllische Angst vor der Wut der normalen Menschen. Das
ist ihre reale Gefahr. Sie brauchen die normalen Menschen, sie
brauchen euch, weil irgendjemand muss ja die Arbeit machen, die
Steuern bezahlen und Dinge kaufen.


Ich denke, ihr habt einen großen Vorteil: Sie werden überrascht sein,
dass eine ganze, geschlossene Klasse für mehr Öffentlichkeit, für die
Wahrheit streikt. Das ist stark. Sie werden ein paar Tage, vielleicht
sogar Wochen brauchen, dafür einen Umgang zu finden. Das ist eure 
Chance. Bis dahin muss euch die Welt kennen. Dann könnt ihr durch-
kommen. Sie werden euch trennen wollen, versuchen, euch gegenseitig
zu Feinden zu machen, über die Eltern, Geschwister, Freunde, Leh-
rer. Lasst euch keine Angst machen und nicht durch Versprechen Hoff-
nung machen. Und benutzt die besten Waffen, die es gibt: PGP, TOR,
OTR, TAILS, CUBES, Pond, Ricochet und Veracrypt. Und Linux oder BSD
natürlich, nur noch Linux oder BSD!


Alles Gute euch.
Ich hoffe, ich sehe euch mal wieder …


Marianne
....
****

Luigi: „Hej!
Das liest sich gut!
Und du hast recht.
Sie sind jetzt in Riesengefahr.
Aber das können wir hinkriegen.
Ich nehme deinen Brief mit, scanne ihn und schicke ihn an WikiLeaks.
Ihr berühmter Briefkasten funktioniert ja jetzt wieder.“

„Kannst du das auch von hier machen?“ fragte Marianne.
„Ich will nicht, dass das Blatt die Wohnung verlässt.“

Luigi: „Ok.“
Er ging weg und kam mit einer älteren Digitalkamera wieder und zeigte sie Marianne.
Sie nickte.
Dann machte er ein Foto von dem Brief.
Marianne nahm ihn, ging zum Terrassenkamin und zündete ihn an.
Dann ging sie zu ihrem Laptop, steckte die SD-Karte der Kamera ein und begann zu tippen.
