== [big-number]#2064# Ein Albatross

[text-caps]#Vor einer Berghütte# standen zwei Gelände-Motorräder.
Davor saß Roger, auf einer Bank an eine Hauswand gelehnt, die Hände hinter dem Kopf verschränkt, Zigarette im Mund, Beine lang ausgestreckt.
Im Haus konnte man Lasse an seinem Laptop sehen.
Er trug Kopfhörer und hatte einen großen Joystick in der Hand.
Vor ihm auf dem Bildschirm sah man ein Steuerungsprogramm für einen fliegenden Kampfroboter.
Es war aktiv.
Der Kampfroboter flog über eine Steppen-Landschaft.
Vor ihm kam ein weiterer Kampfroboter ins Blickfeld.

Lasse: „Sigur?
Ich bin da.
Hinten rechts hinter dir.“

Sigur: „Geil!
Das Team ist wieder zusammen.
Fühlt sich gut an.
Du weißt, das Letzte, was wir so zusammen gemacht haben, war den Fünfstern vom Himmel zu holen.
Der letzte Looping, wir beide zusammen, weißt du noch?“

Lasse: „Klar, weiß ich das noch.
Und ich komme gerne auch mal, um dich rauszuboxen, wenn du Schwierigkeiten hast.
Wo sind die Hubschrauber?“

Sigur: „Die habe ich schon erledigt.
Sie liegen irgendwo im Wüstensand, vielleicht 15 km westlich von uns.
Es war ganz einfach.
Die XJ-11 hat wirklich einiges mehr an Kampfkraft als die Vorgänger, und ist super beweglich.
Ich habe mich zu keinem Zeitpunkt in Gefahr gefühlt.
Deswegen habe ich nicht auf dich gewartet.
Ich habe sie alle in 30 Sekunden runtergeholt.
Es war echt easy.
Allerdings habe ich natürlich jetzt nur noch eine Hellfire-Rakete.“

Lasse: „SHIT!
Sigur!
Wir wollten sie verjagen und dann verschwinden.
Nicht gleich vom Himmel holen.
Da sitzen Menschen drin.
Du kannst nicht einfach auf alles schießen, was dir in die Quere kommt.
Er gibt Regeln.
Es gilt: Nur zur Abwendung unmittelbarer Lebensgefahr.
Oder besser noch die Cypherpunks-Regel: Nur wenn der oder die andere ein Leben unmittelbar bedroht, und dann auch nur sie, nicht noch ein paar Leute um sie herum.“

Sigur: „Ich bin kein Cypherpunk.
Und trotzdem: Ist das keine unmittelbare Gefahr?
Drei Apache-Hubschrauber, mit wärmegesteuerten Lenk-Raketen und 30mm-Bordkanonen.
Das sind keine Spielzeuge.
Ich war in Gefahr.“ 

Lasse: „Sie haben gegen dich keine Chance.
Da sitzen Menschen drin, die müssen auch noch auf ihr Leben achten.
Du verlierst im schlimmsten Fall einen Kampfroboter.“

Sigur: „Hej, das sind Leute, die für ein totalitäres Regime arbeiten, die müssen damit rechnen, dass etwas als Antwort zurück kommt, bei all dem, was sie machen.
Ich habe eine Blausäurekapsel im Bauch.
Die würden die jetzt aktivieren, ohne mit der Wimper zu zucken, wenn sie könnten.
Die machen auf jeden Fall schlimmere Sachen als ich.
Und du hast so ein Ding im Hirn, wovon du noch nicht einmal weißt, was es genau ist.“

Lasse: „Du kannst nicht sagen, weil die das machen, machen wir das auch.
Wenn jemand einen Freund von dir foltert, dann gehst du ja auch nicht hin und folterst einen seiner Freunde.“

Sigur: „Arschloch.“

Lasse: „Ok, sorry, ich ziehe das Beispiel zurück.“

Sigur: „SCHEISSE!“

Lasse: „Nee.
Ist gut.
Es war vielleicht zu drastisch.
Aber andererseits, du hast Menschen umgebracht ...“

Sigur hektisch: „Nee, nee.
Sie haben Großalarm ausgelöst!
Das ganze Kampfrobotergeschwader rückt aus.
Shit.
Alle 15 … 20 … 24 … 27 gehen gerade in die Luft ...
und nehmen Kurs auf uns.
Shit.
Shit.
Wir sind aufgeflogen.
Sie wissen, wo wir sind.“

Lasse: „Was machen wir jetzt?
Wir hauen die Dinger jetzt auf den Boden!“

Sigur: „Geh in Multimode schnell.“

Lasse: „Multimode?“

Sigur: „mm --activate.
mm --flymode albatross.“

Lasse: „Ok, habe ich gemacht.
Was ist das?“

Sigur: „Ich schicke dir meinen fliegenden Kampfroboter rüber.
Er gliedert sich im Albatross-Modus automatisch in Keilform hinter dir ein.
Das sind experimentielle Funktionen für Formationsflüge und Formationsangriffe.“
Sigurs Kampfroboter schloss auf Lasses auf.

Lasse: „Und was machst du?“

Sigur: „Ich kümmere mich um die anderen ...“

Lasse: „WAS?
Lass das!
Lass uns die Dinger auf den Boden hauen und dann weiterziehen.
Sigur!“

Sigur: „Kleinen Moment.“

Lasse hört über seinen Kopfhörer hektische Bewegungen von Sigur, Knopf- und Tastendrücke.
Dann ein Tastaturgewitter.
Ab und zu ein Fluch.

Lasse: „Sigur?
… Sigur?
… Was machst du?“

Sigur reagierte nicht.

Lasse: „Sigur, wir haben einen Auftrag.
Wir sollen die Machenschaften des LBI ans Licht bringen, nicht in einen Krieg mit ihm ziehen.“

Lasse: „Ich fliege mit meinen beiden Kampfrobotern jetzt in die Wüste und schmeiße sie auf den Boden.“

Lasse drehte mit beiden Kampfrobotern ab.

Sigur: „Warte kurz.
Ich bin gleich fertig.“

Lasse: „Fertig mit was???“

Sigur: „So, jetzt habe ich sie!“

Lasse: „Du hast sie alle vom Himmel geholt?“

Sigur: „Nee.“
Er lachte.
„Nee, sie habe sie alle zu mir geholt, alle!
Alle 27.
Das ist so geil, wenn du mit Software umgehst, die nicht Open-Source ist.
Das sind manchmal so billige Fehler drin, über die du das Programm komplett kontrollieren kannst.
Die sind selbst schuld.
Wenn die Software Open-Source wäre, dann wäre das nicht passiert.
Ich hab einen nach dem anderen abgepflückt, ganz automatisch, und bin jetzt im Albatros-Formationsflug auf dem Weg zu dir.
27 Kampfroboter, in Keilform, vorne mein Leit-Albatross.
Es funktioniert super.
Geil, was die da eingebaut haben.“

Lasse: „BIST DU VERRÜCKT GEWORDEN?“

Sigur: „Hej, was ist los mit dir?
Ich habe ein paar Kampfroboter ausgeliehen.
Das war für dich bisher nie ein Problem.“

Lasse: „Aber 27 auf einmal!
Ein ganzes LBI-Geschwader.
Jetzt sehen wir gleich ein paar F22 aufsteigen.“

Sigur: „Kein Problem.
Es gibt einen F22-Fighting-Mode.
Ich kann die Kampfroboter wie einen Haufen Hornissen über eine F22 herfallen lassen, oder über zwei oder drei gleichzeitig.
Erst bei vier bräuchte ich mehr Kampfroboter.
Ich habe die Simulationen gesehen.
Das ist so geil gemacht.“

Lasse: „Du bist total verrückt!!“

Sigur: „Hej, Lasse.
Krieg dich ein.
Ich lese nur das Spiel.
Die Weltöffentlichkeit muss glaubwürdig von uns erfahren, dass es das LBI gibt.
Wie wollen wir denn für genügend Aufmerksamkeit und genügend Glaubwürdigkeit sorgen, wenn wir nicht einen Riesenzauber veranstalten?
Wir können nicht mit großen Zeitungen kooperieren, wie WikiLeaks 2010, oder wie Laura Poitras einen Film drehen, der dann einen Oscar bekommt.
Wir haben 2026, da müssen wir andere Geschütze auffahren.
Und jetzt haben wir gute Geschütze.
Super Geschütze.
Mit denen können wir etwas machen, das auffällt.
29 Kampfroboter, voll bewaffnet, die es eigentlich gar nicht geben dürfte und die auch in No-Fly-Zonen fliegen können.“

Lasse schwieg.

Sigur: „Kommst du mit deinen beiden zu mir?
Wir können jeden Kampfroboter gebrauchen.
Ich habe einen Plan.“

Lasse stand auf, legte sein Headset auf den Tisch und ging aus der Hütte.

Sigur: „Lasse?
Bist du da?
Lasse?“
