== [big-number]#2064# Der Plan

[text-caps]#Lasse saß mit# düsterer Miene und verschränkten Armen auf der Bank vor der Berghütte.
Neben ihm Roger mit Zigarette im Mund.

Roger: „Stress?“

Lasse nach einer Weile: „Sig dreht durch.
Er ist so anders geworden.
Er war immer der Korrekte von uns beiden.
Und jetzt dreht er völlig ab.“

Roger: „Das ist das Zyankali.
So was verändert.“

Lasse: „Aber es ist doch nur ein Spiel.
Wieso nimmt ihn das so mit?“ 

Roger: „Er identifiziert sich zu sehr mit seiner Rolle.“

Lasse: „Wahrscheinlich.
Ich weiß echt nicht, was jetzt kommt.
… Roger, ich gehe wieder rein.
Ich habe ein mulmiges Gefühl.“ 

Er ging in die Hütte, setzte sich vor den Monitor und schaute auf den Bildschirm.
Dort flogen seine zwei Kampfroboter inzwischen am Ende einer großen Formation mit.
Er setze sein Headset auf.

Lasse: „Sigur, hast du meine Kampfroboter übernommen?“

Sigur: „Ich lasse sie nur mitfliegen.
Du kannst sie jederzeit rausnehmen, wenn du willst.
Tim ist jetzt auch dabei.
Er fliegt fünf.
Wie viele willst du?“

Lasse: „Was hast du vor?“

Sigur: „Aufmerksamkeit erzeugen.
Wir brauchen viel Aufmerksamkeit.
Ich will heute noch in alle Nachrichtensendungen.
Weltweit.“

Lasse: „Was hast du vor?“

Sigur: „Ein Gebäude zerstören.
In Schutt und Asche legen.
Komplett planieren.
Ein repräsentatives, sehr bekanntes Gebäude.
Das hatte ich schon lange vor.
Es wird dir gefallen.“

Lasse: „Hör auf herumzuspielen.
Was willst du machen?“

Sigur: „Ist doch klar.
Denk doch mal nach.
Wie geht die Mission weiter?
Was ist jetzt das logische Ziel?
Washington?
Nein.
Es geht nicht um die Amerikanische Regierung.
New York?
Nein, es ist keine Finanzsache, keine Wirtschaftssache.
Zumindest nicht vordergründig.
Das würde die Message unklar machen.
Aber denk mal an Fort Meade?
An das NSA Hauptquartier?
Na?
Was passiert da in dir?
Schau, wir wollen den größten unbekannten Geheimdienst der Welt offenbaren, also machen wir das zentrale Gebäude des größten bekannten Geheimdienstes platt.
Das hat Bildgewalt.
Da werden alle weltweit hinschauen und sich fragen: Warum die NSA?
Warum jetzt?
Und wenn alle konzentriert dabei sind, dann sage ich ihnen: Hej, ich war das!
Dann fragen sie sich, wie das möglich ist, wie ich das machen konnte.
Wie kann ich als Hacker mit so vielen Kampfrobotern in eine No-Fly-Zone hineinkommen?
Und ich sage: 
Ganz einfach, ich habe die Kampfroboter von einem ultrageheimen Geheimdienst entwendet, den ihr alle noch nicht kennt.
Die sind auch für No-Fly-Zonen freigeschaltet.
Und dann sage ich ihnen, dass eben dieser  Geheimdienst weltweit Leute ermordet, Kriege anzettelt, ein totales Überwachungsnetz aufgebaut hat und dass sie zum Beispiel vor ein paar Wochen sieben Präsidenten ermordet haben.
Und vor der Kulisse der Trümmer des NSA-Hauptquartier glauben die Leute mir das. 
Uns, sie glauben uns das.
Weil die Kampfroboter sind ja echt.“

Lasse: „Du willst das NSA-Hauptquartier platt machen?“

Sigur: „Jupp.
Das habe ich vor.“

Lasse: „Das sind 2000 Kilometer.“

Sigur: „Viereinhalb Stunden.
Wir fliegen ein paar Umwege, also werden es fünfeinhalb.
Wir fliegen unterhalb des Radars.
Es ist total bewölkt heute.
Sie werden uns immer wieder verlieren.
Und der Inkognito-Modus der Dinger ist super.
Außerdem habe ich die automatischen Abfangprogramme für F22s aktiviert.
Die sind Beta.
Ich weiß nicht ganz genau wie die arbeiten, aber die Simulation sah gut aus.“

Lasse: „Sie werden zwanzig oder dreißig F22 auf einmal schicken.
Dann reichen deine Kampfroboter nicht aus.“

Sigur: „Tim hat ein paar Leute aufgetrieben, die legen derweil falsches Spuren, "false Positives".
Unsere Kampfroboter werden scheinbar überall in den USA auftauchen.
Es wird Meldungen vom Boden aus geben.
Satelliten werden sie melden.
Wir lassen mindestens zwölf verschiedene Formationen durch Amerika fliegen.
Virtuell.
Alle mit 29 Kampfrobotern.
Ein paar fliegen nach Washington, ein paar nach New York.
Das werden sie am meisten schützen … Und so viele F22 haben sie nicht einsatzbereit.
Nicht im eigenen Land, das schon 150 Jahre keinen Krieg mehr gesehen hat.“

Lasse bekam Herzklopfen.
Er schaute auf seinen Monitor und dachte: „Wenn wir nur das Gebäude bis dahin ganz leer kriegen … Scheiße.“

Lasse: „Wann kommen die Kampfroboter in Fort Meade an?“

Sigur: „18:13 oder 18:14.
Aber das kann sich auch deutlich verschieben, je nach Luftkämpfen.“

Lasse: „Wann willst du warnen, dass die Leute das Haus verlassen?“

Sigur: „Halbe Stunde vorher.
Ich hatte gedacht, sie gar nicht zu warnen, die Saftsäcke.
Wenn du dort arbeitest, weißt du ja, was du tust.
Du arbeitest ja nicht aus Versehen bei der NSA.
Aber andererseits sind auch viele dabei, die das Spiel nicht durchschauen, die genauso auf die Medienmanipulationen reinfallen wie die meisten Menschen.“

Lasse: „Und wenn sie das Gebäude nicht räumen.“

Sigur: „Ich kann nicht sehen, ob sie geräumt haben.
Und wenn du um Bestätigung fragst, dass die Häuser leer sind, dann werden sie das für ein Verzögerungsspiel nutzen.
Du weißt ja: Geheimdienstarbeit heißt, Dinge zu verlangsamen, damit man sie kontrollieren kann.“

Lasse nickte und schluckte.
Er schüttelte den Kopf, stand auf, setzte sich wieder hin.

Sigur: „Was ist jetzt?
Wie viele Reapers willst du?
Wenn du sie hast, kann ich dich in die Multimode-Funktionen einführen.“

Lasse: „Gib mir eine Minute.“

Lasse stand auf, zog sein Headset ab und ging vor die Tür.

Roger schaute ihn an: „Sigur macht Riesenstress, nicht?“

Lasse nickte.

Roger: „Ich kann das an deinem Gesicht sehen.“

Lasse: „Er ist wahnsinnig.
Er riskiert alles.
Ich riskiere alles.
Und er hat mich am Wickel.
Ich finde keinen Grund draußen zu bleiben.“

Roger: „Aber auch keinen reinzugehen.“

Lasse: „Doch!
Doch, doch.
Shit.
Ich habe guten Grund da mitzumachen.
Sag mir eine Zahl zwischen vier und sieben.“

Roger: „Fünf“, aber Lasse hörte das schon nicht mehr.
Er hatte aus dem Augenwinkel heraus gesehen, dass alle Kampfroboterkameras nur noch Rauschen anzeigten und war ins Zimmer gestürzt.
Er griff das Headset.

Lasse: „SIGUR!
Sigur!
Was ist los?“

Sigur: „Arschlöcher!
Sie haben den Satelliten abgeschaltet.
Er ist weg.
Komplett weg.
Alle Fernsehprogramme.
Ganz aus.
Die sind blöd!
Sie können mit den Reapers jetzt auch nichts mehr machen.
Niemand kann das mehr.
Niemand kommt da je wieder ran.“

Lasse: „Was machen die Kampfroboter ohne Satellit?“

Sigur: „Sie fliegen nach Fort Meade und werden 18:13 oder 18:14 dort ankommen, wenn sie nicht vorher noch etwas zu kämpfen bekommen.
Das ist so programmiert.“

Lasse: „Sie kämpfen vollautomatisch?“

Sigur: „Yepp.“

Lasse: „Oh mein Gott.“
