== [big-number]#2021# Die Ansprache

[text-caps]#Das Bild in der Schulklasse# hatte sich verändert.
Überall lagen jetzt schwarze, etwas klobige Laptops auf den Tischen, viele Mini-Computer-Boards, Kabel, Netzteile, USB-Sticks, Schraubenzieher, ein Lötkolben.
Überall saßen kleine Gruppen um einen oder mehrere Laptops herum.
Sie tippten, diskutierten und gestikulierten.
Kevin stand mit Sophie vorne an der Tafel und gab einer Journalistin ein Interview vor einer Fernsehkamera.

Kevin ins Mikrophon eines Reporters: „Was Sie hier sehen, ist eine neue Form von Schule.“ Er zeigte in den Raum.
„Wir haben alle zusammen in den letzten drei Wochen mehr gelernt, als in den drei Jahren zuvor. Und ich meine das wirklich so.
Nicht nur technisch.
Auch menschlich.
Und zwar deswegen, weil es zum ersten Mal ernst ist, weil es mit dem realen Leben zu tun hat.
Die meisten hier haben nicht gewusst, wie einfach es ist, mit hunderttausenden von Menschen im Internet überall auf der Welt zusammen zu arbeiten.
Wir haben nicht gewusst, dass es eine ganze Kultur von Wissensaustausch und gegenseitiger Hilfe gibt.
Es macht so viel Spaß, anderen zu helfen.
Und Hilfe zu erhalten.
Und zu sehen, wie das, was man selbst macht, von anderen verwendet wird.
Wir haben nichts davon in den letzten Jahren in unserer Schule gehabt.

Wenn Sie das hier mit einer normalen Situation in irgendeinem Unterricht vergleichen, dann sehen Sie, dass wir Schüler normalerweise im Unterricht nicht voll dabei sind, eher dahinvegetieren.
Aber hier leben wir.
Alle sind hellwach und voll dabei.
Und bei uns kommen Superleute vorbei, vor allem aus dem Hackerumfeld. 
Sie erzählen uns, was sie über Computer, Programmierung, Computerverwaltung, unser Rechtssystem, unser politisches System oder was auch immer wissen.
Wir hatten hier aber auch schon Rechtsanwälte, Polizisten und Unternehmer.

Es ist eine super vertrauensvolle Atmosphäre.
Wenn jemand etwas nicht versteht, dann fragt er.
Wenn jemanden etwas nicht interessiert, dann geht er woanders hin.
Anstelle der vielen ausgedachten Prüfungen von Lehrern haben wir jetzt das reale Leben als Prüfung.
Das ist echt.
Da machen Prüfungen sogar Spaß.
Können wir so kommunizieren, dass niemand anders das mitbekommt?
Können wir unsere Rechner so sicher machen, dass sie nicht gestört werden?

Wir haben viel gelernt, zum Beispiel, wie man in zwanzig Minuten solch einen Mini-Computer hier in einen Hochsicherheitswebserver verwandelt, von dem draußen niemand weiß, wo auf der Welt er steht.
Wir haben gelernt, wie man einen Laptop ziemlich abhörsicher macht.
Und glauben Sie mir, wir hatten hier einige Angriffe.

Wenn diese Aktion hier vorbei ist, will ich auf jeden Fall genauso weitermachen mit Schule, und das wollen sicherlich die anderen hier auch.
Ich persönlich pfeife inzwischen auf das Abitur.
Das ist doch alles nur ein Fake, das ist doch alles nur ausgedacht.“

Reporter: „Aylin, Jonas und Devin haben die Gruppe verlassen.
Was sagen Sie dazu?
Gibt es weitere Schüler, die überlegen, abzubrechen?“

Kevin: „Aylins Mutter hatte einen Nervenzusammenbruch.
Sie ist alleinerziehend und hat gerade ihren Arbeitsplatz verloren, da wollte Aylin nicht hier bleiben.
Sie kommt zurück, sobald sie kann.
Jonas und Devin war der Druck zu hoch.
Unsere Gegner heißen NSA, BND, auch andere Geheimdienste.
Für die ist das hier ein unberechenbares Chaos.
Ein Flächenbrand.
Es sind inzwischen über 200 Klassen in Deutschland, die mit uns streiken.
Die unser Modell übernommen haben.
Und es kommen täglich welche dazu.
Jetzt stellen Sie sich vor, was bei den Geheimdiensten los sein wird, wenn wir es schaffen, das Bild von Marianne in der Öffentlichkeit wieder gerade zu rücken ... Wenn die meisten Menschen verstehen, dass das mit ihr alles ein Schauspiel war.“

Reporter: „Sie haben inzwischen noch andere Ziele. Sie fordern die Aufhebung der Schulpflicht und freie Lehrerwahl.“

Kevin: „Das sind keine ‚Forderungen‘.
Das ist gesunder Menschenverstand.
Brauchen wir Schulpflicht?
Schauen Sie sich um?
Braucht hier irgendein Schüler die Schulpflicht?
Soll hier irgendein Schüler auch nur eine Stunde mit einem Lehrer verbringen, der ihn nicht interessiert?
Das ist doch Quatsch.
Wir sind hier alle alt genug, um uns unsere Lehrer selbst auszuwählen, und die Lehrer sind auch alt genug, um sich die Schüler auszusuchen.
Wir lernen hier in einer Geschwindigkeit, die ist atemberaubend.
Hier zeigen sich plötzlich echte Talente.
Es ist eine super Lernatmosphäre.
Wenn ich mir vorstelle, was wir alles gemacht und gelernt hätten, wenn wir eine solche Schule die ganzen Jahre gehabt hätten ...

Das kann es in einer hierarchisch geprägten Schulform nicht geben, in der vorgegeben wird, was wir lernen sollen, wann wir das lernen sollen, von wem wir das lernen sollen, sogar wie.
Von Leuten, die ihr ganzes Leben Lehrer waren und nichts vom Leben wissen.
Das ist uralter Quatsch.
Das will hier keiner mehr.
Ich glaube, Sie finden in ganz Deutschland keine Klasse, in der fünf Schüler sind, die das dem hier vorziehen würden.“

Reporter: „Sie sagen, Sie wollen das Bild von Marianne ‚gerade rücken‘.
Man kann das aber auch durchaus als etwas Illegales sehen, wenn man in militärische Computer eindringt und dort Dokumente stiehlt.
Und wir brauchen ja Vereinbarungen in einer Demokratie, was erlaubt ist und was nicht.
Und das kann man dann nicht einfach übergehen ...“

Sophie drehte sich zu ihm.

Sophie: „Die Dokumente, die Marianne der Öffentlichkeit übergeben hat, gehören allen.
Sie betreffen uns alle.
Deswegen gehören sie uns allen.
Wir leben in einer Demokratie und ohne diese Dokumente kann ich mir keine demokratische Meinung bilden.
Wenn jemand Ihr Kind entführt, haben Sie dann ein Recht, in das Haus einzubrechen, in dem es ist, und es herauszuholen?
Klar haben Sie das!
Demokratie ist wichtiger als Geheimhaltung aus taktischen Gründen.

Reporter: Moment! Sie haben nicht das Recht, Gesetze zu brechen, um Ihr Kind zurückzuholen.

Sophie: Wenn Sie niemandem damit schaden?

Reporter: Ich glaube, Sie müssen das der Polizei sagen, und die darf dann in das Haus einbrechen.

Sophie: Dann ist das ein Fehler in unseren Gesetzen, der korrigiert werden muss.
Überlegen Sie: Da ist das Haus, Sie schaden niemandem, machen vielleicht ein Fenster kaputt und holen ihr Kind raus.
Das muss erlaubt sein.
Und wenn Gesetze die Geheimhaltung von Dokumenten erlauben, die für alle sind, dann ist das auch ein Fehler, wie ein Fehler in einem Computerprogramm.
Wir müssen sie korrigieren und neue Gesetzesversionen veröffentlichen.

Und in den Geheimdiensten gibt es offenbar so viele undemokratische und antidemokratische Aktivitäten, dass es für sie das Schlimmste wäre, was ihnen passieren kann, wenn sie ans Licht kämen.
Und deswegen versuchen sie alles, um uns zu stoppen.
Sie sind auf Geheimhaltung angewiesen.
Wenn ans Licht kommen würde, dass sie dafür gesorgt haben, dass Aylins Mutter gemobbt und entlassen wurde und sie danach noch mehr unter Druck gesetzt haben, Angst gemacht haben, so dass sie zusammengebrochen ist, dann werden unsere Zustimmungswerte noch besser.
Und wir sind schon zwischen 70% und 80% hier in Deutschland.“

Reporter: „Andere Länder sehen das anders.
In England wird Marianne in den Medien als Terroristin gesehen.“

Sophie und Kevin schauten sich an.
Kevin zuckte mit den Schultern: „Das ist England. Ich kenne die Situation dort nicht.“

Reporter: „Was sind Ihre nächsten Schritte?“

Sophie: „Wir vernetzen uns immer besser mit den anderen Klassen, inzwischen in ganz Deutschland.
Es sind 217 Klassen im Streik und viele, viele überlegen, ob sie den Schritt gehen.
Wir bekommen enorm viel Zuspruch.
Viele Schüler kommen auf unser neues, ziemlich abhörsicheres Kommunikationssystem.“

Sie lächelte.

„Ich denke, dass das inzwischen sogar Whatsapp und Facebook merken.
Insgesamt gibt es in Deutschland etwa 400000 Schulklassen.
Darauf legen wir gerade unsere Serverkapazitäten aus.
In unserem Team sind einige Jungs und Mädels aus der Topliga im Hackerumfeld.
Marianne ist auch aktiv dabei.
Sie besorgen uns alles, was wir brauchen.
Wir bekommen die beste Ausstattung, die es gibt.“

Reporter: „Wenn Sie jetzt Geheimdienste gegen sich haben, wird Ihnen dann nicht mulmig?
Haben Sie keine Angst?“

Kevin: „Klar haben wir Angst.
Jede Menge.
Aber wir haben auch Mut.
Marianne hat Mut.
Sie ist immer noch aktiv, sie verwendet nicht all ihre Kraft darauf, sich zu verstecken.
Sie hilft _uns_ tatsächlich mehr als wir ihr helfen.
Also, da können wir bei unserem Mut noch eine Schippe drauf legen.
Und dann haben wir euch als Lebensversicherung.
Wenn ihr über uns berichtet, wenn ihr uns bekannt macht, dann gehen Geheimdienste vorsichtiger mit uns.
Von dem, was ihr sendet und schreibt, hängt auch unser Leben ab.“

Reporter: „Euer Leben?“

Kevin: „Klar. Unser Leben.“

Von der anderen Ecke des Raum rief jemand: „Die amerikanische Präsidentin ist im Fernsehen!
Das ist die Ansprache zu den Geheimdiensten.“

Alle drehten sich zu dem großen Bildschirm, der am hinteren Ende der Schulklasse hing.

„Lauter. Lauter“ rief eine Schülerin.

Kevin warf Sophie und dem Reporter einen Blick zu: „Jetzt bin ich ja gespannt, was das wird.“

„Ruhe“, rief eine andere Schülerin.
Alle schauten gebannt auf den Bildschirm.

Präsidentin: „Liebe Landsleute, dies ist meine wöchentliche Ansprache zu unserer Lage, hier im Land und weltweit.
Heute will ich vor allem über ein aktuelles Thema sprechen, und das wird ein wenig anders sein als sonst.
Das liegt daran, dass man sich auch in der besten Familie einmal uneins sein kann, dass man sich sogar streiten kann.
Und ich meine jetzt nicht Republikaner und Demokraten, weil da wird traditionell viel gestritten.“
Sie lächelte.
„Nein, ich meine Einrichtungen, die das Rückgrat bilden unserer großartigen Nation: unsere global agierenden Unternehmen, unsere Geheimdienste und das politische Zentrum der Welt: unsere Regierungsorganisation.
Unsere Unternehmen führen die technische Entwicklung weltweit an.
Unsere Geheimdienste sind die besten und schlagkräftigsten, die es gibt, je gegeben hat, sie setzen ihr Leben aufs Spiel, damit wir hier in Ruhe auf unsere Art leben können.
Sie haben in den letzten Jahren großartige Arbeit geleistet.
Aber der Terrorismus hat uns in den letzten Jahrzehnten immer mehr herausgefordert.
Vieles von diesem Kampf findet inzwischen im Internet statt.
Damit das Internet für uns alle ein sicherer Ort bleibt, haben unsere Geheimdienste in den letzten Jahrzehnten ein Überwachungssystem aufgebaut, dass uns sehr früh meldet, wenn Terroranschläge vorbereitet werden, Aufstände entstehen oder Angriffe auf Amerika vorbereitet werden.

Aber wir sind in diesen Bemühungen in den letzten Jahren an einigen Stellen über das Ziel hinausgeschossen.
Die Geheimdienste haben gegen den Willen der Unternehmen, Überwachungssoftware in Programme wie den Facebook Messenger, Whatsapp, Google Plus und so weiter, eingebaut und damit die Kommunikation von Milliarden von Menschen unsicherer gemacht.
Viele Menschen haben Vertrauen in unsere Unternehmen verloren und sich von ihnen abgewendet.
Diese Maßnahmen gingen zu weit.
Aus diesem Grund möchte ich heute ein neues Programm und ein Gütesiegel vorstellen, das das Vertrauen in unsere Weltklasse-Produkte wieder herstellen soll: Security Star.“

Alle im Raum lachten spontan lauf auf, feixten gegeneinander.

Einer rief: „NSA-frei! Jetzt 100% Garantiert.“ Und lachte laut.

Präsidentin: „Jedes Produkt, das dieses Siegel trägt, ist frei von Hintertüren und absichtlich eingebauten Schwachstellen.“

Noch mehr Gelächter im Raum.

Präsidentin: „Die meisten amerikanischen Firmen, mit denen ich darüber gesprochen habe, sind dazu bereit.
Sie werden ihre Programme einer regelmäßigen, strengen staatlichen Prüfung unterziehen.
Die Geheimdienste, das kann ich hier so offen sagen, waren nicht begeistert von dem Plan, aber sie haben es letztendlich akzeptiert.
Es gibt auch für sie keine Möglichkeit mehr, auf legalem Weg die Kommunikation von solchen Programmen abzufangen und zu entschlüsseln.“

Lukas: „Dann machen sie es eben illegal ...“

Kevin: „Lukas, da ist schon etwas neu dran, was sie da sagt.
Das heißt, die Geheimgerichte wie FISA dürfen keine Erlaubnis mehr geben.
Die Firmen werden sie dann nicht mehr rein lassen.
Und Google ist stinksauer auf die Geheimdienste.“

Präsidentin: „Ich weiß, viel Vertrauen wurde verspielt.
Ich bin willens dafür zu kämpfen, dass dieses Vertrauen wieder zurückkehrt.
Deswegen werde ich in den nächsten Tagen einen Gesetzentwurf in den Kongress bringen, der alle Meldungen von technischen Sicherheitslücken, Schwachstellen, Hintertüren strafffrei stellt.
Wistleblower, die solche Sicherheitslücken melden, bekommen eine Garantie durch dieses Gesetz, dass sie dafür nicht strafrechtlich verfolgt werden.
Auch dann nicht, wenn es sich dabei um Firmengeheimnisse handelt.“

Im Klassenzimmer wurde es ruhiger.

Präsidentin: „Und ich habe heute eine Amnestieverfügung unterschrieben für alle Wistleblower von technischen Sicherheitslücken, die im Augenblick in unserem Land in Haft sind oder unter Anklage stehen.
Sie werden so bald wie möglich entlassen und haben Anspruch auf Entschädigung.“

Es war still im Raum.

„Wow“, sagte Oskar in die Stille.

Sophie: „Was ist das?
Ich traue dem Braten nicht.“

Kevin: „Sie entlassen alle … Hej!
Das ist toll.
Sie müssen es jetzt tun.
Die Präsidentin wird dafür sorgen.
Es ist die wöchentliche nationale Ansprache.
Das ist geil!
Das ist wirklich geil!
Auch wenn das nicht bedeutet, dass sie jetzt vom Wolf zum Schaf geworden sind.“

Sophie: „Aber wie können wir ihnen vertrauen?“

Oskar: „Das können wir nicht.
Aber die Situation für die Wistleblower ist besser geworden.
Ein paar Leute, die ich kenne, werden sich jetzt trauen, Schwachstellen zu melden, die sich das bisher nicht getraut haben.“ 
Er zeigte zum Fernseher.
„Das, das ist eine Katastrophe für die Geheimdienste.“

Sophie: „Was ist mit Marianne?“

Oskar: „Keine Ahnung.
Aber das ist auch gut für sie, denke ich.“

Kevin: „Das klingt ein bisschen nach internem Krieg.“

Der Reporter ging auf Sophie und Anni zu.

Reporter: „Sophie, Anni.
Dürfen wir Sie darüber für die Abendnachrichten interviewen?
Ich denke, das wird eine Meldung werden.“

Sophie: „Ja, klar.“
