== [big-number]#2023# Spaghetti Milanese

[text-caps]#Marlene und Luigi# saßen auf der Terrasse vor ihren Laptops und hörten konzentriert die letzten Worte der Präsidentin.
Sie schauten sich einen Augenblick lang in die Augen.
Dann rissen sie beide ihre Arme hoch und lachten.

Marlene: „Yeah!
Yes!
Das ist wirklich ein Hammer!
Luigi!
Der Berg hat sich bewegt!
Wir sind dran, wir sind nah dran...“

Luigi: „Oh, oh, das wird den Geheimdiensten nicht schmecken.
Aber es war unausweichlich.
Sie legen sich mit den Top-Firmen an, die braucht Amerika mindestens so sehr wie die Geheimdienste.
Und die Firmen sind durch unsere Jungs und Mädels inzwischen so richtig wund.
Das hat Julian schon Anfang der 2000er Jahre vorausgesehen: Whistleblowing schafft den Durchbruch.“

Marlene: „Ja, jetzt ist etwas möglich.
Jetzt müssen wir dran bleiben.
Das, was die Präsidentin gesagt hat, wird für Verwirrung sorgen.
Totales Chaos bei den Geheimdiensten.
Sie werden das nicht einfach hinnehmen.
Da werden wir unsere Chancen bekommen.“

Luigi: „Auf jeden Fall wird es jetzt erst einmal einen Haufen neue Schwachstellenmeldungen geben.
Wir kriegen vielleicht richtige, regelmäßige Schwachstellenupdates, von internen Leuten bei Firmen.
Wie geil ...“

Marlene: „Ja, das ist geil!
Die großen Firmen, die Regierungen, sie sind so abhängig von den kleinen Leuten.
Sie brauchen uns als Konsumenten, als Arbeiter, als Komplizen.
Ohne uns geht es nicht.
Das ist das Diktat der Massen.
Das hat Marwin immer gesagt.
So deutlich habe ich das noch nie öffentlich gesehen.
So geil!“

Sie legte ihr Gesicht in ihre Hände.
„Geil … geil … Marwin … Wenn er das nur mitbekommt. – – – Scheiße.
Vielleicht bekommt er das gar nicht mit.“

Sie schloss die Augen.
Nach einer Weile stand sie auf und ging Richtung Geländer.

Luigi: „Marlene!!“

Marlene: “Gut, gut.
Ich gehe nicht bis vorne.“
Sie setzte sich im Schneidersitz auf den Boden.
„Wo ist er jetzt?
Ich will jetzt endlich wissen, wo er ist.“

Luigi: „Du bist vor drei Tagen zum letzten Mal alle deine Kontakte durchgegangen.
Er ist in Amerika, irgendwo in Amerika.
Sehr wahrscheinlich in einem CIA-Gefängis.
Es gibt nichts Neues dazu.
Aber probier es wieder.“

Marlene: „Irgendwann finde ich eine Spur.“
Sie stand auf, setzte sich auf ihren Sessel, nahm ihren Laptop und fing an zu tippen.

Luigi: „Ich mache Spaghetti Milanese.
Mit Parmigiano-Reggiano und einem Hauch von Pfeffer.
Dazu einen Valpolicella rossa.“

Marlene reagierte nicht.
Sie tippte und schaute gebannt auf ihren Bildschirm.
Luigi verschwand in die Wohnung.

Marlene sagte nach einer Weile vor sich hin: „Keinen Wein für mich.“
