== [big-number]#2021# Die kleine Giftnudel

[text-caps]#Vor dem Haupteingang# der BND-Zentrale in Berlin hielt eine Fahrzeugkolonne aus einer gepanzerten Maybach- und mehreren Mercedes-Limousinen mit zwei Polizeiwagen an der Spitze und zwei am Ende.
Dort wartete bereits der Präsident des BND mit einigen Beamten.
Ein Beamter riss die hintere Türe der Maybach-Limousine auf.
Der Direktor der NSA stieg mit grimmigem Gesicht aus, schaute sich um und lief dann auf die wartende Gruppe zu.
Er gab dem Präsidenten die Hand.

Präsident: „Willkommen!
Es ist mir eine Ehre.“

Direktor kurz: „Gu...morgn.“

Sie gingen hinein zum Aufzug, ohne ein Wort zu sprechen.
Etwa sieben oder acht Beamte folgten ihnen.
Im 13. Stock gab es einen großen, fensterlosen Besprechungsraum mit bequemen Sesseln um einen wuchtigen Tisch herum.
An den Wänden konnte man einen zusätzlichen Abhörschutz erkennen.
Die Gruppe versammelte sich um den Tisch.
Direktor und Präsident nahmen an gegenüberliegenden Seiten Platz.
Die Türe wurde geschlossen.

Der Direktor, über den Tisch hinweg: „Ich habe keine Ahnung, was sie da geritten hat.
Es war gegen unsere Abmachung.
Ich habe deutlich, deutlich von einer Amnestie gewarnt.
Das habe ich noch nicht erlebt, dass sich ein Präsident über einen so klaren Hinweis von uns hinweg setzt.
Heute morgen gab es schon wieder zwei neue Leaks.
Möglicherweise schon eine erste Reaktion auf die Ansprache.

Die neuen Whistleblowing-Gesetze sind eine komplette Katastrophe.
Die Unternehmen tanzen uns auf der Nase herum.
Wir kriegen hier Knüppel zwischen die Beine, von unserer eigenen Verwaltung.
Was ist hier die Sicherheitsstufe im Raum?“

Präsident: „Top Secret.“

Direktor: „Machen Sie Nato Alliance.“

Präsident: „Ok. Nato Alliance.“

Drei Beamte standen auf und verließen den Raum.

Direktor: „Das ist ein ernstes Problem.
Wir müssen das offensiv angehen.
Ich hatte bis zuletzt geglaubt, dass es nur eine PR-Offensive ist, aber sie meint es anscheinend ernst und sie hat einige Leute auf ihrer Seite.
Es kann nicht sein, dass wir uns hier herumschubsen lassen und nichts dazu sagen.
Wir sind der größte und modernste Geheimdienst der Welt.
Wie sollen wir unsere Arbeit machen, wenn wir nicht mehr direkt auf die Computer zugreifen können, die wir überwachen wollen?
Im Jahr 2021?
Am Ende müssen wir wieder händisch an jedes einzelne Gerät, um ein Implantat unterzubringen.
Observieren, einbrechen, Spuren verwischen, die ganze Scheiße aus dem 20. Jahrhundert.
Das ist nicht akzeptabel.“

Präsident: „Ja. Am Ende könnten alle Computer den Level erreichen, den Hacker-Computer heute haben.
Dann brauchen die am Ende gar keine präparierten X60 oder X200 mehr, sondern kaufen sich einfach einen neuen Computer von irgendeinem Hersteller und wir kommen da trotzdem nicht mehr rein.
Dann kommunizieren sie über die normale WhatsApp-Verschlüsselung, und wir können das nicht lesen.
1,8 Milliarden Konten, alle schwarz.
Wahnsinn.“

Direktor schaute in die Runde: „Ja, das ist Wahnsinn. Vorschläge?“

Die Runde schwieg.

Der Direktor schaute sich um: „Das gibt es doch nicht.
_Wir_ sind sprachlos?
Kein Vorschlag?
Wistleblower gehen straffrei aus.
Die Unternehmen zeigen uns grinsend den Mittelfinger.
Was machen wir?“

Heinz: „Wenn der Fernzugriff auf die Mikrophon- und Kamerafunktionen in Smartphones als Hintertür eingestuft wird, dann sind wir bald blind und taub.“

Ein Beamter: „Wir könnten unsere offensiven Hackaktivitäten ausweiten.“

Präsident: „Ohne unsere Schwachstellen?
Das wirft uns zwei Jahrzehnte zurück.“

Direktor laut: „Wie kriegen wir die Schwachstellen wieder in die Computerprogramme und Betriebsysteme hinein?
Ohne dass das jemand merkt.
Das ist die Frage.
Ich will wissen, wie wir Wistleblower in Unternehmen ausschalten können!
Entführen, einschüchtern, mir egal.
Was auch immer nötig ist.
Ich will den alten Zustand zurück.
Wir waren auf einem guten Weg.
Den Weg will ich weiter gehen!“

Die Runde schwieg.

Der Präsident klatschte zweimal in die Hände: „Kommt Leute, wir brauchen Lösungen.
Hier treffen sich zwei der schlagkräftigsten Geheimdienste der Welt.
Was kriegen wir auf die Beine?“

Ein Beamter: „Wir könnten zwei, drei Wistleblower medienwirksam verschwinden lassen.
Selbstmord, Flugzeugabsturz.“

Ein anderer: „Mehr Erfolgsmeldungen: Gefundene Terroristen über unsere Datenbanken.
Angst machen vor weiteren Anschlägen.“

Ein anderer: „Einen Firmenchef ausschalten, das wie einen Unfall aussehen lassen, und vorher ein paar Nachrichten, dass er sich gegen die NSA stellt.“

Direktor: „Angst, Angst ist gut. Wir brauchen mehr Angst.“

Ein anderer: „Wir könnten unsere eigenen Projekte mehr pushen und andere auf den Weg bringen, neue Messenger, Mail, Social Media, als Honey pots.
Da können wir die Hintertüren selbst kontrollieren.“

Ein anderer: „Verstärkte Angriffe auf die zentrale Infrastruktur: Tor, OTR-Clients, GPG etc.“

Präsident und Direktor schüttelten die Köpfe.

Heinz: „Was ist eigentlich mit Wistleblowern bei uns?
NSA, BND.
Gehen die auch straffrei aus nach der neuen Regelung?“

Präsident: „In den USA jetzt schon. Bei uns nicht.“

Direktor aufbrausend: „Denen jage ich eigenhändig eine Kugel zwischen die Augen.
Wenn jetzt irgendjemand bei uns auf die Idee kommt, Dinge an die Öffentlichkeit zu bringen, dann schicke ich ihm einen Todes-Squad hinterher.
Der nächste Snowden überlebt keine drei Tage.
Darauf können Sie einen lassen.
Notfalls kümmere mich dann persönlich ums Aufräumen.
Wenn ich die kleine Giftnudel aus dem weißen Haus das nächste Mal treffe, dann knöpfe ich sie mir vor.
Wir haben hier Verantwortung für die großartigste Nation der Welt, und für unsere Freunde auch.
Wir können nicht hinnehmen, dass sie uns in solcher Weise kastriert.

Wir haben, verdammt noch mal, in den letzten Jahren das beste Nachrichtensystem aufgebaut, dass die Welt je gekannt hat.
Wir gemeinsam.
Wir waren so knapp davor, dass wir in jeden Rechner der Welt live hineinschauen können, dass wir die klitzekleinsten Veränderungen in politischen Bewegungen weltweit vom Bildschirmen in Fort Meade aus bemerken, dass wir Terroristen überall hin und in jeder Sekunde ihres Lebens verfolgen können.
Und wir hatten die Bevölkerung dabei relativ ruhig gehalten, auch in Europa.
Relativ ruhig.
Protest: Ja.
Reale Konsequenzen: Nein!
Wir waren so knapp davor, das zu erreichen, was wir uns vorgenommen hatten.
Und dann diese _Scheiße_ jetzt.
Ich pfeife auf alles, was sie in dieser Ansprache gesagt hat.
Wir machen mit Nachdruck so weiter wie bisher.
Und wenn wir jetzt mehr Gegenwind bei den Firmen bekommen, gut!
Dann machen wir eben auch mehr Wind.
Das können wir.
Das können wir auch bei Firmenchefs von amerikanischen Firmen.
Die glauben, sie hätten Immunität, unter der schützenden Hand der Präsidentin.
Fuck it.
Die werden schon sehen, was es heißt, sich mit der NSA anzulegen.“
Er ballte eine Faust.

Direktor: „Ich habe kein Problem damit, auch mal einen von denen zu verhaften ... oder vielleicht ...“ Er stockte. 

Im Raum war Erstaunen zu spüren.
Niemand sagte etwas.
Nach einer Weile meldete sich Heinz.

Heinz: „Was ist mit Marianne Lasser?“

Der Direktor schloss die Augen und atmete durch.
Sein Gesicht lief leicht rot an.

Direktor laut: „Die kleine Schlampe knöpfe ich mir jetzt selbst vor.
Ein 18-jähriges Mädchen ohne Schulabschluss.
Sie hat das ins Rollen gebracht und sie läuft immer noch frei herum.
Und die CIA-Schlappnasen finden sie nicht.
Ich höre nur Nord-Italien, Kroatien, Montenegro.
Wir sind auf Länderebene.
Ich will Hausnummern.
Ich werde sie heute Nachmittag auf die Todesliste setzen, weit oben.
Das ist überfällig.
Da stehen weit weniger gefährliche Leute drauf.
Und es ist mir egal, was das für Wirbel gibt.
Wenn es getan ist, wird sich die Präsidentin bekennen müssen: Steht sie auf der Seite der Terroristen oder auf unserer Seite?“

Heinz nickte bemüht verständnisvoll.
