== [big-number]#2064# WikiLeaks TV

[text-caps]#Eine Gruppe von Journalisten# saß in einem der Besprechungsräume der CNN-Redaktion um einen Tisch herum.
Sie schauten zusammen auf einen riesigen Computer-Monitor.

Ein Journalist stürzte herein: „Schnell! Schnell.
Auf WikiLeaks-TV, es geht los!“

Ein zweiter Journalist drückte auf den Knopf einer Fernsteuerung: „Scheiße, weißt du schon, was es ist?
Ich bekomme ständig Anrufe.“

Erster Journalist: „Das muss ein super heißes Ding sein!
Das wird uns die nächsten Tage, vielleicht Wochen unter Strom halten.
Ich bekomme Meldungen rein, da stellen sich dir die Nackenhaare hoch.
Das Darknet ist in voller Aufregung.
Ich sage euch.“

Dritter Journalist: „Alle großen Regierungsgebäude an der Ostküste sind evakuiert.
Trotzdem kriegen wir keine offizielle Auskunft was es ist.“ Er zeigte auf den Monitor. “Was ist das jetzt?“

WikiLeaks-TV zeigte in Kacheln Live-Bilder von neun verschiedenen Orten jeweils mit eingeblendeter Ortszeit.
Auf einem war die Golden Gate-Brücke zu sehen, auf dem nächsten das MGM-Hotel in Las Vegas, auf einem das Weiße Haus, der Freedom Tower in New York, Sears Tower in Chicago, das Pentagon.
Unten rechts das Bild des NSA-Hauptquartiers.
Die Zeit dort 18:07 Uhr.

Erster Journalist: „Anschlagziele.
Das sind potentielle Anschlagziele.“

Dritter Journalist: „Ajjj. Shiiiit... Ein Live-Anschlag.“

Erster Journalist: „Und der Senderausfall heute soll auch damit zu tun haben.
Sie haben wohl vorher einen Satelliten gehackt.“

Dritter Journalist leise: „Wow.“

Erster Journalist: „Seht ihr die zwei F22 im Hintergrund, da hinter dem Weißen Haus, und hier eine hinter dem Pentagon, rechts neben dem Freedom Tower.
Die sind überall.
Die kreisen.
Ich glaube, sie haben alle Flieger draußen, die sie haben.“

Dritter Journalist: „Haben wir Leute vor Ort?“

Erster Journalist: „Vier Teams sind mit Kameras unterwegs, ein Haufen weitere ohne.“

Plötzlich vergrößerte sich das Bild des NSA-Hauptquartiers und nahm nach zwei, drei Sekunden den ganzen Bildschirm ein.

„Was ist jetzt?“ rief der dritte Journalist.
Alle rückten näher zum Bildschirm.

Erster Journalist: „Bring das ins Hauptprogramm.
Sofort, ins Hauptprgramm.
Es geht los.
Das wollen wir live mitbekommen.
Untertitel hier zu mir.
Schnell, schreib: NSA-Hauptquartier.
Terroranschlag steht möglicherweise unmittelbar bevor.
Zentrale Gebäude sind landesweit geräumt.
Hast du?“

Die Kamera schwenkte vom NSA-Gebäude weg auf einige schwarze Punkte am Horizont.

Zweiter Journalist: „Was ist das?
Flugkörper?
Flugkörper!
Oh, oh, oh.
Wo ist Tom?
Tom!
Tom, was ist das?“

Tom: „Schwer zu sagen.
Vielleicht … ja … vielleicht Reapers.
Auf jeden Fall bewaffnete Kampfroboter ...
Ja, das sind Reaper MQ-11s.
Shit!
Die sind neu.
Die können Hölle machen.“

Dritter Journalist: „Wie viele sind das?“
Er zählte.
„Vier, fünf, sechs, sieben.“

Zweiter Journalist: „15.
es sind 15.
Was haben die vor?“

Erster Journalist: „Was die vorhaben?
Die greifen das NSA-Hauptquartier an.“

Zweiter Journalist: „Das geht gar nicht.
Die können dort nicht fliegen.
Das ist eine No-Fly-Zone für Kampfroboter.
Alle Kampfroboter sind so programmiert, dass sie nicht in No-Fly-Zonen hinein können.“

Erster Journalist: „Vielleicht wissen die Kampfroboter nicht, dass sie da nicht fliegen können.
Sie tun es einfach trotzdem ...
Scheiße sind die schnell.“
Kleine Blitze zuckten an einigen Kampfrobotern.
„Was ist das?
Oh, nein!
Shit.
Sie feuern auf das Hauptgebäude.“

Zweiter Journalist: „Woah, was sind das für Explosionen?
Das ist ja verrückt.
Das hat die ganze obere Ecke weggesprengt.
Oh mein Gott.
Die legen das Gebäude flach.“

Dritter Journalist: „Sie kreisen.
Nächster Treffer.
Das Gebäude stürzt gleich ein.
Hoffentlich ist da niemand mehr drin.“

Zweiter Journalist: „Aber wer ist das?
Wer macht so etwas?“

Dritter Journalist: „Voller Wahnsinn!
Die ganze rechte Seite stürzt ein!
Fuck!“

Erster Journalist: „Wer geht auf Sendung?
Ich muss hier bleiben, es kommen gleich weitere Informationen.“

Zweiter Journalist: „Bin unterwegs.
Oh, shit!
Was steht da am unteren Bildrand?


****
....
Mehr Informationen in zehn Minuten.
....
****

Das wird ein Bekennerschreiben.
Das ist orchestriert.
WikiLeaks ist da mit an Bord.
Scheiße, was sage ich gleich?
Was ist die Message?
Amerika wird angegriffen?“

Erster Journalist: „Das hatten wir schon.
Nimm 'Terroristen attackieren unser Nervenzentrum'.“

Zweiter Journalist: „Und WikiLeaks ist eine terroristische Vereinigung!“

Erster Journalist: „Nein, 'WikiLeaks ist das Sprachrohr der Terroristen'.
Das sieht man doch klar jetzt.
Nimm das als erste Message, bis wir mehr wissen.
Da werden sich hoffentlich andere dranhängen.
Sonst wird das ein heilloses Chaos in den Medien.“