== [big-number]#2064# Sigur

[text-caps]#Sigur saß in# einem großen, bequemen Sessel im Bunker vor fünf Monitoren in unterschiedlicher Größe.
Auf einem war WikiLeaks TV zu sehen, auf den anderen verschiedene Nachrichten-Sender, eine ausgeschaltete Kampfroboterkontrollstation, viele Terminal-Fenster.
Tim stand hinter ihm mit verschränkten Armen.

Tim nickte: „Guter Text!
Das wird wirken.
Noch 20 Sekunden.
Schießt WikiLeaks das gleich auf den Schirm?
Oder schauen die sich das vorher noch an?“

Sigur schaute kurz nach hinten: „Ich habe direkten Schreibzugriff.
Der Schirm gehört mir.
Ich kann das quasi direkt bei CNN einblenden.
Es wird ein Lauftext, schön langsam zum Mitlesen.
Ein bisschen langsamer als nötig, damit die Leute nebenbei noch Twittern können.
Noch 10 Sekunden.“

Beide schauten gebannt auf die Monitore.

Tim: „5“

Sigur drückte die Enter-Taste: „Und los!“

BLENDE zur CNN-Redaktion /// Auf dem WikiLeaks- und dem CNN-Bildschirm erschien über dem völlig zerstörten, qualmenden NSA-Hauptgebäude eine Guy-Fawkes-Maske und darunter begann ein Text, der sich langsam nach oben schob:

****
....

YES, WE CAN!


Wer immer geglaubt hat, dass die Hackingpower von Anonymous
zurückgegangen ist, sollte heute genau hinschauen. Heute 
haben wir das Zentrum der weltweiten Überwachung mit ihren
eigenen Waffen angegriffen und zerstört. Dazu wollen wir
zwei Fragen beantworten: Wie haben wir das gemacht, und warum.


Mit fliegenden Kampfrobotern wurden in den letzten 5 Jahren
weltweit mindestens 782000 Menschen ermordet. Es ist das 
Nr.1-Unterdrückungsmittel, mit dem eine weltweite, brutale
Angst-Herrschaft aufgebaut werden soll.


Wir lehnen ein solches Vorgehen ab.


Aus diesem Grund haben wir uns entschlossen mit den Waffen
der Unterdrücker ein Zeichen zu setzen. Wir haben Kampfroboter
entwendet, neueste Modelle, experimentielle Kampfroboter, die
zum Beispiel völlig selbstständig F22 Kampfflugzeuge zerstören
können. Kampfroboter, die, wie Sie sehen, in No-Fly-Zonen fliegen
können.


Das sind besondere Kampfroboter. Sie könnten auch über Washington
oder New York fliegen, über London oder Paris, über Tokio,
Canberra und Berlin. Und sie haben eine spezielle Bewaffnung
mit der 15-fachen Sprengkraft herkömmlicher Raketen.


Es sind keine Kampfroboter der CIA, keine Kampfroboter der 
amerikanischen Luftwaffe, sie sind Kampfroboter eines derzeit
noch unbekannten Geheimdienstes mit dem Namen L B I.


Das LBI ist überall, es operiert weltweit. Es hat kein Haupt-
quartier. Seine Mitglieder arbeiten alle mit Zweit-Identitäten:
in Regierungen, in Unternehmen, in Armeen, in anderen Geheimdiensten,
in Scheinfirmen.
....
****

Erster Journalist vor dem CNN-Monitor: „Jetzt kommen die kruden Verschwörungstheorien.“

Zweiter Journalist: „Schalten wir das ab?“

Erster Journalist: „Nein.
Es läuft eh bei WikiLeaks.
Dann kann es auch bei uns laufen.“

****
....
Sie haben die Aufgabe, für Gleichgewicht zu sorgen, für das
Gleichgewicht von verfeindeten Gruppen: in Ländern, in Unternehmen,
Armeen, Geheimdiensten. Divide et impera ist ihre Hauptdevise. Tren-
ne Menschen voneinander, verfeinde sie gegenseitig und achte darauf,
dass es zwischen ihnen einen dauernden Krieg gibt, ein tödliches 
Gleichgewicht, einen Regenbogenkrieg. Wie der Regenbogen scheinbar
immer gleich am Himmel steht, obwohl Millionen von Regentropfen
fallen, so fallen die Menschen in den Ländern und der Krieg
bleibt. Ein Gleichgewicht des Todes.


In Khandahar starben vor vier Monaten 122 Menschen, darunter sieben
Staatspräsidenten. Es war vom LBI geplant als Scheinangriff von
russischen Kampfrobotern, die dann von amerikanischen abgewehrt
werden sollten, von dem berühmten Fünfstern. Das sollte Amerika als
Schutzmacht in der Region stärken. Aber der Fünfstern kam nicht. Er
wurde zerstört, von Kampfrobotern, die von uns gesteuert wurden. Und
so nahm das Verhängnis seinen Lauf. Niemand war da, um die vom
Mossad, dem israelischen Geheimdienst, kontrollierten Kampfroboter
aufzuhalten, sie feuerten ihre Raketen ab.


WikiLeaks.org veröffentlicht, während Sie das hier lesen, die
gesamten Logdateien des Angriffs.


Im Laufe unserer Schlacht mit dem LBI sind wir auch an ihre
Bitcoin-Schätze gelangt: 2,7 Millionen Bitcoins im Wert von 32,4
Milliarden US$.


Zehn Prozent davon haben wir an die Open-Source-Gemeinde verteilt,
den Rest wollen wir zu gleichen Teilen unter den Ländern aufteilen,
deren Präsidenten in Khandahar getötet wurden. Als Wiedergutmachungs-
geld. Die Transaktion findet ebenfalls in diesen Minuten statt.


Anonymous.
....
****

Sigur sprang auf: „Geil. Wir haben es getan!“
Er klatsche sich mit Tim ab und rief in sein Headset: „Lasse, Lasse!
Bist du da?“

Lasse mit Headset vor der Berghütte: „Ja!“

Sigur: „Hast du die Bitcoins verteilt?“

Lasse: „Ja, alles weg.
Ich hoffe, sie sind jetzt eine Zeit lang verwirrt, sodass wir es schaffen, noch einen Moment zu überleben.
Ansonsten: Gratulation.
Ist gut gelaufen.
Es sind noch keine Toten gemeldet worden und die Logfiles und die Bitcoins sollten genug sein, dass die Welt die Geschichte glaubt.
Das LBI im Mossad hat Raketen auf arabische Präsidenten gesteuert.
Das ist schon ein Ding.
Es gibt für einige gerade einiges zu verdauen.
Ich will jetzt nicht beim LBI arbeiten.“

Sigur: „Ganz besonders nicht, wenn ich gleichzeitig beim Mossad bin.
Ich weiß nicht, wie gut es denen gefällt, dass sie einen Geheimdienst im Geheimdienst haben.“

Lasse: „Politische Verwicklungen.
Die Länder der sieben toten Präsidenten werden sich wohl bald treffen und dann kommt wohl der Mittel-Ost-Krieg.
Auch Scheiße, oder?“

Sigur stöhnte: „Richtig Scheiße.
Die lernen das auch nie.
Die werden jetzt einfach so aufeinander hauen.
Weil es nicht anders geht.
Das ist einfach nur Rache.
Wie kleine Kinder.
Da kannst du nichts machen.
Die sind wie blind.
Und am Ende zünden sie die Atombombe … aus Selbstverteidigung.
Die sind so blöd.
Ich könnte schreien.“

Lasse: „Wir sind ja nicht ganz unschuldig dabei, dass das jetzt passiert, oder?“

Sigur: „Scheiße, Lasse!
Ich bin nicht derjenige, der jetzt den Krieg anfängt.
Wenn es nach mir ginge, könnte man das LBI einfach abschalten, das NSA-Hauptquartier in eine Gedenkstätte verwandeln und die CIA in einen Abenteuerspielplatz für Hacker: ein Riesen-Hackspace, mit dem Original-Equipment.
Ich meine das ernst.
Das wäre geil.
Dann würde ich für ein paar Jahre nach Langley ziehen.
Und dann müsste man noch alle Atomraketen entwaffnen, Sprengkopf weg und dann damit ein Riesenfeuerwerk machen, sie in der Luft aufeinander schicken.
Oder mit Patriot-Raketen draufschießen.
Tontaubenschießen für Profis.
Aber was werden sie machen?
Aus einer ganzen Stadt werden sie einen großen Krater machen.
110 Meter tief.
Sie haben die Bombe absichtlich am Boden erst gezündet, damit sie die Bilder von dem Krater kriegen.
Ein paar hunderttausend Menschen kreisten danach in einer Staubwolke ein paar Wochen lang um die Erde.“
Er deutete an, sich zu übergeben.

Lasse: „Ich mache mich mit Roger jetzt auf den Weg.
Wir machen hier noch sauber und dann fahren wir zum Treffpunkt.“

Sigur: „Ok.
Wir sehen uns dort.
Vielleicht.
Viel Glück!“

Lasse: „Dir auch!“
