== [big-number]#2021# Pressekonferenz

[text-caps]#Das Klassenzimmer war# mit Stühlreihen vollgestellt.
Vor dem Pult standen drei Tische mit Stühlen dahinter und jeweils einer Namenskarte.
Kevin und Sophie saßen nebeneinander am mittleren Tisch.
Zwei Kamerateams positionieren sich im Raum.
Lukas arbeitete mit einem anderen Schüler an einem Computer.
Anni kontrollierte mit einer weiteren Schülerin am Eingang Presseausweise.
Der Raum füllte sich langsam.

Ein Journalist rief von der Mitte des Zimmers: „Kevin!
Was habt ihr heute Neues?“

Kevin: „Einen kleinen Moment noch, Christoph.
Es gibt wirklich etwas Neues.
Willst du nicht einen besseren Platz hier vorne?
Es lohnt sich.
Und mach schon mal Twitter auf ...“
Er lächelte ihm zu und dreht sich dann zu Lukas: „Seid ihr so weit?“

Lukas: „Gleich. Läuft fast alles.“

Eine Journalistin rief aus der hinteren Reihe: „Wie viele Klassen streiken jetzt?“

Kevin: „Gleich, gleich.
Es ist alles hier auf dem Zettel.“

Anni rief von der Türe aus: „1220.“

Die Journalistin rief: „Wow!“ und tippte etwas in ihr iPad.

Oskar betrat den Raum und schaute sich um.
Dann ging er zu Kevin legte ihm einen USB-Stick auf den Tisch und sagte: „Das Transskript.
Der Stick ist sauber.
Den kannst du direkt einstecken.“ Kevin stand auf und brachte den Stick zu Lukas.
Der nickte.

Lukas: „Ok, dann sind wir fertig.
Ich lade das noch hoch und dann können wir loslegen.“

Kevin stellt sich vor seinen Tisch.
Er schaute in den Raum.
Er war inzwischen gepackt voll.
Einige Journalisten mussten stehen.

Kevin: „So, ich glaube, wir können anfangen ...“ Er räusperte sich.
„Willkommen!
Der Ablauf für heute ist, dass wir zunächst eine ganz neue Sache für Sie haben, dann etwas zu dem Streiknetzwerk sagen und danach können Sie Fragen stellen.
Hat jemand kein Internet?
– Gut. Ok.“ Er schaute auf einen kleinen Monitor neben ihm.
„Wow, wir haben über 600.000 Internet-Zuschauer.
Na dann.
Punkt eins.
Lukas!“

Der Beamer ging an und es erschien das Gesicht des Direktors der NSA.

Kevin: „Den Herren kennen Sie, nicht?“ Ein leises Lachen ging durch den Raum.

Kevin: „Ok.
Folgendes hat er vor einer Woche im Kongress gesagt.
Der so genannte Cyber-Terrorismus-Bericht.“

Lukas drückte eine Taste.

Stimme des Direktors: „Wir müssen unsere Anstrengungen verstärken.
In der Folge der großen Attacke im letzten Jahr haben wir einen radikalen Anstieg von Angriffen auf unsere Infrastruktur verzeichnet.
Das widerlegt in eklatanter Weise die Behauptung der Cyber-Terroristen, dass das Veröffentlichen von Schwachstellen zu mehr Sicherheit im Internet führt.
Das Gegenteil ist der Fall.
Hunderttausende, vielleicht Millionen von Kriminellen haben die Veröffentlichungen genutzt, um in die Privatsphäre von Menschen einzudringen, sie zu betrügen, zu erpressen und ihre Daten zu zerstören.
Und Terroristen kommunizieren inzwischen frei, wo auch immer sie kommunizieren wollen.
Ohne, dass wir eingreifen können.“

Lukas drückte eine Taste.

Kevin: „Soweit der NSA-Chef vor zwei Wochen.
Ich will den Inhalt hier nicht kommentieren.
Darum geht es uns heute nicht.
Es geht uns heute um seine Stimme.
Wie er spricht, wie er klingt.
Denn es gibt noch eine zweite Aufzeichnung, die wir Ihnen vorspielen wollen.
Und die wurde vor fünf Tagen gemacht, hier in Berlin,
kurz nachdem die Präsidentin der Vereinigten Staaten die Amnestie für Wistleblower verkündet hatte.
Das Gespräch war übrigens hier in der Chausseestraße.“

Lukas drückte eine Taste.

Stimme des Direktors: „Wenn ich die kleine Giftnudel aus dem weißen Haus das nächste Mal treffe, dann knöpfe ich sie mir vor.
Wir haben hier Verantwortung für die großartigste Nation der Welt, und für unsere Freunde auch.
Wir können nicht hinnehmen, dass sie uns in solcher Weise kastriert.

Wir haben, verdammt noch mal, in den letzten Jahren das beste Nachrichtensystem aufgebaut, dass die Welt je gekannt hat.
Wir gemeinsam.
Wir waren so knapp davor, dass wir in jeden Rechner der Welt live hineinschauen können, dass wir die klitzekleinsten Veränderungen in politischen Bewegungen weltweit vom Bildschirmen in Fort Meade aus bemerken, dass wir Terroristen überall hin und in jeder Sekunde ihres Lebens verfolgen können.
Und wir hatten die Bevölkerung dabei relativ ruhig gehalten, auch in Europa.
Relativ ruhig.
Protest: Ja.
Reale Konsequenzen: Nein!
Wir waren so knapp davor, das zu erreichen, was wir uns vorgenommen hatten.
Und dann diese _Scheiße_ jetzt.
Ich pfeife auf alles, was sie in dieser Ansprache gesagt hat.“

Kevin: „Die kleine Giftnudel, die er hier meint, ist die Präsidentin der Vereinigten Staaten.
Seine oberste Chefin.
Und er pfeift auf das, was sie sagt.
Er pfeift damit auch auf das Gesetzgebung der USA, auf das Rechtssystem, auf das politische System, er zeigt Amerika den Mittelfinger.“

Raunen und Gespräche im Raum.

Kevin hob die Arme: „Es geht noch weiter.
Bedeutet das überhaupt etwas für ihn, was seit gestern Realität ist?“

Lukas drückte eine Taste.

Stimme des Direktors: „Wir machen mit Nachdruck so weiter wie bisher.
Und wenn wir jetzt mehr Gegenwind bei den Firmen bekommen, gut!
Dann machen wir eben auch mehr Wind.
Das können wir.
Das können wir auch bei Firmenchefs von amerikanischen Firmen.
Die glauben, sie hätten Immunität, unter der schützenden Hand der Präsidentin.
Fuck it.
Die werden schon sehen, was es heißt, sich mit der NSA anzulegen.
Ich habe kein Problem damit, auch mal einen von denen zu verhaften.“

Kevin: „Das geht in Richtung Google, Apple, Amazon, Microsoft ...
Das ist eine offene Drohung.
Ich bin gespannt, wie die darauf reagieren werden.“

Lauter werdendes Gemurmel.

Kevin machte eine Handbewegung.
Das Gemurmel endete.

Kevin: „One more thing.
Eins haben wir noch.“ Er machte eine Pause und schaute in den Raum.
„Und das liegt uns ganz besonders am Herzen.
Der Direktor spricht über Marianne.“

Lukas drückte wieder.

Stimme des Direktors: „Die kleine Schlampe knöpfe ich mir jetzt selbst vor.
Ein 18-jähriges Mädchen ohne Schulabschluss.
Sie hat das ins Rollen gebracht und sie läuft immer noch frei herum.
Und die CIA-Schlappnasen finden sie nicht.
Ich höre nur Nord-Italien, Kroatien, Montenegro.
Wir sind auf Länderebene.
Ich will Hausnummern.
Ich werde sie heute Nachmittag auf die Todesliste setzen, weit oben.
Das ist überfällig.
Da stehen weit weniger gefährliche Leute drauf.
Und es ist mir egal, was das für Wirbel gibt.
Wenn es getan ist, wird sich die Präsidentin bekennen müssen: Steht sie auf der Seite der Terroristen oder auf unserer Seite?“

Kevin: „Das ist Anstiftung zum Mord.
Auf deutschem Boden.
Und dazu noch ein Staatskomplott im eigenen Land.“ Er schaute ernst ins Publikum.
„Ich erwarte jetzt, und ich meine das ernst, eine Untersuchung und dann eine Anklage der Bundesstaatsanwaltschaft gegen den NSA-Direktor.
Marianne ist eine deutsche Staatsbürgerin.
Der Direktor muss verhaftet werden, wenn er das nächste Mal deutschen Boden betritt.“

Lukas: „Der Mitschnitt des gesamten Gesprächs ist bei uns auf der Webseite und auch ein Transskript davon.
Es ist etwa dreimal so lang wie die Ausschnitte, die Sie gehört haben.“

Reporter: „Wo habt ihr das her?“

Kevin: „Über die Quelle können wir zu diesem Zeitpunkt leider nichts sagen.
Nur soviel: Sie arbeitet beim BND und steht schon mit der Courage Foundation in Kontakt.
Ihre rechtliche Verteidigung wird vorbereitet.
Ich weiß auch nicht, wo sie jetzt gerade ist.“

Sophie stand auf.
Sie schaute ins Publikum und wartete eine kurze Zeit.
Dann sagte sie in ruhigem, ernsten Ton: „Eigentlich, eigentlich hoffe ich, dass wir das gar nicht mehr brauchen.
Sie soll sich nicht verteidigen müssen.
Sie hat viel gewagt.
Es ist ein persönliches Statement, dass sie da geleakt hat, aber es geht uns alle an.
Es deckt Verbrechen auf.
Es ist ein Zeichnen eines korrupten Justizsystems, wenn jemand Morddrohungen aussprechen kann und damit davonkommt, und jemand, der das an die Öffentlichkeit bringt, verfolgt wird.
Aber es gibt wahrscheinlich immer noch solche korrupten Staatsanwälte, die politische Ziele verfolgen, und dafür ihre Unabhängigkeit von anderen staatlichen Stellen verwenden.
So, wie das Marianne Ny in Schweden über viele Jahre mit Julian Assange gemacht hat.
Sie hätte jederzeit den Haftbefehl gegen Julian aufheben können.
Sie hat es nicht getan.
Selbst, als der UNO-Menschenrechts-Rat gesagt hat, dass das illegal ist, hat sie es nicht zurückgenommen.
Und inzwischen ist sie ganz normal pensioniert, ohne dass sie sich jemals dafür verantworten musste.
Ich hoffe, dass wir in Deutschland inzwischen weiter sind.“

Kevin: „Ja, das hoffe ich auch.“
