== [big-number]#1922# Der Hakenkreuzmann

=== SZENE 11: Im selben Gewölbekeller.

____
Der Hauptmann, Bertold, ein weiterer uniformierter Mann mit Hakenkreuzbinde am Oberarm.
Sie stehen in der Mitte des Raumes.

Hakenkreuzmann: “So!
Das ist also euer Raum für Spezialbehandlungen.“ Er schaute sich um und nickte.
„Schöner Ort.
Gefällt mir!
Spezialbehandlungen … Guter Name.
Gefällt mir auch!
Man muss wissen, wie man die Sachen nennt.
Das Volk will verführt werden.
Es hat Lust daran, verführt zu werden.“

Hauptmann: „Wenn man die Reihenfolge bei den Spezialbehandlungen gut wählt, dann reden sie ziemlich schnell.
Die Papenburgs waren hier, beide zusammen in diesem Raum, mit uns beiden“.

Er grinste.

„Es ging sehr schnell.
Und am Ende haben uns beide alles erzählt, was wir wissen wollten.“

Hakenkreuzmann: „Das war eine Tat!
Das haben wir sogar in München gefeiert.
Das rote Gesocks muss ausgerottet werden.
Es gibt keinen anderen Weg.
Sie lassen sich nicht bekehren.“

Hauptmann: „Und vorher müssen sie spezialbehandelt werden.
Informationen sind wichtig.“

Hakenkreuzmann: „Eine technische Frage: Man muss vorher wissen, was sie wissen, sonst ist es schwierig, oder?“

Hauptmann: „Dann dauert es länger.
Irgendwann reden sie.“

Hakenkreuzmann: „Aber was reden sie dann?
Wenn so ein armer Vogel nichts weiß, dann fängt er irgendwann an, etwas zu erfinden.
Und das ist dann auch wieder nicht gut.
Der ganzen Sache fehlt noch etwas.“

Hauptmann: „Was meinen Sie?“

Hakenkreuzmann: „Wir sprechen in München viel darüber.
Irgendetwas, wo er ab und zu wieder ausatmen kann.
Ein bisschen Kraft bekommt.
Wir haben gedacht, vielleicht irgendein Guter, der ihn zwischendurch wieder aufpäppelt.
Ein Freund.
Jemand bei dem er verschnaufen kann.
Dann kriegt er Hoffnung.
Wenn man das dann über ein paar Wochen oder Monate ausdehnt, dann kann man, glaube ich, ziemlich viel herausfinden.“

Hauptmann nachdenklich: „Hmmm. Ja, das könnte was dran sein.“ Bertold nickte ihm zu.

Hakenkreuzmann: „Man braucht überall Illusionen.
Illusionen des Guten, das macht Hoffnung.
Hoffnung ist gut.
Das macht sie schwach.
Illusionen des Bösen.
Das macht Angst.
Hoffnung und Angst.
Mit den beiden Dingen lässt sich viel machen.
Es ist wichtig wie die Dinge aussehen, wie man die Dinge nennt.
Wir bauen in München gerade eine schlagkräftige Propaganda-Abteilung auf.
Das macht Hitler selbst.
Kennen Sie den?“

Hauptmann: „Nein.“

Hakenkreuzmann: „Toller Mann.
Sehr gute Sprache.
Kraftvolle Stimme.
Und wenn etwas mal nicht so läuft, dann redete er eine Weile, und am Ende glauben alle, dass es trotzdem gut gelaufen ist.
Er kriegt jeden rum.
Hält sich dabei aus allen Prügeleien raus, aber mit seinem Mund bügelt er alle platt.
Das ist eine wichtige Sache.
Worte!“

Hauptmann: „Verstehe.
Das klingt gut.
Ich wünschte, wir würden hier einen echten Führer haben.“

Hakenkreuzmann: „Wir kommen bald nach Berlin.
Da brauchen wir so Leute wie euch.“

Hauptmann nickte und schaute zu Bertold: „Wir sind dabei.“
Bertold nickte zurück.
____
