== [big-number]#2021# Ich hab's!

[text-caps]#Marianne und Luigi# saßen auf der Terrasse, beide zusammen am Tisch, vor sich jeweils einen Laptop.
Auf den Bildschirmen schwarze Seiten von Google und Apple.

Luigi: „Das ist richtig gut.
Hej, deine Klasse ist so cool!
Wahnsinn.
Ich kann gar nicht genug von ihnen lesen.
Da musst du eiskalt sein, wenn du so etwas vor der versammelten Presse machst.
Sie stehen Angesicht zu Angesicht mit dem größten Geheimdienst der Welt und veröffentlichen ein ultrageheimes Gespräch seines Chefs.
Und so wie es aussieht, wird er das beruflich nicht überleben, zumindest nicht als Direktor der NSA.
Hej, in so eine Klasse wäre ich gerne gegangen.
Warum bist du da eigentlich weg?
Also ich wäre geblieben ...“

Marianne schlug ihn an den Arm.
„Hej!
Ein paar Stunden nachdem ich weg war, hat eine CIA-Truppe meine Haustür eingetreten.
Und außerdem waren die Mädels und Jungs damals gar nicht so cool, so wie ich mich erinnere.
Die waren ziemlich normal.
Kevin war schon nett und witzig, aber ein Facebook-Junkie.
Ein voller Ich-habe-nichts-zu-verbergen-Typ.
Verschlüsseln?
Wozu?“

Luigi: „Kevin?
Der Kevin?
Nee.
Das glaube ich nicht.“

Marianne schaute ihn ernst an und nickte dabei.
„Doch, der Kevin.
Anni hatte immer Probleme mit ihren langen Fingernägeln auf ihrem iPhone und Sophie hat mit 14 Jahren überhaupt zum ersten Mal einen Computer selbstständig eingeschaltet.“

Luigi schaute sie aus den Augenwinkeln an.
„Hej komm, du erfindest Sachen.
Das kann nicht sein.“

Marianne: „Echt!
Die Klasse ist ein klassischer Spätzünder.
Die sahen alle ganz normal aus, als ich dort weg bin.
Das war nett … und langweilig.
Selbst Lukas: Der konnte technisch ein bisschen was.
Aber er ist an Windows kleben geblieben.“

Luigi beugte sich nach vorne und schaute auf seinen Monitor: „Schau einer an...“

Marianne: „Was?“

Luigi: „Die Präsidentin der Vereinigten Staaten will bei ihrem Deutschlandbesuch nächste Woche über Internet-Themen sprechen.“

Marianne: „Mhmh. Meinst du, sie wird Abbitte leisten?
Sich entschuldigen?
Oder einfach wieder nur drumherum, dran vorbei und drunter durch reden.
Ich kann mir nicht vorstellen, dass sie etwas von Bedeutung sagt.
Sie ist die Präsidentin.
Sie darf gar nicht.“

Luigi: „Hier steht: Sie will mit Regierungs- und Oppositionsvertretern auch über die jüngsten Ereignisse im Internet und das Verhältnis zu Geheimdiensten sprechen.
Es geht schon zur Sache.
Hej, da könnte eine Amnestie für dich rausspringen.“

Marianne: „Komm!
Bis jetzt ist nichts passiert.
Es geht nur um Wistleblower und Journalisten.
Die bekommen Extraschutz.
Aber doch keine Hackerin, die durch NSA-Firewalls spazieren kann.“

Luigi: „Warte es ab.
Bald streiken die meisten Schulklassen in Deutschland.
Deine Regierung kommt da jetzt schon nicht mehr dran vorbei.
Das ist ein echtes Problem für sie.
Und das kann man nicht mit Geld lösen, die Klassen verlangen ja keines: mehr Lehrer, mehr Computer, bessere Gebäude.
Nichts von dem.
Und wenn es nicht um Geld geht, dann wissen sie nicht, was sie tun können.“

Marianne: „Die Schulklasse ist für die Amerikanische Präsidentin nicht interessant.
Deutschland ist für sie ein kleines Land.“

Luigi: „Guck an! Guck ... an.
Außerdem kommt sie noch in eine ARD-Talkshow und stellt sich den Fragen von Journalisten.
Live!
Heike's Talk.
Geil.
Das ist gut...
Live ist immer gut.
Da kann man immer etwas heraushören.“

Marianne schaute auf seinen Monitor und nickte.

Luigi wiederholte nachdenklich: „Die Präsidentin kommt nach Berlin!
Das ist wirklich gut.“

Marianne: „Nee ...“

Luigi: „Doch!
Das ist gut.“

Marianne: „Neeeee!“ Sie hackte auf ihre Tastatur.

Luigi: „Doch!
Schau, ...“

Marianne unterbrach ihn: „Totaot.
Totaot ...“

Luigi: „Was?
Was ist?“

Marianne: „Totaot hat eine Liste mit CIA-Gefangenen gehackt.
Geheimen CIA-Gefangenen!“

Luigi: „Geil. Geil.
Das ist das, was du gesucht hast.
Das ist ein geiler Typ.
Der kann in Überlichtgeschwindigkeit programmieren und jetzt hackt er auch noch.
Von dem hänge ich mir später einmal ein Riesenportrait an die Wand.“ Marianne warf ihm einen verächtlichen Blick zu.
Luigi grinste sie an.
„Sag, was steht drin?“

Marianne: „Weiß nicht.“ Sie rieb sich ihre Hände an den Beinen.
„Oh, scheiße ...
Ich will das Ding nicht aufmachen ...“

Luigi: „Vielleicht ist da Paul dabei.“ Er rückte näher und schaute auf ihren Bildschirm.

Luigi: „Uhhh.
Das ist eine schöne Rose, mit Träne.
Was ist das?“

Marianne: „Das ist von Totaot's Freundin.
Die malt immer so Zeug und Totaot verwendet das dann überall.“

Luigi: „Aber schönes Zeug.
Handgemalt.
Romantisch.
Dann ist Paul bestimmt in der Liste.“

Marianne: „Oder gerade nicht!“ Ihre Hände zitterten leicht.
Sie gab einen Befehl ein, um die Datei zu öffnen.

Marianne: „Eine Tabelle: Namen, Datum und Kürzel.
Was ist NYZ, VGT, MYE?“ Sie blätterte durch Hunderte von Namen.
„A, B, E, I, K.
SCHEISSE!“

Luigi: „Was?
Ist er nicht drin?“

Marianne: „Nein, Amon.
Amon Koch ist da.
Night-Owl.
VGB.
Was heißt VGB?“

Luigi zuckte mit den Schulter.
„Night-Owl?
Der Night-Owl von der BND-Datenbank?“

Marianne: „Ja.
Er ist vor zwei Jahren verschwunden.
Zur gleichen Zeit wie Paul.
Und jetzt sitzt er in einem CIA-Gefängnis.
Scheiße!
Das macht er nicht gut mit.
Das kann er nicht.
Paul könnte das besser.“

Luigi: „Ist Paul auch da?“

Marianne zögerte und blätterte einzelne Zeilen weiter: „Kraft, Kwalis, Lammert, Lamprecht, LASSER!!!“ Sie schrie laut auf.

Luigi erschreckte sich furchtbar, beugte sich instinktiv zu ihr herüber und wollte ihr den Mund zuhalten.
Sie wehrte ihn ab, schüttelte ihre Hände aus und sagte relativ leise: “Lasser, Paul, VGB.
Scheiße.
Scheiße.
Er ist da!
Er ist da!
Er ist da!
Was ist VGB?
Er ist im gleichen Gefängnis wie Amon.
Ja, klar!
Natürlich.
Was ist VGB?“

Luigi: „Das kriegen wir schnell raus.
Ich schreibe es in das Anonymous-Twitter-Konto.
Da haben wir die Antwort in zwanzig Sekunden.“

Marianne: „NEE!
Auf keinen Fall.
Nicht öffentlich!
Nicht jetzt!“

Luigi: „Dann dauert es Stunden bis wir das haben.“

Marianne: „Ok!
Twitter.“

Luigi hackte etwas auf seinem Laptop.
Beide schauten gebannt auf seinen Bildschirm.

Luigi: „Na … na … Da!
Virginia Blacksaw.
CIA-Gefängnis in der Nähe von Harrisonburg.“

Marianne fasste sich an die Brust und atmete tief aus und ein.
„Das ist es.
Das ist es.
Das muss es sein.“ Sie sprang auf und gab Luigi einen Kuss auf den Mund.
Sie lief auf der Terrasse auf und ab, klatschte dabei lautlos die Hände, rieb sich das Gesicht, fuhr sich über die Haare.
„Was jetzt?
Was jetzt?“

Luigi rief laut: „Ich habs!“

Marianne sprang instinktiv zu ihm hin und hielt ihm den Mund zu: „Ruhig!
Ruhig!
Wir dürfen jetzt keine Fehler machen.“ Sie nahm ihre Hand wieder weg.
„Was hast du?“

Luigi: „Ich habe _die_ Idee!
Und nur du kannst das machen ...“

Marianne: „Was?
Was kann nur ich machen?“

Luigi: „Komm her!“ Er winkte sie mit dem Finger her, sie kam und er flüsterte in ihr Ohr.
Die Augen von Marianne leuchteten auf, immer mehr, während Luigi sprach.
Ab und zu nickte sie leicht.
Am Ende sprang sie auf, riss die Arme in die Luft und sagte halblaut: „Das machen wir!
Das machen wir!
Das ist super.
Das kann ich.“
