== [big-number]#2021# Das Interview (1)

[text-caps]#Heinz und Frederik# saßen in sehr legerer Kleidung bei Heinz zu Hause auf dem Sofa vor dem Fernseher, jeder eine Flasche Bier in der Hand.
Im Fernsehen war eine leere Talkshow-Bühne zu sehen.

Achmed fläzte sich auf der Dachterrasse des Eel Garden in einen überbreiten Korbsessel.
Er blickte auf eine riesige Leinwand, auf der sonst Fußballspiele gezeigt wurden.
In einer Hand hielt er einen Cocktail mit Strohhalm und in der anderen eine Fernbedienung.

Hans saß mit seiner Frau in seinem Haus in Tasmanien.
Beide aßen Popcorn mit selbstgemachtem Sirup und Chips mit Curry-Majonäse und schauten dabei auf die gerade aufgehende Sonne.

Das Klassenzimmer in Berlin war brechend voll.
Viele Hackerfreunde und Familienmitglieder waren gekommen.
Manche standen an der Wand, manche knieten, alle schauten auf einen Riesenfernseher.

Der NSA-Direktor saß auf der Rückbank einer Limousine und sah das Bild der Moderatorin vor sich auf einem Bildschirm. Er schaltete ab.

Die Moderatorin kam auf die Bühne und ging nach vorne zu den Zuschauern.
Beifall.

Moderatorin: „Einen schönen guten Abend … guten Abend … Und willkommen zu Heikes Talk.
… Heute mit einem Super-Super-Spezial-Gast ...“

Lauter Applaus.

Moderatorin: „Sie wissen es, Sie wissen es ja!“ Sie lachte.
„Und sie ist tatsächlich da!
Ja, sie ist gekommen!“

Sie nickte ins Publikum, ging dann zum Gesprächstisch auf der Mitte der Bühne und ließ sich in einen der drei Sessel fallen: „Ok.
Dann warten wir nicht lange.
Ich darf begrüßen ... Die Präsidentin der Vereinigten Staaten von Amerika!“

Sie machte eine Armbewegung zu einem Tor in der Mitte der Bühne hin.

Applaus brauste auf, vermischt mit vereinzelten Buh-Rufen, die von der Moderatorin mit einem kurzen Stirnrunzeln kommentiert wurden.
Gleißendes Licht strahlte auf das Tor und die Präsidentin trat heraus.
Der Applaus wurde lauter.
Sie schritt zur Bühnenkante, nickte freundlich ins Publikum, lächelte, winkte.
Einzelne Zuschauer standen von ihren Sitzen auf.
Die Präsidentin wies sie mit Händen, sich wieder zu setzen.

Präsidentin: „Danke.
Danke ...
Danke, für diesen Empfang.“ Sie legte die Hand auf ihre Brust und lächelte.
„Danke!“

Dann ging sie zum Tisch und setzte sich.

Moderatorin: „Frau Präsidentin!
Wie fühlen Sie sich?“

Die Präsidentin lachte: „Ein bisschen müde.
Die Reise hierher, so viele Gespräche den Tag über und heute morgen habe ich den Direktor der NSA entlassen.
Solche Dinge macht man nicht immer alle zusammen an einem Tag.“

Moderatorin: „Wirklich entlassen?
Ich meine, ich kenne die Nachricht.
Warum haben Sie ihm nicht die Chance gegeben, selbst zu gehen?“

Präsidentin: „Er hatte sie.
Er hatte eine Woche Zeit.
Und hat sich klar dazu geäußert.“

Die Moderatorin nickte.
„Mh mh.
Das sieht aus unserer Sicht hier in Deutschland ein wenig nach innerem Machtkampf oder Familienkrieg in den USA aus.“

Die Präsidentin schüttelte den Kopf: „Das ist kein Krieg.
Und auch kein Machtkampf.
Die Rollen in unserem politischen System sind klar verteilt.
Und da gibt es auch niemanden bei uns, der das in Frage stellt.
Aber wir hatten einen Familienstreit, das kann man sagen.
Das passiert in den besten Familien.
Und wissen Sie, ich finde es sogar gut, dass das passiert ist.“

Moderatorin: „Gut?“

Präsidentin: „Ja.
Ein Streit ist wie ein Gewitter.
Es kann ziemlich bedrohlich donnern und blitzen, aber danach, wenn es vorbei ist, ist die Luft sauberer, und dann kommt auch irgendwann wieder die Sonne heraus.
Die große Mehrheit der Menschen in Amerika hat jetzt besser verstanden, was wir wollen. Vieles ist klarer.“

Moderatorin: „Was ist jetzt klarer?“

Präsidentin: „Wir wollen keinen Überwachungsstaat, der alle Bürger bis ins Privatleben hinein verfolgt.
Das wollten wir nie.
Wir Amerikaner haben so etwas wie eine Allergie gegen Überwachung.
Das ist von Anfang an in unserer Verfassung verankert.
Was uns jetzt klarer ist, ist, dass wir auch nicht die Instrumente haben wollen, die einen Überwachungsstaat möglich machen.

Um ein Missverständnis auszuräumen: Normale Bürger werden bei uns nicht überwacht und wurden es auch keiner Zeit.
Es wurde zwar vieles, sehr vieles aufgezeichnet, aber das schaut sich keiner an.
Das wird zu 99,9 Prozent überhaupt nicht verwendet.
Allerdings haben wir Leute auch im Umfeld der Regierung, die träumen von Dingen, die einem Überwachungsstaat sehr nahe kommen.
Und von denen gibt es dort jetzt einen weniger.

Wir wollen im Übrigen auch keine Todes-Schwadrone auf der Welt herum schicken, die irgendwelche Listen abarbeiten, und zu denen ein Geheimdienstchef aus eigenem Ermessen jemanden hinzufügen kann.
Das kann nur mit dem Willen der Präsidentin geschehen.

Was wir zudem wollen, ist, präziser zu werden.
Verstehen Sie mich nicht falsch.
Wir müssen uns gegen den Terrorismus schützen.
Wir dürfen in unseren Anstrengungen in diesem Punkt nicht nachlassen.
Der Terrorismus ist nicht schwächer geworden in den letzten Jahren.
Er ist stärker geworden, brutaler.
Dagegen müssen wir weiterhin entschieden vorgehen.
Aber wir müssen die Art, wie wir gegen ihn kämpfen, gründlich überdenken.“

Moderatorin: „Aber es wird noch Todes-Kommandos geben, die Terroristen aufspüren und, wie viele sagen: aus dem Spiel nehmen?“

Präsidentin: „Wir befinden uns in einem Krieg.
Das ist die Realität.
Schon fast 20 Jahre lang.
In einem Krieg sterben Menschen.
Der Terrorismus hat uns den Krieg erklärt.
Wir haben geantwortet.
Aber es ist eine neue Art von Krieg.
Es ist nicht wie hier in Deutschland vor 80 Jahren.
Es kämpfen nicht mehr Länder gegeneinander, sondern Lebensweisen, Grundüberzeugungen.
Wir stehen für Freiheit, nicht für gottgegebene Gesetze.
Jeder sollte seiner Religion folgen können wie er das für richtig hält und sie nicht jemandem anderen aufzwingen.
Dieser Kampf um Lebensweisen findet weltweit statt, sogar in den USA.
Und da müssen wir uns noch besser darauf einstellen.
Da gibt es bei uns viel altes Denken, das sich Riesenarmeen vorstellt, komplexe Waffensysteme und Weltdiplomatie.
Das alles ist immer noch nötig.
Es gibt China, Nord-Korea, Syrien, Iran … Es gibt viele Länder, wegen denen diese Dinge leider noch sehr relevant sind.

Aber es gibt auch diese neue Entwicklung, wo alle diese Dinge nicht mehr wirken.
Und darauf sind wir noch nicht gut genug eingestellt.
Wir haben versucht das durch kleine, schnelle Militäreinheiten, durch flexiblere Waffen und durch Kontrolle des Internets zu lösen.
Und bei dem Versuch, das Internet zu kontrollieren, sind wir an einigen Stellen klar übers Ziel hinausgeschossen.
Da werden wir jetzt korrigieren.“

Beifall im Publikum.

Moderatorin: „Flexiblere Waffen?
Damit meinen Sie Drohnen?“

Präsidentin: „Ja, unter anderem.
Ich weiß, sie haben hier in Deutschland einen schlechten Ruf.
Aber richtig eingesetzt können sie viele Menschenleben retten.
Wie gesagt, wir müssen präziser werden.
Wir dürfen keine unschuldigen Menschenleben mehr aufs Spiel setzen.
Der Krieg ist jetzt überall, in jedem Land der Erde, Kämpfer und Zivilisten sind kaum noch zu unterscheiden.
Da werden genaue Informationen über die Gegebenheiten vor Ort immer wichtiger.
Wir haben immer gewusst, dass unsere Informationen besser werden müssen.
Wir haben große Anstrengungen dahingehend unternommen.
Das ist ein Grund dafür, warum die Geheimdienste so viel in diese Richtung getan haben.
Sie hatten den Auftrag ... sie _haben_ den Auftrag, unsere Informationsbasis zu verbessern.

Aber sie haben etwas verwechselt.
Sie haben _so gut wie möglich tun_ verwechselt mit _so viel wie möglich tun_.
Und daran werden wir jetzt arbeiten: Dass unsere Informationen besser werden, genauer, und dass unschuldige Menschen nicht mehr in dieses Raster fallen, dass unsere Computer alle Informationen über Menschen, die unsere Art zu leben nicht bedrohen, so schnell wie möglich wieder vergessen.“

Moderatorin: „Ich habe gerade überlegt, ob jetzt wohl Beifall kommt oder nicht, auf das, was Sie gesagt haben.
Er kam nicht, obwohl wir wir hier in Deutschland auch nicht überwacht werden wollen und uns eigentlich in der Mehrheit freuen würden, wenn persönliche Daten von uns nicht in riesigen Datenspeichern in den USA gespeichert werden.
Wir mögen auch diese Schwachstellen nicht, die unsere Computer und Smartphones unsicher machen, und die ja auch ihre Geheimdienste wirklich überall eingebaut haben.
Und die wieder und wieder eingebaut wurden.
Wir haben zu viel darüber gehört.
Machen Sie jetzt damit Ernst, normale Menschen wie mich oder irgendjemand hier im Raum nicht mehr zu überwachen?“

Präsidentin: „Ja, wir machen jetzt Ernst damit!
Ich weiß nicht, ob das für alle hier im Raum gilt“, sie lächelte, „man weiß nie wer um einen herum ist, aber ich gehe einmal davon aus.
Ich verstehe die Skepsis gut.
Deswegen will ich Taten sprechen lassen.
Deswegen habe ich die Amnestie für Wistleblower und Journalisten erlassen.
Und wir haben bald Gesetze, die es explizit erlauben, Schwachstellen auch dann zu melden, wenn dadurch Firmengeheimnisse verletzt werden.
Wir sind da nur noch am Diskutieren, wie wir sicherstellen können, dass in einer solchen Veröffentlichung tatsächlich nur die Schwachstellen genannt werden und nicht nebenbei auch noch andere Firmengeheimnisse, die man gar nicht dafür verraten müsste.
Das ist nicht einfach.
Aber wir kommen voran.“

Moderatorin: „Aber wenn man sich, um solche Schwachstellen aufzudecken, in fremde Computer einhackt, dann ist das nach wie vor nicht erlaubt, oder?
Das war ja so im Fall von Marianne Lasser.“

Präsidentin: „In fremde Computer ohne Erlaubnis einzubrechen, das geht direkt gegen die Privatsphäre von Menschen oder Firmen.
Diese Computer gehören jemandem.
Dieser jemand hat das Recht, zu entscheiden, was damit passiert, auch wenn es eine Firma oder eine Behörde ist. Das können wir nicht generell erlauben.“ Sie schüttelte den Kopf und lächelte.
„Aber, wenn mein Plan aufgeht, wenn Mitarbeiter in Firmen und Behörden alle Schwachstellen melden, die in Programme eingebaut werden, dann muss ja auch niemand mehr hacken, um das herauszufinden.
Das wäre meine Lösung.
Ich überlege einen Staatspreis auszusprechen für Leute, die Schwachstellen melden.
Der wird hoch dotiert werden.
Und wird auch für Nicht-Amerikaner gelten.“

Moderatorin: „Aber ohne die mutige Tat von Frau Lasser, wäre das Ganze gar nicht erst ins Rollen gekommen?
Könnte man das nicht so machen, dass bis zu der Zeit, in der alle Schwachstellen von Mitarbeitern gemeldet werden, es erlaubt ist … oder akzeptabel … oder vielleicht sage ich, man kann da ein oder zwei Augen zu drücken, wenn jemand an solche Daten über einen Hack kommt?“

Präsidentin: „Ich bin generell gegen Gewaltanwendung.
Und das ist Computergewalt.
Alle Gewalt soll vom Staat ausgehen.
Ich will da eine Lösung, die auf Verständnis aus ist.
Wir alle müssen verstehen, dass Schwachstellen unsere Freiheit einschränken.
Sie können ja immer auch von anderen ausgenutzt werden, nicht nur von denen, die sie einbauen.
Deswegen möchte ich hier lieber eine Kultur des Miteinanders, wo wir als Gemeinschaft zusammen beschließen: Wir wollen das nicht.
Wir wollten keine Diebstähle, wir wollen keine Morde und wir wollen auch keine absichtlich eingebauten Schwachstellen.
Ich kann mir vorstellen, dass das FBI eine eigene Abteilung bekommt, um das durchzusetzen.
Das wird tatsächlich gerade diskutiert.“

Beifall im Publikum.

Die Moderatorin atmete ein: „Ich glaube, an dieser Stelle passt jetzt das gut, was unsere Sendung ausmacht, das Besondere an Heike's Talk.
Sie wissen davon?“

Die Präsidentin nickte.

Moderatorin: „Wir haben in jeder Sendung einen Überraschungsgast.
Er hat immer einen persönlichen Bezug zum Gesprächsgast, und er darf drei Fragen stellen.
Und in diesem Zusammenhang darf ich an dieser Stelle auch einmal etwa leaken.“ Sie lächelte ins Publikum.
„Es ist mir ein wenig peinlich.
Aber wir haben im Vorfeld in ihrem Stab nachgefragt, ob unser Überraschungsgast für Sie in Ordnung ist.
Das machen wir normalerweise nicht.
Aber in diesem Fall haben wir das gemacht.
Deswegen gehe ich davon aus, dass der Gast, den wir vorgeschlagen haben, Ihnen nicht ganz unbekannt ist, oder?“

Die Präsidentin schüttelte den Kopf und lächelte.

Moderatorin: „Wir hatten zwei Kandidaten, die beide schon intensiven Kontakt oder sagen wir Auseinandersetzungen mit amerikanischen Präsidenten hatten, einer davon auch direkt mit Ihnen.
Beide würden für dieses Thema bestens passen: Julian Assange und Edward Snowden.
Wir hatten uns für Julian entschieden.
Und das ist, was Sie jetzt denken: Julian Assange wartet hinter diesem Tor ...
Und das tut er auch.“ Sie machte eine Pause.

„Aber, vor zwei Tagen ist etwas passiert, das hat unsere Pläne durcheinander geworfen.
Wir haben einen Anruf bekommen von einem jungen Mann aus Italien.
Und er hat uns einen anderen Überraschungsgast vorgeschlagen und versichert, dass er auch kommen würde, wenn er eingeladen wird.
Wir haben das zunächst für einen Scherz gehalten, aber es hat sich als wahr heraus gestellt.
Und es ist kein er, sondern eine sie.
Sie können sich vielleicht schon denken, wen ich meine?“

Die Präsidentin schüttelte leicht verwirrt den Kopf.

Aus dem Vorhang hinter der Bühne lugte Linda hervor.
Sie versuchte vorsichtig, aber nachdrücklich, Blickkontakt mit der Präsidentin herzustellen.
Aber diese sah nicht zu ihr hin.

Die Moderation zitterte leicht: „Es ist Marianne.
Marianne Lasser.“

Ein Raunen ging durch das Publikum.
Und im Gesicht der Präsidentin sah man blankes Erstaunen.
Sie blickte um sich, zur Moderatorin, ins Publikum, auf den Tisch, aber fing sich schnell wieder.
Dann sah sie Linda hinter dem Vorhang.
Linda schüttelte deutlich den Kopf.

Moderatorin: „Sie ist hier.
Sie steht in diesem Augenblick hinter diesem Tor.
Wenn Sie nichts dagegen haben, dann lasse ich sie herein.
Als echten Überraschungsgast.
Ansonsten kommt Julian Assange.
Er ist nur für den Fall da, dass Sie es ablehnen, mit Marianne Lasser zu sprechen.“

Linda begann mit den Armen zu winken und dachte: „Nein, nein, auf keinen Fall!
Mach das nicht!“ Im Publikum war es gespenstisch still geworden.

Präsidentin nickte: „Auf jeden Fall will ich das!
Ich meine, sie hat ja einen gewaltigen Mut, hierher zu kommen.
Da kann ich schon den Mut haben, mit ihr zu sprechen.“

Applaus brauste auf im Publikum, er wurde lauter.

Moderatorin, laut: „Dann, herzlich Willkommen, MARIANNE … LASSER!“

Das Licht ging an, das Tor ging auf und Marianne kam herein.

Das Publikum johlte auf, das Klatschen wurde immer lauter und dann standen alle fast gleichzeitig auf.
Alle schauten auf Marianne, wie sie nach vorne zur Bühne kam.
Sie klatschten, johlten.
Einzelne riefen „Marianne!“

Vorne an der Bühne blieb sie stehen.
Das Publikum wurde nicht leiser.

Ein Mann rief: „Marianne, bleib bei uns.“

Sie nickte leicht. Eine Träne lief ihr die Wange herunter. Sie stand da, 10 Sekunden, 20 Sekunden, eine Ewigkeit. Dann wischte sie sich die Träne aus dem Gesicht, nickte wieder ins Publikum und ging zum Tisch. Die Präsidentin war aufgestanden und beide gaben sich die Hand. Beide hatten es ein wenig schwer, sich in die Augen zu schauen, aber nach einer kleinen Weile klappte es. Sie setzten sich.

(Fortsetzung)