== [big-number]#2021# Das Interview (2)

Die Moderatorin, die Präsidentin und Marianne am Gesprächstisch.

[text-caps]#Die Moderatorin schaute# zu Marianne: „Ja!“

Sie lächelte und nickte ihr zu.

Moderatorin: „Herzlich willkommen, Marianne.
Solche Dinge passieren tatsächlich.
Sie sind der erste Gast hier, der auch für mich ein Überraschungsgast ist.
Bis gestern wusste ich nichts davon.
Mir klopft das Herz ein wenig.
Denn hier sitzt die Präsidentin der Vereinigten Staaten und hier die bekannteste Hackerin der Welt, die uns allen im letzten Jahr so viele bleibende Erlebnisse verschafft hat, und immer noch mit internationalem Haftbefehl gesucht wird.

Wie oft mussten wir seit den Veröffentlichungen der Schwachstellen unsere Passwörter ändern, uns neue merken, weil die alten von Google, Apple, Facebook und wem auch immer abgelehnt wurden.
Und jeder von uns kennt jemanden, dessen Smartphone, WhatsApp-Konto oder E-Mail gehackt wurde.
Manche Konten sind komplett verschwunden, andere völlig verwüstet.
Viel Geld ist verschwunden und das meiste auch nicht wieder aufgetaucht.
Firmen sind pleite gegangen.
Und wir alle haben etwas über Passwörter, Hintertüren und Verschlüsselung gelernt und warum diese Dinge eine größere Bedeutung im Leben haben, als wir jemals gedacht hätten. Marianne, wie geht es Ihnen?“

Marianne machte eine kurze Pause, lachte dann, fing sich wieder: „Ja, gut, eigentlich.
Ich habe genug zu essen, gute Freunde und meistens ein Dach über dem Kopf.
Das Einzige ist, dass ich peinlich darauf achten muss, dass mich die CIA nicht findet, der BND oder Academi oder wer auch immer.
Aber, das ist ja jetzt passiert ...“ Sie warf einen flüchtigen Blick in die Kamera.

Moderatorin: „Sie wollten zunächst noch etwas darüber sagen, was Sie nach der Sendung vor haben, wie Sie Ihren _Heimweg_ geplant haben, wenn ich das so sagen darf.“

Marianne: „Ich werde nicht viel darüber sagen, was wir geplant haben.
Ich würde nur gerne den Twitter-Namen: @MarianneUndLuigi hier bekannt machen.
Darüber werden wir, wenn möglich, alle 10 bis 30 Minuten etwas von uns hören lassen.
Es wäre schön, wenn möglichst viele dabei sind.“

Moderatorin: „Okay.
@MarianneUndLuigi, bitte alle notieren.
Wer ist Luigi?“

Marianne schüttelte den Kopf.
„Ein Freund, der mir hilft.“

Moderatorin: „Gut.
So, dann kommen wir zur eigentlichen Sache.
Sie haben, wie jeder Überraschungsgast, drei Fragen mitgebracht?“

Marianne nickte.

Moderatorin: „Dann können Sie diese jetzt stellen.“

Marianne: „Okay.“ Sie nickte der Präsidentin zu.
„Dann fange ich an?“

Die Präsidentin nickte zurück.

Moderatorin zur Präsidentin: „Eine Frage dürfen Sie ablehnen.
Als Joker sozusagen.
Dafür gibt es dann eine Zusatzfrage.“

Marianne zog einen Zettel heraus und las: „Erste Frage:“

****
....
Was hat Ihrer Meinung nach in einer Demokratie eine größere
Bedeutung: Das Recht der mündigen Bürger, die Dinge zu erfahren,
die sie etwas angehen? Damit meine ich alles, was sie als mündige Bürger brauchen, um
demokratische Entscheidungen zu treffen, zum Beispiel, was der
Staat alles tut, um ihre Sicherheit zu gewährleisten. Oder auf
der anderen Seite die Geheimhaltung von solchen Dingen aus
taktischen Überlegungen, damit sie nicht von feindlichen Kräften
ausgenutzt werden?

....
****


Die Präsidentin lachte: „Oh, ja.
Das ist eine gute Frage ...
So viel wie möglich von beidem.
Das ist ein Widerspruch, ich weiß.
Aber wir brauchen Geheimhaltung.
Die Kräfte da draußen in der Welt sind nicht alle gut.
Und ich glaube, ich sehe da als Präsidentin mehr von den schlimmen Dingen, als die meisten anderen Menschen.
Und ich will sie sehen, damit ich Entscheidungen treffen kann auf der Grundlage, wie die Welt wirklich ist und nicht, wie ich sie mir vorstelle.
Diese Kräfte dürfen wir nicht frei wüten lassen.
Wir müssen zu unserem Schutz etwas dagegen tun.
Und das geht nur unter Geheimhaltung.
Wenn wir immer sagen würden, was wir vorhaben und was wir gerade tun, dann wären wir sehr leicht berechenbar.
Das ist wahrscheinlich ein bisschen so, wie bei Ihnen in den letzten zwei Jahren.
Sie haben Ihre Aufenthaltsorte auch geheim gehalten.
Aber den Brief, den Sie an Ihre Klasse geschrieben haben, den mussten Sie nicht geheim halten.
Den durften alle lesen.
So gibt es Dinge, die man geheim halten muss und solche, die man öffentlich sagen kann.
Und im demokratischen Prozess müssen wir entscheiden, welche das sind.
Die mündigen Bürger legen über ihre gewählten Vertreter fest, welche Informationen öffentlich sein sollen und welche geheim.
Und die geheimen werden ja auch irgendwann öffentlich.
Zum Beispiel nach 30 Jahren.
Dann ist es Teil der Geschichte und es kann öffentlich werden.“

Marianne: „Ich würde eher nach vier bis sechs Wochen sagen.“

Präsidentin: „Würden Sie Ihre Aufenthaltsorte nach vier bis sechs Wochen preisgeben?
Dann müssen Sie dort weg und können auch nicht wieder dahin zurück.“

Marianne schluckte und sagte nach einigen Momenten: „Vier bis sechs Wochen nachdem ich dort weg bin, nachdem es vorbei ist.“ Sie machte eine Pause und sagte dann langsam: „Berlin, Dahab, George Town, Nairobi, Addis Abeba und ... Luino.“ Ihr Herz fing an zu klopfen.

Die Präsidentin schluckte.
Beide schauten sich in die Augen.

Marianne: „Zweite Frage?“

Die Präsidentin nickte.

****
....
Wenn ein Hacker oder eine Hackerin Schwachstellen öffentlich
macht, die er oder sie in einem Hack herausgefunden hat und
dafür international gesucht wird, würden Sie im Rahmen eines
präsidialen Pardons seinen oder ihren internationalen Haftbefehl
aufheben?


Würden Sie im konkreten Fall meinen Haftbefehl aufheben?
....
****

Moderatorin: „Stop!
Marianne, das ist eine persönliche Frage.
Das ist gegen die Regeln dieser Sendung.
Sie haben sie gelesen.“

Moderatorin zur Präsidentin: „Das müssen Sie nicht beantworten.“

Präsidentin: „Ich werde darauf antworten.
Dann habe ich dann ja schon zwei Fragen hinter mir.“ Sie lächelte warm.
„Ich werde Ihren Haftbefehl untersuchen lassen.
Ich glaube, das ist jetzt geboten.
Wenn wirklich nichts anderes vorliegt, als der Hack in die NSA-Datenbank, alles, was mit der Schwachstellen-Datenbank zu tun hat, dann werde ich eine Empfehlung aussprechen.
Ich darf in das amerikanische Rechtssystem nicht eingreifen, das würde dessen Unabhängigkeit verletzen, und ein Pardon kann ich erst aussprechen, wenn Sie verurteilt wurden.
Aber ich werde auf jeden Fall von vornherein durchblicken lassen, dass ich gewillt bin, das zu tun, sollte es zu einer Verurteilung kommen.
Wenn es das einzige ist, was gegen Sie vorliegt.“

Sie nickte ihr ernst zu.

Beifall und vereinzeltes Johlen im Publikum.

Präsidentin: „Das ist für mich auch eine demokratische Entscheidung.
Sie haben Unterstützung von einer großen Mehrheit in der hiesigen Bevölkerung.“

Marianne nickte und lächelte die Präsidentin an.

Marianne: „Meine dritte Frage:“

Sie zögerte und schaute kurz zur Präsidentin, atmete durch.

****
....
Wenn ich einen Bruder hätte, der wegen meines Hacks verhaftet
wurde und seit jetzt zwei Jahren in einem geheimen CIA-Gefängnis
sitzt, ohne dass er irgendetwas damit zu tun hat, der vermutlich
nur festgehalten wird, weil er mein Bruder ist, würden Sie mir
helfen, ihn da herauszubekommen?

Und wenn ...
....
****

Die Moderatorin ging verärgert dazwischen: „Marianne!
Das sind persönliche Fragen.
Wir hatten gesagt, keine persönlichen Fragen.
Frau Präsidentin, ich würde vorschlagen, wir nehmen die Zusatzfrage.“

Marianne: „Ich habe keine Zusatzfrage.“

Linda stand inzwischen kreidebleich vor dem Vorhang, so dass sie fast vom Publikum gesehen wurde.
Sie nahm beide Hände vor ihr Gesicht.
Die Präsidentin schaute zu ihr hinüber.
Sie wirkte ratlos.
Das Publikum wurde unruhig.

Moderatorin: „Marianne, haben Sie wirklich keine Zusatzfrage?
Wir hatten das besprochen.“

Marianne schüttelte den Kopf.

Die Präsidentin drehte sich zu ihr: „Sind Sie sicher, dass er in einem geheimen CIA-Gefängnis ist?
Es gibt da sehr viele falsche Informationen und falsche Listen, die im Internet umhergeistern.“

Marianne nickte: „Ganz sicher.
Die Liste ist von der CIA direkt, und ganz aktuell.
Sie zog ein Blatt Papier heraus und schob es der Präsidentin über den Tisch.“

Präsidentin schaute auf das Blatt: „Wie haben Sie das bekommen?“

Marianne: „Ein Hack.“

Die Präsidentin lief rot an im Gesicht, schloss die Augen und hielt den Atem an.

Marianne: „Nicht von mir.
Ich war das nicht.
Ich habe das nicht gehackt.“

Präsidentin ernster: „Dann sind Sie auch nicht sicher, dass das echt ist.
Die Liste ist fast sicher eine Fälschung.“

Marianne: „Nein, sie ist echt.
Sie könnten das prüfen.
Sie können ja einfach da anrufen und fragen … lassen.“

Die Präsidentin atmete kräftig durch, schaute auf Linda: „Ich werde das prüfen lassen.
Gleich morgen.“

Marianne: „Okay.“ Sie schaute die Präsidentin ruhig an. „Ich verstehe.“

Präsidentin: „Oder, warten Sie.“ Sie drehte sich nach hinten und rief Linda zu sich an den Tisch.

Präsidentin zur Moderatorin: „Das ist Linda, meine Assistentin für interkulturelle Beziehungen.“

Sie gab Linda das Blatt und flüsterte in ihr Ohr: „Ist das möglich, solche Informationen sofort zu prüfen?“

Linda zuckte mit den Schultern: „Wahrscheinlich.“

Präsidentin: „Kannst du sie prüfen?
Und herausfinden, was wir für Optionen haben?“

Linda nickte vorsichtig, nahm die Liste mit leicht zitternden Händen und verschwand damit hinter den Vorhang.

Präsidentin laut. „Meine Assistentin prüft das.“

Applaus im Publikum.

Moderatorin: „Wow.
Das fühlt sich anders an.
Das ging sehr schnell.
Es ist wirklich alles live hier.“

Sie warf der Präsidentin einen bewundernden Blick zu.

Moderatorin: „So schnell. Hmm. Ich schlage vor, wir machen die Zuschauerfragen in der Zwischenzeit ...“

Sie stand auf, ging nach vorne an die Bühnenkante und las von einem Blatt.
“Soll an Deutschlands Schulen generell nur noch offene und freie Software eingesetzt werden?
Was meinen Sie?“

Etwa zwanzig Minuten später, war hinter dem Vorhang ein lautes Gespräch zwischen Linda und einem Mann zu hören.
Dann schob Linda den Vorhang zu Seite und ging so gefasst wie sie konnte zur Präsidentin.
Sie begann, ihr ins Ohr zu flüstern.
Die Präsidentin nickte von Zeit zu Zeit, flüsterte etwas zurück, hörte wieder zu.
Die Moderatorin stellte derweil dem Publikum eine weitere Frage.
Nach sehr langen drei oder vier Minuten sagte die Präsidentin so laut, dass es Marianne und die Moderatorin hören konnte: „So machen wir das.“ Linda nickte ihr zu und verschwand hinter dem Vorhang.
Alle schauten gespannt auf die Präsidentin.
Es wurde still.
Sie wandte sich zu Marianne.

Präsidentin: „Marianne.
Es ist tatsächlich wahr.
Sie haben Recht.
Es ist zwar peinlich, dass die CIA ihre Geheimnisse nicht für sich behalten kann, aber in diesem Fall hat das etwas Gutes.
Ihr Bruder sitzt in einem Gefängnis in Virginia und es wurde tatsächlich keine Anklage gegen ihn erhoben.
Wir hatten den Fall sogar schon auf unserer Liste, und auch schon angeschaut.
Es ist aus meiner Sicht eindeutig einer der Fälle, in denen die Geheimdienste ihre Kompetenzen überschritten haben.
Und diese Fälle wollen wir korrigieren, und tun das auch schon eine Zeit lang.
Nicht öffentlich natürlich.
Ich werde diesen Fall zu einem Beispiel dafür machen, wie wir anders mit Dingen umgehen.
Wie ich gesagt habe, ich will durch Taten überzeugen und zeigen, dass unser Rechtssystem sehr lebendig ist und schlagkräftig.“

Lauter Beifall im Publikum.
Marianne strahlte über das ganze Gesicht, schüttete den Kopf, schaute dann die Präsidentin an.

Präsidentin: „Es gibt allerdings noch ein paar Dinge zu besprechen.
Aber das machen Sie am besten mit Linda direkt.
Sie hat da eine Idee.
Sie wollen ja Ihren Bruder auch schnell sehen.“

Marianne sprang instinktiv auf, ging um den Tisch und umarmte die Präsidentin.
Zwei Sicherheitsbeamte, die man vorher nicht sehen konnte, sprangen von zwei Seiten hinzu und hielten sie an der Schulter fest.

Marianne lächelte die Präsidentin an und schaute dann Richtung Vorhang.

Moderatorin: „Ja, gehen Sie …“

Moderatorin mit einer Handbewegung zu Marianne hin: „Marianne Lasser!
Danke dir!
Danke dir.
Wir werden das hier nicht so schnell vergessen.
Vielen Dank. Und viel Glück!“

Marianne schaute noch einmal ins klatschende Publikum, winkte und verschwand dann hinter dem Vorhang.
