== [big-number]#2021# Linda und Marianne

[text-caps]#Linda erwartete Marianne# hinter dem Vorhang. Neben ihr stand Robert.

Sie streckte ihr die Hand entgegen: „Linda Meyer“.
Sie schaute sie ernst an.

Robert: „Robert Foster“ Sie gaben sich die Hand.

Linda: „Ich würde zu viel sagen, wenn ich sagen würde: 'Es freut mich, Sie kennen zu lernen'.
Es hat wegen Ihnen schon jetzt jede Menge Aufregung gegeben.
Und das wird erst der Anfang sein.
Aber gut, wir machen das Beste daraus.“

Marianne nickte: „Ich kann mir gut vorstellen, dass das Wellen schlägt.“

Von hinten drängte sich Julian Assange an die Gruppe heran und legte Marianne die Hand auf die Schulter.
Sie drehte sich zu ihm.

Julian: „Hej.
Super Sache.
Du hast das hier im Griff.
Ich kann jetzt beruhigt nach Hause gehen.
Lass dich nicht unterkriegen.
Das ist ja nur die USA …“

Er nickte in Richtung von Linda und grinste sie an.
Zu Marianne: „Nee, wirklich, mach das weiter: Das ist echter Cypherpunk.“

Marianne lachte ihn an und sie umarmten sich lange.

Marianne: „Danke dir, für alles!
Und sorry, dass ich dir heute die Show gestohlen habe.“

Julian grinste schelmisch.
„Ciao!“ Er drehte sich um und ging.

Linda: „Okay.
Wie wir das machen: Sie kommen mit uns, morgen früh, in der Präsidentinnenmaschine nach Washington.“

Marianne schaute sie erstaunt an: „Wie? Wirklich?“ Sie atmete aus.

Linda: „Es geht nicht anders.
Ich weiß, Sie haben einen eigenen Plan, aber wir wollen das nicht riskieren.
In Deutschland werden Sie offiziell noch mit Haftbefehl gesucht, hier sind Sie landesweit bekannt.
Das bringt die Behörden in Bedrängnis.
In den USA kennt Sie vielleicht ein Prozent der Menschen.
Da können wir das unter der Wistleblower-Amnestie verbuchen.
Es ist auch nicht massentauglich, jetzt einen Skandalbericht zu machen, über eine Präsidentin, die eine Hackerin mit nach Washington bringt.
Das passt gerade nicht.
Das ist für ein paar Wochen nicht im Fluss der Nachrichten.
Vielleicht ein paar rechte Randgruppen, aber nichts von Bedeutung.
Wir werden die Staatsanwaltschaft dann morgen den Haftbefehl aussetzen lassen und dann können Sie mit Ihrem Bruder frei wieder zurück fliegen.“

Marianne: „Wenn ein deutsches Fernsehteam mitfliegen darf, ist das für mich in Ordnung.“

Linda atmete aus und wieder ein: „Okay. Haben Sie denn eins?“

Marianne: „Zehn, wenn Sie wollen!“ Sie lächelte, Linda nicht.

Marianne: „Ich frage die Jungs, die uns aus Italien hierher begleitet haben.“

Linda überlegte, schaute Robert an. Der zuckte mit den Schultern.

Robert: „Wir sehen das Material am Ende eh.
Und die sind vom ZdF.
Das wird gehen.“

Linda: „Okay. Dann machen wir das.
Wir kontaktieren das Team.
Dann ist das ein Ja?“ Sie schaute Marianne an.

Marianne: „Ja.“

Linda: „Aber darüber twittern erst im Flugzeug.
Wir starten morgen um 7:30 Uhr.
Sie werden von unserem Sicherheitsdienst abgeholt.
So lange können Sie hier in irgendwelchen Räumen bleiben, wie ich verstanden habe.
Robert wird sie ihnen zeigen.“
