== [big-number]#2021# Im Flugzeug

[text-caps]#Marianne saß neben# Linda in einem breiten Flugzeugsessel.
Durch das Fenster sah man einen Wolkenteppich und strahlende Sonne.
Sie unterhielten sich angeregt.
Weiter hinter ihnen gab die Präsidentin an einem Gesprächstisch einem Fernsehteam ein Interview.

Robert kam vorbei und sagte ruhig zu Linda: „Sie will dich sprechen.
In ihrer Kabine.“

Linda nickte, stand auf und verschwand in einer Türe.
Die Präsidentin folgte ihr.

Drinnen schauten sich beide an.

Linda: „Ich weiß, ich weiß.
Es ist ein Risiko.
Aber es wird gehen.
Es passt alles gerade sehr gut in unseren Plan.
Genau wie die Sache mit der Begnadigung.
Die hatten wir ja eh schon auf dem Plan.“

Präsidentin: „Aber wie konnte es dazu kommen, dass alles plötzlich so luftig war, so ungeplant, vollkommen unsicher?
Wie konnte die Lasser da plötzlich auftauchen?
Ich meine, sie haben keinen Ton vorher gesagt?
Ich will, dass das nicht mehr passiert.“

Linda: „sie haben keinen Ton gesagt.
Das wird nicht mehr passieren.
Aber unser Plan wird funktionieren.
Der Leiter des Virginiaer Gefängnisses, ein Oberst der Rangers, war sowieso für die LBI vorgesehen.
Er ist in der gleichen Einheit wie der NSA Direktor.
Wirklich ein Zufall.
Offiziell verlieren beide ihre CIA-Jobs und jeder wird uns das abnehmen.
Dann bekommen sie ihre Tarnung in der Rüstungsindustrie.
An zwei verschiedenen Stellen.
Da wundert sich auch niemand darüber.
Und beiden wird die neue Arbeit bei der LBI gefallen, da kannst du drauf wetten.
Sie bekommen mehr Befugnisse, haben weniger Kontrolle.
Alles ist endlich wieder wirklich geheim.“

Präsidentin: „Das klingt gut.
Ich mag das Risiko in dem Fall trotzdem nicht, diese Ad Hoc-Entscheidungen, in zwanzig Minuten.
Ich war das letzte Mal in so einer europäischen Talkshow.
Das LBI ist zu wichtig, um so viel zu riskieren.
Wir brauchen es.
Wir brauchen wieder etwas, was wirklich ganz uns gehört.
Wo wir frei agieren können.
Wo nicht Millionen von Menschen drauf schauen.
Und wir die meiste Zeit damit verbringen, die Dinge unter der Decke zu halten.“

Linda: „Das Gute ist, dass uns durch die Sache mit Marianne Lasser die Masse in Europa die vielen Veränderungen in der NSA und der CIA abnehmen werden.
Das gibt uns Freiheit eine große Anzahl an Leuten jetzt rauszuwerfen und damit frei zu machen für die LBI.
Da beißen sicherlich auch ein paar fremde Geheimdienste an und werben Leute ab, die wir offiziell fallen lassen.
Dann bekommen wir LBI im FSB oder LBI im Mossad oder besser, bei den Chinesen.
Glaube mir, das war ein gutes Ding, was uns da in den Schoß gefallen ist.“

Präsidentin: „Ja.
Vielleicht.
Aber wir dürfen jetzt auf keinen Fall Fehler machen.“

Linda: „Keine Sorge.
Marianne fliegt morgen mit ihrem Bruder zurück nach Berlin.
Die beiden werden Ikonen für die Wandlung von CIA und NSA zum Positiven.
Man wird die beiden sehen.
Das macht den Menschen Hoffnung.
Und das gibt uns Spielraum.“
