== [big-number]#2021# Linda, Robert und der Oberst

[text-caps]#Der Oberst stand auf,# stützte beide Hände auf den Besprechungstisch und schaute drohend auf Linda und Robert, die ihm gegenüber saßen. Linda schaute sehr konzentriert.
Dann schlug er plötzlich mit der flachen Hand auf den Tisch.

Oberst: „IHR SEID VOLLKOMMEN DURCHGEDREHT!!!
Ihr kommt aus Washington und meint, ihr könntet die Sachen hier am Ground Zero besser machen als wir.
Kapiert ihr nicht: Wir haben mit den gefährlichsten Leuten der Welt zu tun.
Wenn wir Fehler machen, dann sterben Menschen, viele Menschen, Amerikaner!
Da kann man nicht einfach mal von irgendeinem Sessel aus eingreifen, ohne Dinge kaputt zu machen.

_Der_ Junge geht bei mir heute nur über meine Leiche raus!“ Er schnaubte.
„Das ist eh bloß wieder eine von seinen Einlagen.
Der hat hier schon Sachen angestellt, ich sage euch.
Einer meiner Männer hat den Dienst quittiert, wegen ihm.
Der schreibt jetzt Strafzettel in New York.
Ich wette, da hat euch irgendeiner seiner Freunde etwas ins Ohr geflüstert, und ihr fallt darauf herein.
Ich sage, ihr kriegt ihn frühestens in drei Wochen.
Wenn er bis dahin keine Gefahr mehr darstellt.“

Robert stand auf und brüllte ihn von der anderen Seite des Tisches aus an: „MIR REICHTS JETZT!
Wir haben hier nicht ewig Zeit!
Lesen Sie, was auf dem Blatt hier steht, dann die Unterschrift!
Das ist Ihr Chef, verdammt nochmal!“ Er schob das Blatt auf ihn zu.

Der Oberst stieß es weg und schüttelte seinen Kopf, sein Gesicht war inzwischen rot-violett angelaufen.
Er stand auf.
„Der soll kommen und mir das persönlich sagen ...“

Robert: „Das ist eine dienstliche Anweisung, das ist keine Bitte!
Wie können Sie sich dagegen sperren?
Ich fasse es nicht.
Ist das hier Militär oder Kindergarten?“

Linda: „CIA.“

Robert: „CIA.
Egal.
Kindergarten.“ Er setzte sich hin.

Linda ruhig: „Oberst, mit dem persönlich sagen liegen sie gar nicht so falsch.
Es ist wirklich eine große Sache.
Die wirbelt gerade ziemlich viel Staub auf.
Es ist nötig, dass wir ihn heute bekommen.
Und deswegen kommt nachher nicht ihr Chef, sondern dessen Chefin, die Präsidentin der USA.“

Oberst: „WAS?“ Er schaute wild um sich.
„WAS?
WANN?
Das ist ein Witz?“

Linda: „In sechs Stunden.“

Der Oberst setzte sich wieder hin und schüttelte den Kopf.
Hierher?
Die Präsidentin?
Nein, das könnt ihr nicht machen.
Das könnt ihr nicht machen.“ Er schaute im Raum herum.
„Oh, ihr seid … ECHTE WICHSER!“

Robert sprang auf, ballte die Faust und ging auf den Oberst zu.
Der sprang ihm in Kampfhaltung entgegen und schaute ihn wild drohend an.

Linda eilte um den Tisch und ging dazwischen.
„Wir bleiben jetzt ruhig.
Alle.
Wir haben nicht mehr viel Zeit.“ Sie fasste beide an die Arme.

Alle setzten sich wieder an den Tisch.

Linda: „Was ist das Problem mit einer vorzeitigen Entlassung?“

Der Oberst schloss seine Augen und sagte leise: „Was ist das Problem?
Was ist das Problem?“

Er zischte: „Das Problem ist, dass ihr keine Ahnung habt, wie das hier vor sich geht.
Das Problem ist Information.
Die Jungs und Mädels, die hier ein paar Jahre sind, haben viel gesehen, viel mitbekommen.
Taktiken, Techniken.
Das ist alles ultrageheim hier.
Sie kennen Leute.
Merken sich Gesichter.
Die will ich nicht auf irgendwelchen Phantombildern im Internet sehen.“

Linda nickte: „Und warum ginge es dann in drei Wochen?“

Oberst: „Dafür haben wir eine Spezialbehandlung „Entlassung“.
Die Leute müssen wissen, dass sie nur rauskommen, wenn sie mit uns kooperieren.
Oder anders ausgedrückt: Sie bekommen so etwas wie lebenslange Bewährung.
Es geht um kooperatives, konstruktives Verhalten.
Man kann auch Respekt oder Angst dazu sagen.
Wenn sie rauskommen und gleich auftreten wie King Kong, dann ist das ein Problem.
Wenn sie sich vorsichtig, seltsam oder widersprüchlich verhalten, dann hilft uns das mehr, dann erzeugt das Respekt vor unserer Arbeit.
Wir wollen im Ruf stehen, dass sich Leute bei uns verändern.
Wir entlassen etwa 10% - 15% auf diese Weise, zu diesem Zweck.“

Linda: „Okay.
Dann müssen wir das jetzt eben abkürzen.
Sechs Stunden haben wir noch.“

Der Oberst atmete aus: „Das reicht nicht.
Sie haben keine Ahnung.
Bei Lasser wären drei Wochen noch zu kurz.
Haben sie sich überhaupt seine Akte angeschaut?“

Robert richtete sich drohend auf.
Linda machte zu ihm eine beschwichtigende Handbewegung.
„Herr Oberst, wir wissen, dass das gegen ihr normales Vorgehen geht, vielleicht auch gegen ihre Erfahrungen.
Aber wir arbeiten auch am Ground Zero.
Wir müssen oft Leute zu etwas bringen, von dem Sie vorher nicht dachten, dass sie das je tun würden.
Manchmal in Stunden.
Das ist ein guter Teil meines Jobs.
Und ich denke, ich kann das hier hinkriegen.“

Oberst, gespielt neugierig: „Was wollen Sie tun?“

Linda: „Ich will ihn etwas unterschrieben lassen, eine Geschichte, wie sie für mich, für Sie und ein bisschen auch für ihn tragbar ist.
Er kommt raus.
Das wird ihn überraschen.
Er will raus.
Da wird er uns ein wenig entgegenkommen.“

Oberst: „Unterschreiben?
Das ist ein Terrorist...
Was kümmert den seine Unterschrift.“

Linda: „Sie dürfen ihm dann auch noch ein wenig drohen.
Er wird am Ende wissen, dass seine Unterschrift ernst genommen wird.
Da haben Sie ja Erfahrung.“

Der Oberst runzelte die Stirn: „Das wird ein Super-GAU, sage ich euch.
Sie lesen das in ein paar Wochen überall in der Presse.
Und dann sitzen wir wieder hier zusammen und überlegen, wie es soweit kommen konnte.“

Linda: „Er ist nicht aus der Welt.
Wir werden ihn nicht verlieren.
Und Presse ist unsere Sache.
Da werden wir einiges tun, damit das nicht an die Oberfläche gespült wird.
Er wird Teil einer Verdunkelungskampagne, wir machen sein Leben ein wenig weniger sichtbar.
In vier, fünf Monaten kennt ihn niemand mehr.
Was hat er?
Eine Gefängnis-Geschichte.
Da gibt es viele da draußen.
Und die Leute sagen ...“

Der Oberst unterbrach: „... wissen wir schon.
Ich weiß.
Die Masse will Neuigkeiten, sie will verführt werden.
Aber ich habe dummes Gefühl dabei.
Der Typ, ich sage euch, Lasser, der ist ...“

Linda: „Der Typ wird vergessen werden.
Darum kümmere ich mich.
Und sie bekommen für diesen Fall hier eine Promotion.
Von höchster Stelle.“

Oberst: „Was für eine?“

Linda: „Das kann ich jetzt nicht sagen. Aber eine, die sie nicht ausschlagen können und auch nicht wollen.“

Der Oberst lehnte sich zurück: „Mh mh“

Linda: „Kommen Sie, gehen wir an den Text, und dann besuchen wir den Kerl mal.“

Etwa eine Stunde später.

Linda ordnete die Papiere zurecht und sagte zu Robert: „Komm wir gehen!“
Dann zum Oberst: „Sie warten hier.
Wir machen ihn erst einmal ein wenig warm.“

Sie standen auf und gingen durch einige Gänge zum Verhörzimmer.
Paul saß dort schon am Tisch, mit dem Rücken zu ihnen gewandt.
Linda und Paul gingen an ihm vorbei und setzten sich ihm gegenüber.

Linda: „Paul Lasser?“ Sie nickte ihm freundlich zu.
