== [big-number]#2021# Wiedersehen

[text-caps]#Paul saß immer noch# alleine im Besprechungszimmer. Er bewegte seine Finger wieder in der absurdesten Weise über dem Büchlein, schaute sehr ernst und sagte: „Abira Kadabira.
Klaviera Baradira.
Fliegt zu Marianne, Oskar ...“

Die Türe öffnete sich und Linda stand im Zimmer.
Hinter ihr Robert mit einem Stapel frischer Alltagskleidung.
Paul legte seine Hände etwas verschämt auf seine Beine und schaute die beiden an.

Linda: „Paul ...“

Paul: „Ja?“

Linda: „Marianne wartet draußen auf Sie.“

Paul schaute sie mit großen Augen an.

Linda: „Wir haben hier ein paar Kleidungsstücke, die Sie sich anziehen können.“

Paul schaute immer noch auf Linda und regte sich nicht.

Linda: „Es ist echt!
Sie können mir glauben.
Sie wartet draußen.
Es gibt keine Spiele mehr.
Das war der Grund, warum wir heute so viel gesprochen haben.“

Paul fasste sich und sah sie skeptisch an: „Marianne war die ganze Zeit über da?
Seit heute Mittag?“

Linda: „Nein, sie ist eben gekommen.“

Paul musterte Linda.
Er wischte sich mit der Hand seinen Mund ab, schaute auf den Tisch.
Dann wieder zu Linda: „Und _warum_ ist sie so viel später gekommen als Sie?
Warum ist sie nicht mit Ihnen zusammen gekommen? Sie arbeiten ja nicht hier im Gefängnis.“

Linda: „Ich musste das hier vorbereiten.
Es war alles sehr, sehr kurzfristig, überraschend.
Das sind viele Leute, die damit zu tun haben, nicht gewohnt.
Und da konnte sie nicht dabei sein.“

Paul schaute Linda konzentriert an, kniff die Augen ein wenig zusammen: „Und warum mussten Sie das so kurzfristig vorbereiten?
Warum wussten Sie nicht schon früher davon?“

Linda: „Es ging alles sehr schnell.
Gestern Abend war eine Talkshow im deutschen Fernsehen, und da ist Marianne aufgetreten, hat von Ihnen gesprochen und wir haben entschieden, Sie hier herauszuholen.
Die hier im Gefängnis haben heute früh noch nichts davon gewusst.“

Paul stutzte.
Er fühlte keine Lüge in ihren Antworten.
Er atmete ein und dachte: „Weiter, ich muss sie irgendwo erwischen.“

Er fragte: „Und warum haben Sie nicht noch einen Tag warten können, oder eine Woche?“

Linda strich sich mit dem Finger die Nase, machte eine kleine Pause und sagte dann: „Wir brauchten den Überraschungseffekt hier.
Sonst hätte das so nicht geklappt.“

Paul lief ein Schauer über den Rücken.
Sein Herz fing an spürbar zu pochen.
„Es ist wahr ...“, dachte er.
„... es ist wahr!
Marianne.
Marianne ist hier!“

Er schaute Linda an, Robert, den Stapel Kleider, die Wachleute.
Dann schnappte er sich das Büchlein, sprang auf und ging um den Tisch herum auf Linda zu, die immer noch am Eingang stand.
Er schaute ihr tief in die Augen.
Er fragte aufgeregt: „Wo ist Marianne jetzt?“

Linda: „Links, den Gang runter und dann rechts zum Haupttor.
Wollen Sie nicht vorher diese Kleider …?“

Paul ging an ihr vorbei, schob Robert zur Seite und wurde an der Tür von einem Soldaten aufgehalten.

Paul murrte ihn an: „Lass mich durch!“

Linda: „Lassen Sie ihn durch!“

Paul grinste und schlug mit der flachen Hand zweimal leicht auf die Brust des Soldaten: „Lassen Sie mich durch.“ Sein Herz pochte stärker und stärker.

Der Soldat machte einen Schritt zu Seite.
Paul sprang aus der Tür, dann nach links und lief den Gang herunter, immer schneller, dann rechts einen weiteren Gang.
„Das Tor, das Tor“, dachte er.
„Das muss es sein!“ Zwei Soldaten standen davor.
Sie gingen in Position.
Er hielt an.
Draußen hörte er Stimmen.
Viele Stimmen.
Die Soldaten schauten ihn an.
Einer griff an seine Waffe.
Linda kam von hinten und rief: „Lassen Sie ihn raus!“

Der Soldat steckte seine Waffe zurück und öffnete das Tor.
Paul sah Licht, viel Licht und hörte ein lautes Stimmenwirrwarr.
Er lief vorsichtig an den Soldaten vorbei durch das Tor.

Grelles Licht blendete ihn.
Ein Blitzlichtgewitter.
So viele Menschen.
Es war laut.
Unendlich laut.
Er schaute zu Boden und auf einmal stand sie vor ihm: Marianne.

Sie öffnete ihre Arme: „Hi, Bruderherz!
Schön dich zu sehen.“

Er schaute sie ungläubig an, es war so unreal.
Sie war älter geworden.
Erwachsen.
Aber es war Marianne.
Marianne!
Sie fielen sich in die Arme.
Er brach in Tränen aus.
Sie standen da, umarmten sich, eine Minute, zwei Minuten.
Er spürte ihren Atem, ihre Wärme, ihr Herz schlug deutlich spürbar.
„Ohhh, Wahnsinn...“, dachte er und sagte ihr leise ins Ohr: „Das ist ein Ding!“ Dann begann er sich im Raum umzuschauen.
„Geil!
Geil.
Geil.
Uhh.
Wer ist das?“, fragte er erschrocken, während sie sich immer noch umarmten.


Marianne: „Das ist die Präsidentin der Vereinigten Staaten.“

Paul: „Shiiiit!
Ich werd verrückt.“ Dann drückte er sie fester und sagte: „Meine Schwester! Meine Schwester.“ Er atmete zwei, dreimal kräftig und flüsterte dann „Das sind nicht unsere Freunde.
Wir haben nicht viel Zeit, oder?“

Marianne: „Nein, wir haben nicht viel Zeit.“

Dann wischte er seine Tränen ab und sie drehten sich zu den Kameras, lächelten, winkten in das Blitzlichtgewitter.
Die Präsidentin begrüßte Paul. Auch einige Leute neben ihr. Er schaute Linda in die Augen, schüttelte den Kopf.

Paul: „Fuck it, du ...“ Er lächelte.

Sie lächelte mit einem Augenzwinkern zurück.
Dann drehte er sich wieder zu Marianne: „Hej, du! Das habe ich fast vergessen.
Ich habe dir natürlich etwas mitgebracht zu diesem großen Ereignis.“ Er drückte ihr das Büchlein in die Hand.

Marianne schaute es überrascht an: „Was ist das?“

Paul: „Ein Geschenk.
Ich dachte, wenn du schon den weiten Weg machst, dann habe ich auch ein Geschenk für dich.“ Er grinste sie an.
Sie schaute verwundert zurück.

Paul: „Es wird dir gefallen.“

Linda kam zu ihnen und deutete auf die Türe: „Kommt, wir müssen weiter.
Das Flugzeug nach Berlin wartet schon.“

Paul nahm die Hand von Marianne und sie gingen zusammen hinaus.

Die Präsidentin ins Mikrofon eines Reporters: „Das sind genau die Fälle, die wir gemeint haben.
Einige bei der CIA haben geglaubt, sie würden über dem Recht stehen.
Sie könnten Bürger von befreundeten Staaten, einfach so, ohne Anklage über Jahre in einem Gefängnis wie diesem fest halten.
Das geht gegen unser moralisches Verständnis als Amerikaner.
Und ich sage Ihnen: Das hier wird personelle Konsequenzen haben.
Auch hier in diesem Gefängnis.“

Eine Reporterin ging mit Mikrofon auf den Oberst los: „Sie sind der Kommandant dieses Gefängnisses.
Wie kann so etwas passieren?
Was sagen Sie zu diesem Fall?“

Der Oberst schaute sie grimmig an, deutete auf sein Schulterabzeichen und sagte: „Ich gebe keine Interviews.“ Er schaute ihr tief in die Augen.
