== [big-number]#2064# Wo geht’s zur Akademie?

[text-caps]#Tims Haus lag# in einer ruhigen, amerikanischen Vorstadt.
Es hatte eine schöne, weiße Fassade mit zwei weißen Holzsäulen rechts und links neben dem Eingang, rings herum einen gepflegten Garten und eine große Garage.
Das Garagentor stand weit offen.
Von drinnen war ein lautes, helles Motorgeräusch zu hören.

Plötzlich schoss ein riesiges, geländegängiges Motorad mit einem lauten Heulen aus dem Garagentor.
Auf ihm saßen Tim und Sigur mit aufgeschnallten Helmen.
Tim bremste auf der Straße scharf, sodass der Hinterreifen zur Seite rutschte.
Dann gab er Gas.
Das Vorderrad hob sich sofort in die Höhe und Sigur griff fester um Tims Bauch.

Sigur schrie: „Woaaaahhh.
Das ist eine Maschine!
Voll geil!“

Tim: „140 PS.
Aber warte, bis wir querfeldein gehen.
Das mein Ding.
Querfeldein habe ich vor zwei Jahren den Westküstentitel geholt.“

Sigur: „Das habe ich gehört. Super geil!“

Tim bremste wieder abrupt und lies die Maschine rutschen, gab Gas, die Räder drehten durch.
Sie fuhren auf ein unbebautes Grundstück zu.
Dahinter war eine Steppenlandschaft zu sehen und am Horizont Berge.
In dem Augenblick kamen von rechts zwei schwarze SUVs angefahren und von links ein dunkelblauer.
Sigur schaute nach beiden Seiten.

Sigur: „Hej, das ist nicht gut.
Wo kommen die plötzlich her?“

Tim: „Egal.
Uns kriegen sie nicht.
Die Steppe ist mein Wohnzimmer.
Hier habe ich fahren gelernt.
Hier kenne ich jeden Grasbüschel.“ Er gab Gas.
Sie fuhren auf freies Gelände.
Weiter hinten war eine Landstraße zu sehen, die aus der Stadt kam und sich irgendwo in den Bergen verlor.

Sigur zeigte in Richtung Landstraße und brüllte: „Shiiit.
Zehn SUVs.
Warum haben die alle die gleichen Autos?
Und da hinten noch mehr.“

Tim: „Sie haben uns gefunden!
Aber sie haben uns noch nicht.
Ich wollte schon immer mal Jason Bourne spielen.
Die Verfolgungsjagden sind so geil dort.“

Sigur: „Ich eigentlich nicht!“

Tim: „Die haben keine Chance.
Die haben keine Ahnung, wie schnell wir sind.“ Er gab noch einmal Gas.

Etwa 300 Meter weiter war eine Kolonne von fünf Wagen von der Landstraße abgefahren und versuchte, ihnen den Weg abzuschneiden.
Tim lenkte die Maschine leicht nach links.
Sie waren atemberaubend schnell.
Sigur rief immer wieder „Geil!“ um sich zu suggerieren, dass die Motorradfahrt irgendeine Jahrmarktattraktion wäre.
Aber mit den Händen klammerte er sich panisch an Tims Bauch fest.
Tim fuhr in etwa 50 Metern Entfernung an der Auto-Gruppe vorbei und dann weiter auf offenes Feld.
Die SUVs versuchten, hinterher zu fahren, brachen aber nach kurzer Zeit ab.

Sigur schaute nach hinten: „Geil.
Die sind wir los!“ Dann sah er nach oben in den Himmel: „Scheiße!
Oh shit.“

„Was?“, rief Tim.

Sigur: „Zwei Apache-Hubschrauber.“

Tim drehte sich kurz um: „Shit!
Ich kann hier nicht schneller fahren.
Aber wir sind bald im Wald.“

Sigur: „Oooh, Gott!“

In einem der Hubschrauber zielte ein Soldat mit seinem Scharfschützengewehr auf die beiden und sprach in sein Headset: „Roger.
Habe Beifahrer grün.
Bitte um Feuerfreigabe.“

Über seinen Kopfhörer krächzte eine Stimme.
„Negativ.
Keine Freigabe.
Nicht schießen.
Schießen Sie so auf das Motorrad oder den Fahrer, dass sie stürzen.“

Soldat: „Ich kann den Fahrer erwischen.
Aber die Geschwindigkeit ist zu hoch.
50 Prozent Wahrscheinlichkeit, dass der Beifahrer stirbt.“

Stimme: „Dann stopp.
Warten Sie, bis sie langsamer werden.“

Soldat: „Roger.“

Das Motorrad machte einen gewaltigen Satz über ein Hindernis, kam ins Straucheln.
Der Soldat zielte genauer, aber Tim konnte die Maschine abfangen und gab wieder Gas.
Sigur nahm seinen Helm ab und warf ihn weg.

Tim: „Was zum Teufel machst du?“

Sigur: „Sie schießen nicht.
Sie wollen mich lebend.
Beim Collateral-Muder-Video waren sie viel weiter weg als jetzt.
Das wäre kein Problem, aus der Entfernung zu treffen.
Also ziehe ich den Helm ab, sodass sie nicht auf die Idee kommen, auf das Motorrad zu schießen.
Schau, dass du weiter am Limit fährst.“

Tim steuerte das Motorrad in ein trockenes Flussbett.
Der Wald war noch etwa einen halben Kilometer entfernt.

Sigur: „Wo fahren wir eigentlich hin?“

Tim zeigte halb rechts auf eine Bergkette.

Tim: „Da hin.
Dahinter.“

Sigur sah über der Bergkette einen riesigen, weißen Ballon schweben, mit einer aufgemalten Mosquito-Fliege.

Sigur: „Zu dem Ballon dort?“

Tim: „Welchem Ballon?“

Sigur: „Dem weißen Ballon dort!
Siehst du den nicht?“

Die Mosquito-Fliege begann sich zu bewegen.

Tim: „Ich sehe keinen Ballon.
Das sind Berge, Wolken, Bäume.
Was meinst du?“

Sigur schaute verwundert in die Richtung und sagte leise zu sich selbst: „Na, der da ...“
