== [big-number]#2064# Dmitri

[text-caps]#Die Berge lagen# hinter ihnen.
Das Motorrad schoss einen Fußgängerpfad hinunter.
Sie verließen den Wald.
Am Himmel waren inzwischen vier Apache Hubschrauber zu sehen.
Vor ihnen im Tal tauchte die Landebahn eines kleinen Flughafens auf.

Tim: „Genau wie Lasse gesagt hat: Ein verlassener Flughafen.
Da treffen wir ihn.“

Sigurs Pond-Armbanduhr piepste.
Er holte sie aus der Tasche und schaute drauf.
Sie zeigte eine Nachricht von Lasse: „Der Ballon ist weitergeflogen.
Du hast zu viele Verfolger.
Aber Dmitri wird dir weiterhelfen.
Fahr einfach zum Flugzeug.“

Sigur rief: „Fahr zum Flugzeug!“

Tim: „Welches Flugzeug?“

Sigur: „Da vorne, siehst du nicht?“

Tim: „Doch, doch.“

Am anderen Ende der Landebahn stand ein zweistrahliges Flugzeug.
Man konnte gerade so erkennen, dass die Tür bereits offen war.

Tim: „Ihr seid ganz schön gut organisiert.
Ich muss schon sagen.
Wo kriegt Lasse jetzt so schnell ein Flugzeug her?“

Sigur: „Keine Ahnung.“

Als sie näher kamen, sahen sie einen Mann winken: Sie sollten schneller machen.
Tim gab noch einmal Gas.
Das Motorrad sprang auf der kleinen Bergstraße hin- und her.
Links ein kleiner Bachlauf, rechts eine Wiese.
In einem geeigneten Augenblick fuhr Tim ins Bachbett und das Motorrad sprang mit einem Riesensatz auf der anderen Seite wieder heraus.
In der Luft brachte er es in Position, landete, um dann gleich wieder über einen kleinen Hügel zu springen.
Noch 400 Meter bis zum Flughafen.
Sigur schaute nach hinten.
Dort standen zwei Apache-Hubschrauber am Himmel und drehten sich langsam zur Seite.

Sigur schrie: „Sie schießen.
Die haben 30mm Bordkanonen.
Shit.“

Tim fuhr ein Stück nach links, dann wieder nach rechts.
Links neben ihnen schlug eine Salve ein.
Dann zwanzig Meter vor ihnen.

Der Mann vor dem Flugzeug hatte inzwischen eine Panzerfaust aus einer Kiste vor ihm herausgeholt und zielte damit zwischen die Hubschrauber.
Eine Rakete fauchte los.
Die Hubschrauber drehten in zwei verschiedene Richtungen ab.
Tim machte kurz vor dem Flugzeug eine Vollbremsung und schrie: „Spring!“ Beide ließen sich zur Seite fallen, genau vor die Füße des Mannes.
Das Motorrad rollte noch ein paar Meter weiter.
Der Mann schoss eine zweite Rakete in Richtung der Hubschrauber und zog dann beide ins Flugzeug hinein, das sofort los rollte.
Als sie gerade in der Luft waren, fragte Sigur: „Dmitri?“

Dmitri nickte und sagte mit starkem Akzent.
„Willkommn in Kirrgississtan.“

Tim lachte: „Was?“ 

Sigur: „Wo?“

Dmitri: „Sie bäfenden sich auf Kirrrgisischem Hoheitsgebiet.
Dis ist ein diplomattisches Flugzeug.“

Sigur: „Und was verschafft uns die Ehre?“

Dmitri: „Wirr habben vor ainign Taggen Lasse Brrodowin kontaktiert und gefraggt wie wirr uns firr die Bitcoin errkenntlich zeigen kennen. Und err hat uns angeruffen und gefraggt, ob wirr ein schnälles Flugzeug habben. Wir sind serr schnäll. Und gutt verstäckt.“

Sigur lachte.
„Ja, klar.
Ist ja logisch.
Kirgisistan.
Super.
Weißt du, wo Lasse ist?“

Dmitri: „Ja, wirr fliegen dirrekt dorthin.“
