== [big-number]#2064# Die Cypherpunk-Akademie

[text-caps]#Das Flugzeug war# auf einem regionalen Flughafen gelandet.
Sigur und Tim stiegen aus.
Neben dem Rollfeld schwebte der riesige, weiße Ballon in etwa 20 Metern Höhe über dem Boden.
Er hüllte die ganze Szene in Schatten.
Seine Außenhaut schien aus härterem Material zu bestehen als normale Ballons, vielleicht hartes Plastik oder sogar Metall.
Er sah schwer aus und machte nicht den Eindruck als könnte er fliegen.
Er hatte auch keinen eigentlichen Korb an der Unterseite, nur eine Art von Gewicht.
Sigur staunte wieder über seine schiere Größe.
Er entdeckte neben dem Gewicht einen Schacht, der in den Ballon hinein zu führen schien und aus dem zwei blaue Seile herunter bis zum Boden hingen.
Darunter wartete Lasse mit einem breiten Grinsen.

Sigur lief los und fiel Lasse in die Arme.

Lasse: „Hej!
So gut dich zu sehen!
Du Cyber-Terrorist!“

Sigur: „Selber!“ Sie lachten und klatschen sich ab.
Tim kam hinzu und Lasse umarmte ihn.

Sigur: „Das war eine Aktion!
Unfassbar!
So viel und so oft habe ich noch nie geschwitzt bei irgendeiner Mission.
Ich habe nicht mehr erwartet, das wir uns in dem Spiel noch einmal begegnen.
Und die Fahrt hierüber, mit Tim, der volle Wahnsinn ...“

Lasse atmete aus.
„Und dann treffen wir uns auch noch hier.“ Er zeigte auf den Ballon.
„Du siehst den Ballon, nicht?“

Sigur: „Ja, klar.
Ist ja groß genug.
Wie soll ich ihn übersehen?
Was ist das eigentlich?
Tim hat ihn vorhin nicht gesehen ...“

Lasse wandte sich zu Tim und zeigte auf den Ballon: „Tim, siehst du den Ballon?“

Tim: „Welchen Ballon schon wieder?
Da ist ein Flughafen, ein Rollfeld, ein paar Wiesen dahinter.
Fängst du jetzt auch schon an?
Was soll die Frage?“

Sigur erstaunt.
„Aber siehst du nicht, wir stehen im Schatten?
Wo kommt denn der her?“

Tim: „Hej, jetzt hör auf!
Hier ist kein Schatten.
Mich blendet die Sonne.“ Und tatsächlich kniff er ein wenig die Augen zu.

Sigur schaute erstaunt zu Lasse: „Was ist das?
Ist er blind?“

Lasse schüttelte den Kopf: „Nein, überhaupt nicht.
Der Ballon ist die Cypherpunk-Akademie.
Die kannst du nur sehen, wenn du Cypherpunk bist.“

Sigur: „_Das_ ist die Cypherpunk-Akademie?
Geil!
Aber ich bin kein ...“

Lasse: „Doch!
Bist du.
Du kannst das aber auch anders nennen, wenn du willst.“ Er schlug ihm stolz auf die Schulter: „Gratuliere.
Komm, schnapp dir ein Seil.
Wir müssen zur Sphinx.“

Sigur schüttelte den Kopf und nahm eines der Seile: „Und wenn ich kein Cypherpunk sein will...“

Lasse: „Doch, das willst du.
Vertrau mir.
Mach den Fuß so unten in die Schlaufe.
Und dann fass hier an.“

Sigur: „Erst noch von Tim verabschieden.“

Lasse: „Brauchst du nicht!
Das macht TRON.
Alles, was wir mit den Seilen machen, sieht Tim schon gar nicht mehr.
TRON macht, dass wir uns ganz normal verabschieden, oder irgendetwas anderes.
Ist wahrscheinlich schon passiert.
Du kannst dir das dann später anschauen.“

Sigur schaute ihn erstaunt an.
Lasse zwinkerte ihm zu, steckte seinen Fuß in das Seil und sauste nach oben.
Nach ein paar Sekunden war er im Schacht des Ballons verschwunden.
Sigur schaute noch einmal zu Tim, der sich aber schon abgewandt hatte und wieder Richtung Flugzeug ging.
Er war im Gespräch mit irgendjemand Unsichtbaren.

Sigur setzte vorsichtig seinen Fuß in die Schlaufe, schaute nach oben und hielt sich fest.
Dann machte das Seil von selbst einen Ruck und er sauste nach oben.
Seine Hände waren wie festgeklebt, seine Beine wurden von irgendeiner seltsamen Kraft durchgedrückt.
Er wurde immer schneller.
Im Schacht war es stockfinster.
Er sauste weiter nach oben.
Nach einiger Zeit sah er an der Schachtwand um sich herum einzelne Farbpunkte erscheinen, dann kamen sie in Bewegung, wurden mehr und größer und schließlich verwandelte sich alles in ein Meer von bunten Blättern, kleinen Fischen und anderen Dingen, die durcheinander schwebten und flossen.
Er schoss aus der Röhre.
Das Seil verschwand aus seiner Hand und er landete auf einer Plattform in der Mitte einer riesigen Kuppel.
Die Plattform hatte etwa fünf Meter Durchmesser und fiel nach allen Seiten senkrecht nach unten.
Er sah den Boden nicht.
Rechts neben ihm stand Lasse auf einem ähnlichen Plateau.
Sigur hob seinen Daumen zu ihm hin, aber Lasse sah nur kurz zu ihm und antwortete nicht.
Lasse schaute konzentriert zu einer Stelle weit vor ihm an der Kuppelwand, als ob dort jeden Moment etwas herauskommen würde.
Er ging dabei leicht in die Knie und breitete die Arme aus.

„Willkommen in der Akademie, Sigur“, sagte eine Stimme neben Sigur und er drehte sich zu ihr.
Mostafa, die Mosquito-Fliege, flatterte vor sein Gesicht und schaute ihn freundlich an.
„Ich bin Mostafa!
Wir kennen uns schon von der Einführungsveranstaltung.“

Sigur nickte.

Mostafa: „Lasse wartet schon auf die Sphinx.
Das ist immer gefährlich.
Bei der Sphinx weiß man nie, was passiert.
Da muss man wirklich aufpassen.“

Sie schauten eine Weile zu Lasse.

Mostafa: „Du bist der, der mit Lasse die erste LBI-Mission gemacht hat, oder?“

Sigur: „Genau! Und dich kann man alles über die Cypherpunk-Akademie fragen, oder?“

Mostafa: „Nicht nur das. Ich bin auch der Lehrer für das Lesen und Schreiben.
Natürlich das Lesen und Schreiben von Code, von Programmen.
Cypherpunks schreiben Programme.
Das ist quasi das Einmal-Eins hier.
Dafür haben wir den Cypherpunk-Computerspielplatz.“

Sigur: „Ich kann programmieren.“

Mostafa: „Ich weiß.
Deswegen gehst du nicht gleich auf den Spielplatz.
Aber es gibt dort schon noch einiges, was du nicht kennst.
Das kommt für dich dann später dran.“

Sigur lugte wieder herüber zu Lasse, der seltsame ausweichende Bewegungen machte: „Muss ich auch zur Sphinx?“

Mostafa: „Du musst nicht.“ Er grinste.
„Du musst schon.
Die Sphinx bewacht alle Aus- und Eingänge in der Akademie.
Du musst immer wieder an ihr vorbei, sonst kommst du nicht einmal in die Akademie hinein.“

Sigur: „Wie?
Das hier ist noch nicht drin?“

Er zeigte auf die riesige Kuppelhalle, die in seinen Augen ungefähr so groß sein musste wie der ganze Ballon.
Er schaute nach rechts und erschrak.
Lasse war plötzlich verschwunden und dort, wo vorher seine Plattform war, stand jetzt ein riesiger Felsblock mit einem überdimensionalen Bienenkorb in der Mitte.
Oben drauf saß Wim, der Bär, und blickte mit ruhigen Augen zu ihnen herüber.

Sigur staunte: „Was …?
Wo ist …?“

„Komm mit“, meinte Mostafa und flog los.
„Wim wartet auf dich.“

„Wie soll ich da hinüber kommen?
Ich kann nicht fliegen und zum Springen ist es zu weit“, rief Sigur hinter ihm her und schaute die Kante der Plattform hinunter.

Mostafa rief von der anderen Seite: „In der Cypherpunk-Akademie geht alles mit Gedanken.
Denk dich dorthin!“

Sigur nickte Mostafa zu: „Ich verstehe.“
Er trat einen Schritt zurück, legte seine Hände seitlich an die Stirn und sagte leise: „Zum Bär, zum Bär.“ Nichts rührte sich.

Mostafa: „Du musst loslassen.
Denk einfach.
Vertrau!“

Sigur probierte es noch ein paar Mal und wiederum tat sich nichts.

Mostafa flog wieder zu ihm herüber: „Na?
Fehlzündung?
Du musst nicht denken, dass du dahin willst, sondern denken, dass du dort bist.“

Sigurs Ohren ploppten, es ging ein Stich durch seine Augen, er kniff sie zu, und als er die Augen wieder öffnete stand er direkt vor dem Felsen des Bären.
Ihm wurde schwindlig.
Er stolperte nach rechts und konnte sich gerade so fangen.
Mostafa flog unter seinen Arm und stütze ihn.

Mostafa: „Kein Problem, kein Problem.
Das ist immer beim ersten Teleport.
Gleich wird dir schlecht werden.
Dein Gehirn registriert ziemlich langsam, dass du jetzt woanders bist, ohne dahin gegangen zu sein.
Das kennt es noch nicht.“

Sigur fasste sich an den Bauch.
Er kniete sich hin.

Wim sprang vom Bienenstock herunter und setzte sich im Schneidersitz vor Sigur auf den Boden.
Der richtete sich nach einer Weile auf und setzte sich auch.
Von Wim ging eine angenehme Atmosphäre aus.
Er schaute Sigur mit wachen, interessierten Augen und einem unsichtbaren Lächeln an.
Sigurs Körper entspannte sich.
Er fühlte sich leichter.
Die Anstrengungen der letzten Tage fielen von ihm ab.

„Willkommen in der Akademie, Sigur“, brummte der Bär mit einer dunklen Stimme. „Dieser Stein markiert den Eingang zu den Ebenen-Inseln.
Du wirst sehen, warum sie so heißen.
Es gibt elf davon.“

Sigur: „Elf? So viele wie Grundgedanken?“

Wim: „Genau.
Und über der elften Ebene schwebt mein Garten.
Das ist das Ziel.
Es wird eine Weile dauern, bis du dahin kommst.
Die Aufgabe ist, den Weg dorthin zu finden, oder eigentlich, ihn zu bauen.

Es ist eine Art Gedankenweg, Verbindungen von einem Gedanken zum nächsten, mit vielen Abzweigungen.
Abzweigungen sind Widersprüche und ihre Auflösung.
Man kann alles in der Welt aus verschiedenen Richtungen anschauen, zum Beispiel einen Baum.
Der sieht von einer Seite ganz anders aus, als von einer anderen.
Das widerspricht sich.
Aber es ist trotzdem derselbe Baum.
Genauso ist das mit Gedanken.
Menschen streiten sich oft, nur weil sie ein und denselben Gedanken von zwei verschiedenen Richtungen aus anschauen.
Wenn du in einer Stadt auf einer Insel einen Gedanken findest, wirst du zuerst dessen Widersprüche auflösen, dann neue Widersprüche finden und am Ende eigene Gedanken hinzufügen, zu denen andere Cypherpunks dann Widersprüche und Auflösungen finden werden.
Es ist eine Art von Kreislauf.
Die besten Widersprüche, Auflösungen und Gedanken bleiben.
Die anderen verschwinden nach einiger Zeit wieder.
Auf diese Weise verändern die Cypherpunks, die den Weg suchen, die Ebenen-Inseln fortwährend.
Und zu dieser Welt ist hier der Eingang.“

Sigur nickte. Er schaute sich um.

Sigur: „Wo?“

Wim: „Bist du bereit?“

Sigur: „Hinein zu gehen?
Ja!“

Wim: „Bist du bereit für das, was kommt.“

Sigur: „Was kommt denn?“

Wim: „Das, was kommt, das kommt.
Schau dich um!
Stelle fest, dass nichts Gefährliches um dich herum ist, nichts, das dein Leben bedroht.“

Sigur schaute sich um, schüttelte den Kopf.

Wim: „Wenn sich irgendetwas unsicher anfühlt, fokussiere darauf.“

Sigur: „Nichts.“

Wim: „Frage dich: Hast du alles, was du brauchst.
Gibt es etwas, auf das du wartest, das nötig ist, bevor du weiter machen kannst?
Muss du etwas wissen? Oder klären?
Oder kannst du einfach hier sein, so wie du bist?“

Sigur schloss seine Augen und atmete ruhig.
Er nickte.

Wim: „Gehe mit deinem Bewusstsein an einen Platz hinter deinen Augen.“

Wim: „Verweile dort für einen Moment.“

Wim: „Nein, bleib dort.
Geh nicht weg.“

Wim: „Jetzt geh ein wenig tiefer.“

Wim: „Es ist nichts Gefährliches um dich herum.“

Wim: „Geh langsam weiter herunter und sieh, wo du Widerstand fühlst.
Hals … Brust … Bauch … Beine.
Dann zurück zur Brust und durch die Arme.
Wieder zurück zum Kopf an den Ausgangspunkt.“ Er wartete einige Augenblicke.
„Jetzt gehe dahin, wo du am meisten Widerstand gespürt hast.“

Wim: „Bleib da für eine Minute.“

Nach einer Minute sagte Wim: „Okay.“

Sigur schaute Wim an.
„Wozu ist das gut?“

Wim: „Nicht weggehen.
Bleib in dem Gefühl.
Das ist Vorbereitung für das, was jetzt kommt.“

Sigur: „Was kommt jetzt?“

Aber Wim war schon verschwunden, der Bienenkorb auch, auch Sigurs Plattform war weg.
Die ganze Kuppel änderte sich in atemberaubender Geschwindigkeit.
Sigur stand instinktiv auf und machte einen Schritt zurück.
Er schaute nach allen Seiten.
Er stand jetzt auf einer Felsen-Ebene, die nach allen Seiten bis zur Kuppel reichte.
Alles wurde dunkler, bekam schärfere Kanten und Umrisse und plötzlich hörte man in der ganzen Kuppel ein düsteres Grollen.
Der ganze Raum erzitterte, dann stand auf einmal ein riesiger, kreisförmiger Bereich der Kuppel in Flammen.
Sigur starrte dorthin.
Manche Flammen schlugen weit in die Kuppel hinein.
Urplötzlich schoss aus der Mitte des Kreises mit hoher Geschwindigkeit eine dunkle Gestalt mit Vogelkopf und gewaltigen Schwingen heraus und flog nach oben zum Kuppeldach, dann von dort direkt auf Sigur zu.
Sie ließ etwa ein Dutzend eiförmige, brennende Gebilde Richtung Sigur fliegen.
Er warf sich auf den Boden, drehte sich zur Seite und konnte gerade so vermeiden, getroffen zu werden.
Die Sphinx landete etwa zwanzig Meter vor ihm auf dem Boden und wurde größer und größer und größer, bis sie etwa ein Drittel der Höhe der Kuppel einnahm.

Sigur sagte leise: „Die Sphinx!“

Sie beugte sich zu ihm herunter und fragte mit lauter, grollender Stimme:

„WER BIST DU, DASS DU ES WAGST, VOR MICH ZU TRETEN?“

Sigur richtete sich auf und antwortete, ohne zu zögern: „Ein Mensch!“ Er wusste, dass er schnell antworten musste.

Die Sphinx lies ihre Flügel hochflattern und schrie in Schmerzen auf.
Dann sammelte sie ihre Kräfte und legte die Flügel an.
Sie war ein wenig geschrumpft und schaute Sigur dunkler und strenger an.

Sphinx: „WAS WILLST DU HINTER DIESER PFORTE TUN?“

Sigur: „Lernen.
Ich will lernen.“

Die Sphinx schrie zum zweiten Mal markerschütternd auf.
Sigur schaute sie hochkonzentriert an.
Immer wenn er „richtig“ antworten würde, würde sie an Kraft verlieren, und wütender werden.
„Richtig“ hieß, aus ihrer Sicht richtig.
Das war wichtig, das hatte ihm Lasse gesagt.
Die Sphinx wähnte sich im Besitz der ganzen Weisheit der Welt, der vollständigen Wahrheit.
Um die Sphinx zu besiegen, musste man verstehen, wie sie dachte.

Die Sphinx beruhigte sich wieder, beugte sich zu Sigur und drehte dabei drohend ihren Kopf hin und her:

Sphinx: „WELCHE TUGEND BRAUCHST DU HIER AM MEISTEN?“

Sigur: “Gerechtigkeitsliebe“

„Das war einfach“, dachte Sigur, „Die Feinde des Internets im Jahr 2026 waren darauf aus, die Welt zu spalten, in Menschen, die in Wohlstand lebten und solchen, die für sie arbeiten sollten.
In solche, die unterdrückten und in solche die unterdrückt wurden, in solche die in Sicherheit lebten und in solche, die ständig in Gefahr waren.“

Der Schrei der Sphinx wurde immer mehr zu einem Aufjaulen.
Ihre Augen wurden düsterer, sie begann deutlich an Kraft zu verlieren, ihre Flügel wurden steifer, sie schrumpfte weiter.

Sphinx: „WAS IST STÄRKER ALS ALLE GEHEIMDIENSTE UND ARMEEN UND UNTERNEHMEN DIESER WELT?“

Sigur stutzte einen kurzen Moment.
Es hatte es einmal gewusst.
Es war ihm entfallen.
Aber es war so einfach gewesen.
Was war das?
Er konzentrierte sich.
Die Sphinx begann sich aufzuplustern.

Sigur: „Die Jugend!“ Er atmete aus.
Das war knapp.
Man musste innerhalb von drei Sekunden antworten, sonst war es zu spät.

Die Sphinx jaulte laut auf und fluchte donnerend: „Hurensohn!
Taugenichts!
Dummkopf!“ Sie rauschte mit ihren Flügeln.

Sphinx: „WAS TUST DU, WENN DU VERSAGST?“

Sigur: „Ich kann nicht versagen. Wenn ich Fehler mache, lerne ich, wenn ich keine Fehler mache, freue ich mich.“

Die Sphinx seufzte, laut und kläglich.
Ihr Stimme wurde brüchig.
Sie zitterte leicht.

Sphinx: „DU WIRST DICH HIER VERLIEREN!“

Sigur nickte deutlich.

„Und genau das will ich!“, sagte er mit einem breiten Grinsen.

Eine dunkle, warme Stimme erklang aus dem Hintergrund:

TRON: „Sage es noch einmal anders.“

Sigur ernster: „Ich will mich verlieren, um mich zu finden.“

Ein klägliches Krächzen kam aus dem Schnabel der Sphinx.
Sie kauerte auf dem Boden und wandte sich vor Schmerzen.
Dann richtete sie sich mit letzter Kraft wieder auf.

Sphinx: „DU KANNST GEGEN MICH NICHT GEWINNEN.“

Das war eine Trickfrage.
Das Wort „gegen“ war das Entscheidende.
Sigur sagte triumphierend: „Aber ich kann gewinnen. Immer wieder!“

Er sprang von seinem Podest, lief auf die Sphinx zu, die zu Stein erstarrt war, und gab ihr einen Tritt.
Alles zerbröselte zu Staub und wurde nach und nach von einem aufkommenden Wind herausgetragen.

Die ganze Halle änderte sich wieder.
Um ihn herum erschienen ungeheuer dicke, matt glänzende Eichen mit herabhängenden Lianen, viele andere Bäume, moosbewachsene Steine, die ihn anzuschauen schienen, und direkt vor ihm ein kleiner, spiegelnder Teich mit dichtem Buschwerk darum herum und einem schwebenden Nebel darüber, der ein eigenes Leben zu haben schien.
Alles um Sigur herum verwandelte sich in einen Zauberwald.
Verschiedenste, sonderbarste Tiere krochen, flogen oder krabbelten umher.
Er entdeckte eine wunderschöne, große, giftig aussehende Lotusblume, nicht weit von ihm auf einer Lichtung.
Nichts von alldem war chaotisch.
Alles schien eine seltsame Ordnung zu haben, jede Bewegung verriet ihren Sinn.
Sigur blickte sich um, er staunte, fürchtete sich ein wenig.
Von hinten sagte eine klare, weiche Stimme: „Sigur!“ Er drehte sich um und vor ihm saß auf einem Baumstumpf Tin, die Eule.

Sigur verneigte sich.

Tin: „Auch ich heiße dich herzlich Willkommen.
Lasse wartet schon auf dich im Cypherpunk Café."

Sigur: „Ist das der Zauberwald?
Warum bin ich jetzt hier gelandet?
Ich stand gerade noch vor dem Eingang zu den Ebenen-Inseln.“

Tin: „Der Zauberwald ist der Ort, wo alle vergangenen Gedanken und Entscheidungen aufbewahrt werden.
Du kannst hier Rätsel lösen und Antworten auf Fragen finden.
Für die Ebenen-Inseln brauchst du den Zauberwald wegen der Nahrung, die in ihm wächst.
Solche zum Beispiel.“

Tin zeigte auf einen Baum, an dem lustig geformte, blaue und rosa Früchte hingen.

„Du kannst sie nicht pflücken, du musst das Rätsel des Baumes lösen, dann bekommst du von ihm immer wieder Früchte, die du auf den Ebenen-Inseln brauchen wirst.
Das Wichtigste hier im Zauberwald sind aber Denkfehler, vor allem die Denkfehler, die alle oder die allermeisten Menschen einer Zeit oder einer Gegend in sich tragen.
Sie sehen so aus.“

Tin zeigte auf die Lichtung mit der Lotusblume.

„Wenn du sie berührst, dann erscheint über der Blüte, was sie ist.“

Tin schickte eine Libelle zur Lotusblume.
Über ihr erschien eine Schrift aus Blütenstaub, die seltsam leuchtete.

****
....
Man muss sich anpassen, um im Leben etwas zu erreichen, um
erfolgreich zu sein. Und alles, was man nicht macht, weil
man sich anpasst, das muss man ersetzen. Zum Beispiel dadurch,
viel Geld zu haben, das schönste Haus, die aufregendsten Reisen,
zu machen oder irgendetwas anderes Spannendes oder Schönes.
....
****

„Auf den Ebenen-Inseln wirst du einen Menschen finden, auf den dieser Gedankenfehler passt.
Es passt ja für fast alle Menschen dieser Zeit, aber bei diesem einen ist es ganz besonders deutlich.
Er oder sie sucht nach dem Gedanken und du kannst ihm oder ihr dann den Gedanken schenken, dann wirst du dafür etwas bekommen.“

Die Libelle flog durch die Schrift hindurch und sie verschwand.
Gleichzeitig öffnete Sigur instinktiv seine Hand und auf ihr erschien ein kleines, quadratisches, bunt bemaltes Blättchen.
Er schaute es an und überlegte, wo er es aufbewahren könnte.

Tin: „Denke einfach: Das ist meins. Dann verschwindet es in deinem unsichtbaren Rucksack.“

Das Blättchen verschwand aus Sigurs Hand.

Tin „Es gibt hier viele davon.
Um in den Garten von Wim zu kommen, musst du alle finden und verschenken.
Aber aber es gibt hier nicht nur falsche Gedanken.
Es gibt auch vieles, das man einfach so entdecken kann.
Siehst du den Moderhaufen dahinten?“

Sigur nickte.

Tin: „Mit weißem Schimmel darunter und giftigem, stinkenden Matsch, in dem nichts wachsen kann.“

Sigur blickte auf den Haufen.

Tin: „Das ist eine Beziehung zwischen zwei Menschen, die viel gestritten und sich gegenseitig zu Dingen gezwungen haben, die sie nicht tun wollten.
Sie haben sich gefühlsmäßig sehr stark ineinander verwickelt, wollten sich gegenseitig ändern.
Und sie haben das nie aufgeräumt.“

Sigur schauderte bei dem Anblick. Sein Blick wandte sich zu einem dürren Gestrüpp, das daneben lag.

Tin: „Der Dornenbusch hier?
Das waren Wortgefechte, Diskussionen.
Alles stirbt, wenn man es nur mit fremden Worten betrachtet.
Deswegen wirst du hier in der Akademie deine eigenen Worte für die Dinge machen.
Es hilft nicht, wenn du wiederholst, was ein anderer gesagt hat.
Du wirst lernen, alles von verschiedenen Seiten aus zu sehen und zu Gedanken zu kommen, die lebendig sind, statt nur Worte zu haben.
Es gibt nicht die Wahrheit, es gibt nur Wahres.
Die widersprüchlichsten Dinge können wahr sein.“

Sigur: „Lasse meinte, das hier wäre die Weisheit.“

Tin sagte: „Weisheit ist Vergangenheit.
Liebe ist Zukunft.“

Sigur nickte.

Tin: „Ich sehe, du willst jetzt schnell vorangehen … Aber du bist noch nicht bereit.
… du musst auch noch an den Ebenen-Sphinxen vorbei.“

Sigur: „Ich weiß, Tin.
Die Ebenen-Sphinxen.
Ich bin bereit.“

Tin: „Du bist bereit?“

Sigur: „Ich bin bereit!“ Er stellte sich aufrecht vor sie.

Tin musterte ihn mit besorgten Augen.

Tin: „Auf welche Ebene willst du?“

Sigur: „Auf welcher Ebene ist Lasse?“

Tin: „Auf Ebene 4.“

Sigur: „Dann auf Ebene 4!“

Tin nickte: „So soll es sein.
Ebene 1: Freie Software, Verschlüsselung, dezentrale Dienste und alles andere, was jeder Macht der Welt standhalten kann.“

Sigur nickte zurück: „Ich kenne die 11 Grundgedanken der Cypherpunks.“

Tin: „Ich weiß, ich weiß.
Ebene 1 wird dir geschenkt.“ Sie warf einen bunt leuchtenden Glasball in die Luft, der fortschwebte und nach einer Zeit in Tausende von kleinen Stäubchen in allen Farben zerfiel.
Sigur bestaunte sie lachend.

Sie sah Sigur an: “Ebene 2: Lebensideale: Gerechtigkeit, Offenheit, Gleichheit, Brüderlichkeit, und alles andere, was uns als Menschen erhebt.“

Sigur nickte: „Freiheit, andere Anteil haben lassen ...“

Tin: „Ebene 2 … wird dir ebenfalls geschenkt.
Das ist sehr selten, dass zwei Ebenen geschenkt werden. Du kannst sie natürlich jederzeit besuchen und erforschen.“ Sie warf eine andersfarbige Kugel in die Luft, die auch zerstob.

Sigur lächelte.
Seine Augen strahlten.

Tin: „Ebene 3: Das Dagegen-Sein überwinden, und alles andere, was die Grenzen zwischen Menschen aufhebt.“

Sigur nickte.

Tin: „Ebene 3: Die Ebenen-Sphinx wartet auf dich.
Bist du bereit?“ Sie schaute ihn eindringlich an.

Sigur: „Ja.“

Tin flatterte mit ihren Flügeln und in einem Blitz verschwand der Zaubergarten und Sigur fand sich in einem Kerker ohne Fenster wieder.
Überall grob gehauene, feuchte Steine, von Mörtel zusammengehalten, viel Moos und ein strohbedeckter Steinboden.
Es roch scharf nach Fäkalien.
Sigur hielt sich die Nase zu.
Er schaute sich verwundert um.
Das kannte er nicht.
Davon hatte ihm Lasse nicht erzählt.
Er dachte nach, lief herum, schaute die Wände an.
Das einzige Licht kam von einer winzigen Gittertüre mit massiven Eisenstäben an einem Ende des Raumes.
Sie war gerade so groß, dass er durch sie herauskriechen könnte, wenn sie denn offen wäre.
Er prüfte die massiven Scharniere, fand aber keine Schwachstelle, sogar das Schloss fehlte.
Das Gitter war festgeschweißt.
Er umfasste die Stäbe, rüttelte daran.
Unmöglich sie auch nur einen Millimeter zu bewegen.
Er rief laut den daran anschließenden Gang hinunter.
Keine Antwort.
Er versuchte sich ins Cypherpunk-Café zu denken, zurück zum Bären, in den Zaubergarten, aber nichts geschah.
Dann fasste er sich mit beiden Händen an den Kopf: „Oh nein!
Nicht Wunderlich, nicht Wunderlich.“

„Doch!“, sagte eine Stimme hinter ihm.
Sigur drehte sich um.
Eine kleine Ratte blickte ihn mit großen, scheuen Augen an.

Er hielt beide Hände vor sein Gesicht und dachte: „Oh, nein!
Ich bin kaum zehn Minuten hier und schon bei Wunderlich.
Lasse war in seiner ganzen Zeit erst zweimal bei ihm!“

Wunderlich: „Ja, ja.
Du hast großen Mist gebaut, du Cypherpunk!“
