== [big-number]#2064# Das Cypherpunk Cafe

Das Cypherpunk-Cafe lag ganz oben auf dem Ballon, unter freiem Himmel.
Ringsherum sah man Berge, im Hintergrund einen See, eine Miniatur-Landschaft.
Sigur setzte sich zu Lasse.
Vor ihm stand schon ein großes Glas Latte Macchiato.
Daneben lag ein dickes, lederbeschlagenes Buch, das er aber nicht beachtete.
Der Bär saß auf dem Geländer des Cafes mit den Beinen nach draußen baumelnd.
Wunderlich plauderte angeregt mit Mostafa am Nachbartisch, beide vor sich einen großen, aufwändigen Cocktailbecher mit vielen Strohhalmen und bunten Glitzerbändchen.
Wunderlich zeigte mit dem Daumen ab und zu Sigur und grinste.

Sigur blickte sich um: „Boah, schau, wer hier alles da ist!
Das ist ja Wahrsinn … So viele Cypherpunks an einem Fleck … Hey, Tobi!“ Er winkte zu einem Tisch an der anderen Seite.
Tobi winkte zurück.

Lasse: „Ja, das ist nett hier.
Und du siehst nur bis Ebene 4 und die Lehrer natürlich ...“

Sigur: „Aber ich bin noch nicht einmal vorbei an der Sphinx von Ebene 3.“

Lasse: „Das macht nichts, die bekommst du morgen.
Du bist hier immer in der Ebene, in der du sein willst.
Wenn zu hoch wählst, dann bist du eben öfter bei Wunderlich.
Und du kannst auf einer Ebene erst etwas machen, wenn du an ihm und an den Sphinxen vorbei bist.
Ins Cafe kannst du immer kommen, das ist immer offen.“

Sigur trocken: „Wunderlich hat mich richtig rangenommen.
Da ist ja die Sphinx nichts dagegen.“

Lasse nickte: „Es gibt auch ein paar lästige Sphinxen.
Da kann man auch hängenbleiben.
Aber Wunderlich ist schon speziell.
Und du kannst an den verschiedensten Stellen treffen.
Ich musste mit ihm einmal in einer Bank einen Geldkredit aushandeln.
Er war der Bankmanager.
Ich sag dir, er hat mich wahnsinnig gemacht.
Ich habe ihn geschlagen!
Echt.
Ich habe ihm eine verpasst ...
Bumm!
Ich bin Tage später noch in der realen Welt mitten in der Nacht aufgewacht und habe an ihn gedacht.“

Wunderlich prostete herüber und grinste.
Dann rülpste er laut.

Lasse leise zu Sigur: „Das Schlimmste ist, dass er Gedanken lesen kann.“

Sigur: „Echt! Shit ...“ Er schaute zu Wunderlich.

Lasse: „Hej!
In zehn Minuten ist Spielende.
Deswegen bist du übrigens nicht mehr zur Sphinx gekommen.
Die dritte Sphinx ist gut, spannend.
Heute hätte sie mich beinahe erwischt.“

Sigur: „Du musst immer wieder zu ihr?“

Lasse nickte: „Oft.
Manchmal total überraschend.
Das ist Auffrischung, Übung, beweglich bleiben.
Komm, wir sitzen noch ein bisschen rüber zu Wim.
Der kann dir noch ein paar Tipps zu Wunderlich geben.
So wie ich dich kenne, wirst du ihn morgen gleich nochmal treffen.“ Er grinste ihn an.

Sigur stöhnte.
Er schaute auf den Tisch und zeigte auf das Buch: „Was ist das da eigentlich?“

Lasse: „Ah, hätte ich fast vergessen.
Dein Logbuch.
Da ist ein neue Medaille drin, für das, was wir heute gemacht haben, und die drei Wunderlich-Kugeln sind auch drin.“ Er gab ihm das Buch.
„Kein schlechter Anfang.
Es ist auch unsere neue Mission drin.“

Sigur: „Unsere neue Mission?
Was ist das?“  Er wollte das Buch öffnen, aber schaffte es nicht.
Es war wie zugeklebt.

Lasse: „Einfach denken, was du willst.
Du bist in der Cypherpunk-Akademie.“

Sigur schaute das Buch an und es klappte auf einer Seite mit einer glänzenden Medaille auf.

Sigur: „Wow!“

Lasse: „Die Steffens-Lampresa-Medaille.
Das sind die beiden, die in Wirklichkeit das NSA-Hauptgebäude mit geklauten Kampfrobotern in Schutt und Asche gelegt haben.
Das war vor 36 Jahren, im Jahr 2028.
Ich habe sie auch bekommen.“

Sigur: „Die sieht echt gut aus!
Sind das die beiden da unten?“ Er zeigte auf zwei Bilder.

Lasse nickte.

Sigur: „Der eine sieht brasilianisch aus.
Boa, und der andere hat eine Bodybuilder-Figur.
Hej.“

Lasse: „Beide sind Brasilianer.“

Sigur: „Ok. Leben die eigentlich noch?“

Lasse: „Nee. Die haben es nicht geschafft.“

Sigur: „Shit.
Die Welt war echt so, damals. Wahnsinn.“

Lasse: „Ja, lieber in einem Zimmer mit Wunderlich leben, als damals in einem Geheimdienst arbeiten, der Leute ermordet und so.“

Sigur atmete aus. „Wunderlich ...“ Er schaute wieder auf das Buch und es klappte zu und wieder auf.
Wunderlich grinste ihm auf der aufgeschlagenen Seite entgegen.
Sigur schüttelte erschrocken den Kopf.

Sigur: „Lass uns zu Wim gehen.“

Sie kletterten über das Geländer und setzten sich links und rechts neben Wim.
Der legte um beide seine Arme.
