== [big-number]#2021# Auf einer Berliner Dachterrasse

Paul saß neben Marianne auf einem Liegestuhl auf einer großen Dachterrasse mitten in Kreuzberg.
Die Abendsonne tauchte alles in warme Farben.
Die Terrasse war umrahmt von einem breiten Steingeländer.
Es gab Liegestühle, kleine Tischchen, Pflanzen, eine Bar.
Auf seinem Schoß lag einen Laptop, auf dem er gelegentlich etwas tippte.
Oskar lag auf der gegenüberliegenden Seite, neben Anni.
Kevin saß auf dem Geländer mit dem Rücken zu den anderen, die Beine nach draußen baumelnd und schaute in Richtung Kottbusser Tor.

Paul legte seinen Laptop auf den Boden und zog zwei Flaschen Mate aus dem Eiskübel.
Eine davon gab er Marianne.
Die andere verlangte Oskar.
Er warf sie ihm zu.
Dann holte er zwei weitere und bot Anni davon eine an, aber sie schüttelte den Kopf.
Er prostete Marianne und Oskar zu, trank einen Schluck, lehnte sich zurück und blickte in die Sonne.
Marianne schaute ihn an, schüttelte den Kopf und lachte los.
Sie lachte und lachte.
Sie konnte nicht mehr aufhören.
Paul schaute sie an, hielt sich dann mit einer Hand seine Augen zu und lachte mit.
Oskar hielt seine Flasche theatralisch in die Luft und stieß dann einen Ur-Schrei aus: „Jaaaaaaaahhhhhhh!“ 

Ein seltsam brummendes Geräusch kam von hinter dem Geländer.
Kevin deutete darauf.
Oskar stand auf und ging mit der Mateflasche zu ihm.
In dem Augenblick stiegen vor ihm zwei, etwa einen Meter lange, ferngesteuerte Drohnen hoch, beide mit einem gläsernen Cockpit.
Oskar wich leicht zurück.
Sie standen jetzt fast in Greifweite vor ihm in der Luft.
Perfekt nebeneinander, beide deutlich mit vielen Kameras und anderen Sensoren bestückt.
Sie drehten sich langsam zu Oskar hin.
Auf der Scheibe des Cockpits erschien eine grüne, blinkende Computerschrift: „Hi!“ und „Oskar!“ 

Oskar: „What the fuck!“ 

Er ging näher hin.
Sie flogen genau auf seine Kopfhöhe.
Er schaute sie an, schaute sich ein wenig verwirrt um.
Dann drehten sich beide gemeinsam, exakt synchron, einmal um sich selbst und blieben wieder in Richtung von Oskar stehen.
Zwei lange Wasserstrahlen schossen aus kleinen Röhrchen unter den Drohnen direkt auf Oskars Brust.
Eine rote Laufschrift auf den Cockpitscheiben zeigte: „Kill confirmed.
Kill confirmed.“ und „Oskar down! Oskar down!“ Oskar drehte sich wild suchend um.
Er zog sich an seinem nassen T-Shirt, beugte sich dann über das Geländer und schnappte nach einer der Drohnen.
Die wich elegant zurück und schoss beim Zurückgehen noch einmal einen Wasserstrahl.
Diesmal mitten in Oskars Gesicht.

In dem Augenblick sprang die Türe auf und auf die Dachtterrasse kamen lachend zwei etwa 18-jährige Jungs: Ein schmächtiger lateinamerikanisch aussehender und ein schwarzer mit athletischem Körperbau.
Beide hatten kompliziert aussehende Fernsteuerungen in der Hand, zeigten auf Oskar und prusteten los.

Paul und Marianne schauten ein wenig fragend auf die Szene.
Oskar wischte sich mit dem Ärmel über das Gesicht, zeigte in die Richtung der beiden und sagte trocken zu Paul und Marianne: „Darf ich vorstellen: Ali Steffens und Eduardo Lampresa“, dann zu den beiden: „Paul und Marianne Lasser.“ Dann ging er zu ihnen und sie umarmten sich lange.
Paul und Marianne kamen hinzu, und auch Kevin und Anni.
